-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,username text not null unique,avatar_url text,rating integer not null default 1200,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.rooms (code text primary key,host_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'waiting' check (status in ('waiting','playing','finished')),created_at timestamptz not null default now(),started_at timestamptz,finished_at timestamptz);
create table if not exists public.room_players (room_code text not null references public.rooms(code) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,ready boolean not null default false,seat text check (seat in ('white','black')),joined_at timestamptz not null default now(),primary key (room_code,user_id));
create table if not exists public.game_moves (id bigint generated always as identity primary key,room_code text not null references public.rooms(code) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,move_number integer not null,move jsonb not null,created_at timestamptz not null default now(),unique(room_code,move_number));
create table if not exists public.matches (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,room_code text references public.rooms(code) on delete set null,result text not null,difficulty text,moves jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
alter table public.profiles enable row level security;alter table public.rooms enable row level security;alter table public.room_players enable row level security;alter table public.game_moves enable row level security;alter table public.matches enable row level security;
create policy "profiles readable" on public.profiles for select to authenticated using (true);create policy "profile own insert" on public.profiles for insert to authenticated with check (auth.uid() = id);create policy "profile own update" on public.profiles for update to authenticated using (auth.uid() = id);
create policy "rooms readable" on public.rooms for select to authenticated using (true);create policy "rooms create" on public.rooms for insert to authenticated with check (auth.uid() = host_id);create policy "rooms host update" on public.rooms for update to authenticated using (auth.uid() = host_id);create policy "rooms host delete" on public.rooms for delete to authenticated using (auth.uid() = host_id);
create policy "room players readable" on public.room_players for select to authenticated using (true);create policy "room players join" on public.room_players for insert to authenticated with check (auth.uid() = user_id);create policy "room players own update" on public.room_players for update to authenticated using (auth.uid() = user_id);create policy "room players own delete" on public.room_players for delete to authenticated using (auth.uid() = user_id);
create policy "moves readable" on public.game_moves for select to authenticated using (true);create policy "moves own insert" on public.game_moves for insert to authenticated with check (auth.uid() = user_id);
create policy "matches own read" on public.matches for select to authenticated using (auth.uid() = user_id);create policy "matches own insert" on public.matches for insert to authenticated with check (auth.uid() = user_id);
alter publication supabase_realtime add table public.rooms;alter publication supabase_realtime add table public.room_players;alter publication supabase_realtime add table public.game_moves;
