from pathlib import Path
p=Path('manhaj/base-head.html').read_text()
head=p.replace('نظام سِناد للنشاط المدرسي','منهج | مساحة المعلم الكويتي').replace("'Satoshi',sans-serif","'Cairo',Tahoma,Arial,sans-serif")
head=head.replace('https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700&display=swap','https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&display=swap')
extra='''<style>
:root{--text-xs:1rem;--text-sm:1.1rem;--text-base:1.15rem;--sidebar:290px} .view[hidden]{display:none!important} .tools{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0} .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:16px} .empty{padding:35px;text-align:center;color:var(--color-text-muted)} .note{padding:14px;border-radius:12px;background:var(--color-primary-highlight);margin:16px 0} .field select{appearance:none} .header{gap:12px}.header h2{font-size:1.5rem}.header p{font-size:.95rem} :focus-visible{outline:3px solid #cf9335;outline-offset:3px} .task{flex-wrap:wrap}.table-wrap{overflow:auto} #toast{position:fixed;bottom:24px;left:24px;background:var(--color-text);color:var(--color-bg);padding:14px 24px;border-radius:12px;z-index:90} @media(max-width:860px){.sidebar{inset:0 0 0 auto;transform:translateX(100%)}.header{flex-wrap:wrap}.header-actions{flex-wrap:wrap}.form-grid{grid-template-columns:1fr}.hero-metrics{grid-template-columns:1fr 1fr}.main{overflow:visible}} @media print{html,body,.app,.content,.main{height:auto;overflow:visible;display:block}.sidebar,.header,.tools,button,.no-print{display:none!important}.view{display:none!important}#reportsView{display:block!important}.panel{border:0;box-shadow:none}body{background:#fff;color:#000}.task{break-inside:avoid}a{color:#000}}
</style>'''
extra += '<style>'+Path('manhaj/pro.css').read_text()+Path('manhaj/assistant.css').read_text()+Path('manhaj/language.css').read_text()+Path('manhaj/reader.css').read_text()+Path('manhaj/storefront.css').read_text()+Path('manhaj/choices.css').read_text()+Path('manhaj/sahel.css').read_text()+Path('manhaj/curriculum-audit.css').read_text()+Path('manhaj/teams-export.css').read_text()+Path('manhaj/teacher-path.css').read_text()+Path('manhaj/kuwait-refresh.css').read_text()+Path('manhaj/activity.css').read_text()+'</style>'
body=Path('manhaj/body.html').read_text()
js=Path('manhaj/activity-core.js').read_text()+'\n'+Path('manhaj/vendor/qrcode.js').read_text()+'\n'+Path('manhaj/app.js').read_text()+'\n'+Path('manhaj/workhub.js').read_text()+'\n'+Path('manhaj/studio.js').read_text()+'\n'+Path('manhaj/pro.js').read_text()+'\n'+Path('manhaj/analysis/core.js').read_text()+'\n'+Path('manhaj/analysis/client.js').read_text()+'\n'+Path('manhaj/assistant-attachments.js').read_text()+'\n'+Path('manhaj/assistant.js').read_text()+'\n'+Path('manhaj/language.js').read_text()+'\n'+Path('manhaj/reader.js').read_text()+'\n'+Path('manhaj/storefront.js').read_text()+'\n'+Path('manhaj/choices.js').read_text()+'\n'+Path('manhaj/sahel.js').read_text()+'\n'+Path('manhaj/curriculum-audit.js').read_text()+'\n'+Path('manhaj/teams-export.js').read_text()+'\n'+Path('manhaj/teacher-path.js').read_text()+'\n'+Path('manhaj/activity.js').read_text()
Path('manhaj/index.html').write_text(head.replace('</head>',extra+'</head>')+body+'<script>'+js+'</script></body></html>')
