(()=>{
const KD=n=>`${Number(n||0).toFixed(3)} د.ك`;
const today=new Date('2026-08-14T00:00:00+03:00');
const defaultData={restaurantName:'حساب المطعم',creditLimit:5000,outstanding:3800,monthCreditSpend:2150,dueNow:1200,overdue:0,overdueDays:0,nextDue:'2026-08-20',monthlyBudget:5200,monthSpend:3975,healthScore:82,monthTrend:7.4,
spendByCategory:[['دواجن ولحوم',817],['خضار وفواكه',451],['أرز وحبوب',344],['زيوت',279],['أخرى',259]],
purchases:[
{date:'2026-08-13',order:'#10567',category:'زيوت',items:'زيت قلي 40 لتر',payment:'credit',amount:245},
{date:'2026-08-11',order:'#10540',category:'أرز وحبوب',items:'أرز بسمتي 100 كجم',payment:'credit',amount:310},
{date:'2026-08-07',order:'#10491',category:'خضار وفواكه',items:'طماطم، بصل، بطاطا',payment:'credit',amount:185},
{date:'2026-08-03',order:'#10458',category:'دواجن ولحوم',items:'دجاج مبرد 160 كجم',payment:'credit',amount:420},
{date:'2026-08-01',order:'#10422',category:'مواد تنظيف',items:'منظفات ومستلزمات',payment:'direct',amount:118}
],
invoices:[
{id:'INV-1082',date:'2026-08-05',due:'2026-08-20',amount:750,status:'due'},
{id:'INV-1074',date:'2026-08-01',due:'2026-08-18',amount:450,status:'due'},
{id:'INV-1051',date:'2026-07-22',due:'2026-08-06',amount:980,status:'paid'}
],
topProducts:[['دجاج مبرد','520 كجم'],['أرز بسمتي','300 كجم'],['زيت قلي','120 لتر'],['بطاطا','240 كجم'],['بصل','180 كجم']],
monthlySpend:[['مارس',3100],['أبريل',3480],['مايو',3660],['يونيو',4020],['يوليو',4320],['أغسطس',3975]],
budgetCategories:[['دواجن ولحوم',1700,1420],['خضار وفواكه',900,720],['أرز وحبوب',750,610],['زيوت',550,475],['مواد أخرى',1300,750]],
scheduled:[
{title:'طلب أسبوعي أساسي',when:'كل أحد',next:'16 أغسطس 2026',items:'أرز 100 كجم • زيت 40 لتر • بصل 50 كجم'},
{title:'توريد الخضار',when:'كل 3 أيام',next:'15 أغسطس 2026',items:'طماطم 60 كجم • بطاطا 80 كجم • خيار 35 كجم'}
]};
let data={...defaultData,...safeJSON(localStorage.getItem('zadRestaurantAccount'))};
function safeJSON(v){try{return v?JSON.parse(v):{} }catch{return{}}}
function state(){const available=Math.max(0,data.creditLimit-data.outstanding);const usage=data.creditLimit?data.outstanding/data.creditLimit:0;let level='safe',locked=false,reason='';if(data.overdue>0){level='locked';locked=true;reason=`لديك مبلغ متأخر عن السداد بقيمة ${KD(data.overdue)}.`}else if(usage>=1){level='locked';locked=true;reason='تم الوصول إلى الحد الائتماني الكامل.'}else if(usage>=.81){level='risk';reason='استخدام الكريدت مرتفع. نوصي بالسداد قبل تنفيذ طلبات إضافية.'}else if(usage>=.61){level='warning';reason='اقتربت من الحد الائتماني. راقب الرصيد المتاح.'}else{reason='وضع الحساب الائتماني ضمن المستوى الآمن.'}return{available,usage,level,locked,reason}}
const S=()=>state();
const $=id=>document.getElementById(id);
const text=(id,v)=>{const e=$(id);if(e)e.textContent=v};
function render(){const s=S();text('restaurantName',data.restaurantName);text('creditPercent',`${Math.min(100,Math.round(s.usage*100))}%`);text('creditLimit',KD(data.creditLimit));text('creditUsed',KD(data.outstanding));text('creditAvailable',KD(s.available));text('totalDebt',KD(data.outstanding));text('creditLimit2',KD(data.creditLimit));text('outstanding2',KD(data.outstanding));text('available2',KD(s.available));text('overdue2',KD(data.overdue));text('monthCreditSpend',KD(data.monthCreditSpend));text('monthSpendTrend',`${data.monthTrend>=0?'+':''}${data.monthTrend}% عن الشهر السابق`);text('dueNow',KD(data.dueNow));text('overdueAmount',KD(data.overdue));text('overdueDays',`${data.overdueDays||0} يوم`);text('monthlyBudget',KD(data.monthlyBudget));text('budgetTotal2',KD(data.monthlyBudget));text('budgetUsage2',`${Math.round((data.monthSpend/data.monthlyBudget)*100)}% مستخدم`);text('budgetRemaining',`المتبقي ${KD(Math.max(0,data.monthlyBudget-data.monthSpend))}`);text('healthScore',data.healthScore);text('nextDueDate',formatDate(data.nextDue));
const badge=$('creditStatusBadge'),meter=$('creditMeterFill'),alert=$('creditAlert'),creditBtn=$('creditOrderBtn');const labels={safe:'آمن',warning:'تنبيه',risk:'خطر',locked:'الكريدت موقوف'};text('creditStatusText',labels[s.level]);badge.textContent=labels[s.level];badge.className=`status-pill ${s.level}`;meter.style.width=`${Math.min(100,s.usage*100)}%`;meter.style.background=s.level==='locked'?'var(--danger)':s.level==='risk'?'var(--risk)':s.level==='warning'?'var(--warn)':'var(--safe)';alert.className=`credit-alert show ${s.level}`;alert.textContent=s.reason;creditBtn.disabled=s.locked;creditBtn.dataset.locked=String(s.locked);text('creditGateStatus',s.locked?`⛔ الشراء بالكريدت موقوف. الطلبات الجديدة تعمل بالدفع المباشر فقط. ${s.reason}`:`✓ الشراء بالكريدت متاح حتى ${KD(s.available)}.`);text('healthRingText',data.healthScore>=80?'جيد':data.healthScore>=60?'متوسط':'خطر');text('healthNote',data.overdue>0?'يوجد تأخر في السداد ويجب معالجته قبل إعادة تفعيل الكريدت.':'السداد منتظم ولا توجد مبالغ متأخرة.');
renderSpend();renderReminders();renderPurchases();renderInvoices();renderProducts();renderMonthly();renderBudget();renderScheduled();}
function renderSpend(){const max=Math.max(...data.spendByCategory.map(x=>x[1]),1);$('spendBars').innerHTML=data.spendByCategory.map(([n,v])=>`<div class="bar-row"><span>${n}</span><div class="bar-track"><span style="width:${Math.round(v/max*100)}%"></span></div><strong class="bar-value">${KD(v)}</strong></div>`).join('')}
function renderReminders(){const due=data.invoices.filter(x=>x.status!=='paid').sort((a,b)=>a.due.localeCompare(b.due));$('reminderList').innerHTML=due.length?due.map(x=>`<div class="reminder ${new Date(x.due)<today?'warn':''}"><div><strong>${x.id}</strong><small>${formatDate(x.due)}</small></div><b>${KD(x.amount)}</b></div>`).join(''):'<p class="muted">لا توجد استحقاقات حالية.</p>';text('notificationCount',String(Math.max(1,due.length)))}
function purchaseRows(list){return list.map(p=>`<tr><td>${formatDate(p.date)}</td><td>${p.order}</td><td>${p.items||p.category}</td><td class="${p.payment==='credit'?'pay-credit':'pay-direct'}">${p.payment==='credit'?'كريدت':'دفع مباشر'}</td><td>${KD(p.amount)}</td></tr>`).join('')}
function renderPurchases(){$('recentPurchasesBody').innerHTML=purchaseRows(data.purchases.slice(0,4));$('allPurchasesBody').innerHTML=purchaseRows(data.purchases)}
function renderInvoices(){$('invoicesBody').innerHTML=data.invoices.map(x=>`<tr><td>${x.id}</td><td>${formatDate(x.date)}</td><td>${formatDate(x.due)}</td><td>${KD(x.amount)}</td><td>${x.status==='paid'?'<span class="status-pill safe">مسددة</span>':new Date(x.due)<today?'<span class="status-pill locked">متأخرة</span>':'<span class="status-pill warning">مستحقة</span>'}</td></tr>`).join('')}
function renderProducts(){$('topProducts').innerHTML=data.topProducts.map((x,i)=>`<div class="rank-item"><span class="rank-num">${i+1}</span><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
function renderMonthly(){const max=Math.max(...data.monthlySpend.map(x=>x[1]),1);$('monthlySpendChart').innerHTML=data.monthlySpend.map(([m,v])=>`<div class="month-col"><strong>${Math.round(v)}</strong><i style="height:${Math.max(10,v/max*145)}px"></i><small>${m}</small></div>`).join('')}
function renderBudget(){$('budgetCategories').innerHTML=data.budgetCategories.map(([n,b,s])=>{const p=Math.min(100,Math.round(s/b*100));return`<div class="budget-row"><span>${n}</span><div class="bar-track"><span style="width:${p}%"></span></div><strong>${KD(s)} / ${KD(b)}</strong></div>`}).join('')}
function renderScheduled(){$('scheduledList').innerHTML=data.scheduled.map(x=>`<article class="scheduled-card"><div><h3>${x.title}</h3><small>${x.items}</small><div class="scheduled-meta"><span>التكرار: ${x.when}</span><span>القادم: ${x.next}</span></div></div><a class="secondary-btn" href="./index.html?scheduled=1">مراجعة الطلب</a></article>`).join('')}
function formatDate(s){if(!s)return'—';const d=new Date(`${s}T12:00:00+03:00`);return new Intl.DateTimeFormat(document.documentElement.lang==='en'?'en-GB':'ar-KW',{day:'numeric',month:'short',year:'numeric'}).format(d)}
function go(section){document.querySelectorAll('.page-section').forEach(x=>x.classList.remove('active-section'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));$(section)?.classList.add('active-section');document.querySelector(`.nav-item[data-section="${section}"]`)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const e=$('toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function modal(reason){text('modalReason',reason);$('paymentModal').classList.add('open');$('paymentModal').setAttribute('aria-hidden','false')}
function wire(){document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.section)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('creditOrderBtn').addEventListener('click',()=>{const s=S();if(s.locked)return modal(s.reason);localStorage.setItem('zad-payment-mode','credit');location.href='./index.html?payment=credit'});$('directOrderBtn').addEventListener('click',()=>localStorage.setItem('zad-payment-mode','direct'));$('payNowBtn').addEventListener('click',()=>toast('تم فتح مسار السداد. ربط بوابة الدفع يتم من لوحة الإدارة.'));$('statementBtn').addEventListener('click',downloadStatement);$('closeModal').addEventListener('click',()=>$('paymentModal').classList.remove('open'));$('paymentModal').addEventListener('click',e=>{if(e.target.id==='paymentModal')e.currentTarget.classList.remove('open')});$('languageSelect').addEventListener('change',e=>setLang(e.target.value));}
function downloadStatement(){const rows=['كشف حساب المطعم','',`حد الكريدت,${data.creditLimit}`,`إجمالي المديونية,${data.outstanding}`,`المتاح,${S().available}`,`المستحق,${data.dueNow}`,`المتأخر,${data.overdue}`,'','الفاتورة,التاريخ,الاستحقاق,القيمة,الحالة',...data.invoices.map(x=>[x.id,x.date,x.due,x.amount,x.status].join(','))];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='zad-account-statement.csv';a.click();URL.revokeObjectURL(a.href)}
const dict={en:{overview:'Overview',creditAccount:'Credit account',purchases:'Purchases',invoices:'Invoices',budget:'Budget',scheduledOrders:'Scheduled orders',backToStore:'Back to store',restaurantPortal:'Restaurant portal',creditStatus:'Credit status',creditLimit:'Credit limit',usedCredit:'Used',availableCredit:'Available',totalDebt:'Total debt',orderOnCredit:'Order on credit',directOrder:'Direct payment order',accountHealth:'Account health',monthCreditSpend:'Credit spend this month',dueNow:'Due now',overdue:'Overdue',monthlyBudget:'Monthly budget',creditSpendBreakdown:'Where credit was spent',spendByCategory:'Spend by category',paymentReminder:'Payment reminder',upcomingDues:'Upcoming dues',payNow:'Pay now',latestActivity:'Latest activity',latestPurchases:'Latest purchases',viewAll:'View all',date:'Date',order:'Order',category:'Category',paymentMethod:'Payment method',amount:'Amount',creditManagement:'Credit management',creditAndDebt:'Credit & debt',outstandingBalance:'Outstanding balance',creditRules:'Current credit rules',analytics:'Analytics',purchaseAnalysis:'Purchase analysis',topProducts:'Top purchased items',monthlySpend:'Monthly spend',items:'Items',statements:'Statements',invoicesAndDues:'Invoices & dues',downloadStatement:'Download statement',invoice:'Invoice',dueDate:'Due date',status:'Status',planning:'Planning',purchaseBudget:'Purchase budget',preorder:'Pre-order',directPaymentRequired:'Direct payment required',creditUnavailable:'Credit is currently unavailable',continueDirect:'Continue with direct payment'},hi:{overview:'अवलोकन',creditAccount:'क्रेडिट खाता',purchases:'खरीद',invoices:'चालान',budget:'बजट',scheduledOrders:'निर्धारित ऑर्डर',backToStore:'स्टोर पर वापस',restaurantPortal:'रेस्टोरेंट पोर्टल',creditLimit:'क्रेडिट सीमा',usedCredit:'उपयोग',availableCredit:'उपलब्ध',totalDebt:'कुल बकाया',orderOnCredit:'क्रेडिट पर ऑर्डर',directOrder:'सीधा भुगतान',dueNow:'अभी देय',overdue:'अतिदेय',monthlyBudget:'मासिक बजट'},ur:{overview:'جائزہ',creditAccount:'کریڈٹ اکاؤنٹ',purchases:'خریداری',invoices:'انوائسز',budget:'بجٹ',scheduledOrders:'شیڈول آرڈرز',backToStore:'اسٹور پر واپس',restaurantPortal:'ریستوران پورٹل',creditLimit:'کریڈٹ حد',usedCredit:'استعمال شدہ',availableCredit:'دستیاب',totalDebt:'کل واجبات',orderOnCredit:'کریڈٹ پر آرڈر',directOrder:'براہ راست ادائیگی',dueNow:'ابھی واجب الادا',overdue:'تاخیر شدہ',monthlyBudget:'ماہانہ بجٹ'}};
function setLang(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='en'||lang==='hi'?'ltr':'rtl';$('languageSelect').value=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(lang==='ar')return;const v=dict[lang]?.[key]||dict.en[key];if(v)el.textContent=v});localStorage.setItem('zad-lang',lang);render()}
window.ZadAccount={get:()=>({...data,...S()}),update:patch=>{data={...data,...patch};localStorage.setItem('zadRestaurantAccount',JSON.stringify(data));render();return window.ZadAccount.get()},reset:()=>{localStorage.removeItem('zadRestaurantAccount');location.reload()}};
wire();render();const lang=localStorage.getItem('zad-lang')||'ar';if(lang!=='ar')setLang(lang);
})();
