(()=>{
const API='https://tamweenat-api.onrender.com';
let token=sessionStorage.getItem('tamweenatAdminToken');
if(!token){location.replace('./admin-login.html');return;}
let dashboard=null,restaurants=[];
const $=id=>document.getElementById(id), KD=n=>`${Number(n||0).toFixed(3)} د.ك`, esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(path,opts={}){const r=await fetch(API+path,{...opts,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(opts.headers||{})}});if(r.status===401){sessionStorage.removeItem('tamweenatAdminToken');location.replace('./admin-login.html');throw new Error('انتهت الجلسة');}const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'تعذر تنفيذ العملية');return data;}
function toast(msg){const e=$('adminToast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function badge(level,text){return `<span class="badge ${level}">${text}</span>`}
function page(id){document.querySelectorAll('.admin-page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('#adminNav button').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active');document.querySelector(`#adminNav button[data-page="${id}"]`)?.classList.add('active');$('pageTitle').textContent=document.querySelector(`#adminNav button[data-page="${id}"]`)?.textContent||'لوحة الإدارة';}
async function load(){try{const h=await fetch(API+'/health').then(r=>r.json());$('apiStatus').textContent='API متصل';$('apiStatus').classList.remove('off');$('aiStatus').textContent=h.ai?'AI متصل':'AI بانتظار المفتاح';$('aiStatus').classList.toggle('off',!h.ai);dashboard=await api('/api/admin/dashboard');restaurants=await api('/api/admin/restaurants');renderAll();}catch(e){$('apiStatus').textContent='API غير متصل';$('apiStatus').classList.add('off');toast(e.message)}}
function renderAll(){renderKpis();renderRestaurants();renderRisk();renderOrders();renderCredit();renderMessages();renderAudit();renderAI();renderSettings();}
function renderKpis(){const k=dashboard.kpis;$('adminKpis').innerHTML=[['المطاعم المشتركة',k.restaurants,'النشطة '+k.active],['إجمالي الكريدت',KD(k.totalCredit),'المستخدم '+KD(k.outstanding)],['المديونية المتأخرة',KD(k.overdue),'تحتاج متابعة'],['الطلبات',k.orders,'استفسارات مفتوحة '+k.openMessages]].map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('')}
function renderRisk(){const rows=restaurants.slice().sort((a,b)=>(b.overdue+b.usage*100)-(a.overdue+a.usage*100)).slice(0,6);$('riskRestaurants').innerHTML=rows.map(r=>`<div class="risk-row"><div><strong>${esc(r.name)}</strong><small>${r.code} • مديونية ${KD(r.outstanding)} • متأخر ${KD(r.overdue)}</small></div>${badge(r.level,r.level==='safe'?'آمن':r.level==='warning'?'تنبيه':r.level==='risk'?'خطر':'موقوف')}</div>`).join('')}
function renderRestaurants(){const q=($('restaurantSearch')?.value||'').toLowerCase();const rows=restaurants.filter(r=>[r.name,r.code,r.phone,r.email].some(v=>String(v||'').toLowerCase().includes(q)));$('restaurantsBody').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.name)}</strong><br><small>${esc(r.code)} • ${esc(r.phone)}</small></td><td>${r.active?badge(r.level,r.level==='safe'?'نشط - آمن':r.level==='warning'?'تنبيه':r.level==='risk'?'خطر':'كريدت موقوف'):badge('locked','موقوف')}</td><td>${KD(r.creditLimit)}</td><td>${KD(r.outstanding)}</td><td>${KD(r.overdue)}</td><td>${KD(r.available)}</td><td>${r.users?.length||0}</td><td><div class="actions"><button data-view="${r.id}">فتح</button><button data-edit="${r.id}">تحرير</button><button data-user="${r.id}">مستخدم</button><button class="danger" data-disable="${r.id}">${r.active?'إيقاف':'موقوف'}</button></div></td></tr>`).join('');wireRows();}
function renderOrders(){const steps=['placed','confirmed','preparing','dispatched','delivered'];$('recentOrders').innerHTML=(dashboard.recentOrders||[]).slice(0,6).map(orderMini).join('');$('ordersGrid').innerHTML=(dashboard.recentOrders||[]).map(o=>`<article class="order-card"><h3>${o.number}</h3><div class="meta"><span>${restaurantName(o.restaurantId)}</span><span>${KD(o.total)}</span><span>${o.paymentMethod==='credit'?'كريدت':'دفع مباشر'}</span></div><p>الحالة: <strong>${statusLabel(o.status)}</strong></p><div class="tracking">${steps.map((s,i)=>`<i class="${steps.indexOf(o.status)>=i?'done':''}"></i>`).join('')}</div><div class="actions" style="margin-top:12px">${steps.slice(1).map(s=>`<button data-order="${o.id}" data-status="${s}">${statusLabel(s)}</button>`).join('')}</div></article>`).join('');document.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>updateOrder(b.dataset.order,b.dataset.status));}
function orderMini(o){return `<div class="risk-row"><div><strong>${o.number} — ${esc(restaurantName(o.restaurantId))}</strong><small>${KD(o.total)} • ${o.paymentMethod==='credit'?'كريدت':'مباشر'}</small></div>${badge(o.status==='delivered'?'safe':'warning',statusLabel(o.status))}</div>`}
function statusLabel(s){return({placed:'تم الاستلام',confirmed:'مؤكد',preparing:'قيد التجهيز',dispatched:'خرج للتوصيل',delivered:'تم التسليم',cancelled:'ملغي'})[s]||s}
function restaurantName(id){return restaurants.find(r=>r.id===id)?.name||id}
function renderCredit(){const total=restaurants.reduce((s,r)=>s+r.creditLimit,0),used=restaurants.reduce((s,r)=>s+r.outstanding,0),over=restaurants.reduce((s,r)=>s+r.overdue,0);$('creditSummary').innerHTML=[['إجمالي الحدود',KD(total)],['المستخدم',KD(used)],['المتاح',KD(total-used)],['المتأخر',KD(over)]].map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></article>`).join('');$('creditBody').innerHTML=restaurants.map(r=>`<tr><td>${esc(r.name)}</td><td>${KD(r.creditLimit)}</td><td>${KD(r.outstanding)}</td><td>${KD(r.available)}</td><td>${KD(r.overdue)}</td><td>${r.health}/100</td><td>${badge(r.level,r.level)}</td></tr>`).join('')}
function renderMessages(){const ms=dashboard.messages||[];$('openMessages').innerHTML=ms.slice(0,5).map(m=>`<div class="risk-row"><div><strong>${esc(restaurantName(m.restaurantId))}</strong><small>${esc(m.subject)} — ${esc(m.body)}</small></div>${badge('warning','مفتوح')}</div>`).join('')||'<p>لا توجد استفسارات مفتوحة</p>';$('messagesList').innerHTML=ms.map(m=>`<article class="message-card"><h3>${esc(m.subject)}</h3><div class="meta"><span>${esc(restaurantName(m.restaurantId))}</span><span>${new Date(m.createdAt).toLocaleString('ar-KW')}</span></div><p>${esc(m.body)}</p>${(m.replies||[]).map(x=>`<p><strong>${x.from}:</strong> ${esc(x.body)}</p>`).join('')}<div class="reply-box"><input id="reply-${m.id}" placeholder="اكتب الرد"><button data-reply="${m.id}">إرسال</button></div></article>`).join('');document.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>reply(b.dataset.reply));}
function renderAudit(){const list=dashboard.audit||[];$('auditList').innerHTML=list.length?list.map(a=>`<div class="audit-item"><small>${new Date(a.at).toLocaleString('ar-KW')}</small><strong>${esc(a.actor)}</strong><span>${esc(a.action)} — ${esc(a.target)}</span></div>`).join(''):'<p>لا توجد سجلات بعد.</p>'}
function renderAI(){const enabled=!$('aiStatus').classList.contains('off');$('aiInfo').innerHTML=`<p>${enabled?badge('safe','متصل ويعمل'):badge('warning','بانتظار تفعيل مفتاح OpenAI')}</p><p>المساعد الصوتي يستخدم اتصالاً لحظياً ويقرأ بيانات المطعم المصرح بها فقط. التحليلات المالية وقواعد الكريدت تستمر حتى عند توقف الذكاء الاصطناعي.</p>`}
function renderSettings(){$('settingsPanel').innerHTML='<h3>سياسات النظام</h3><div class="form-grid"><label>تنبيه الكريدت<input value="60%" disabled></label><label>الخطر<input value="80%" disabled></label><label>الإيقاف<input value="100%" disabled></label><label>مدة السداد الافتراضية<input value="30 يوم" disabled></label><div class="full"><p>يتم حفظ جميع تغييرات الإدارة في سجل التدقيق. الإيقاف يعطل الكريدت ولا يمنع الدفع المباشر.</p></div></div>'}
function wireRows(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>viewRestaurant(b.dataset.view));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRestaurant(b.dataset.edit));document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>addUser(b.dataset.user));document.querySelectorAll('[data-disable]').forEach(b=>b.onclick=()=>disableRestaurant(b.dataset.disable));}
function openModal(html){$('adminModalContent').innerHTML=html;$('adminModal').classList.add('open')}
function closeModal(){$('adminModal').classList.remove('open')}
function viewRestaurant(id){const r=restaurants.find(x=>x.id===id);if(!r)return;openModal(`<h2>${esc(r.name)}</h2><div class="kpis"><article class="kpi"><span>الحد</span><strong>${KD(r.creditLimit)}</strong></article><article class="kpi"><span>المديونية</span><strong>${KD(r.outstanding)}</strong></article><article class="kpi"><span>المتاح</span><strong>${KD(r.available)}</strong></article><article class="kpi"><span>الصحة</span><strong>${r.health}/100</strong></article></div><h3>بيانات المطعم</h3><p>${esc(r.legalName||'—')} • ${esc(r.phone)} • ${esc(r.email)} • ${esc(r.address)}</p><p>الفروع: ${(r.branches||[]).map(esc).join('، ')||'—'}</p><h3>المستخدمون</h3>${(r.users||[]).map(u=>`<div class="risk-row"><div><strong>${esc(u.name)}</strong><small>${esc(u.username)} • ${esc(u.role)}</small></div><div class="actions"><button data-edituser="${r.id}:${u.id}">تحرير</button><button class="danger" data-killuser="${r.id}:${u.id}">إيقاف</button></div></div>`).join('')||'<p>لا يوجد مستخدمون.</p>'}<h3>الطلبات</h3>${(r.orders||[]).map(orderMini).join('')||'<p>لا توجد طلبات.</p>'}<h3>الفواتير</h3>${(r.invoices||[]).map(i=>`<div class="risk-row"><div><strong>${i.number}</strong><small>${new Date(i.dueAt).toLocaleDateString('ar-KW')}</small></div><strong>${KD(i.amount-i.paid)}</strong></div>`).join('')||'<p>لا توجد فواتير.</p>'}`);document.querySelectorAll('[data-edituser]').forEach(b=>b.onclick=()=>editUser(...b.dataset.edituser.split(':')));document.querySelectorAll('[data-killuser]').forEach(b=>b.onclick=()=>disableUser(...b.dataset.killuser.split(':')));}
function restaurantForm(r={}){return `<h2>${r.id?'تحرير مطعم':'إضافة مطعم'}</h2><form id="restaurantForm" class="form-grid"><label>اسم المطعم<input name="name" value="${esc(r.name||'')}" required></label><label>الكود<input name="code" value="${esc(r.code||'')}"></label><label>الاسم القانوني<input name="legalName" value="${esc(r.legalName||'')}"></label><label>الهاتف<input name="phone" value="${esc(r.phone||'')}"></label><label>البريد<input name="email" value="${esc(r.email||'')}"></label><label>العنوان<input name="address" value="${esc(r.address||'')}"></label><label>حد الكريدت<input name="creditLimit" type="number" step="0.001" value="${r.creditLimit||0}"></label><label>المديونية<input name="outstanding" type="number" step="0.001" value="${r.outstanding||0}"></label><label>المتأخر<input name="overdue" type="number" step="0.001" value="${r.overdue||0}"></label><label>مدة السداد<input name="termsDays" type="number" value="${r.termsDays||30}"></label><label>ميزانية الشهر<input name="monthlyBudget" type="number" step="0.001" value="${r.monthlyBudget||0}"></label><label>الفروع مفصولة بفاصلة<input name="branches" value="${esc((r.branches||[]).join(','))}"></label><div class="full modal-actions"><button class="primary" type="submit">حفظ</button></div></form>`}
function editRestaurant(id){const r=restaurants.find(x=>x.id===id);openModal(restaurantForm(r));$('restaurantForm').onsubmit=e=>saveRestaurant(e,id)}
function addRestaurant(){openModal(restaurantForm());$('restaurantForm').onsubmit=e=>saveRestaurant(e)}
async function saveRestaurant(e,id){e.preventDefault();const fd=new FormData(e.currentTarget),b=Object.fromEntries(fd.entries());b.branches=String(b.branches||'').split(',').map(x=>x.trim()).filter(Boolean);['creditLimit','outstanding','overdue','termsDays','monthlyBudget'].forEach(k=>b[k]=Number(b[k]||0));await api(id?`/api/admin/restaurants/${id}`:'/api/admin/restaurants',{method:id?'PATCH':'POST',body:JSON.stringify(b)});closeModal();toast('تم حفظ بيانات المطعم');await load();}
function addUser(rid){openModal(`<h2>إضافة مستخدم للمطعم</h2><form id="userForm" class="form-grid"><label>الاسم<input name="name" required></label><label>اسم المستخدم<input name="username" required></label><label>كلمة المرور<input name="password" required></label><label>الصلاحية<select name="role"><option value="owner">مالك/مدير</option><option value="buyer">مشتريات</option><option value="finance">مالية</option><option value="branch">مدير فرع</option></select></label><div class="full"><button class="primary">إضافة المستخدم</button></div></form>`);$('userForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget).entries());await api(`/api/admin/restaurants/${rid}/users`,{method:'POST',body:JSON.stringify(b)});closeModal();toast('تمت إضافة المستخدم');await load();}}
function editUser(rid,uid){const r=restaurants.find(x=>x.id===rid),u=r?.users.find(x=>x.id===uid);if(!u)return;openModal(`<h2>تحرير المستخدم</h2><form id="editUserForm" class="form-grid"><label>الاسم<input name="name" value="${esc(u.name)}"></label><label>اسم المستخدم<input name="username" value="${esc(u.username)}"></label><label>كلمة مرور جديدة<input name="password" placeholder="اتركها فارغة بدون تغيير"></label><label>الصلاحية<select name="role"><option value="owner">مالك/مدير</option><option value="buyer">مشتريات</option><option value="finance">مالية</option><option value="branch">مدير فرع</option></select></label><div class="full"><button class="primary">حفظ</button></div></form>`);$('editUserForm').role.value=u.role;$('editUserForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.currentTarget).entries());if(!b.password)delete b.password;await api(`/api/admin/restaurants/${rid}/users/${uid}`,{method:'PATCH',body:JSON.stringify(b)});closeModal();toast('تم تعديل المستخدم');await load();}}
async function disableUser(rid,uid){await api(`/api/admin/restaurants/${rid}/users/${uid}`,{method:'DELETE'});closeModal();toast('تم إيقاف المستخدم');await load();}
async function disableRestaurant(id){await api(`/api/admin/restaurants/${id}`,{method:'DELETE'});toast('تم إيقاف المطعم');await load();}
async function updateOrder(id,status){await api(`/api/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})});toast('تم تحديث حالة الطلب');await load();}
async function reply(id){const input=$(`reply-${id}`);if(!input.value.trim())return;await api(`/api/messages/${id}/reply`,{method:'POST',body:JSON.stringify({body:input.value.trim()})});toast('تم إرسال الرد');await load();}
$('adminNav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)page(b.dataset.page)};document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>page(b.dataset.jump));$('refreshAdmin').onclick=load;$('adminLogout').onclick=()=>{sessionStorage.removeItem('tamweenatAdminToken');location.replace('./admin-login.html')};$('closeAdminModal').onclick=closeModal;$('adminModal').onclick=e=>{if(e.target.id==='adminModal')closeModal()};$('addRestaurant').onclick=addRestaurant;$('restaurantSearch').oninput=renderRestaurants;
load();
})();