/* Evidence-first local analysis. No LLM calls, semantic claims, or invented outcomes. */
function normalizeArabic(s){return String(s||'').normalize('NFKC').replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').toLowerCase()}
function analysisTokens(s){const stop=new Set(['من','في','على','الي','الى','عن','ان','هو','هي','هذا','هذه','ذلك','التي','الذي','مع','ما','او','و','ثم','تم','كل','كان','كما','لا','the','and','of','to','in','a']);return [...new Set((normalizeArabic(s).match(/[\p{L}\p{N}]{2,}/gu)||[]).filter(w=>!stop.has(w)))]}
function documentQuality(pages){const words=pages.reduce((n,p)=>n+(p.text.match(/[\p{L}\p{N}]+/gu)||[]).length,0),empty=pages.filter(p=>p.text.trim().length<30).length;return {pageCount:pages.length,words,emptyPages:empty,needsOcr:words<30||empty/Math.max(1,pages.length)>.4,usable:words>=30}}
function retrieveEvidence(pages,question,limit=5){const query=analysisTokens(question);if(!query.length)return [];return pages.map(p=>{const normalized=normalizeArabic(p.text),matched=query.filter(t=>normalized.includes(t));if(!matched.length)return null;const pos=normalized.indexOf(matched[0]);let start=Math.max(0,pos-80),end=Math.min(p.text.length,start+500);return {page:p.number,text:p.text.slice(start,end),matched,score:matched.length/query.length}}).filter(Boolean).sort((a,b)=>b.score-a.score||a.page-b.page).slice(0,limit)}
function extractObjectives(pages){const found=[];const pattern=/(?:ناتج|نواتج|اهداف|هدف|ان\s+ي(?:حدد|شرح|قارن|حلل|طبق|كتب|قرا|صنف|ستنتج|تعرف|رسم)|يتوقع\s+من)/;for(const p of pages){const lines=p.text.split(/\n|[.!؟؛]/).map(s=>s.trim()).filter(Boolean);for(const line of lines)if(line.length>=12&&pattern.test(normalizeArabic(line)))found.push({page:p.number,text:line.slice(0,400),needsReview:true});if(found.length>=12)break}return found.slice(0,12)}
function reviewTeacherRecord(kind,r,allTasks=[]){const issues=[],checks=[];const add=(ok,yes,no)=>{checks.push({ok,message:ok?yes:no});if(!ok)issues.push(no)};if(['workplans','projects','lessons'].includes(kind)){add(Boolean(r.goal?.trim()),'يوجد هدف مكتوب','أضف هدفًا أو ناتج تعلم واضحًا');if(r.goal)add(/(?:يحدد|يشرح|يقارن|يحلل|يطبق|يكتب|يقرأ|يصنف|يستنتج|يرسم|ينفذ|يلخص|يقيس|يحل|تحديد|شرح|مقارنة|تحليل|تطبيق|تصميم|قياس)/.test(r.goal),'يحتوي الهدف على فعل يمكن متابعته','راجع قابلية قياس الهدف؛ لم يُرصد فعل واضح في النص')}add(Boolean(r.date),'يوجد موعد محدد','حدد موعد التنفيذ أو المراجعة');if(kind==='projects'){add(Boolean(r.owner),'يوجد مسؤول للمشروع','حدد المسؤول عن المشروع');add(allTasks.some(t=>t.project===r.id),'توجد مهام مرتبطة بالمشروع','حوّل المشروع إلى مهام مرتبطة بمسؤول وموعد')}if(kind==='workplans')add(Boolean(r.steps),'خطوات التنفيذ مدونة','أضف خطوات التنفيذ والموارد');if(kind==='lessons'){add(Boolean(r.grade),'الصف محدد','حدد الصف أو الشعبة');add(Boolean(r.steps),'خطوات الحصة مدونة','أضف خطوات الحصة');add(Boolean(r.assessment),'التقويم مدون','حدد طريقة التحقق من ناتج التعلم');add(Boolean(r.materials),'الوسائل مدونة','حدد الوسائل والمراجع')}if(kind==='meetings'){add(Boolean(r.agenda),'جدول الأعمال موجود','أضف جدول أعمال');if(r.state==='عُقد'){add(Boolean(r.minutes),'المحضر مدون','دوّن محضر الاجتماع');add(Boolean(r.decisions),'القرارات مدونة','دوّن القرارات أو اذكر عدم صدور قرارات')}}return {checks,issues,scope:'قواعد اكتمال النص والحقول، وليست تقييمًا تربويًا نهائيًا'}}
function runAnalysis({document:doc,question='',record=null,kind='',tasks=[]}){const trace=['تحديد نوع المدخل','اختيار المصدر','استخراج الشواهد','مراجعة الاكتمال','بوابة الجودة'];const quality=doc?documentQuality(doc.pages):null;if(doc&&!quality.usable)return {blocked:true,reason:'النص المستخرج غير كافٍ؛ يحتاج الملف إلى OCR أو نسخة نصية.',trace,quality};const evidence=doc&&question?retrieveEvidence(doc.pages,question):[],objectives=doc?extractObjectives(doc.pages):[],review=record?reviewTeacherRecord(kind,record,tasks):null;return {blocked:false,trace,quality,evidence,objectives,review,source:doc?{title:doc.title,edition:doc.edition||'غير مؤكدة',sha256:doc.sha256,sourceUrl:doc.sourceUrl,linkStatus:doc.sourceId?'ربط أكدّه المستخدم؛ لم يُطابق الملف مع بصمة من الوزارة':'مستند أضافه المستخدم'}:null,method:'تحليل قواعدي واسترجاع لفظي من النص. لا توجد إجابات مولدة بنموذج ذكاء اصطناعي.'}}
window.ManhajAnalysis={normalizeArabic,analysisTokens,documentQuality,retrieveEvidence,extractObjectives,reviewTeacherRecord,runAnalysis};
