const {JSDOM,VirtualConsole}=require('/tmp/manhaj-dom/node_modules/jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync('manhaj/index.html','utf8'),{url:'https://q8-ux.github.io/saad/manhaj/',runScripts:'dangerously',virtualConsole:console,beforeParse(w){w.MANHAJ_ASSISTANT_THINK_MS=1;w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('manhaj/data/curricula.json','utf8'))});w.indexedDB=require('/tmp/manhaj-dom/node_modules/fake-indexeddb').indexedDB;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.HTMLCanvasElement.prototype.toDataURL=()=>'';w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.spoken=[];w.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};w.speechSynthesis={cancel(){},getVoices(){return[]},speak(utterance){w.spoken.push(utterance.text)}};w.SpeechRecognition=class{start(){w.testRecognition=this;this.onstart?.()}stop(){this.onend?.()}abort(){this.onend?.()}};}});
(async()=>{const w=dom.window,d=w.document;await w.ManhajCurriculum.ready;await new Promise(r=>setTimeout(r,0));
assert.equal(errors.length,0,errors.join('\n'));assert.equal(d.querySelector('#homeView').hidden,false);assert.ok(d.documentElement.classList.contains('storefront'));d.querySelector('[data-go="analysis"]').click();assert.equal(d.querySelector('#analysisView').hidden,false);
d.querySelector('#teacherLauncher').click();assert.equal(d.querySelector('#teacherAssistant').hidden,false);
const firstCount=d.querySelectorAll('.teacher-message').length;d.querySelector('#teacherClose').click();assert.equal(d.querySelector('#analysisView').hidden,false);d.querySelector('#teacherLauncher').click();assert.equal(d.querySelectorAll('.teacher-message').length,firstCount);
assert.equal(d.querySelector('#teacherChat .field-language-tools'),null);d.querySelector('#teacherMic').click();assert.equal(d.querySelector('#teacherMic').getAttribute('aria-pressed'),'true');assert.equal(w.testRecognition.continuous,true);const spokenPart=[[{transcript:'مشروع جديد'}]];spokenPart[0].isFinal=true;w.testRecognition.onresult({resultIndex:0,results:spokenPart});assert.equal(d.querySelector('#teacherInput').value,'مشروع جديد');assert.equal(d.querySelectorAll('.teacher-user').length,0);d.querySelector('#teacherMic').click();assert.equal(d.querySelector('#teacherMic').getAttribute('aria-pressed'),'false');d.querySelector('#teacherInput').value='';
async function send(s){d.querySelector('#teacherInput').value=s;d.querySelector('#teacherChat').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(d.querySelector('#teacherAssistant').getAttribute('aria-busy'),'true');assert.equal(d.querySelector('#teacherThinking').hidden,false);await new Promise(r=>setTimeout(r,8));assert.equal(d.querySelector('#teacherAssistant').getAttribute('aria-busy'),'false')}
await send('مشروع جديد');for(const value of ['مشروع اختبار','2026-10-25','معلم الاختبار','يقارن طرق التدريس','لم يبدأ'])await send(value);assert.ok(w.spoken.some(text=>text.includes('اسم المشروع')));
let stored=()=>JSON.parse(w.localStorage.getItem('manhaj-v1')||'{"hub":{"projects":[]}}');assert.equal(stored().hub.projects.length,0);
const approve=[...d.querySelectorAll('#teacherMessages button')].find(b=>b.textContent==='اعتماد وحفظ السجل');assert.ok(approve);approve.click();assert.equal(stored().hub.projects.length,1);approve.click();assert.equal(stored().hub.projects.length,1);
assert.ok(d.querySelector('#catalogCount').textContent.includes('سجل'));assert.equal(errors.length,0,errors.join('\n'));const field=d.querySelector('#projects_goal');field.value='بناءا على  نتائج التقويم';const tools=field.nextElementSibling;assert.ok(tools.classList.contains('field-language-tools'));assert.equal(Boolean(d.querySelector('#docFile').nextElementSibling?.classList.contains('field-language-tools')),false);[...tools.querySelectorAll('button')].find(b=>b.textContent==='مراجعة اللغة').click();assert.equal(field.value,'بناءا على  نتائج التقويم');assert.equal(d.querySelector('#languageDraft').value,'بناءً على نتائج التقويم');d.querySelector('#languageApply').click();assert.equal(field.value,'بناءً على نتائج التقويم');[...tools.querySelectorAll('button')].find(b=>b.textContent==='تراجع').click();assert.equal(field.value,'بناءا على  نتائج التقويم');tools.querySelector('.field-mic').click();w.testRecognition.onresult({results:[[{transcript:'وتحسين التحصيل'}]]});w.testRecognition.onend();assert.equal(field.value,'بناءا على  نتائج التقويم');assert.ok(d.querySelector('#languageDraft').value.includes('وتحسين التحصيل'));d.querySelector('#languageApply').click();assert.ok(field.value.includes('وتحسين التحصيل'));assert.equal(stored().hub.projects[0].goal,'يقارن طرق التدريس');
const day=d.querySelector('#projects_date');day.nextElementSibling.querySelector('.field-mic').click();w.testRecognition.onresult({results:[[{transcript:'٢٠٢٦-١٠-٢٥'}]]});w.testRecognition.onend();d.querySelector('#languageApply').click();assert.equal(day.value,'2026-10-25');
[...tools.querySelectorAll('button')].find(b=>b.textContent==='مراجعة اللغة').click();field.value='تعديل أحدث';d.querySelector('#languageApply').click();assert.equal(field.value,'تعديل أحدث');assert.ok(d.querySelector('#languageStatus').textContent.includes('تغيّر'));d.querySelector('#languageEditor').close();
const kind=d.querySelector('#analysisKind');const oldKind=kind.value;kind.nextElementSibling.querySelector('.field-mic').click();w.testRecognition.onresult({results:[[{transcript:'خطة'}]]});w.testRecognition.onend();assert.equal(kind.value,oldKind);assert.equal(d.querySelector('#languageSelect').value,'workplans');assert.equal(d.querySelector('#languageDraft').hidden,true);d.querySelector('#languageApply').click();assert.equal(kind.value,'workplans');
const count=d.querySelectorAll('.field-language-tools').length;w.ManhajLanguage.enhance(d);assert.equal(d.querySelectorAll('.field-language-tools').length,count);assert.equal(errors.length,0,errors.join('\n'));
const id='a'.repeat(64),fixture={id,title:'مستند تجريبي أصلي',subject:'العلوم',grade:'السادس',term:'الأول',edition:'تجريبية',sourceId:'',sourceUrl:'',sha256:id,fileName:'teacher-own-notes.txt',uploadedAt:new Date().toISOString(),pages:[{number:1,text:'الهدف أن يقارن المعلم طرق التدريس في الحصة.'},{number:2,text:'التقويم يعتمد ملاحظة تنفيذ النشاط وتوثيق نتائج العمل.'}],quality:{words:40,needsOcr:false}};
await new Promise((resolve,reject)=>{const req=w.indexedDB.open('manhaj-curriculum-analysis',1);req.onsuccess=()=>{const db=req.result,t=db.transaction('documents','readwrite');t.objectStore('documents').put(fixture);t.oncomplete=()=>{db.close();resolve()};t.onerror=()=>reject(t.error)}});await w.ManhajCurriculum.refresh();assert.ok(d.querySelector('[data-read-document]'));await w.ManhajReader.open(id);assert.equal(d.querySelector('#readerView').hidden,false);assert.ok(d.querySelector('#readerText').textContent.includes('يقارن'));d.querySelector('#readerNext').click();assert.ok(d.querySelector('#readerText').textContent.includes('التقويم'));d.querySelector('#readerQuestion').value='يقارن';d.querySelector('#readerSearch').click();d.querySelector('[data-reader-page]').click();assert.equal(d.querySelector('#readerPage').value,'1');d.querySelector('#readerLesson').click();assert.equal(d.querySelector('#lessonsView').hidden,false);assert.ok(d.querySelector('#lessons_materials').value.includes('صفحة 1'));assert.ok(d.querySelector('#lessons_goal').value.includes('يقارن'));assert.equal(stored().hub.lessons.length,0);await w.ManhajReader.open(id);d.querySelector('#readerPlan').click();assert.ok(d.querySelector('#workplans_steps').value.includes('صفحة 1'));assert.equal(stored().hub.workplans.length,0);
const snapshot=w.localStorage.getItem('manhaj-v1');w.location.hash='home';await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#homeView').hidden,false);assert.ok(d.documentElement.classList.contains('storefront'));assert.equal(d.querySelectorAll('.store-product').length,13);const saveButton=d.querySelector('[data-store-save="weekly"]');saveButton.click();assert.ok(w.localStorage.getItem('manhaj-template-favorites').includes('weekly'));d.querySelector('#storeSavedFilter').click();assert.equal(d.querySelectorAll('.store-product').length,1);d.querySelector('[data-store-preview="weekly"]').click();assert.ok(d.querySelector('#storePreviewContent').textContent.includes('الأعمال ذات الأولوية'));d.querySelector('#storePreviewUse').click();assert.equal(d.querySelector('#workplans_name').value,'خطة عمل أسبوعية');assert.equal(d.querySelector('#workplansView').hidden,false);assert.equal(d.documentElement.classList.contains('storefront'),false);assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);w.ManhajStorefront.browse('all');d.querySelector('#storeSearch').value='محضر';d.querySelector('#storeSearch').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelectorAll('.store-product').length,1);for(const k of ['dashboard','projects','workplans','meetings','tasks','lessons','schedule','plans','events','studio','library','resources','evidence','reports','settings','analysis','reader']){assert.ok(d.querySelector('#'+k+'View'));assert.ok(d.querySelector('#nav [data-go="'+k+'"]'))}assert.equal(errors.length,0,errors.join('\n'));
const uniqueSections=new Set();
for(const [id,tool] of [['planning','workplans'],['teacher','lessons'],['administration','meetings'],['activities','projects'],['occasions','projects'],['design','studio']]){
 d.querySelector('#homeView [data-store-category="'+id+'"]').click();
 assert.equal(w.location.hash,'#category-'+id);const view=d.querySelector('#category-'+id+'View');assert.equal(view.hidden,false);assert.equal(d.querySelector('#homeView').hidden,true);assert.equal(d.querySelectorAll('.view:not([hidden])').length,1);
 uniqueSections.add(view.querySelector('.store-category-intro p').textContent);
 const expected=w.ManhajStorefront.products.filter(p=>p.category===id);assert.equal(view.querySelectorAll('.store-product').length,expected.length);assert.deepEqual([...view.querySelectorAll('[data-store-use]')].map(b=>b.dataset.storeUse),Array.from(expected,p=>p.id));assert.ok(view.querySelector('.store-how').textContent.trim());
 view.querySelector('[data-store-preview]').click();assert.equal(d.querySelector('#storePreviewTitle').textContent,expected[0].title);d.querySelector('#storePreview').close();
 view.querySelector('.store-category-intro [data-go]').click();assert.equal(w.location.hash,'#'+tool);assert.equal(d.querySelector('#'+tool+'View').hidden,false);assert.equal(d.documentElement.classList.contains('storefront'),false);
}
assert.equal(uniqueSections.size,6);assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);
w.location.hash='category-administration';await new Promise(r=>setTimeout(r,0));assert.equal(d.querySelector('#category-administrationView').hidden,false);assert.ok(d.documentElement.classList.contains('storefront'));
for(const k of ['dashboard','projects','workplans','meetings','tasks','lessons','schedule','plans','events','studio','library','resources','evidence','reports','settings','analysis','reader']){d.querySelector('#nav [data-go="'+k+'"]').click();assert.equal(d.querySelector('#'+k+'View').hidden,false,k);assert.equal(d.querySelectorAll('.view:not([hidden])').length,1,k);assert.equal(d.documentElement.classList.contains('storefront'),false,k)}
assert.equal([...d.querySelectorAll('a[href]')].filter(a=>{const h=new URL(a.href).hostname;return h==='github.com'||h.endsWith('.github.com')}).length,0);assert.equal(w.eval("canOpenResource('https://github.com/robbietilton/Compositor')"),false);assert.equal(w.eval("canOpenResource('https://gist.github.com/example')"),false);assert.equal(w.eval("canOpenResource('https://elibrary.moe.edu.kw/StudentsLibrary')"),true);for(const id of w.ManhajChoices.fields){assert.equal(d.getElementById(id).tagName,'SELECT',id);assert.ok(d.getElementById(id).querySelector('[data-custom-choice]'),id);assert.ok(d.getElementById(id+'Custom'),id);assert.ok(d.getElementById(id).nextElementSibling.querySelector('.field-mic'),id)}
const subjectChoice=d.getElementById('lessons_subject');subjectChoice.value='مادة مخصصة قديمة';assert.equal(subjectChoice.value,'مادة مخصصة قديمة');subjectChoice.value='العلوم';assert.equal(subjectChoice.value,'العلوم');const customOption=subjectChoice.querySelector('[data-custom-choice]');customOption.selected=true;subjectChoice.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.getElementById('lessons_subjectCustom').parentElement.hidden,false);const customField=d.getElementById('lessons_subjectCustom');customField.value='التعلم الرقمي';customField.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(subjectChoice.value,'التعلم الرقمي');subjectChoice.form.reset();await new Promise(r=>setTimeout(r,0));assert.equal(customField.parentElement.hidden,true);assert.equal(subjectChoice.value,'');assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);
assert.ok(d.documentElement.classList.contains('sahel'));d.querySelector('#appTabs [data-go="home"]').click();assert.equal(d.querySelectorAll('#serviceList .sahel-service').length,12);assert.equal(d.querySelector('#appScreenTitle').textContent,'الخدمات');if(!d.querySelector('#storeCatalog').hidden)d.querySelector('#showModels').click();assert.equal(d.querySelector('#storeCatalog').hidden,true);d.querySelector('#showModels').click();assert.equal(d.querySelector('#storeCatalog').hidden,false);assert.ok(d.querySelector('#storeSearch').nextElementSibling.querySelector('.field-mic'));d.querySelector('#serviceSearch').value='محاضر';d.querySelector('#serviceSearch').dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(d.querySelectorAll('#serviceList .sahel-service').length,1);d.querySelector('#serviceList .sahel-service').click();assert.equal(w.location.hash,'#category-administration');assert.equal(d.querySelector('#appScreenTitle').textContent,'الإدارة والاجتماعات');assert.equal(d.querySelector('#homeView').hidden,true);for(const k of ['dashboard','home','tasks','schedule','settings']){d.querySelector('#appTabs [data-go="'+k+'"]').click();assert.equal(d.querySelector('#'+k+'View').hidden,false);assert.equal(d.querySelectorAll('#appTabs [aria-current="page"]').length,1)}d.querySelector('#appMenu').click();assert.equal(d.querySelector('#sidebar').classList.contains('open'),true);d.querySelector('#appMenu').click();assert.equal(d.querySelector('#sidebar').classList.contains('open'),false);assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);
const metadata=JSON.parse(fs.readFileSync('manhaj/data/curricula.json','utf8'));assert.equal(d.querySelectorAll('#curriculumCoverage tr').length,new Set(metadata.records.map(r=>r.stage)).size);assert.ok(d.querySelector('#curriculumAuditLimit').textContent.includes('لم نتحقق'));assert.equal(d.querySelectorAll('#standardRecords article').length,metadata.audit.standardsCount);d.querySelector('#standardSearch').value='القرآن';d.querySelector('#standardSearch').dispatchEvent(new w.Event('input',{bubbles:true}));assert.ok(d.querySelectorAll('#standardRecords article').length>0);for(const node of d.querySelectorAll('#standardRecords article'))assert.ok(node.textContent.includes('القرآن'));assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);
assert.equal(d.querySelector('#homeView').firstElementChild.id,'teamsConnectCard');d.querySelector('#teamsConnectCard').click();assert.equal(d.querySelector('#teamsConnectDialog').open,true);d.querySelector('#teamsConnectDone').click();assert.equal(d.querySelector('#teamsConnectDialog').open,false);for(const k of w.ManhajTeamsExport.sections)assert.ok(d.querySelector('#'+k+'View [data-teams-export="'+k+'"]'));w.ManhajTeamsExport.open('projects');assert.equal(d.querySelector('#teamsExportDialog').open,true);assert.ok(d.querySelector('#teamsExportBody').value.includes('يقارن طرق التدريس'));assert.equal(d.querySelector('#teamsExportBody').value.includes('معلم الاختبار'),false);assert.ok(d.querySelector('#teamsExportDialog button[disabled]'));assert.equal(w.localStorage.getItem('manhaj-v1'),snapshot);d.querySelector('#teamsExportClose').click();assert.equal(d.querySelector('#teamsExportDialog').open,false);
await w.eval("renderEvidence()");await new Promise(r=>setTimeout(r,50));assert.equal(errors.length,0,errors.join('\n'));
process.stdout.write('Full DOM: initial analysis route, assistant reopen, close isolation, preview and explicit save, duplicate prevention, catalogue refresh, voice review, language preview/apply/undo and no automatic save, local reader pagination/search and sourced lesson/plan drafts, storefront previews/favorites/search, six distinct category routes/content/cards/actions, direct hash navigation all workspace routes/data and dropdown custom/saved values/reset, service search, app tabs and menu: PASS\n');dom.window.close();})().catch(e=>{process.stderr.write(e.stack);dom.window.close();process.exitCode=1});
