const {JSDOM,VirtualConsole}=require('/tmp/manhaj-dom/node_modules/jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const errors=[];const console=new VirtualConsole();console.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync('manhaj/index.html','utf8'),{url:'https://q8-ux.github.io/saad/manhaj/#analysis',runScripts:'dangerously',virtualConsole:console,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('manhaj/data/curricula.json','utf8'))});w.indexedDB=require('/tmp/manhaj-dom/node_modules/fake-indexeddb').indexedDB;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.HTMLCanvasElement.prototype.toDataURL=()=>'';w.confirm=()=>true;w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.SpeechRecognition=class{start(){w.testRecognition=this}stop(){this.onend?.()}abort(){this.onend?.()}};}});
(async()=>{const w=dom.window,d=w.document;await w.ManhajCurriculum.ready;await new Promise(r=>setTimeout(r,0));
assert.equal(errors.length,0,errors.join('\n'));assert.equal(d.querySelector('#analysisView').hidden,false);
d.querySelector('#teacherLauncher').click();assert.equal(d.querySelector('#teacherAssistant').hidden,false);
const firstCount=d.querySelectorAll('.teacher-message').length;d.querySelector('#teacherClose').click();assert.equal(d.querySelector('#analysisView').hidden,false);d.querySelector('#teacherLauncher').click();assert.equal(d.querySelectorAll('.teacher-message').length,firstCount);
function send(s){d.querySelector('#teacherInput').value=s;d.querySelector('#teacherChat').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))}
send('مشروع جديد');for(const value of ['مشروع اختبار','2026-10-25','معلم الاختبار','يقارن طرق التدريس','لم يبدأ'])send(value);
let stored=()=>JSON.parse(w.localStorage.getItem('manhaj-v1')||'{"hub":{"projects":[]}}');assert.equal(stored().hub.projects.length,0);
const approve=[...d.querySelectorAll('#teacherMessages button')].find(b=>b.textContent==='اعتماد وحفظ السجل');assert.ok(approve);approve.click();assert.equal(stored().hub.projects.length,1);approve.click();assert.equal(stored().hub.projects.length,1);
assert.ok(d.querySelector('#catalogCount').textContent.includes('سجل'));assert.equal(errors.length,0,errors.join('\n'));const field=d.querySelector('#projects_goal');field.value='بناءا على  نتائج التقويم';const tools=field.nextElementSibling;assert.ok(tools.classList.contains('field-language-tools'));assert.equal(Boolean(d.querySelector('#docFile').nextElementSibling?.classList.contains('field-language-tools')),false);[...tools.querySelectorAll('button')].find(b=>b.textContent==='مراجعة اللغة').click();assert.equal(field.value,'بناءا على  نتائج التقويم');assert.equal(d.querySelector('#languageDraft').value,'بناءً على نتائج التقويم');d.querySelector('#languageApply').click();assert.equal(field.value,'بناءً على نتائج التقويم');[...tools.querySelectorAll('button')].find(b=>b.textContent==='تراجع').click();assert.equal(field.value,'بناءا على  نتائج التقويم');tools.querySelector('.field-mic').click();w.testRecognition.onresult({results:[[{transcript:'وتحسين التحصيل'}]]});w.testRecognition.onend();assert.equal(field.value,'بناءا على  نتائج التقويم');assert.ok(d.querySelector('#languageDraft').value.includes('وتحسين التحصيل'));d.querySelector('#languageApply').click();assert.ok(field.value.includes('وتحسين التحصيل'));assert.equal(stored().hub.projects[0].goal,'يقارن طرق التدريس');
const day=d.querySelector('#projects_date');day.nextElementSibling.querySelector('.field-mic').click();w.testRecognition.onresult({results:[[{transcript:'٢٠٢٦-١٠-٢٥'}]]});w.testRecognition.onend();d.querySelector('#languageApply').click();assert.equal(day.value,'2026-10-25');
[...tools.querySelectorAll('button')].find(b=>b.textContent==='مراجعة اللغة').click();field.value='تعديل أحدث';d.querySelector('#languageApply').click();assert.equal(field.value,'تعديل أحدث');assert.ok(d.querySelector('#languageStatus').textContent.includes('تغيّر'));d.querySelector('#languageEditor').close();
const count=d.querySelectorAll('.field-language-tools').length;w.ManhajLanguage.enhance(d);assert.equal(d.querySelectorAll('.field-language-tools').length,count);assert.equal(errors.length,0,errors.join('\n'));
process.stdout.write('Full DOM: initial analysis route, assistant reopen, close isolation, preview and explicit save, duplicate prevention, catalogue refresh, voice review, language preview/apply/undo and no automatic save: PASS\n');dom.window.close();})().catch(e=>{process.stderr.write(e.stack);dom.window.close();process.exitCode=1});
