/* Run with Node 24+: npm install --prefix <temp> jsdom fake-indexeddb jsqr
   NODE_PATH=<temp>/node_modules node manhaj/activity-check.cjs */
const fs=require('node:fs'),assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom'),jsQR=require('jsqr'),C=require('./activity-core.js');
const html=fs.readFileSync('manhaj/index.html','utf8');
const hub=()=>({projects:[],workplans:[],meetings:[],tasks:[],lessons:[],resources:[]});
const slot=(a,overrides={})=>({id:C.uid(),stage:'early',day:0,period:1,teacherId:a.teachers[0]?.id||'',grade:'الأول',group:'أ',title:'نشاط',goal:'تعلم عملي',domain:C.domains[0],state:'planned',receipt:false,due:'',minutes:45,...overrides});
let a=C.empty();assert.ok(C.valid(a));assert.ok(C.valid(undefined));assert.equal(C.metrics(a,'early').capacity,30);a.profiles.early.students=451;assert.equal(C.metrics(a,'early').targetStudents,46);assert.equal(C.metrics(a,'early').targetSessions,3);
let preview=C.previewImport('الاسم,المادة,النصاب\nأحمد,العلوم,8\nأحمد,العلوم,8\nفاطمة,اللغة العربية,6',a,'early');assert.equal(preview.rows.length,2);assert.equal(preview.duplicates,1);a=C.applyImport(a,preview);assert.equal(a.teachers.length,2);
preview=C.previewImport('احمد,العلوم,30',a,'middle');assert.equal(preview.linked,1);a=C.applyImport(a,preview);assert.equal(a.teachers.length,2);assert.equal(a.teachers[0].load,8);assert.ok(a.teachers[0].stages.includes('middle'));
assert.throws(()=>C.previewImport('"غير مكتمل',a,'early'));assert.ok(C.previewImport('معلم,العلوم,-2',a,'early').errors.length);assert.ok(C.previewImport('معلم,العلوم,١٢',a,'early').rows[0].load===12);assert.equal(C.previewImport('أمل - العلوم\nزيد\tالعربية\t4',a,'early').rows.length,2);
a.slots.push(slot(a,{minutes:40}));a.slots.push(slot(a,{period:2,minutes:55}));assert.ok(C.valid(a));assert.deepEqual([C.metrics(a,'early').hours,C.metrics(a,'early').minuteRemainder],[1,35]);assert.equal(C.assignment(a,a.teachers[0].id).slots.length,2);
assert.equal(C.conflicts(a,slot(a,{stage:'middle',grade:'السادس'})).length,1);a.slots.push(slot(a,{stage:'middle',grade:'السادس'}));assert.ok(C.alerts(a,'middle').some(x=>x.type==='conflict'));a.slots.pop();
const generated=C.autoFill(a,'early');assert.equal(generated.created.length,12);assert.equal(generated.next.slots.length,14);assert.deepEqual(generated.next.slots.slice(0,2),a.slots);assert.equal(C.countTeacher(generated.next,a.teachers[0].id),8);assert.equal(C.countTeacher(generated.next,a.teachers[1].id),6);assert.equal(C.metrics(generated.next,'early').remaining,16);assert.ok(C.valid(generated.next));
let full=C.empty();full.teachers=[{id:'t',name:'معلم كامل',subject:'العلوم',load:30,stages:['early']}];full=C.autoFill(full,'early').next;assert.equal(full.slots.length,30);assert.equal(C.metrics(full,'early').remaining,0);assert.equal(C.autoFill(full,'early').created.length,0);assert.equal(C.metrics(full,'early').minutes,1350);assert.equal(C.metrics(full,'early').hours,22);assert.equal(C.metrics(full,'early').minuteRemainder,30);
let bad=structuredClone(full);bad.slots.push({...bad.slots[0],id:'duplicate'});assert.equal(C.valid(bad),false);bad=structuredClone(full);bad.profiles.early.periods=5;assert.equal(C.valid(bad),false);bad=structuredClone(full);bad.slots[0].due='2026-02-31';assert.equal(C.valid(bad),false);bad=structuredClone(full);bad.teachers.push({...bad.teachers[0],id:'another'});assert.equal(C.valid(bad),false);
assert.equal(C.tone({...full.slots[0],due:'2020-01-01'},'2026-10-11'),'red');assert.equal(C.tone({...full.slots[0],receipt:true},'2026-10-11'),'green');assert.equal(C.tone({...full.slots[0],state:'active'},'2026-10-11'),'amber');assert.equal(C.tone({...full.slots[0],state:'done'},'2026-10-11'),'green');
function boot(url='https://q8-ux.github.io/saad/manhaj/#activity',saved){const errors=[],vc=new VirtualConsole;vc.on('jsdomError',e=>errors.push(e.message));const dom=new JSDOM(html,{url,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.indexedDB=require('fake-indexeddb').indexedDB;w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.fetch=async()=>({ok:true,json:async()=>JSON.parse(fs.readFileSync('manhaj/data/curricula.json','utf8'))});w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{}});w.HTMLCanvasElement.prototype.toDataURL=()=>'';w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.confirm=()=>true;w.print=()=>{w.printCalls=(w.printCalls||0)+1};w.MANHAJ_ASSISTANT_THINK_MS=1;if(saved)w.localStorage.setItem('manhaj-v1',JSON.stringify(saved));}});return {dom,w:dom.window,d:dom.window.document,errors}}
const pause=()=>new Promise(r=>setTimeout(r,60));
(async()=>{
 const legacy={plan:{school:'مدرسة قديمة'},events:[],hub:hub()};legacy.hub.projects.push({id:'legacy',name:'مشروع سابق',date:'2026-10-20',owner:'معلم',goal:'هدف',state:'لم يبدأ'});
 const b=boot(undefined,legacy),{w,d,dom,errors}=b;const $=id=>d.getElementById(id),click=q=>d.querySelector(q).click(),submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true})),set=(id,value)=>{$(id).value=String(value);$(id).dispatchEvent(new w.Event('input',{bubbles:true}))},stored=()=>JSON.parse(w.localStorage.getItem('manhaj-v1'));
 await w.ManhajCurriculum.ready;await pause();assert.deepEqual(errors,[]);assert.equal($('activityView').hidden,false);assert.ok($('nav').textContent.includes('المراحل والحصص والتكليفات'));assert.ok($('serviceList').querySelector('[data-go="activity"]'));assert.equal(stored().hub.projects[0].id,'legacy');
 set('actSchool','مدرسة أولية');w.confirm=()=>false;click('[data-act-stage="middle"]');assert.equal($('actSchool').value,'مدرسة أولية');assert.equal(d.querySelector('[data-act-stage="early"]').getAttribute('aria-pressed'),'true');w.confirm=()=>true;set('actNumber','12345');set('actStudents',400);submit('actProfileForm');assert.equal(stored().activity.profiles.early.students,400);assert.equal(stored().plan.school,'مدرسة قديمة');assert.ok($('actMetrics').textContent.includes('40 طالبًا'));
 click('[data-act-stage="middle"]');assert.equal($('actSchool').value,'');set('actSchool','متوسطة مستقلة');set('actStudents',700);submit('actProfileForm');click('[data-act-stage="early"]');assert.equal($('actSchool').value,'مدرسة أولية');assert.equal(stored().activity.profiles.middle.school,'متوسطة مستقلة');
 click('[data-act-tab="teachers"]');set('actImportText','الاسم,المادة,النصاب\nالمعلم الخاص,العلوم,12\nالمعلمة الخاصة,الرياضيات,18\nالمعلم الخاص,العلوم,12');$('actImportPreview').click();assert.equal(stored().activity.teachers.length,0);assert.equal($('actImportApply').disabled,false);$('actImportApply').click();assert.equal(stored().activity.teachers.length,2);const tid=stored().activity.teachers[0].id;
 click('[data-act-stage="middle"]');set('actImportText','المعلم الخاص,العلوم,30');$('actImportPreview').click();$('actImportApply').click();assert.equal(stored().activity.teachers.length,2);assert.equal(stored().activity.teachers[0].load,12);click('[data-act-stage="early"]');
 click('[data-act-tab="timetable"]');set('actTitle','بطاقة عامة');set('actGoal','اكتشاف دورة الماء عمليًا');set('actDue','2026-10-20');submit('actSlotForm');assert.equal(stored().activity.slots.length,1);assert.ok($('actAlerts').textContent.includes('لم يُحدد المعلم'));assert.equal(w.eval("hubSchedule().some(s=>s.kind==='activity')"),true);assert.ok($('evidenceEvent').querySelector('option[value^="activity:"]'));assert.equal(w.eval("evidenceRecord('activity:'+data.activity.slots[0].id).name"),'بطاقة عامة');
 set('actSlotTeacher',tid);submit('actSlotForm');assert.equal(stored().activity.slots.length,1);assert.equal(stored().activity.slots[0].teacherId,tid);assert.ok($('actMetrics').textContent.includes('29'));const record=structuredClone(stored().activity.slots[0]);
 $('actAutoPreview').click();assert.equal(stored().activity.slots.length,1);assert.equal($('actFillPreview').hidden,false);$('actAutoApply').click();assert.equal(stored().activity.slots.length,30);assert.deepEqual(stored().activity.slots[0],record);assert.equal(w.ManhajActivity.core.metrics(stored().activity,'early').remaining,0);assert.ok($('actMetrics').textContent.includes('22 س 30 د'));
 // Updating a quota/capacity cannot silently erase allocated slots.
 click('[data-act-tab="profiles"]');set('actPeriods',5);submit('actProfileForm');assert.equal(stored().activity.profiles.early.periods,6);assert.ok($('toast').textContent.includes('انقلها أو احذفها'));set('actPeriods',6);
 click('[data-act-stage="middle"]');click('[data-act-tab="timetable"]');set('actSlotTeacher',tid);set('actPeriod',1);set('actDay',0);set('actTitle','تعارض');const oldCount=stored().activity.slots.length;submit('actSlotForm');assert.equal(stored().activity.slots.length,oldCount);assert.ok($('toast').textContent.includes('الحصة نفسها'));
 click('[data-act-stage="early"]');click('[data-act-tab="assignments"]');set('actAssignmentTeacher',tid);$('actAssignmentTeacher').dispatchEvent(new w.Event('change'));assert.ok($('actAssignmentLetter').textContent.includes('إجمالي الحصص: 12'));assert.equal($('actAssignmentDownload').disabled,false);$('actAssignmentPrint').click();assert.equal(w.printCalls,1);assert.equal(d.body.classList.contains('act-letter-print'),false);
 set('actReportDomain','القيم والهوية');$('actReportDomain').dispatchEvent(new w.Event('change'));$('actShareOpen').click();assert.equal($('actShareDialog').open,true);assert.equal($('actShareGenerate').disabled,true);assert.equal($('actShareOutput').hidden,true);$('actShareConsent').checked=true;$('actShareConsent').dispatchEvent(new w.Event('change'));$('actShareGenerate').click();assert.equal($('actShareOutput').hidden,false);const shareURL=$('actShareURL').value;assert.ok(shareURL.includes('#activity-share='));assert.equal(shareURL.includes('v='),false);assert.ok($('actShareImage').querySelector('svg'));assert.equal(shareURL.includes('المعلم الخاص'),false);
 const payload=w.ManhajActivity.decodePayload(shareURL.split('#activity-share=')[1]);assert.equal(payload.cards[0].title,'بطاقة عامة');assert.equal(JSON.stringify(payload).includes('teacherId'),false);assert.equal(JSON.stringify(payload).includes('school'),false);assert.equal(JSON.stringify(payload).includes('المعلم الخاص'),false);
 // Decode an actual QR pixel grid independently, not just its URL input.
 const qr=w.qrcode(0,'M');qr.addData(shareURL);qr.make();const size=qr.getModuleCount(),scale=5,margin=4,width=(size+margin*2)*scale,rgba=new Uint8ClampedArray(width*width*4);rgba.fill(255);for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(qr.isDark(y,x))for(let iy=0;iy<scale;iy++)for(let ix=0;ix<scale;ix++){const k=(((y+margin)*scale+iy)*width+(x+margin)*scale+ix)*4;rgba[k]=rgba[k+1]=rgba[k+2]=0}assert.equal(jsQR(rgba,width,width)?.data,shareURL);
 // Editing the review revokes consent and hides stale QR output.
 set('actShareTitle0','تعديل للمراجعة');assert.equal($('actShareGenerate').disabled,true);assert.equal($('actShareOutput').hidden,true);$('actShareClose').click();
 const shared=boot(shareURL);await shared.w.ManhajCurriculum.ready;await pause();assert.deepEqual(shared.errors,[]);assert.equal(shared.d.getElementById('activityShareView').hidden,false);assert.ok(shared.d.getElementById('actSharedCards').textContent.includes('بطاقة عامة'));assert.equal(shared.w.localStorage.getItem('manhaj-v1'),null);shared.dom.window.close();
 const malicious={v:1,domain:C.domains[0],cards:[{title:'<img src=x onerror="alert(1)">',goal:'<script>bad()</script>',day:0,period:1,state:'planned'}]};const evil=boot('https://q8-ux.github.io/saad/manhaj/#activity-share='+w.ManhajActivity.encodePayload(malicious));await pause();assert.equal(evil.d.getElementById('actSharedCards').querySelector('img'),null);assert.ok(evil.d.getElementById('actSharedCards').textContent.includes('<img'));evil.dom.window.close();assert.throws(()=>w.ManhajActivity.decodePayload('@@invalid'));
 // Backup round trip and persistence across reload preserve both new and old data.
 const backup={format:'manhaj-v1',...stored()};assert.equal(w.eval('valid('+JSON.stringify(backup)+')'),true);const restored=boot(undefined,backup);await pause();assert.equal(restored.w.ManhajActivity.getData().slots.length,30);assert.equal(restored.w.eval('data.hub.projects[0].id'),'legacy');restored.dom.window.close();
 Object.defineProperty($('restore'),'files',{configurable:true,value:[{size:1000,text:async()=>JSON.stringify(backup)}]});await $('restore').onchange({target:$('restore')});assert.equal(stored().activity.slots.length,30);assert.equal(stored().hub.projects[0].id,'legacy');
 const badBackup=structuredClone(backup);badBackup.activity.slots.push({...badBackup.activity.slots[0],id:'another-slot'});const beforeInvalid=w.localStorage.getItem('manhaj-v1');Object.defineProperty($('restore'),'files',{configurable:true,value:[{size:1000,text:async()=>JSON.stringify(badBackup)}]});await $('restore').onchange({target:$('restore')});assert.equal(w.localStorage.getItem('manhaj-v1'),beforeInvalid);
 // Manual receipt is green; delete restores count without deleting other records.
 click('[data-act-tab="timetable"]');click('[data-act-cell="'+record.id+'"]');$('actReceipt').checked=true;submit('actSlotForm');assert.ok(d.querySelector('[data-act-cell="'+record.id+'"]').classList.contains('green'));await $('actSlotDelete').onclick();assert.equal(stored().activity.slots.length,29);assert.equal(stored().hub.projects[0].id,'legacy');assert.equal(w.ManhajActivity.core.metrics(stored().activity,'early').remaining,1);
 assert.ok([...d.querySelectorAll('a[href]')].every(a=>!/^https?:\/\/(?:[^/]+\.)?github\.com(?:\/|$)/i.test(a.href)));assert.deepEqual(errors,[]);dom.window.close();
 process.stdout.write('PASS: stage isolation, import preview/dedup/merge, quotas, 30-session capacity, exact hours/minutes, conflict/missing-teacher alerts, safe autofill, unified letters, manual status colors, evidence/calendar links, backup validation/restore/reload, real QR decoding, fresh-device share, XSS protection, consent reset and legacy data preservation.\n');
})().catch(e=>{process.stderr.write(e.stack+'\n');process.exitCode=1});
