/* Independent stage profiles, local timetable and consolidated teacher assignments. */
(function(){
 'use strict';
 const C=window.ManhajActivityCore,route='activity';pages[route]='المراحل والحصص والتكليفات';
 let selectedStage='early',selectedTab='profiles',importPreview=null,fillPreview=null,profileSnapshot='',shareURL='',shareQR=null;
 const dirtyForms=new Set();
 const current=()=>data.activity||C.empty(),stage=()=>C.stages.find(s=>s.id===selectedStage),today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuwait',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const opt=(values,value)=>values.map(v=>`<option value="${esc(typeof v==='object'?v.value:v)}"${(typeof v==='object'?v.value:v)===value?' selected':''}>${esc(typeof v==='object'?v.label:v)}</option>`).join('');
 const subjects=['اللغة العربية','اللغة الإنجليزية','الرياضيات','العلوم','التربية الإسلامية','القرآن الكريم','الاجتماعيات','الحاسوب','تقنية المعلومات','التربية الفنية','التربية البدنية','الفيزياء','الكيمياء','الأحياء','اللغة الفرنسية','أنشطة مدرسية'];
 const field=(id,label,markup)=>`<div class="field"><label for="${id}">${label}</label>${markup}</div>`;
 const input=(id,label,attrs='')=>field(id,label,`<input id="${id}" ${attrs}>`);
 const select=(id,label,values)=>field(id,label,`<select id="${id}">${opt(values)}</select>`);
 const view=document.createElement('section');view.id=route+'View';view.className='view activity-view';view.hidden=true;
 view.innerHTML=`<header class="act-hero"><div><span class="act-kicker">تنظيم محسوب من بياناتك</span><h2>المراحل والحصص والتكليفات</h2><p>ملف مستقل لكل مرحلة، جدول مباشر، وخطاب واحد لكل معلم حتى إن تعددت صفوفه.</p></div><button type="button" class="btn secondary" data-go="reports">التقرير الشامل</button></header>
 <div class="act-stage-tabs" role="group" aria-label="المرحلة الحالية">${C.stages.map(s=>`<button type="button" data-act-stage="${s.id}">${s.name}</button>`).join('')}</div>
 <div id="actMetrics" class="act-metrics" aria-live="polite"></div>
 <nav class="act-tabs" aria-label="أدوات إدارة النشاط">${[['profiles','١ · بيانات المرحلة'],['teachers','٢ · المعلمون والاستيراد'],['timetable','٣ · الجدول والخطة'],['assignments','٤ · التكليفات والتقرير']].map(([id,label])=>`<button type="button" data-act-tab="${id}" aria-controls="act-${id}">${label}</button>`).join('')}</nav>
 <section id="act-profiles" class="act-tab-panel panel section"><h3 id="actProfileHeading"></h3><p class="muted">هذه البيانات منفصلة عن ملف المعلم العام، ولا تغير بيانات المراحل الأخرى. الأرقام أدناه إعدادات تخطيط تختارها أنت وليست تعليمات وزارية.</p>
 <form id="actProfileForm" class="form-grid">
 ${input('actSchool','اسم المدرسة','maxlength="300"')}${input('actNumber','الرقم الوزاري أو الإحصائي (اختياري)','maxlength="80"')}
 ${input('actStudents','عدد الطلاب في هذه المرحلة','type="number" min="0" max="20000" step="1" required')}
 ${select('actPeriods','الحصص المتاحة في اليوم',Array.from({length:12},(_,i)=>({value:String(i+1),label:(i+1)+' حصص'})))}
 ${input('actMinutes','مدة الحصة الافتراضية بالدقائق','type="number" min="5" max="120" step="1" required')}
 ${input('actPercent','النسبة المستهدفة التي تختارها (%)','type="number" min="0" max="100" step="1" required')}
 <p id="actProfileCalculation" class="act-wide note"></p><p class="act-wide muted">خمسة أيام عمل. مثال: ٦ حصص × ٥ أيام = ٣٠ حصة متاحة. تغيير المدة يخص الحصص الجديدة فقط؛ لا يغيّر مدد السجلات المحفوظة.</p>
 <div class="tools act-wide"><button class="btn">حفظ بيانات المرحلة</button><span id="actProfileStatus" role="status"></span></div></form></section>
 <section id="act-teachers" class="act-tab-panel" hidden><div class="act-two-panels"><section class="panel section"><h3>المعلمون المرتبطون بالمرحلة</h3><p class="muted">النصاب هنا عدد حصص النشاط الأسبوعي الذي تختاره عبر جميع المراحل، وليس نصاب التدريس الرسمي.</p>
 <form id="actTeacherForm" class="form-grid"><input type="hidden" id="actTeacherId">${input('actTeacherName','اسم المعلم','maxlength="120" required')}${select('actTeacherSubject','المادة',[{value:'',label:'غير محددة'},...subjects,{value:'other',label:'مادة أخرى'}])}${input('actTeacherOther','المادة الأخرى (عند اختيار أخرى)','maxlength="120"')}${input('actTeacherLoad','نصاب النشاط المختار أسبوعيًا','type="number" min="0" max="60" step="1" value="6" required')}
 <fieldset class="act-wide act-checkboxes"><legend>المراحل التي يعمل بها</legend>${C.stages.map(s=>`<label><input type="checkbox" name="actTeacherStage" value="${s.id}">${s.name}</label>`).join('')}</fieldset><div class="tools act-wide"><button class="btn">حفظ المعلم</button><button class="btn secondary" type="button" id="actTeacherReset">معلم جديد</button></div></form><div id="actTeacherList" class="act-roster"></div></section>
 <section class="panel section"><h3>استيراد دفعة واحدة</h3><p>الصق الأسماء من Excel أو ارفع CSV. الأعمدة: الاسم، المادة، النصاب الاختياري. يُدمج التكرار حسب الاسم والمادة، وتُربط المراحل دون تكرار المعلم أو استبدال نصابه السابق.</p>
 ${input('actImportFile','رفع CSV أو نص UTF-8','type="file" accept=".csv,.txt,text/csv,text/plain"')}${field('actImportText','بيانات المعلمين',`<textarea id="actImportText" rows="7" maxlength="250000" placeholder="الاسم,المادة,النصاب\nأحمد,العلوم,6\nفاطمة,اللغة العربية,6"></textarea>`)}${input('actImportLoad','نصاب افتراضي للأسماء دون نصاب','type="number" min="0" max="60" step="1" value="6"')}
 <div class="tools"><button type="button" class="btn secondary" id="actImportPreview">معاينة الاستيراد</button><button type="button" class="btn" id="actImportApply" disabled>اعتماد الاستيراد</button></div><div id="actImportResult" role="status"></div></section></div></section>
 <section id="act-timetable" class="act-tab-panel" hidden><div class="act-split"><section class="panel section act-editor"><h3>شاشة العمل</h3><p class="muted">اختر خلية من الجدول أو أدخل حصة. العنوان والتاريخ اختياريان. كل حصة تمثل بطاقة تنفيذ في التقرير.</p>
 <form id="actSlotForm" class="form-grid"><input id="actSlotId" type="hidden">${select('actDay','اليوم',C.days.map((label,i)=>({value:String(i),label})))}${select('actPeriod','الحصة',[])}${select('actSlotTeacher','المعلم',[])}${select('actGrade','الصف',[])}${select('actGroup','الشعبة',['أ','ب','ج','د','هـ','و','ز','ح','ط','ي','١','٢','٣','٤','٥','٦'])}${input('actTitle','عنوان النشاط (اختياري)','maxlength="180" placeholder="يُنشأ عنوان عند تركه فارغًا"')}${select('actDomain','مجال النشاط',C.domains)}${input('actSlotMinutes','مدة هذه الحصة بالدقائق','type="number" min="5" max="120" step="1" required')}${select('actState','حالة التنفيذ',Object.entries(C.states).map(([value,label])=>({value,label})))}${input('actDue','موعد التنفيذ (اختياري)','type="date"')}${field('actGoal','الهدف وخطوات التنفيذ (اختياري)',`<textarea id="actGoal" rows="3" maxlength="1500"></textarea>`)}
 <label class="act-wide act-check"><input type="checkbox" id="actReceipt"> سجّلت استلام التكليف يدويًا — ليس توقيعًا إلكترونيًا</label>
 <div id="actDraftSummary" class="act-wide note" role="status"></div><div class="tools act-wide"><button class="btn">حفظ الحصة</button><button type="button" class="btn secondary" id="actSlotReset">حصة جديدة</button><button type="button" class="btn secondary" id="actSlotDelete" disabled>حذف الحصة</button></div></form></section>
 <section class="panel section act-table-panel"><div class="act-section-head"><div><h3>الجدول والخطة المباشرة</h3><p class="muted" id="actTableCaption"></p></div><button type="button" class="btn secondary" id="actAutoPreview">تعبئة آلية — معاينة</button></div><p class="act-notice">يُفترض أن رقم الحصة نفسه متزامن بين المراحل. التعبئة لا تتجاوز نصاب المعلم ولا تستبدل أي خلية محفوظة. النتيجة قالب توزيع محلي للمراجعة وليست اعتمادًا.</p><div class="table-wrap act-table-wrap"><table id="actTable"><caption class="sr-only">جدول الحصص الأسبوعي — اختر خلية لتعديلها</caption></table></div>
 <div id="actFillPreview" hidden></div><section class="act-alerts" aria-labelledby="actAlertsTitle"><h4 id="actAlertsTitle">التنبيهات المحسوبة</h4><div id="actAlerts" aria-live="polite"></div></section></section></div></section>
 <section id="act-assignments" class="act-tab-panel" hidden><div class="act-two-panels"><section class="panel section"><h3>خطاب تكليف موحّد لكل معلم</h3><p class="muted">تُجمع صفوف المعلم وشعبه وبرامجه من جميع المراحل في خطاب واحد. الحالة والاستلام مدخلان يدويًا؛ لا تُرسل رسائل أو روابط توقيع.</p>${select('actAssignmentTeacher','المعلم',[])}<div class="tools"><button class="btn secondary" type="button" id="actAssignmentDownload">تنزيل الخطاب النصي</button><button class="btn" type="button" id="actAssignmentPrint">طباعة / PDF للخطاب</button></div><div id="actAssignmentLetter" class="act-letter"></div></section>
 <section class="panel section"><h3>بطاقات التنفيذ ورمز المشاركة</h3><p class="muted">أخضر: منفذ أو استلام مسجل يدويًا. أحمر: مخطط دون استلام أو متأخر. أصفر: قيد التنفيذ. اللون مصحوب بوصف نصي.</p>${select('actReportDomain','المجال',C.domains)}<div id="actExecutionCards"></div><button type="button" class="btn secondary" id="actShareOpen">إنشاء QR لهذا المجال</button><p class="act-notice">المشاركة نسخة ثابتة لبطاقات مختارة، وليست رابطًا مباشرًا إلى قاعدة بيانات مشتركة. لا تُدرج أسماء المعلمين أو أرقام المدارس آليًا.</p></section></div></section>
 <p class="act-footnote">الحفظ على هذا الجهاز فقط. تشمل النسخة الاحتياطية بيانات المراحل والمعلمين والحصص والتكليفات. أكواد التفعيل، تسجيل الدخول بالجوال، وروابط التوقيع تحتاج خدمة خلفية آمنة ولا تعمل في هذه النسخة.</p>`;
 document.querySelector('main').append(view);
 const report=document.createElement('section');report.id='activityReport';report.className='act-report';$('reportsView').querySelector('.panel').append(report);
 const shareView=document.createElement('section');shareView.id='activityShareView';shareView.className='view';shareView.hidden=true;shareView.innerHTML='<section class="panel section"><h2>بطاقات تنفيذ مشتركة</h2><p class="note">نسخة ثابتة اختار صاحب الرابط مشاركتها. ليست سجلًا حيًا أو اعتمادًا رسميًا، ولا تُستورد إلى بياناتك.</p><div id="actSharedCards"></div><button class="btn secondary" type="button" data-go="home">الرئيسية</button></section>';document.querySelector('main').append(shareView);pages.activityShare='بطاقات مشتركة';
 const dialog=document.createElement('dialog');dialog.id='actShareDialog';dialog.setAttribute('aria-labelledby','actShareTitle');dialog.innerHTML=`<header class="act-section-head"><h3 id="actShareTitle">مراجعة نسخة المشاركة</h3><button class="btn secondary" type="button" id="actShareClose" aria-label="إغلاق المشاركة">×</button></header><p>يمكن لأي شخص يحصل على الرابط قراءة هذه النسخة. راجع العنوان والهدف واحذف الأسماء والمعلومات الخاصة. الرابط لا يُلغى بعد مشاركته، ولا يتحدث عند تعديل سجلاتك.</p><p class="muted">حد أقصى ثلاث بطاقات مختصرة لكل رمز، لضمان وضوحه. أعد إنشاء الرمز عند تغير البيانات.</p><div id="actShareReview"></div><label class="act-check"><input type="checkbox" id="actShareConsent"> راجعت المحتوى وأوافق على مشاركة هذه النسخة</label><div class="tools"><button class="btn" id="actShareGenerate" type="button" disabled>إنشاء الرمز والرابط</button></div><div id="actShareOutput" hidden><div id="actShareImage"></div><div class="tools"><button class="btn secondary" type="button" id="actShareCopy">نسخ الرابط</button><button class="btn secondary" type="button" id="actShareSVG">تنزيل QR</button><a class="btn secondary" id="actShareLink" target="_blank" rel="noopener">فتح نسخة البطاقات</a></div>${input('actShareURL','رابط النسخة','readonly data-language-skip="true"')}</div><p id="actShareStatus" role="status"></p>`;document.body.append(dialog);
 function commit(next,message){if(!C.valid(next)){toast('تعذر الحفظ: تحقق من الأرقام وحدود الحصص.');return false}if(save({...data,activity:next})){importPreview=null;fillPreview=null;$('actImportApply').disabled=true;$('actFillPreview').hidden=true;toast(message);return true}return false}
 const clone=()=>JSON.parse(JSON.stringify(current()));
 function metricMarkup(a){const m=C.metrics(a,selectedStage),p=a.profiles[selectedStage];return [['الحصص الموزعة',m.allocated+' / '+m.capacity],['الرصيد المتاح',m.remaining],['الزمن المجدول',m.hours+' س '+m.minuteRemainder+' د'],['هدف '+p.percent+'٪',m.targetSessions+' حصص • '+m.targetStudents+' طالبًا']].map(([label,value])=>`<div><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`).join('')}
 function profileCalculation(){const periods=Number($('actPeriods').value),percent=Number($('actPercent').value),students=Number($('actStudents').value);$('actProfileCalculation').textContent=`معاينة: ${periods*5} حصة متاحة أسبوعيًا؛ الهدف ${Math.ceil(periods*5*percent/100)} حصص و${Math.ceil(students*percent/100)} طالبًا عند ${percent}٪. أعداد مستهدفة للتخطيط، وليست دليلًا على التنفيذ.`}
 function hydrateProfile(force=false){const p=current().profiles[selectedStage],snapshot=selectedStage+JSON.stringify(p);if(!force&&profileSnapshot===snapshot)return;profileSnapshot=snapshot;$('actProfileHeading').textContent='بيانات '+stage().name;for(const [id,key] of [['actSchool','school'],['actNumber','number'],['actStudents','students'],['actPeriods','periods'],['actMinutes','minutes'],['actPercent','percent']])$(id).value=p[key];profileCalculation()}
 function resetTeacher(){$('actTeacherForm').reset();$('actTeacherId').value='';view.querySelectorAll('[name="actTeacherStage"]').forEach(el=>el.checked=el.value===selectedStage);$('actTeacherOther').closest('.field').hidden=true;dirtyForms.delete('actTeacherForm')}
 function rebuildSelect(id,values){const old=$(id).value;$(id).innerHTML=opt(values);if([...$(id).options].some(o=>o.value===old))$(id).value=old}
 function resetSlot(day=0,period=1){$('actSlotForm').reset();$('actSlotId').value='';$('actDay').value=String(day);$('actPeriod').value=String(period);$('actSlotMinutes').value=current().profiles[selectedStage].minutes;$('actSlotDelete').disabled=true;dirtyForms.delete('actSlotForm');previewSlot()}
 function slotFromForm(){return {id:$('actSlotId').value||C.uid(),stage:selectedStage,day:Number($('actDay').value),period:Number($('actPeriod').value),teacherId:$('actSlotTeacher').value,grade:$('actGrade').value,group:$('actGroup').value,title:$('actTitle').value.trim()||'نشاط '+($('actGrade').value||'تعليمي'),goal:$('actGoal').value.trim(),domain:$('actDomain').value,state:$('actState').value,receipt:$('actReceipt').checked,due:$('actDue').value,minutes:Number($('actSlotMinutes').value)}}
 function problem(a,s){if(a.slots.some(x=>C.cellKey(x)===C.cellKey(s)&&x.id!==s.id))return 'هذه الخلية محفوظة؛ اخترها من الجدول لتعديلها.';const teacher=a.teachers.find(t=>t.id===s.teacherId);if(teacher&&!teacher.stages.includes(selectedStage))return 'اربط المعلم بهذه المرحلة أولًا.';if(C.conflicts(a,s).length)return 'المعلم مكلف في الحصة نفسها بمرحلة أخرى؛ اختر وقتًا آخر.';if(teacher&&C.countTeacher(a,teacher.id)-(a.slots.some(x=>x.id===s.id&&x.teacherId===teacher.id)?1:0)>=teacher.load)return 'لا توجد حصة متبقية في نصاب النشاط المختار لهذا المعلم.';return ''}
 function previewSlot(){const a=current(),s=slotFromForm(),error=problem(a,s),slots=a.slots.some(x=>x.id===s.id)?a.slots.map(x=>x.id===s.id?s:x):[...a.slots,s],m=C.metrics({...a,slots},selectedStage);$('actDraftSummary').textContent=error?'تنبيه قبل الحفظ: '+error:`معاينة غير محفوظة: بعد الحفظ ${m.allocated} / ${m.capacity} حصص، المتبقي ${m.remaining}، والزمن ${m.hours} ساعة و${m.minuteRemainder} دقيقة.${s.teacherId?'':' لم يُحدد المعلم؛ ستظهر الحصة كغير مكتملة.'}`;}
 function editSlot(id,day,period){const s=current().slots.find(x=>x.id===id);if(!s){resetSlot(day,period);return}for(const [id,key] of [['actSlotId','id'],['actDay','day'],['actPeriod','period'],['actSlotTeacher','teacherId'],['actGrade','grade'],['actGroup','group'],['actTitle','title'],['actGoal','goal'],['actDomain','domain'],['actState','state'],['actDue','due'],['actSlotMinutes','minutes']])$(id).value=String(s[key]);$('actReceipt').checked=s.receipt;$('actSlotDelete').disabled=false;previewSlot()}
 function statusText(s){const overdue=s.due&&s.due<today()&&s.state!=='done';return C.states[s.state]+(overdue?' — متأخر':'')+(s.receipt?' • استلام مسجل يدويًا':' • لم يُسجّل الاستلام')}
 function card(s,a=current()){const t=a.teachers.find(t=>t.id===s.teacherId);return `<article class="act-execution"><div><strong>${esc(s.title)}</strong><small>${esc(C.days[s.day])} • الحصة ${s.period} • ${esc(s.grade)} / ${esc(s.group)} • ${s.minutes} د</small><small>${esc(t?.name||'المعلم غير محدد')}</small><p>${esc(s.goal||'لم يُكتب هدف بعد')}</p></div><span class="act-status ${C.tone(s,today())}">${esc(statusText(s))}</span></article>`}
 function renderTable(){const a=current(),p=a.profiles[selectedStage];$('actTableCaption').textContent=stage().name+' • '+p.periods*5+' حصة متاحة • اضغط الخلية للتعديل';$('actTable').innerHTML='<thead><tr><th scope="col">اليوم</th>'+Array.from({length:p.periods},(_,i)=>'<th scope="col">الحصة '+(i+1)+'</th>').join('')+'</tr></thead><tbody>'+C.days.map((day,i)=>'<tr><th scope="row">'+day+'</th>'+Array.from({length:p.periods},(_,j)=>{const s=a.slots.find(s=>s.stage===selectedStage&&s.day===i&&s.period===j+1),t=a.teachers.find(t=>t.id===s?.teacherId);return `<td><button type="button" class="act-cell ${s?C.tone(s,today()):'empty-cell'}" data-act-cell="${esc(s?.id||'')}" data-day="${i}" data-period="${j+1}" aria-label="${esc(day+'، الحصة '+(j+1)+(s?'، '+s.title:'، فارغة'))}">${s?`<strong>${esc(s.title)}</strong><small>${esc(t?.name||'⚠ معلم غير محدد')}</small><small>${esc(s.grade+' / '+s.group)}</small><span>${esc(C.states[s.state])}${s.receipt?' • استلام':''}</span>`:'<strong>+</strong><small>حصة متاحة</small>'}</button></td>`}).join('')+'</tr>').join('')+'</tbody>';const alerts=C.alerts(a,selectedStage);$('actAlerts').innerHTML=alerts.length?'<ul>'+alerts.map(x=>'<li class="'+(x.type==='under'?'act-soft':'')+'">'+esc(x.text)+'</li>').join('')+'</ul>':'<p class="act-clear">لا يوجد نقص أو تعارض وفق بياناتك ونصابك المختار.</p>'}
 function assignmentText(item){if(!item)return '';return ['خطاب تكليف نشاط — إعداد المعلم (ليس اعتمادًا رسميًا)','المعلم: '+item.teacher.name,'المادة: '+(item.teacher.subject||'غير محددة'),'إجمالي الحصص: '+item.slots.length+' | الزمن: '+item.hours+' ساعة و'+item.minuteRemainder+' دقيقة','',...item.slots.map(s=>C.stages.find(t=>t.id===s.stage).name+' | '+C.days[s.day]+' | حصة '+s.period+' | '+s.grade+' / '+s.group+' | '+s.title+' | '+s.minutes+' دقيقة | '+statusText(s)),'','الاستلام المسجل يدويًا لا يُعد توقيعًا إلكترونيًا.'].join('\n')}
 function renderAssignment(){const item=C.assignment(current(),$('actAssignmentTeacher').value);$('actAssignmentLetter').textContent=item?(item.slots.length?assignmentText(item):'لم تسجل لهذا المعلم أي حصص بعد.'):'أضف معلمًا، ثم وزّع حصصه لإنشاء خطاب موحّد.';for(const id of ['actAssignmentDownload','actAssignmentPrint'])$(id).disabled=!item?.slots.length;const slots=current().slots.filter(s=>s.stage===selectedStage&&s.domain===$('actReportDomain').value);$('actExecutionCards').innerHTML=slots.map(s=>card(s)).join('')||'<p class="empty">لا توجد بطاقات لهذا المجال في المرحلة الحالية.</p>';$('actShareOpen').disabled=!slots.length}
 function renderReport(){const a=current();report.innerHTML='<h3>تقرير المراحل والحصص</h3><p class="muted">المؤشرات من الحصص المحفوظة. النسب والنصاب يختارهما المعلم. الاستلام يدوي وليس توقيعًا.</p><div class="table-wrap"><table class="act-summary-table"><thead><tr><th>المرحلة</th><th>المدرسة / الرقم</th><th>الطلاب</th><th>الموزع / المتاح</th><th>المنفذ</th><th>الوقت المجدول</th><th>هدف النسبة</th></tr></thead><tbody>'+C.stages.map(s=>{const p=a.profiles[s.id],m=C.metrics(a,s.id);return `<tr><th>${s.name}</th><td>${esc(p.school||'غير محددة')}<small>${esc(p.number||'—')}</small></td><td>${p.students}</td><td>${m.allocated} / ${m.capacity}</td><td>${m.done}</td><td>${m.hours} س ${m.minuteRemainder} د</td><td>${p.percent}٪: ${m.targetSessions} حصص / ${m.targetStudents} طالبًا</td></tr>`}).join('')+'</tbody></table></div><h4>خطابات التكليف الموحّدة</h4>'+a.teachers.filter(t=>C.countTeacher(a,t.id)).map(t=>`<details class="act-assignment-detail" open><summary>${esc(t.name)} — ${C.countTeacher(a,t.id)} حصص</summary><pre>${esc(assignmentText(C.assignment(a,t.id)))}</pre></details>`).join('')+(a.slots.length?'':'<p class="muted">لا توجد حصص محفوظة بعد.</p>')}
 function renderActivity(){const a=current();hydrateProfile();$('actMetrics').innerHTML=metricMarkup(a);$('evidenceEvent').querySelectorAll('optgroup[data-act-evidence]').forEach(n=>n.remove());if(a.slots.length){const group=document.createElement('optgroup');group.label='بطاقات حصص النشاط';group.dataset.actEvidence='true';group.innerHTML=a.slots.map(s=>`<option value="activity:${esc(s.id)}">${esc(s.title+' — '+C.stages.find(t=>t.id===s.stage).name+' / '+C.days[s.day]+' / '+s.period)}</option>`).join('');$('evidenceEvent').append(group)}view.querySelectorAll('[data-act-stage]').forEach(b=>{const active=b.dataset.actStage===selectedStage;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});view.querySelectorAll('[data-act-tab]').forEach(b=>{const active=b.dataset.actTab===selectedTab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');$('act-'+b.dataset.actTab).hidden=!active});
  const teachers=a.teachers.filter(t=>t.stages.includes(selectedStage));$('actTeacherList').innerHTML=teachers.map(t=>`<article class="act-teacher"><div><strong>${esc(t.name)}</strong><small>${esc(t.subject||'غير محددة')} • ${C.countTeacher(a,t.id)} / ${t.load} حصص موزعة عبر المراحل</small></div><div class="tools"><button type="button" class="btn secondary" data-act-edit-teacher="${esc(t.id)}">تعديل</button><button type="button" class="btn secondary" data-act-remove-teacher="${esc(t.id)}">حذف</button></div></article>`).join('')||'<p class="empty">أضف معلمًا أو استورد قائمة المعلمين لهذه المرحلة.</p>';
  rebuildSelect('actSlotTeacher',[{value:'',label:'غير محدد — يظهر تنبيه'},...teachers.map(t=>({value:t.id,label:t.name+' • '+(t.subject||'غير محددة')}))]);rebuildSelect('actPeriod',Array.from({length:a.profiles[selectedStage].periods},(_,i)=>({value:String(i+1),label:'الحصة '+(i+1)})));rebuildSelect('actGrade',stage().grades);rebuildSelect('actAssignmentTeacher',a.teachers.map(t=>({value:t.id,label:t.name+' • '+(t.subject||'غير محددة')})));renderTable();renderAssignment();renderReport();previewSlot();
 }
 const oldRender=render;render=function(){oldRender();renderActivity()};
 $('actProfileForm').onsubmit=e=>{e.preventDefault();const next=clone(),p={school:$('actSchool').value.trim(),number:$('actNumber').value.trim(),students:Number($('actStudents').value),periods:Number($('actPeriods').value),minutes:Number($('actMinutes').value),percent:Number($('actPercent').value)};if(next.slots.some(s=>s.stage===selectedStage&&s.period>p.periods))return toast('توجد حصص محفوظة خارج العدد الجديد. انقلها أو احذفها بنفسك قبل تقليل العدد.');next.profiles[selectedStage]=p;if(commit(next,'حُفظت بيانات هذه المرحلة فقط.')){$('actProfileStatus').textContent='تم الحفظ على هذا الجهاز.';hydrateProfile(true);dirtyForms.delete('actProfileForm')}};
 ['actPeriods','actPercent','actStudents'].forEach(id=>$(id).addEventListener('input',profileCalculation));
 $('actTeacherSubject').onchange=()=>{$('actTeacherOther').closest('.field').hidden=$('actTeacherSubject').value!=='other'};
 $('actTeacherForm').onsubmit=e=>{e.preventDefault();const next=clone(),t={id:$('actTeacherId').value||C.uid(),name:$('actTeacherName').value.trim(),subject:$('actTeacherSubject').value==='other'?$('actTeacherOther').value.trim():$('actTeacherSubject').value,stages:[...view.querySelectorAll('[name="actTeacherStage"]:checked')].map(e=>e.value),load:Number($('actTeacherLoad').value)};if(!t.name||!t.stages.length)return toast('اكتب الاسم واختر مرحلة واحدة على الأقل.');if(next.teachers.some(x=>x.id!==t.id&&C.teacherKey(x)===C.teacherKey(t)))return toast('المعلم موجود بالمادة نفسها. عدّل سجله واربط المرحلة دون تكرار.');if(C.countTeacher(next,t.id)>t.load)return toast('النصاب الجديد أقل من الحصص المحفوظة؛ عدّل الحصص أولًا.');if(next.slots.some(s=>s.teacherId===t.id&&!t.stages.includes(s.stage)))return toast('للمعلم حصص في مرحلة أزلتها؛ انقل تلك الحصص أولًا.');const i=next.teachers.findIndex(x=>x.id===t.id);if(i<0)next.teachers.push(t);else next.teachers[i]=t;if(commit(next,'تم حفظ المعلم دون تكرار.'))resetTeacher()};$('actTeacherReset').onclick=resetTeacher;
 $('actImportFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>250000)return toast('الحد الأقصى ٢٥٠ كيلوبايت لملف الاستيراد.');try{$('actImportText').value=await f.text();invalidateImport();toast('تمت قراءة الملف؛ اضغط معاينة قبل الاستيراد.')}catch{toast('تعذر قراءة الملف.')}e.target.value=''};
 function invalidateImport(){importPreview=null;$('actImportApply').disabled=true;$('actImportResult').textContent='أعد المعاينة بعد تغيير البيانات.'}
 for(const id of ['actImportText','actImportLoad'])$(id).addEventListener('input',invalidateImport);
 $('actImportPreview').onclick=()=>{try{importPreview=C.previewImport($('actImportText').value,current(),selectedStage,Number($('actImportLoad').value));$('actImportResult').innerHTML=`<p>${importPreview.rows.length} سجلات جاهزة، منها ${importPreview.linked} ربط لمرحلة إضافية؛ تجاهل ${importPreview.duplicates} تكرارًا. لم يُحفظ شيء بعد.</p>`+(importPreview.errors.length?'<ul>'+importPreview.errors.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':'')+'<ul>'+importPreview.rows.slice(0,12).map(t=>'<li>'+esc(t.name+' • '+(t.subject||'غير محددة')+' • '+t.load+' حصص')+'</li>').join('')+'</ul>';$('actImportApply').disabled=!!importPreview.errors.length||!importPreview.rows.length}catch(err){invalidateImport();$('actImportResult').textContent=err.message}};
 $('actImportApply').onclick=()=>{if(!importPreview)return;try{const count=importPreview.rows.length;if(commit(C.applyImport(current(),importPreview),'تم استيراد '+count+' سجل وربطها بالمرحلة.')){$('actImportText').value='';$('actImportResult').textContent='اكتمل الاستيراد دون تكرار المعلمين.'}}catch(err){toast(err.message)}};
 $('actSlotForm').onsubmit=e=>{e.preventDefault();const next=clone(),s=slotFromForm(),error=problem(next,s);if(error)return toast(error);const i=next.slots.findIndex(x=>x.id===s.id);if(i<0)next.slots.push(s);else next.slots[i]=s;if(commit(next,s.teacherId?'تم حفظ الحصة وتحديث العدادات.':'حُفظت الحصة؛ أكمل المعلم من التنبيهات.')){dirtyForms.delete('actSlotForm');$('actSlotId').value=s.id;$('actSlotDelete').disabled=false;previewSlot()}};
 for(const type of ['input','change'])$('actSlotForm').addEventListener(type,previewSlot);$('actSlotReset').onclick=()=>resetSlot();$('actSlotDelete').onclick=async()=>{const id=$('actSlotId').value;if(!id||!confirm('حذف هذه الحصة وشواهدها وإعادة رصيدها للمرحلة؟'))return;try{await removeEventEvidence('activity:'+id);const next=clone();next.slots=next.slots.filter(s=>s.id!==id);if(commit(next,'حُذفت الحصة وشواهدها المحلية وعاد رصيدها. النسخة النصية لا تعيد المرفقات.'))resetSlot()}catch{toast('تعذر حذف الشواهد؛ لم تُحذف الحصة.')}};
 $('actAutoPreview').onclick=()=>{fillPreview=C.autoFill(current(),selectedStage);const box=$('actFillPreview');box.hidden=false;box.innerHTML=`<h4>معاينة توزيع ${fillPreview.created.length} حصة جديدة</h4><p>المتبقي ${fillPreview.remaining} حصص بسبب النصاب المتاح أو التعارض. لم تتغير الخلايا المحفوظة. راجع الصفوف والشعب والعناوين بعد الاعتماد.</p><ul>${fillPreview.created.slice(0,8).map(s=>'<li>'+esc(C.days[s.day]+' / الحصة '+s.period+' — '+current().teachers.find(t=>t.id===s.teacherId)?.name)+'</li>').join('')}</ul><div class="tools"><button type="button" class="btn" id="actAutoApply" ${fillPreview.created.length?'':'disabled'}>اعتماد التوزيع</button><button type="button" class="btn secondary" id="actAutoCancel">إلغاء</button></div>`;$('actAutoApply').onclick=()=>{if(fillPreview&&commit(fillPreview.next,'حُفظ التوزيع الآلي. راجع بطاقات التنفيذ وأهدافها.'))resetSlot()};$('actAutoCancel').onclick=()=>{fillPreview=null;box.hidden=true}};
 $('actAssignmentTeacher').onchange=renderAssignment;$('actReportDomain').onchange=renderAssignment;
 $('actAssignmentDownload').onclick=()=>{const text=assignmentText(C.assignment(current(),$('actAssignmentTeacher').value));if(text)download(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}),'manhaj-assignment.txt')};
 $('actAssignmentPrint').onclick=()=>{const item=C.assignment(current(),$('actAssignmentTeacher').value);if(!item?.slots.length)return;document.body.classList.add('act-letter-print');show(route);selectedTab='assignments';renderActivity();window.print();document.body.classList.remove('act-letter-print')};window.addEventListener('afterprint',()=>document.body.classList.remove('act-letter-print'));
 view.addEventListener('click',e=>{const st=e.target.closest('[data-act-stage]'),tab=e.target.closest('[data-act-tab]'),cell=e.target.closest('[data-act-cell]'),edit=e.target.closest('[data-act-edit-teacher]'),remove=e.target.closest('[data-act-remove-teacher]');if(st&&st.dataset.actStage!==selectedStage){if(!dirtyForms.size||confirm('لديك تعديلات غير محفوظة. هل تريد تركها وتغيير المرحلة؟ تبقى السجلات المحفوظة كما هي.')){selectedStage=st.dataset.actStage;importPreview=null;fillPreview=null;invalidateImport();$('actFillPreview').hidden=true;dirtyForms.clear();renderActivity();resetTeacher();resetSlot()}}if(tab){selectedTab=tab.dataset.actTab;renderActivity()}if(cell)editSlot(cell.dataset.actCell,Number(cell.dataset.day),Number(cell.dataset.period));if(edit){const t=current().teachers.find(t=>t.id===edit.dataset.actEditTeacher);if(!t)return;$('actTeacherId').value=t.id;$('actTeacherName').value=t.name;$('actTeacherLoad').value=t.load;$('actTeacherSubject').value=subjects.includes(t.subject)||!t.subject?t.subject:'other';$('actTeacherOther').value=t.subject;$('actTeacherOther').closest('.field').hidden=$('actTeacherSubject').value!=='other';view.querySelectorAll('[name="actTeacherStage"]').forEach(el=>el.checked=t.stages.includes(el.value));$('actTeacherName').focus()}if(remove){const id=remove.dataset.actRemoveTeacher;if(C.countTeacher(current(),id))return toast('للمعلم حصص محفوظة؛ انقلها أو احذفها قبل حذف سجله.');if(confirm('حذف سجل هذا المعلم من جميع المراحل؟')){const next=clone();next.teachers=next.teachers.filter(t=>t.id!==id);if(commit(next,'حُذف سجل المعلم؛ يمكن استعادته من نسختك الاحتياطية.'))resetTeacher()}}});
 for(const type of ['input','change'])view.addEventListener(type,e=>{const form=e.target.closest('#actProfileForm,#actTeacherForm,#actSlotForm');if(form)dirtyForms.add(form.id)});
 // Static, privacy-reviewed shares. No external QR service receives the data.
 function encodePayload(payload){const bytes=new TextEncoder().encode(JSON.stringify(payload));if(bytes.length>1500)throw Error('المحتوى طويل للرمز؛ اختر بطاقات أقل أو اختصر الهدف.');let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
 function decodePayload(token){if(token.length>2200||!/^[A-Za-z0-9_-]+$/.test(token))throw Error();const bin=atob(token.replace(/-/g,'+').replace(/_/g,'/')),payload=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(bin,c=>c.charCodeAt(0))));if(!C.validShare(payload))throw Error();return payload}
 let shareDraft=null;
 $('actShareOpen').onclick=()=>{shareDraft=C.sharePayload(current(),selectedStage,$('actReportDomain').value);shareDraft.cards=shareDraft.cards.slice(0,3).map(c=>({...c,title:c.title.slice(0,60),goal:c.goal.slice(0,80)}));shareURL='';shareQR=null;$('actShareOutput').hidden=true;$('actShareConsent').checked=false;$('actShareGenerate').disabled=true;$('actShareStatus').textContent='';$('actShareReview').innerHTML='<h4>'+esc(shareDraft.domain)+'</h4>'+shareDraft.cards.map((c,i)=>`<section class="act-share-edit"><label class="act-check"><input type="checkbox" data-act-share-include="${i}" checked> مشاركة البطاقة ${i+1} • ${esc(C.days[c.day])} / ${c.period}</label>${input('actShareTitle'+i,'العنوان','maxlength="60" data-language-skip="true"')}${field('actShareGoal'+i,'الهدف المختصر',`<textarea id="actShareGoal${i}" rows="2" maxlength="80" data-language-skip="true"></textarea>`)}</section>`).join('');shareDraft.cards.forEach((c,i)=>{$('actShareTitle'+i).value=c.title;$('actShareGoal'+i).value=c.goal});dialog.showModal()};
 $('actShareConsent').onchange=()=>{$('actShareGenerate').disabled=!$('actShareConsent').checked};
 $('actShareReview').addEventListener('input',()=>{$('actShareConsent').checked=false;$('actShareGenerate').disabled=true;$('actShareOutput').hidden=true;shareURL='';shareQR=null});
 $('actShareGenerate').onclick=()=>{if(!shareDraft||!$('actShareConsent').checked)return;try{const payload={...shareDraft,cards:shareDraft.cards.filter((c,i)=>dialog.querySelector(`[data-act-share-include="${i}"]`).checked).map(c=>{const i=shareDraft.cards.indexOf(c);return {...c,title:$('actShareTitle'+i).value.trim(),goal:$('actShareGoal'+i).value.trim()}})};if(!C.validShare(payload))throw Error('اختر بطاقة واحدة على الأقل.');const url=new URL(location.href);url.search='';url.hash='activity-share='+encodePayload(payload);if(url.href.length>2200)throw Error('الرابط طويل؛ اختصر المحتوى.');if(typeof window.qrcode!=='function')throw Error('مولّد QR غير متاح.');const qr=window.qrcode(0,'M');qr.addData(url.href);qr.make();shareURL=url.href;shareQR=qr;$('actShareImage').innerHTML=qr.createSvgTag({cellSize:5,margin:20,scalable:true});$('actShareImage').querySelector('svg').setAttribute('aria-label','QR لنسخة بطاقات '+payload.domain);$('actShareURL').value=shareURL;$('actShareLink').href=shareURL;$('actShareOutput').hidden=false;$('actShareStatus').textContent='أُنشئ الرمز محليًا. جرّب فتحه أو مسحه قبل إرساله.'}catch(err){shareURL='';shareQR=null;$('actShareOutput').hidden=true;$('actShareStatus').textContent=err.message||'تعذر إنشاء الرمز.'}};
 $('actShareCopy').onclick=async()=>{if(!shareURL)return;try{await navigator.clipboard.writeText(shareURL);$('actShareStatus').textContent='نُسخ الرابط.'}catch{$('actShareURL').focus();$('actShareURL').select();$('actShareStatus').textContent='انسخ الرابط المحدد يدويًا.'}};$('actShareSVG').onclick=()=>{if(shareQR)download(new Blob([shareQR.createSvgTag({cellSize:5,margin:20})],{type:'image/svg+xml'}),'manhaj-domain-qr.svg')};$('actShareClose').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{$('actShareOpen').focus()});
 function showShare(token){let payload;try{payload=decodePayload(token)}catch{$('actSharedCards').innerHTML='<p class="empty">رابط غير صالح أو محتواه أكبر من الحد المسموح. اطلب رمزًا جديدًا من صاحب البطاقة.</p>'}if(payload)$('actSharedCards').innerHTML='<h3>'+esc(payload.domain)+'</h3>'+payload.cards.map(c=>`<article class="act-execution"><div><strong>${esc(c.title)}</strong><small>${esc(C.days[c.day])} • الحصة ${c.period}</small><p>${esc(c.goal||'لا يوجد هدف في النسخة المشتركة')}</p></div><span class="act-status ${c.state==='done'?'green':c.state==='active'?'amber':'red'}">${esc(C.states[c.state])}</span></article>`).join('');document.querySelectorAll('.view').forEach(v=>v.hidden=v!==shareView);$('pageTitle').textContent=pages.activityShare;$('appScreenTitle').textContent=pages.activityShare;$('sidebar').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false');$('appMenu').setAttribute('aria-expanded','false');document.querySelectorAll('.nav-btn,#appTabs button').forEach(b=>{b.classList.remove('active');b.removeAttribute('aria-current')})}
 const oldShow=show;show=function(k){if(String(k).startsWith('activity-share=')){showShare(k.slice('activity-share='.length));return}oldShow(k)};
 window.ManhajActivity={route,core:C,render:renderActivity,getData:()=>JSON.parse(JSON.stringify(current())),encodePayload,decodePayload,assignmentText};
 renderActivity();resetTeacher();resetSlot();window.ManhajLanguage?.enhance(view);window.ManhajLanguage?.enhance(dialog);if(initialViewKey===route)show(route);else if(initialViewKey.startsWith('activity-share=')){location.hash=initialViewKey;show(initialViewKey)}
})();
