const initialViewKey=location.hash.slice(1);
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='manhaj-v1';let data={plan:{},events:[]};try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved))data=saved}catch(e){}
function valid(d){return d&&typeof d.plan==='object'&&d.plan!==null&&Array.isArray(d.events)&&d.events.length<=2000&&d.events.every(e=>e&&['id','name','date','owner','subject','goal','state'].every(k=>typeof e[k]==='string')&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&['مخطط','قيد التنفيذ','منفذ'].includes(e.state))&&new Set(d.events.map(e=>e.id)).size===d.events.length&&validateHub(d.hub)&&window.ManhajActivityCore.valid(d.activity)}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').hidden=true,4500)}
function save(next){try{localStorage.setItem(key,JSON.stringify(next));data=next;render();return true}catch(e){toast('تعذر الحفظ. صدّر نسخة احتياطية وتحقق من مساحة المتصفح.');return false}}
const pages={dashboard:'الرئيسية',plans:'الخطة وبنك الأنشطة',events:'البرامج والفعاليات',library:'مراجع المناهج',evidence:'ملف الإنجاز والشواهد',reports:'التقارير',studio:'استوديو المعلم',settings:'الإعدادات'};
$('nav').innerHTML=Object.entries(pages).map(([k,v])=>`<button class="nav-btn" data-go="${k}">${v}</button>`).join('');
function show(k){if(!pages[k])k='dashboard';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==k+'View');$('pageTitle').textContent=pages[k];document.querySelectorAll('.nav-btn').forEach(b=>{b.classList.toggle('active',b.dataset.go===k);b.setAttribute('aria-current',b.dataset.go===k?'page':'false')});$('sidebar').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false');location.hash=k;if(k==='evidence')renderEvidence().catch(()=>toast('الشواهد غير متاحة في هذا المتصفح.'))}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)show(b.dataset.go)});window.addEventListener('hashchange',()=>show(location.hash.slice(1)));$('menuBtn').onclick=()=>{const on=$('sidebar').classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',String(on))};$('themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';
const fields=['school','region','stage','term','year','goal'];fields.forEach(k=>{if(typeof data.plan[k]==='string')$(k).value=data.plan[k]});$('planForm').onsubmit=e=>{e.preventDefault();const plan=Object.fromEntries(fields.map(k=>[k,$(k).value.trim()]));if(save({...data,plan}))toast('تم حفظ الخطة على هذا الجهاز')};
const templates=[{name:'نادي القراءة',subject:'اللغة العربية',goal:'قراءة نص مختار وتلخيص فكرته، ثم عرض ملخص شفهي ومناقشة زملاء الصف.'},{name:'مختبر العلوم الصغير',subject:'العلوم',goal:'تنفيذ تجربة آمنة بإشراف المعلم، وتسجيل الملاحظة وشرح النتيجة بالأدلة.'},{name:'الكويت في عيوننا',subject:'الاجتماعيات',goal:'البحث في معلم كويتي وتوثيق مصدر المعلومات وإعداد عرض جماعي.'},{name:'الأمان الرقمي',subject:'الحاسوب',goal:'تمييز الرسائل المشبوهة وشرح حماية كلمات المرور من خلال مواقف تمثيلية.'},{name:'تحدي الحساب',subject:'الرياضيات',goal:'حل مسائل مناسبة للصف وشرح خطوات الحل مع تبادل الأدوار.'},{name:'حوار باللغة الإنجليزية',subject:'اللغة الإنجليزية',goal:'إجراء حوار قصير يستخدم مفردات الدرس مع مراجعة المعلم للنطق والمعنى.'}];
$('templates').innerHTML=templates.map((t,i)=>`<article class="price-card"><h3>${t.name}</h3><p>${t.goal}</p><div class="tools"><button class="btn secondary" data-template="${i}">إنشاء بطاقة</button></div></article>`).join('');document.addEventListener('click',e=>{const b=e.target.closest('[data-template]');if(b){resetEvent();const t=templates[Number(b.dataset.template)];$('eventName').value=t.name;$('subject').value=t.subject;$('eventGoal').value=t.goal;show('events');$('eventDate').focus()}});
function resetEvent(){$('eventForm').reset();$('eventId').value=''}$('cancelEdit').onclick=resetEvent;$('addEvent').onclick=()=>{resetEvent();show('events');$('eventName').focus()};
$('eventForm').onsubmit=e=>{e.preventDefault();const item={id:$('eventId').value||crypto.randomUUID(),name:$('eventName').value.trim(),date:$('eventDate').value,owner:$('owner').value.trim(),subject:$('subject').value,goal:$('eventGoal').value.trim(),state:$('state').value};if(!item.name||!item.owner||!item.goal)return toast('أكمل الحقول المطلوبة');let events=data.events.some(x=>x.id===item.id)?data.events.map(x=>x.id===item.id?item:x):[...data.events,item];if(save({...data,events})){resetEvent();toast('تم حفظ الفعالية')}};
function eventCard(e,actions=false){return `<article class="task"><div><strong>${esc(e.name)}</strong><small>${esc(e.date)} · ${esc(e.owner)} · ${esc(e.subject)}</small><p>${esc(e.goal)}</p></div><span class="status ${e.state==='منفذ'?'ok':'warn'}">${esc(e.state)}</span>${actions?`<div class="tools"><button class="btn secondary" data-design-event="${esc(e.id)}">تصميم بطاقة</button><button class="btn secondary" data-edit="${esc(e.id)}">تعديل</button><button class="btn secondary" data-delete="${esc(e.id)}">حذف</button></div>`:''}</article>`}
document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit){const t=data.events.find(x=>x.id===edit.dataset.edit);if(!t)return;$('eventId').value=t.id;$('eventName').value=t.name;$('eventDate').value=t.date;$('owner').value=t.owner;$('subject').value=t.subject;$('eventGoal').value=t.goal;$('state').value=t.state;show('events');$('eventName').focus()}if(del&&confirm('حذف الفعالية وشواهدها من هذا الجهاز؟')){try{await removeEventEvidence(del.dataset.delete);if(save({...data,events:data.events.filter(x=>x.id!==del.dataset.delete)}))toast('تم الحذف')}catch(e){toast('تعذر حذف الشواهد، لم تُحذف الفعالية.')}}});
function render(){const completed=data.events.filter(e=>e.state==='منفذ').length;$('metrics').innerHTML=[['الفعاليات',data.events.length],['المنفذ',completed],['نسبة التنفيذ',data.events.length?Math.round(completed/data.events.length*100)+'%':'—']].map(([l,n])=>`<div class="metric"><span>${l}</span><strong>${n}</strong></div>`).join('');const q=$('eventSearch').value.trim();$('eventList').innerHTML=data.events.filter(e=>[e.name,e.owner,e.subject].some(v=>v.includes(q))).sort((a,b)=>a.date.localeCompare(b.date)).map(e=>eventCard(e,true)).join('')||'<p class="empty">لا توجد فعاليات مطابقة. أضف فعالية أو استخدم بنك الأنشطة.</p>';const today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuwait'});$('upcoming').innerHTML=data.events.filter(e=>e.date>=today&&e.state!=='منفذ').sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5).map(e=>eventCard(e)).join('')||'<p class="empty">لا توجد فعاليات قادمة مسجلة.</p>';$('evidenceEvent').innerHTML='<option value="">اختر الفعالية</option>'+data.events.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('');$('reportSchool').textContent=[data.plan.school||'لم تُحدد المدرسة',data.plan.region,data.plan.stage,data.plan.term&&'الفصل '+data.plan.term,data.plan.year].filter(Boolean).join(' · ');$('reportSummary').textContent=`عدد الفعاليات: ${data.events.length} | المنفذ: ${completed} | هدف الخطة: ${data.plan.goal||'لم يُحدد'}`;$('reportEvents').innerHTML=data.events.map(e=>eventCard(e)).join('')||'<p class="empty">لا توجد فعاليات في التقرير.</p>'}
$('eventSearch').oninput=render;
const grades=['الأول','الثاني','الثالث','الرابع','الخامس','السادس','السابع','الثامن','التاسع','العاشر','الحادي عشر','الثاني عشر'],ids=[23,24,22,18,20,1,3,14,6,8,10,12];const books=grades.map((g,i)=>({grade:g,stage:i<5?'ابتدائية':i<9?'متوسطة':'ثانوية',url:'https://hasobgpt.moe.edu.kw/pages/library?handler=File&id='+ids[i]+'&part=main'}));function renderBooks(){const q=$('bookSearch').value.trim(),stage=$('bookStage').value;$('books').innerHTML=books.filter(b=>(!stage||b.stage===stage)&&('الحاسوب '+b.grade+' '+b.stage).includes(q)).map(b=>`<article class="price-card"><span class="status ok">مصدر رسمي</span><h3>الحاسوب — ${b.grade}</h3><p>${b.stage} · الفصل الأول</p><div class="tools"><a class="btn secondary" href="${b.url}" target="_blank" rel="noopener">فتح كتاب الوزارة</a></div></article>`).join('')||'<p class="empty">لا توجد نتيجة في الفهرس الأولي. انتقل إلى مكتبة الوزارة لجميع المواد.</p>'}$('bookSearch').oninput=renderBooks;$('bookStage').onchange=renderBooks;
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}$('backup').onclick=()=>download(new Blob([JSON.stringify({format:'manhaj-v1',...data},null,2)],{type:'application/json'}),'manhaj-backup.json');$('restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error();const d=JSON.parse(await f.text());if(d.format!=='manhaj-v1'||!valid(d))throw Error();if(confirm('استبدال الخطط والفعاليات والمشاريع والاجتماعات والمهام والمراحل والمعلمين والحصص بالنسخة الاحتياطية؟ الشواهد الموجودة ستبقى محفوظة.')){if(save({plan:d.plan,events:d.events,hub:d.hub||emptyHub(),...(d.activity?{activity:d.activity}:{})})){fields.forEach(k=>{if(typeof d.plan[k]==='string')$(k).value=d.plan[k]});toast('تمت الاستعادة')}}}catch(e){toast('ملف غير صالح للاستعادة')}$('restore').value=''};$('print').onclick=()=>window.print();$('csv').onclick=()=>{const cell=s=>'"'+String(s).replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"';const rows=[['العنوان','التاريخ','المسؤول','المادة','الهدف','الحالة'],...data.events.map(e=>[e.name,e.date,e.owner,e.subject,e.goal,e.state])];download(new Blob(['\ufeff'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'manhaj-events.csv')};
let dbPromise;function db(){return dbPromise||(dbPromise=new Promise((res,rej)=>{const r=indexedDB.open('manhaj-evidence',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}))}async function dbOp(mode,fn){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('files',mode);fn(tx.objectStore('files'));tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)})}async function allFiles(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('files').objectStore('files').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function removeEventEvidence(id){const files=await allFiles();await dbOp('readwrite',s=>files.filter(f=>f.event===id).forEach(f=>s.delete(f.id)))}
$('evidenceForm').onsubmit=async e=>{e.preventDefault();const f=$('evidenceFile').files[0],event=$('evidenceEvent').value;if(!f||!evidenceRecord(event))return toast('اختر فعالية');if(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))return toast('اختر صورة أو PDF بحجم لا يتجاوز ٥ ميغابايت');try{await dbOp('readwrite',s=>s.put({id:crypto.randomUUID(),event,name:f.name,blob:f}));$('evidenceFile').value='';await renderEvidence();toast('تم حفظ الشاهد على الجهاز')}catch(e){toast('تعذر حفظ الشاهد. تحقق من مساحة التخزين.')}};
async function renderEvidence(){const files=await allFiles();$('evidenceList').innerHTML=files.map(f=>`<article class="task"><div><strong>${esc(f.name)}</strong><small>${esc(evidenceRecord(f.event)?.name||'سجل غير موجود في النسخة الحالية')}</small></div><div class="tools"><button class="btn secondary" data-file="${esc(f.id)}">تنزيل</button><button class="btn secondary" data-remove-file="${esc(f.id)}">حذف</button></div></article>`).join('')||'<p class="empty">لا توجد شواهد محفوظة.</p>'}document.addEventListener('click',async e=>{const b=e.target.closest('[data-file]'),r=e.target.closest('[data-remove-file]');try{if(b){const f=(await allFiles()).find(f=>f.id===b.dataset.file);if(f)download(f.blob,f.name)}if(r&&confirm('حذف الشاهد؟')){await dbOp('readwrite',s=>s.delete(r.dataset.removeFile));await renderEvidence()}}catch(e){toast('تعذر الوصول إلى الشاهد')}});
render();renderBooks();
