/* Local guided teacher assistant; never sends documents to an AI provider. */
function teacherIntent(text){const s=normalizeArabic(text);const routes=[['lessons',/درس|تحضير|حصه/],['meetings',/اجتماع|محضر/],['projects',/مشروع/],['workplans',/خطه|خطة|خطط/],['tasks',/مهمه|مهمة|مهام/],['studio',/تصميم|فوتوشوب|ملصق/],['evidence',/شاهد|شواهد|انجاز/],['reports',/تقرير|تقارير/],['schedule',/تقويم|جدول|مواعيد/],['analysis',/تحليل|منهج|مناهج|مصدر|ابحث/],['resources',/مرجع|مراجع|رابط/],['settings',/نسخ|اعدادات/]];return routes.find(([,pattern])=>pattern.test(s))?.[0]||''}
(function(){
let flow=null,welcome=false,returnFocus=null,recognition=null;
const launcher=document.createElement('button');launcher.id='teacherLauncher';launcher.className='btn';launcher.textContent='✦ مساعد المعلم';launcher.setAttribute('aria-expanded','false');launcher.setAttribute('aria-controls','teacherAssistant');document.body.append(launcher);
const panel=document.createElement('aside');panel.id='teacherAssistant';panel.hidden=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-labelledby','teacherAssistantTitle');panel.innerHTML=`<header class="teacher-head"><div><strong id="teacherAssistantTitle">مساعد المعلم</strong><small>معك في التخطيط والتنفيذ والمتابعة</small></div><button type="button" class="btn secondary" id="teacherClose" aria-label="إغلاق مساعد المعلم">×</button></header><p class="teacher-note">مساعد إرشادي محلي يعتمد أدوات الموقع والنصوص المضافة. المحادثة التوليدية غير متصلة.</p><div class="teacher-chips"><button data-teacher-start="lessons">تحضير درس</button><button data-teacher-start="workplans">إعداد خطة</button><button data-teacher-start="projects">مشروع</button><button data-teacher-start="meetings">اجتماع</button><button data-teacher-go="analysis">تحليل المناهج</button><button data-teacher-go="studio">تصميم</button></div><div id="teacherMessages" role="log" aria-live="polite" aria-relevant="additions"></div><div class="teacher-controls"><button class="btn secondary" id="teacherCancel" type="button">إلغاء المسودة</button><button class="btn secondary" id="teacherNew" type="button">محادثة جديدة</button></div><form id="teacherChat"><label class="sr-only" for="teacherInput">طلبك للمساعد</label><textarea id="teacherInput" rows="2" maxlength="2000" placeholder="ما الذي تحتاجه اليوم؟"></textarea><div class="teacher-send"><button class="btn" type="submit">إرسال</button><button class="btn secondary" id="teacherMic" type="button" aria-label="إملاء صوتي">🎙</button></div></form>`;document.body.append(panel);
function say(text,user=false,actions=[]){const row=document.createElement('div');row.className='teacher-message '+(user?'teacher-user':'teacher-reply');const p=document.createElement('p');p.textContent=text;row.append(p);for(const a of actions){const b=document.createElement('button');b.className='btn secondary';b.textContent=a.label;b.onclick=a.run;row.append(b)}$('teacherMessages').append(row);$('teacherMessages').scrollTop=$('teacherMessages').scrollHeight}
function open(){returnFocus=document.activeElement;panel.hidden=false;launcher.setAttribute('aria-expanded','true');if(!welcome){say('أهلًا بك. أساعدك خطوة بخطوة في إعداد سجلاتك، أو البحث في مستنداتك مع رقم الصفحة. اختر خدمة أو اكتب طلبك.');welcome=true}$('teacherInput').focus()}
function close(){recognition?.abort();panel.hidden=true;launcher.setAttribute('aria-expanded','false');returnFocus?.focus()}
launcher.onclick=()=>panel.hidden?open():close();$('teacherClose').onclick=close;panel.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
function start(kind){flow={kind,index:0,values:{}};say('لنعدّ '+hubConfig[kind].singular+' معًا. اكتب «تخطي» للحقل الاختياري، أو ألغِ المسودة.');ask()}
function ask(){const f=hubConfig[flow.kind].fields[flow.index];if(!f){const draft=flow;flow.ready=true;say('راجع المسودة قبل الحفظ:\n'+hubConfig[draft.kind].fields.map(([k,label])=>label+': '+(draft.values[k]||'—')).join('\n'),false,[{label:'اعتماد وحفظ السجل',run:()=>commit(draft)},{label:'مراجعة في النموذج',run:()=>{if(flow!==draft)return;fillForm(draft);flow=null;say('فتحت المسودة في نموذج الخدمة. راجعها ثم احفظها من هناك.')}}]);return}const [key,label,type,optional]=f;const current=flow,index=flow.index;const guarded=v=>{if(flow===current&&flow.index===index&&!flow.ready)answer(v)};const actions=Array.isArray(type)?type.map(v=>({label:v,run:()=>guarded(v)})):[];if(type==='project'){actions.push({label:'مهمة مستقلة',run:()=>guarded('تخطي')});for(const p of data.hub.projects.slice(0,12))actions.push({label:p.name,run:()=>guarded(p.id)})}say(label+(type==='date'?' — بصيغة YYYY-MM-DD':type==='datetime-local'?' — بصيغة YYYY-MM-DDTHH:mm بتوقيت الكويت':'')+(optional?' (اختياري)':''),false,actions)}
function answer(text){if(!flow||flow.ready)return;const [key,label,type,optional]=hubConfig[flow.kind].fields[flow.index];let value=text==='تخطي'?'':text;if(!value&&!optional){say('هذا الحقل مطلوب: '+label);return}if(type==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(value)||type==='datetime-local'&&!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)){say('استخدم صيغة التاريخ المطلوبة.');return}if((type==='date'||type==='datetime-local')&&!Number.isFinite(Date.parse(value))){say('راجع التاريخ المدخل.');return}if(Array.isArray(type)&&!type.includes(value)){say('اختر إحدى القيم المعروضة.');return}if(type==='project'&&value&&!data.hub.projects.some(p=>p.id===value)){say('اختر المشروع من الأزرار أو اختر مهمة مستقلة.');return}flow.values[key]=value;flow.index++;ask()}
function fillForm(draft){resetHubForm(draft.kind);for(const [key,value] of Object.entries(draft.values))$(draft.kind+'_'+key).value=value;show(draft.kind)}
function commit(draft){if(flow!==draft||!draft.ready)return;const item={id:crypto.randomUUID(),...draft.values};const hub=upsertHub(data.hub,draft.kind,item);if(!validateHub(hub)){say('تعذر اعتماد البيانات؛ افتح النموذج وراجعها.');return}if(save({...data,hub})){flow=null;say('تم حفظ '+hubConfig[draft.kind].singular+' على هذا الجهاز.',false,[{label:'فتح السجل',run:()=>show(draft.kind)}])}else say('لم يُحفظ السجل. صدّر نسخة احتياطية وتحقق من مساحة المتصفح.')}
function search(text){const api=window.ManhajCurriculum;const hits=api?.search(text)||[];if(hits.length){say('هذه شواهد لفظية من المستند المحدد في التحليل، أو آخر خمسة مستندات مضافة. راجع النص في مصدره.');for(const h of hits)say(h.title+' — صفحة '+h.page+'\n'+h.text)}else{say('لم أجد شاهدًا مطابقًا في المستندات المضافة. أضف ملف المنهج النصي أو استخدم قسم التحليل.',false,[{label:'فتح التحليل والمناهج',run:()=>show('analysis')}])}}
$('teacherChat').onsubmit=e=>{e.preventDefault();const text=$('teacherInput').value.trim();if(!text)return;$('teacherInput').value='';say(text,true);if(flow){if(flow.ready)say('راجع المسودة واضغط اعتماد وحفظ، أو ألغِ المسودة للبدء مجددًا.');else answer(text);return}const kind=teacherIntent(text);if(hubConfig[kind]&&/راجع|مراجعه|مراجعة/.test(normalizeArabic(text))){const records=data.hub[kind].slice(-5);if(!records.length){say('لا توجد سجلات في هذا القسم بعد.');return}say('اختر السجل الذي تريد مراجعته.',false,records.map(r=>({label:r.name,run:()=>{const review=reviewTeacherRecord(kind,r,data.hub.tasks);say(r.name+'\n'+review.checks.map(c=>(c.ok?'✓ ':'• ')+c.message).join('\n')+'\n'+review.scope,false,[{label:'فتح القسم للمراجعة',run:()=>show(kind)}])}})));return}if(kind&&/اعرض|كم|متابعه|متابعة|مواعيد|تقارير/.test(normalizeArabic(text))){say(hubConfig[kind]?hubConfig[kind].title+': '+data.hub[kind].length+' سجل.':'افتح '+pages[kind]+' لعرض بيانات عملك.',false,[{label:'فتح '+pages[kind],run:()=>show(kind)}]);return}if(/ابحث|مصدر|ما هي|ماهي|اشرح|نواتج|اهداف/.test(normalizeArabic(text))){search(text);return}if(hubConfig[kind]&&kind!=='resources'){start(kind);return}if(kind){say('يمكنك استخدام '+pages[kind]+'.',false,[{label:'فتح '+pages[kind],run:()=>show(kind)}]);return}say('هل تريد إعداد درس، خطة، مشروع، اجتماع أو مهمة؟ أستطيع أيضًا توجيهك للتصميم والتقارير والشواهد والبحث في المناهج. للحوار التربوي المفتوح يلزم توصيل خدمة ذكاء اصطناعي.')};
panel.querySelectorAll('[data-teacher-start]').forEach(b=>b.onclick=()=>{if(flow){say('ألغِ المسودة الحالية أولًا أو أكملها.');return}start(b.dataset.teacherStart)});panel.querySelectorAll('[data-teacher-go]').forEach(b=>b.onclick=()=>show(b.dataset.teacherGo));$('teacherCancel').onclick=()=>{flow=null;say('أُلغيت المسودة؛ لم تُحفظ بياناتها.')};$('teacherNew').onclick=()=>{flow=null;$('teacherMessages').replaceChildren();welcome=false;open()};
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(Speech){recognition=new Speech();recognition.lang='ar-KW';recognition.interimResults=false;recognition.onresult=e=>{$('teacherInput').value=e.results[0][0].transcript;$('teacherInput').focus()};recognition.onend=()=>{$('teacherMic').textContent='🎙';$('teacherMic').disabled=false};recognition.onerror=e=>say('تعذر الإملاء الصوتي ('+e.error+'). يمكنك الكتابة.');$('teacherMic').onclick=()=>{say('قد يستخدم الإملاء خدمة المتصفح لمعالجة الصوت.');try{recognition.start();$('teacherMic').textContent='يستمع…';$('teacherMic').disabled=true}catch{say('تعذر بدء الإملاء.')}}}else{$('teacherMic').disabled=true;$('teacherMic').title='الإملاء غير مدعوم في هذا المتصفح'}
window.ManhajTeacher={teacherIntent,open,close};
})();
