(function(){
 const panel=document.createElement('section');panel.className='panel section';panel.id='curriculumAudit';panel.innerHTML='<h3>تدقيق قاعدة المناهج</h3><p>تحليل لتغطية الفهرس ومصادره؛ الطبعة والاعتماد للسنة الحالية يحتاجان تحققًا مستقلًا من الوثائق الرسمية.</p><div id="curriculumAuditSummary" role="status">جارٍ إعداد تقرير التغطية…</div><div class="table-wrap"><table><caption>التغطية بحسب أسماء المراحل في المصدر</caption><thead><tr><th>المرحلة</th><th>السجلات</th><th>المواد</th><th>الصفوف / المسارات</th><th>الفصل الأول</th><th>الفصل الثاني</th></tr></thead><tbody id="curriculumCoverage"></tbody></table></div><p id="curriculumAuditLimit" class="note"></p><div class="tools"><button class="btn secondary" type="button" id="curriculumAuditDownload">تنزيل تقرير التغطية</button><a class="btn secondary" href="https://elibrary.moe.edu.kw/NationalStandards" target="_blank" rel="noopener">مصفوفات المدى والتتابع الرسمية</a></div><h3>مصفوفات المدى والتتابع</h3><div class="field"><label for="standardSearch">بحث في بيانات المصفوفات</label><input type="search" id="standardSearch" placeholder="المادة أو المرحلة"></div><div id="standardRecords" class="list"></div><p class="muted">لتحليل المحتوى: أضف ملفًا مسموحًا باستخدامه من قسم التحليل، ثم اقرأه وابحث في صفحاته داخل الموقع.</p>';
 $('libraryView').append(panel);let report=null,standards=[];function renderStandards(){const q=analysisTokens($('standardSearch').value);$('standardRecords').innerHTML=standards.filter(s=>q.every(t=>normalizeArabic(s.title+' '+s.stage).includes(t))).map(s=>'<article class="task"><div><strong>'+esc(s.title)+'</strong><small>'+esc(s.stage)+' • بيانات مصدر رسمي؛ الطبعة غير مؤكدة</small></div><a class="btn secondary" href="'+esc(s.sourceUrl)+'" target="_blank" rel="noopener">فتح المصدر الرسمي</a></article>').join('')||'<p class="empty">لا توجد نتيجة مطابقة.</p>'}$('standardSearch').oninput=renderStandards;
 window.ManhajCurriculum.ready.then(async()=>{const response=await fetch('./data/curricula.json',{cache:'no-cache'});if(!response.ok)throw Error('fetch');const manifest=await response.json(),records=manifest.records;standards=manifest.audit?.standards||[];renderStandards();const coverage=[...new Set(records.map(r=>r.stage))].map(stage=>{const rows=records.filter(r=>r.stage===stage);return {stage,records:rows.length,subjects:new Set(rows.map(r=>r.subject)).size,grades:new Set(rows.map(r=>r.grade)).size,firstTerm:rows.filter(r=>r.term==='الأول').length,secondTerm:rows.filter(r=>r.term==='الثاني').length}});report={recordCount:records.length,uniqueSourceFiles:new Set(records.map(r=>r.sourceUrl)).size,subjects:new Set(records.map(r=>r.subject)).size,unknownEditions:records.filter(r=>!r.edition).length,currentYearVerified:0,lookupYearParameter:manifest.lookupYearParameter,generatedAt:manifest.generatedAt,sourceErrors:manifest.errors?.length||0,coverage,standardsCount:standards.length,standards,contentAnalysis:'metadata-only'};
 $('curriculumAuditSummary').textContent=report.recordCount+' سجل • '+report.uniqueSourceFiles+' ملف مصدر • '+report.subjects+' مسمى مادة في الفهرس • '+standards.length+' مصفوفة مدى وتتابع. آخر جمع: '+new Date(report.generatedAt).toLocaleDateString('ar-KW',{timeZone:'Asia/Kuwait'})+' • أخطاء المصادر: '+report.sourceErrors;
 $('curriculumCoverage').innerHTML=coverage.map(c=>'<tr><td>'+esc(c.stage)+'</td><td>'+c.records+'</td><td>'+c.subjects+'</td><td>'+c.grades+'</td><td>'+c.firstTerm+'</td><td>'+c.secondTerm+'</td></tr>').join('');$('curriculumAuditLimit').textContent='الطبعة غير مؤكدة في '+report.unknownEditions+' سجل. لم نتحقق من اعتماد أي طبعة للسنة الدراسية الحالية. قيمة البحث في واجهة المصدر ('+report.lookupYearParameter+') لا تثبت سنة اعتماد الكتاب. الأعداد تخص الفهرس الذي جُمع ولا تثبت اكتمال جميع مناهج الوزارة.';
 }).catch(()=>{$('curriculumAuditSummary').textContent='تعذر تحميل تقرير الفهرس. أعد المحاولة بعد تحديث الصفحة.'});
 $('curriculumAuditDownload').onclick=()=>{if(report)download(new Blob([JSON.stringify(report,null,2)],{type:'application/json;charset=utf-8'}),'manhaj-curriculum-audit.json')};
})();
