/* Local language and editorial rules, with review before any field changes. */
function editTeacherText(source,mode='proofread'){
 const changes=[];let text=String(source);const apply=(pattern,value,label)=>{const next=text.replace(pattern,value);if(next!==text){changes.push(label);text=next}};
 // Keep quoted passages, links and email addresses intact.
 const protectedParts=[];text=text.replace(/https?:\/\/[^\s]+|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}|«[^»]*»|"[^"\n]*"/g,s=>{protectedParts.push(s);return '\uE000'+(protectedParts.length-1)+'\uE001'});
 apply(/[ \t]+$/gm,'','حذف المسافات في نهاية السطر');apply(/^[ \t]+/gm,'','تنظيف بداية السطر');apply(/[ \t]{2,}/g,' ','توحيد المسافات');apply(/ +([،؛؟!])/g,'$1','ضبط المسافة قبل علامات الترقيم');apply(/([،؛؟!])(?=[\p{L}])/gu,'$1 ','إضافة مسافة بعد علامة الترقيم');
 const spelling=[[/بناءا على/g,'بناءً على','تصحيح بناءً على'],[/انشاء الله/g,'إن شاء الله','تصحيح إن شاء الله'],[/برجاء المراجعه/g,'برجاء المراجعة','تصحيح المراجعة'],[/الرجاء مراجعه/g,'الرجاء مراجعة','تصحيح مراجعة'],[/مراجعه الخطه/g,'مراجعة الخطة','تصحيح عبارة مراجعة الخطة']];spelling.forEach(([p,v,l])=>apply(p,v,l));
 if(mode!=='proofread'){
  const phrases=[[/(^|[\s،؛])راح نقوم بـ(?=\S)/g,'$1سنقوم بـ','تحويل عبارة عامية إلى صياغة رسمية'],[/(^|[\s،؛])نبي نوضح(?=$|[\s،.])/g,'$1نود توضيح','صياغة توضيحية رسمية'],[/(^|[\s،؛])نبي نناقش(?=$|[\s،.])/g,'$1نود مناقشة','صياغة المناقشة'],[/(^|[\s،؛])يرجى العلم بأنه(?=$|[\s،.])/g,'$1نحيطكم علمًا بأن','صياغة إدارية أوضح']];phrases.forEach(([p,v,l])=>apply(p,v,l));
 }
 if(mode==='concise'){
  apply(/(^|[\s،؛])في الوقت الحالي(?=$|[\s،.])/g,'$1حاليًا','اختصار عبارة زمنية');apply(/(^|[\s،؛])من أجل القيام بـ(?=\S)/g,'$1لـ','تقليل الحشو');apply(/(^|[\s،؛])وذلك بهدف(?=$|[\s،.])/g,'$1بهدف','اختصار العبارة دون حذف الهدف');
 }
 text=text.replace(/\uE000(\d+)\uE001/g,(_,i)=>protectedParts[Number(i)]);
 return {text,changes:[...new Set(changes)],scope:'قواعد تحرير محلية محدودة؛ راجع المعنى والأسماء قبل الاعتماد.'};
}
(function(){
 const micIcon='<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0014 0v-2M12 19v3M8 22h8"/></svg>';
 const supportedTypes=new Set(['text','search','email','url','tel','number','date','datetime-local','month','time']);
 const isWriting=el=>el.tagName==='TEXTAREA'||el.tagName==='INPUT'&&['text','search'].includes(el.type);
 const eligible=el=>!el.disabled&&!el.readOnly&&el.dataset.languageSkip!=='true'&&(el.tagName==='TEXTAREA'||el.tagName==='SELECT'||el.tagName==='INPUT'&&supportedTypes.has(el.type));
 const dialog=document.createElement('dialog');dialog.id='languageEditor';dialog.innerHTML=`<form method="dialog" class="language-dialog"><header><h3 id="languageTitle">مراجعة النص</h3><button class="btn secondary" value="cancel" aria-label="إغلاق محرر اللغة">×</button></header><p id="languageScope" class="muted"></p><div class="field"><label for="languageOriginal">النص الحالي</label><textarea id="languageOriginal" readonly rows="3"></textarea></div><div class="field"><label id="languageDraftLabel" for="languageDraft">الصياغة المقترحة — يمكنك تعديلها</label><textarea id="languageDraft" rows="5"></textarea><select id="languageSelect" hidden></select></div><ul id="languageChanges"></ul><p id="languageStatus" role="status"></p><div class="tools"><button type="button" class="btn" id="languageApply">اعتماد التعديل</button><button class="btn secondary" value="cancel">إلغاء</button></div></form>`;document.body.append(dialog);dialog.setAttribute('aria-labelledby','languageTitle');
 let target=null,original='',recording=null,lastUndo=new WeakMap(),returnFocus=null;
 function label(el){return el.labels?.[0]?.textContent.trim()||el.getAttribute('aria-label')||el.placeholder||'الحقل'}
 function open(el,draft,title,notes=[]){target=el;original=el.value;returnFocus=document.activeElement;$('languageTitle').textContent=title+' — '+label(el);$('languageOriginal').value=el.tagName==='SELECT'?(el.selectedOptions[0]?.textContent||''):original;const selecting=el.tagName==='SELECT';$('languageDraft').hidden=selecting;$('languageSelect').hidden=!selecting;$('languageDraftLabel').htmlFor=selecting?'languageSelect':'languageDraft';if(selecting){$('languageSelect').replaceChildren(...[...el.options].map(o=>o.cloneNode(true)));$('languageSelect').value=draft;if(!$('languageSelect').selectedOptions.length)$('languageSelect').selectedIndex=el.selectedIndex}$('languageDraft').value=draft;$('languageDraft').maxLength=el.maxLength>0?el.maxLength:10000;$('languageScope').textContent='التعديل يخص هذا الحقل فقط. راجعه قبل الاعتماد؛ لا يُحفظ السجل تلقائيًا.';$('languageChanges').replaceChildren();notes.forEach(note=>{const li=document.createElement('li');li.textContent=note;$('languageChanges').append(li)});$('languageStatus').textContent='';dialog.showModal();(el.tagName==='SELECT'?$('languageSelect'):$('languageDraft')).focus()}
 dialog.addEventListener('close',()=>{target=null;returnFocus?.focus()});
 function validValue(el,value){if(el.maxLength>0&&value.length>el.maxLength)return false;if(el.tagName==='SELECT')return [...el.options].some(o=>o.value===value&&!o.disabled);const probe=el.cloneNode();probe.removeAttribute('id');probe.value=value;return probe.value===value&&probe.checkValidity()}
 $('languageApply').onclick=()=>{if(!target?.isConnected)return dialog.close();if(target.value!==original){$('languageStatus').textContent='تغيّر الحقل بعد فتح المراجعة. أغلق النافذة وافتحها مجددًا حتى لا تُستبدل تعديلاتك.';return}const draft=target.tagName==='SELECT'?$('languageSelect').value:$('languageDraft').value;if(!validValue(target,draft)){$('languageStatus').textContent='تحقق من صيغة القيمة وطولها والحقول المطلوبة. '+(target.type==='date'?'التاريخ بصيغة YYYY-MM-DD.':target.type==='datetime-local'?'الموعد بصيغة YYYY-MM-DDTHH:mm.':'');return}lastUndo.set(target,{before:original,after:draft});target.value=draft;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}));dialog.close();toast('تم اعتماد التعديل في الحقل. احفظ السجل من النموذج عند الانتهاء.')};
 function review(el,mode){const result=editTeacherText(el.value,mode);open(el,result.text,mode==='proofread'?'مراجعة اللغة':mode==='formal'?'صياغة رسمية':'اختصار الصياغة',result.changes.length?result.changes:['لم ترصد القواعد المحلية تعديلًا مناسبًا. يمكنك تحرير النص يدويًا.']);$('languageScope').textContent=result.scope+' لا يُحفظ السجل تلقائيًا.'}
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
 function numeric(s){return s.replace(/[٠-٩۰-۹]/g,c=>String('٠١٢٣٤٥٦٧٨٩'.includes(c)?'٠١٢٣٤٥٦٧٨٩'.indexOf(c):'۰۱۲۳۴۵۶۷۸۹'.indexOf(c)))}
 function transcriptValue(el,s){s=s.trim();if(el.tagName==='SELECT'){const matches=[...el.options].filter(o=>!o.disabled&&normalizeArabic(o.textContent.trim())===normalizeArabic(s));return matches.length===1?matches[0].value:s}if(['number','tel','date','datetime-local','month','time'].includes(el.type))return numeric(s);if(['url','email'].includes(el.type))return s;const start=el.selectionStart??el.value.length,end=el.selectionEnd??start;const left=el.value.slice(0,start),right=el.value.slice(end);return left+(left&&!/\s$/.test(left)?' ':'')+s+(right&&!/^\s/.test(right)?' ':'')+right}
 function dictate(el,button){if(!Speech){toast('الإملاء الصوتي غير مدعوم في هذا المتصفح. يمكنك الكتابة أو استخدام ميكروفون لوحة المفاتيح.');return}if(recording){recording.recognition.stop();return}const recognition=new Speech(),snapshot=el.value;recording={recognition,button};recognition.lang='ar-KW';recognition.interimResults=false;recognition.maxAlternatives=1;button.classList.add('recording');button.setAttribute('aria-pressed','true');button.title='إيقاف التسجيل';recognition.onresult=e=>{if(el.value!==snapshot){toast('تغيّر الحقل أثناء التسجيل؛ أعد الإملاء للحفاظ على تعديلاتك.');return}const text=e.results[0][0].transcript;open(el,transcriptValue(el,text),'مراجعة الإملاء الصوتي',['النص المسموع: '+text,'راجع الأسماء والأرقام. الحقول المنظمة تتطلب صيغة صحيحة.'])};recognition.onerror=e=>toast(e.error==='not-allowed'?'لم يُسمح باستخدام الميكروفون؛ فعّل الإذن من إعدادات المتصفح.':'تعذر الإملاء الصوتي. يمكنك إعادة المحاولة أو الكتابة.');recognition.onend=()=>{button.classList.remove('recording');button.setAttribute('aria-pressed','false');button.title='إملاء صوتي — '+label(el);recording=null};toast('بدأ الإملاء. قد يستخدم المتصفح خدمة لمعالجة الصوت. اضغط الميكروفون للإيقاف.');try{recognition.start()}catch{recognition.onend();toast('تعذر بدء الميكروفون. أعد المحاولة.')}}
 function attach(el){if(!eligible(el)||el.closest('#languageEditor')||el.dataset.languageTools)return;el.dataset.languageTools='ready';if(!el.id)el.id='voiceField-'+crypto.randomUUID();if(isWriting(el)){el.lang='ar';el.spellcheck=true}const bar=document.createElement('div');bar.className='field-language-tools no-print';bar.setAttribute('role','group');bar.setAttribute('aria-label','أدوات '+label(el));const mic=document.createElement('button');mic.type='button';mic.className='field-mic';mic.innerHTML=micIcon;mic.title='إملاء صوتي — '+label(el);mic.setAttribute('aria-label',mic.title);mic.setAttribute('aria-pressed','false');mic.onclick=()=>dictate(el,mic);bar.append(mic);if(isWriting(el)){for(const [mode,title] of [['proofread','مراجعة اللغة'],['formal','صياغة رسمية'],['concise','اختصار']]){const b=document.createElement('button');b.type='button';b.textContent=title;b.onclick=()=>review(el,mode);bar.append(b)}const undo=document.createElement('button');undo.type='button';undo.textContent='تراجع';undo.onclick=()=>{const state=lastUndo.get(el);if(!state)return toast('لا يوجد تعديل معتمد للتراجع عنه.');if(el.value!==state.after)return toast('تغيّر النص بعد الاعتماد؛ لم يُستبدل حتى لا تفقد تعديلاتك.');el.value=state.before;lastUndo.delete(el);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));toast('تم التراجع عن آخر تعديل.')};bar.append(undo)}el.after(bar)}
 function enhance(root){if(root.matches?.('input,textarea,select'))attach(root);root.querySelectorAll?.('input,textarea,select').forEach(attach)}enhance(document);const observer=new MutationObserver(records=>{for(const record of records)record.addedNodes.forEach(node=>{if(node.nodeType===1)enhance(node)})});observer.observe(document.querySelector('.app')||document.body,{childList:true,subtree:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)recording?.recognition.abort()});
 window.ManhajLanguage={editTeacherText,enhance};
})();
