/* Internal reader for documents supplied by the user; no Ministry book mirroring. */
function readerScale(w,h,fit){if(!Number.isFinite(w)||!Number.isFinite(h)||w<=0||h<=0)throw Error('Invalid page dimensions');return Math.min(fit/w,8192/Math.max(w,h),Math.sqrt(16000000/(w*h)))}
(function(){
 const section=document.createElement('section');section.id='readerView';section.className='view';section.hidden=true;section.innerHTML=`<div class="panel section"><p class="muted">المكتبة الخاصة • قراءة وتحليل داخل منهج</p><h3 id="readerTitle">قارئ المستندات</h3><p id="readerMeta">اختر مستندًا أضفته إلى قاعدة التحليل.</p><div class="tools"><button class="btn secondary" data-go="analysis">إضافة مستند أو اختيار مستند</button><button class="btn secondary" id="readerAnalyze">تحليل المستند</button><button class="btn secondary" id="readerLesson">تحضير درس من الصفحة</button><button class="btn secondary" id="readerPlan">خطة مرتبطة بالمستند</button><button class="btn secondary" id="readerDownload">تنزيل الملف الأصلي</button></div><p id="readerStatus" role="status"></p></div><div class="panel section reader-panel"><div class="tools"><button class="btn secondary" id="readerPrevious">السابقة</button><div class="field"><label for="readerPage">رقم الصفحة</label><input id="readerPage" type="number" min="1" step="1" value="1"></div><span id="readerTotal"></span><button class="btn secondary" id="readerNext">التالية</button><button class="btn secondary" id="readerToggle">عرض الصفحة الأصلية</button></div><div id="readerCanvasWrap" hidden><canvas id="readerCanvas" aria-label="صورة صفحة المستند"></canvas></div><article id="readerText" dir="auto"></article><div class="field" style="margin-top:24px"><label for="readerQuestion">البحث داخل المستند</label><input id="readerQuestion" type="search" placeholder="اكتب كلمة أو موضوعًا"></div><button class="btn" id="readerSearch">بحث مع أرقام الصفحات</button><div id="readerHits" class="list" style="margin-top:18px"></div></div>`;document.querySelector('main').append(section);pages.reader='قارئ المستندات';const nav=document.createElement('button');nav.className='nav-btn';nav.dataset.go='reader';nav.innerHTML=uiIcon('library')+'<span>قارئ المستندات</span>';$('nav').querySelector('[data-go="library"]').after(nav);
 let doc=null,index=0,pdf=null,loading=null,pdfPromise=null,renderTask=null,revision=0,showImage=false;
 function status(s){$('readerStatus').textContent=s}
 async function release(){renderTask?.cancel();renderTask=null;if(loading)try{await loading.destroy()}catch{}loading=null;pdf=null;pdfPromise=null}
 async function open(id){const current=++revision;await release();const next=await window.ManhajCurriculum.getDocument(id);if(current!==revision)return;if(!next){status('لم يعد المستند موجودًا في القاعدة المحلية.');return}doc=next;index=0;showImage=false;$('readerHits').replaceChildren();$('readerQuestion').value='';$('readerTitle').textContent=doc.title;$('readerMeta').textContent=[doc.subject,doc.grade,doc.term?'الفصل '+doc.term:'','الطبعة: '+(doc.edition||'غير مؤكدة')].filter(Boolean).join(' · ');$('readerPage').max=doc.pages.length;$('readerDownload').disabled=!doc.originalFile;show('reader');status(doc.originalFile?'الملف محفوظ على هذا الجهاز، ويمكن قراءته هنا.':'هذا المستند يحتوي النص المستخرج فقط. أعد إضافة الملف للاحتفاظ بنسخته الأصلية.');await renderPage()}
 async function renderPage(){if(!doc)return;renderTask?.cancel();renderTask=null;$('readerPage').value=index+1;$('readerTotal').textContent='من '+doc.pages.length;$('readerPrevious').disabled=index===0;$('readerNext').disabled=index===doc.pages.length-1;$('readerText').textContent=doc.pages[index].text||'لا يوجد نص مستخرج في هذه الصفحة.';$('readerText').hidden=showImage;$('readerCanvasWrap').hidden=!showImage;$('readerToggle').disabled=!doc.originalFile||!/\.pdf$/i.test(doc.fileName);$('readerToggle').textContent=showImage?'عرض النص المستخرج':'عرض الصفحة الأصلية';if(!showImage)return;const current=revision,pageIndex=index;try{if(!pdf){if(!pdfPromise){const source=doc;status('جارٍ تحميل قارئ الصفحة…');pdfPromise=(async()=>{const module=await import('./vendor/pdfjs/pdf.mjs');if(current!==revision)return null;module.GlobalWorkerOptions.workerSrc=new URL('./vendor/pdfjs/pdf.worker.mjs',location.href).href;const bytes=new Uint8Array(await source.originalFile.arrayBuffer());if(current!==revision)return null;loading=module.getDocument({data:bytes,isEvalSupported:false,cMapUrl:new URL('./vendor/pdfjs/cmaps/',location.href).href,cMapPacked:true,standardFontDataUrl:new URL('./vendor/pdfjs/standard_fonts/',location.href).href});return loading.promise})()}const loaded=await pdfPromise;if(current!==revision||!loaded)return;pdf=loaded;}if(current!==revision||pageIndex!==index)return;const page=await pdf.getPage(doc.pages[index].number);if(current!==revision||pageIndex!==index)return;const natural=page.getViewport({scale:1}),width=Math.min(1600,Math.max(320,$('readerCanvasWrap').clientWidth||800)),viewport=page.getViewport({scale:readerScale(natural.width,natural.height,width)});const canvas=$('readerCanvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const task=page.render({canvasContext:canvas.getContext('2d'),viewport});renderTask=task;await task.promise;if(current===revision&&pageIndex===index)status('الصفحة الأصلية — راجعها عند اختلاف النص المستخرج.')}catch(e){if(current!==revision||e.name==='RenderingCancelledException')return;pdfPromise=null;showImage=false;$('readerCanvasWrap').hidden=true;$('readerText').hidden=false;status('تعذر عرض صورة الصفحة. النص المستخرج متاح، ويمكن تنزيل الملف الأصلي.')}}
 function changePage(next){if(!doc||!Number.isInteger(next)||next<0||next>=doc.pages.length)return;index=next;renderPage()}
 $('readerPrevious').onclick=()=>changePage(index-1);$('readerNext').onclick=()=>changePage(index+1);$('readerPage').onchange=()=>changePage(Number($('readerPage').value)-1);$('readerToggle').onclick=()=>{showImage=!showImage;renderPage()};
 $('readerSearch').onclick=()=>{if(!doc)return status('اختر مستندًا أولًا.');const hits=retrieveEvidence(doc.pages,$('readerQuestion').value,20);$('readerHits').innerHTML=hits.map(h=>`<article class="task"><div><p style="white-space:pre-wrap">${esc(h.text)}</p><small>${esc(doc.title)} — صفحة ${h.page}</small><button class="btn secondary" data-reader-page="${h.page}">الانتقال للصفحة</button></div></article>`).join('')||'<p class="empty">لم يُعثر على تطابق لفظي في النص المستخرج.</p>'};
 $('readerAnalyze').onclick=()=>{if(!doc)return status('اختر مستندًا أولًا.');$('analysisDocument').value=doc.id;show('analysis');$('analysisQuestion').value=$('readerQuestion').value;$('runAnalysis').click()};
 function prepare(kind){if(!doc)return status('اختر مستندًا أولًا.');resetHubForm(kind);const reference=doc.title+' — صفحة '+doc.pages[index].number+' — الطبعة '+(doc.edition||'غير مؤكدة');$(kind+'_name').value=(kind==='lessons'?'درس: ':'خطة: ')+doc.title.slice(0,150);if(kind==='lessons'){$('lessons_subject').value=doc.subject;$('lessons_grade').value=doc.grade;$('lessons_materials').value=reference;$('lessons_steps').value='مرجع الصفحة:\n'+doc.pages[index].text.slice(0,1800)+'\n\nخطوات الحصة المقترحة للمراجعة:\nالتهيئة:\nالنشاط:\nالمناقشة:\nالخاتمة:';const objectives=extractObjectives([doc.pages[index]]);$('lessons_goal').value=objectives[0]?.text||''}else{$('workplans_steps').value='المرجع: '+reference+'\nالأعمال المطلوبة:\nالموارد:\nمؤشر الإنجاز:\nالمتابعة:'}show(kind);toast('أُعدت مسودة مرتبطة بالمرجع. أكمل الهدف والتقويم والموعد وراجعها ثم احفظها.')}
 $('readerLesson').onclick=()=>prepare('lessons');$('readerPlan').onclick=()=>prepare('workplans');$('readerDownload').onclick=()=>{if(doc?.originalFile)download(doc.originalFile,doc.fileName)};
 document.addEventListener('click',e=>{const openButton=e.target.closest('[data-read-document]'),page=e.target.closest('[data-reader-page]');if(openButton)open(openButton.dataset.readDocument).catch(err=>status('تعذر فتح المستند: '+err.message));if(page&&doc){const n=doc.pages.findIndex(p=>p.number===Number(page.dataset.readerPage));changePage(n)}});window.addEventListener('hashchange',()=>{if(location.hash!=='#reader'){renderTask?.cancel();renderTask=null}});
 if(initialViewKey==='reader')show('reader');window.ManhajReader={open};
})();
