/* Service-first teacher interface inspired by Sahel's navigation pattern. */
(function(){
 document.documentElement.classList.add('sahel');
 const services=[
 ['teacherPath','مسار المعلم','lessons','اختر المرحلة والصف والمادة، ثم أنجز عملك من مكان واحد'],
 ['activity','المراحل والحصص والتكليفات','schedule','ملفات المراحل، استيراد المعلمين، جدول وتنبيهات، وخطاب تكليف موحّد'],
 ['analysis','المناهج والتحليل','library','استيراد ملفاتك، قراءتها، وتحويلها إلى عمل تعليمي'],
 ['studio','استوديو المعلم','studio','تصميم البطاقات والشهادات وأوراق العمل'],
 ['evidence','ملف الإنجاز','evidence','توثيق أعمالك بالصور وملفات PDF'],
 ['reports','التقارير','reports','تجميع سجلاتك وشواهدك للطباعة'],
 ['schedule','التقويم والمواعيد','schedule','الحصص والاجتماعات ومواعيد المشاريع في جدول واحد']
 ].map(([go,title,icon,desc])=>({go,title,icon,desc}));
 const header=document.createElement('header');header.className='sahel-header';header.innerHTML='<div class="sahel-header-inner"><div class="sahel-heading"><span class="sahel-logo" aria-hidden="true">م</span><div><span class="sahel-brand">منهج <small>نسخة الكويت</small></span><h1 id="appScreenTitle">الخدمات</h1></div></div><div class="sahel-header-actions"><button type="button" id="appTeacher" aria-label="فتح مساعد المعلم"><span class="sahel-action-icon">'+uiIcon('lessons')+'</span><span class="sahel-action-label">مساعد المعلم</span></button><button type="button" id="appMenu" aria-label="فتح قائمة الأدوات">☰</button></div></div>';document.body.prepend(header);
 $('appMenu').setAttribute('aria-controls','sidebar');$('appMenu').setAttribute('aria-expanded','false');$('appTeacher').onclick=()=>window.ManhajTeacher.open();$('appMenu').onclick=()=>{$('menuBtn').click();$('appMenu').setAttribute('aria-expanded',String($('sidebar').classList.contains('open')))};
 const home=$('homeView'),catalog=$('storeCatalog'),search=$('storeSearch'),browse=$('storeBrowse');
 const hero=document.createElement('section');hero.className='kuwait-home-hero';hero.setAttribute('aria-labelledby','kuwaitHeroTitle');hero.innerHTML='<div class="kuwait-hero-copy"><span class="kuwait-edition"><i aria-hidden="true"></i> مساحة المعلم الكويتي</span><h2 id="kuwaitHeroTitle">كل أعمالك التعليمية،<br><em>في مساحة واحدة.</em></h2><p>حضّر الدروس، خطّط للمشاريع، نظّم الاجتماعات، وحوّل ملفاتك إلى محتوى عملي بمساعدة ذكية تحافظ على تحكمك الكامل.</p><div class="kuwait-hero-actions"><button class="btn" data-go="teacherPath">ابدأ من مسار المعلم</button><button class="btn secondary" data-go="dashboard">عرض أعمالي</button></div><div class="kuwait-trust"><span>بياناتك على جهازك</span><span>محتوى قابل للتعديل</span><span>مصمم للمعلم</span></div></div><aside class="kuwait-work-preview" aria-label="ملخص أعمال المعلم"><div class="kuwait-preview-top"><span><i aria-hidden="true"></i> ملخصك المباشر</span><small id="kuwaitToday"></small></div><div class="kuwait-preview-stats"><div><strong id="kuwaitProjects">٠</strong><span>مشاريع</span></div><div><strong id="kuwaitLessons">٠</strong><span>دروس</span></div><div><strong id="kuwaitUpcoming">٠</strong><span>مواعيد قادمة</span></div></div><div class="kuwait-next"><span>الموعد القادم</span><strong id="kuwaitNextTitle">لا توجد مواعيد مسجلة</strong><small id="kuwaitNextDate">أضف موعدك الأول من التقويم</small></div><div class="kuwait-private">مساحتك شخصية، ولا يُنشر أي عمل دون اختيارك.</div></aside>';
 function renderHomeSummary(){const hub=data.hub||{},today=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kuwait'}),entries=typeof hubSchedule==='function'?hubSchedule().filter(item=>item.date.slice(0,10)>=today):[],next=entries[0],number=new Intl.NumberFormat('en-US');$('kuwaitProjects').textContent=number.format(hub.projects?.length||0);$('kuwaitLessons').textContent=number.format(hub.lessons?.length||0);$('kuwaitUpcoming').textContent=number.format(entries.length);$('kuwaitToday').textContent=new Intl.DateTimeFormat('ar-KW',{timeZone:'Asia/Kuwait',weekday:'long',day:'numeric',month:'long'}).format(new Date());$('kuwaitNextTitle').textContent=next?next.title:'لا توجد مواعيد مسجلة';$('kuwaitNextDate').textContent=next?(next.label+' • '+next.date.replace('T',' — ')):'أضف موعدك الأول من التقويم'}
 const intro=document.createElement('div');intro.className='sahel-search-area';intro.innerHTML='<label class="sr-only" for="serviceSearch">بحث في الخدمات</label><input id="serviceSearch" type="search" placeholder="بحث في الخدمات"><div class="sahel-home-heading"><h2>خدمات المعلم</h2><span>'+services.length+' قسمًا</span></div>';
 const list=document.createElement('div');list.id='serviceList';list.className='sahel-services';
 const models=document.createElement('div');models.className='sahel-model-access';models.innerHTML='<button class="btn secondary" id="showModels">النماذج والمختارات</button><button class="btn secondary" data-go="dashboard">ملخص أعمالي</button>';
 const searchLabel=document.createElement('label');searchLabel.htmlFor='storeSearch';searchLabel.textContent='بحث في النماذج';const catalogSearch=document.createElement('div');catalogSearch.className='field';search.removeAttribute('data-language-tools');catalogSearch.append(searchLabel,search);catalog.prepend(catalogSearch);catalog.classList.add('sahel-catalog');catalog.hidden=true;
 const teamsCard=document.createElement('button');teamsCard.type='button';teamsCard.id='teamsConnectCard';teamsCard.className='teams-connect-card';teamsCard.setAttribute('aria-haspopup','dialog');teamsCard.setAttribute('aria-controls','teamsConnectDialog');teamsCard.innerHTML='<span class="teams-connect-icon" aria-hidden="true">T</span><span><strong>اربط أعمالك مع تيمز</strong><small>شارك المحتوى والمشاريع مع طلابك</small></span><span class="teams-connect-action">إعداد الربط</span>';
 const teamsDialog=document.createElement('dialog');teamsDialog.id='teamsConnectDialog';teamsDialog.setAttribute('aria-labelledby','teamsConnectTitle');teamsDialog.innerHTML='<div class="teams-dialog-heading"><h2 id="teamsConnectTitle">اربط أعمالك مع تيمز</h2><button type="button" id="teamsConnectClose" aria-label="إغلاق">×</button></div><p class="note">المشاركة المباشرة إلى تيمز قيد التجهيز. يمكنك إعداد المحتوى ومراجعته الآن.</p><p>أنت تتحكم بمشاركة أعمالك مع طلابك من جميع الأقسام التعليمية.</p><h3>خطوات المشاركة للمعلم</h3><ol><li>اختر المحتوى الذي تريد مشاركته من القسم المناسب.</li><li>راجع العنوان والصياغة، واحذف أي ملاحظات خاصة بك.</li><li>عند تفعيل المشاركة، سجّل الدخول بحسابك في Microsoft Teams.</li><li>اختر الصف أو القناة التي تريد مشاركة المحتوى فيها.</li><li>راجع وجهة المشاركة وأكّد النشر بنفسك.</li></ol><p class="muted">أنت تختار ما تشاركه، ومع من، ومتى.</p><button class="btn" type="button" id="teamsConnectDone">حسنًا</button>';document.body.append(teamsDialog);teamsCard.onclick=()=>teamsDialog.showModal();$('teamsConnectClose').onclick=$('teamsConnectDone').onclick=()=>teamsDialog.close();teamsDialog.addEventListener('close',()=>teamsCard.focus());
 home.replaceChildren(hero,teamsCard,intro,list,models,catalog);renderHomeSummary();
 function renderServices(){const q=analysisTokens($('serviceSearch').value);const matches=services.filter(s=>q.every(t=>normalizeArabic(s.title+' '+s.desc).includes(t)));list.innerHTML=matches.map(s=>'<button class="sahel-service" '+(s.category?'data-store-category="'+s.category+'"':'data-go="'+s.go+'"')+'><span class="sahel-service-icon">'+uiIcon(s.icon)+'</span><span><strong>'+esc(s.title)+'</strong><small>'+esc(s.desc)+'</small></span><span class="sahel-service-action" aria-hidden="true">+</span></button>').join('')||'<p class="empty">لا توجد خدمة مطابقة للبحث.</p>'}
 renderServices();$('serviceSearch').oninput=renderServices;$('showModels').onclick=()=>{catalog.hidden=!catalog.hidden;$('showModels').setAttribute('aria-expanded',String(!catalog.hidden));if(!catalog.hidden)catalog.scrollIntoView?.({block:'start'})};$('showModels').setAttribute('aria-expanded','false');
 const nav=document.createElement('nav');nav.id='appTabs';nav.className='sahel-tabs';nav.setAttribute('aria-label','التنقل الرئيسي');nav.innerHTML=[['dashboard','بياناتي','dashboard'],['home','الخدمات','resources'],['tasks','المتابعة','tasks'],['schedule','المواعيد','schedule'],['settings','الإعدادات','settings']].map(([go,title,icon])=>'<button data-go="'+go+'">'+uiIcon(icon)+'<span>'+title+'</span></button>').join('');document.body.append(nav);
 const previousShow=show;show=function(k){previousShow(k);const route=location.hash.slice(1);$('appMenu').setAttribute('aria-expanded','false');$('appScreenTitle').textContent=route==='home'?'الخدمات':pages[route]||'منهج';let tab=route;if(route.startsWith('category-')||['teacherPath','activity','library','analysis','reader','studio','lessons','projects','workplans','meetings','events','plans','evidence','reports','resources'].includes(route))tab='home';nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.go===tab;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(route==='home'){renderHomeSummary();if(!catalog.hidden)$('showModels').setAttribute('aria-expanded','true')}};
 const oldBrowse=window.ManhajStorefront.browse;window.ManhajStorefront.browse=function(id){oldBrowse(id);if(id==='all'){catalog.hidden=false;$('showModels').setAttribute('aria-expanded','true')}};
 document.addEventListener('click',e=>{if(e.target.closest('[data-store-category="all"]')){catalog.hidden=false;$('showModels').setAttribute('aria-expanded','true')}});
 window.ManhajLanguage.enhance(document);show(location.hash.slice(1)||'home');window.ManhajServiceUI={services};
})();
