/* Service-first teacher interface inspired by Sahel's navigation pattern. */
(function(){
 document.documentElement.classList.add('sahel');
 const groups=[['planning','الخطط والتنظيم','workplans','خطط العمل والمهام ومواعيد المراجعة'],['teacher','المعلم والتحضير','lessons','تحضير الدروس وخطط الدعم والمراجع'],['administration','الإدارة والاجتماعات','meetings','محاضر الاجتماعات والقرارات والمتابعة'],['activities','الأنشطة والمشاريع','projects','المشاريع والمبادرات وتوثيق الأنشطة'],['occasions','المناسبات المدرسية','schedule','تنظيم المناسبات وبرامج التنفيذ'],['design','التصميم والشهادات','studio','شهادات وبطاقات نشاط وأوراق عمل']];
 const services=[...groups.map(([category,title,icon,desc])=>({category,title,icon,desc})),...[
 ['library','المناهج والمراجع','library','فهرس المواد والصفوف والمصادر'],['analysis','التحليل والمناهج','reports','تحليل مستنداتك ومراجعة اكتمال العمل'],['reader','القارئ الداخلي','library','قراءة ملفاتك والبحث في الصفحات'],['evidence','ملف الإنجاز والشواهد','evidence','توثيق الأعمال بالمرفقات'],['reports','التقارير','reports','تجميع سجلاتك وتصديرها للطباعة'],['resources','الموارد الخاصة','resources','مراجعك وروابطك وملاحظاتك']].map(([go,title,icon,desc])=>({go,title,icon,desc}))];
 const header=document.createElement('header');header.className='sahel-header';header.innerHTML='<div class="sahel-header-inner"><div><span class="sahel-brand">منهج</span><h1 id="appScreenTitle">الخدمات</h1></div><div class="sahel-header-actions"><button type="button" id="appTeacher" aria-label="مساعد المعلم">'+uiIcon('lessons')+'</button><button type="button" id="appMenu" aria-label="فتح قائمة الأدوات">☰</button></div></div>';document.body.prepend(header);
 $('appMenu').setAttribute('aria-controls','sidebar');$('appMenu').setAttribute('aria-expanded','false');$('appTeacher').onclick=()=>window.ManhajTeacher.open();$('appMenu').onclick=()=>{$('menuBtn').click();$('appMenu').setAttribute('aria-expanded',String($('sidebar').classList.contains('open')))};
 const home=$('homeView'),catalog=$('storeCatalog'),search=$('storeSearch'),browse=$('storeBrowse');
 const intro=document.createElement('div');intro.className='sahel-search-area';intro.innerHTML='<label class="sr-only" for="serviceSearch">بحث في الخدمات</label><input id="serviceSearch" type="search" placeholder="بحث في الخدمات"><div class="sahel-home-heading"><h2>خدمات المعلم</h2><span>'+services.length+' قسمًا</span></div>';
 const list=document.createElement('div');list.id='serviceList';list.className='sahel-services';
 const models=document.createElement('div');models.className='sahel-model-access';models.innerHTML='<button class="btn secondary" id="showModels">النماذج والمختارات</button><button class="btn secondary" data-go="dashboard">ملخص أعمالي</button>';
 const searchLabel=document.createElement('label');searchLabel.htmlFor='storeSearch';searchLabel.textContent='بحث في النماذج';const catalogSearch=document.createElement('div');catalogSearch.className='field';search.removeAttribute('data-language-tools');catalogSearch.append(searchLabel,search);catalog.prepend(catalogSearch);catalog.classList.add('sahel-catalog');catalog.hidden=true;
 home.replaceChildren(intro,list,models,catalog);
 function renderServices(){const q=analysisTokens($('serviceSearch').value);const matches=services.filter(s=>q.every(t=>normalizeArabic(s.title+' '+s.desc).includes(t)));list.innerHTML=matches.map(s=>'<button class="sahel-service" '+(s.category?'data-store-category="'+s.category+'"':'data-go="'+s.go+'"')+'><span class="sahel-service-icon">'+uiIcon(s.icon)+'</span><span><strong>'+esc(s.title)+'</strong><small>'+esc(s.desc)+'</small></span><span class="sahel-service-action" aria-hidden="true">+</span></button>').join('')||'<p class="empty">لا توجد خدمة مطابقة للبحث.</p>'}
 renderServices();$('serviceSearch').oninput=renderServices;$('showModels').onclick=()=>{catalog.hidden=!catalog.hidden;$('showModels').setAttribute('aria-expanded',String(!catalog.hidden));if(!catalog.hidden)catalog.scrollIntoView?.({block:'start'})};$('showModels').setAttribute('aria-expanded','false');
 const nav=document.createElement('nav');nav.id='appTabs';nav.className='sahel-tabs';nav.setAttribute('aria-label','التنقل الرئيسي');nav.innerHTML=[['dashboard','بياناتي','dashboard'],['home','الخدمات','resources'],['tasks','المتابعة','tasks'],['schedule','المواعيد','schedule'],['settings','الإعدادات','settings']].map(([go,title,icon])=>'<button data-go="'+go+'">'+uiIcon(icon)+'<span>'+title+'</span></button>').join('');document.body.append(nav);
 const previousShow=show;show=function(k){previousShow(k);const route=location.hash.slice(1);$('appMenu').setAttribute('aria-expanded','false');$('appScreenTitle').textContent=route==='home'?'الخدمات':pages[route]||'منهج';let tab=route;if(route.startsWith('category-')||['library','analysis','reader','studio','lessons','projects','workplans','meetings','events','plans','evidence','reports','resources'].includes(route))tab='home';nav.querySelectorAll('button').forEach(b=>{const active=b.dataset.go===tab;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});if(route==='home'&&!catalog.hidden)$('showModels').setAttribute('aria-expanded','true')};
 const oldBrowse=window.ManhajStorefront.browse;window.ManhajStorefront.browse=function(id){oldBrowse(id);if(id==='all'){catalog.hidden=false;$('showModels').setAttribute('aria-expanded','true')}};
 document.addEventListener('click',e=>{if(e.target.closest('[data-store-category="all"]')){catalog.hidden=false;$('showModels').setAttribute('aria-expanded','true')}});
 window.ManhajLanguage.enhance(document);show(location.hash.slice(1)||'home');window.ManhajServiceUI={services};
})();
