/* Compositor package bridge: image-layer schema from upstream writing-comp-files.md. */
function designZip(files){const enc=new TextEncoder(),chunks=[],central=[];let offset=0;function header(size){const a=new Uint8Array(size);return [a,new DataView(a.buffer)]}function crc(bytes){let n=0xffffffff;for(const b of bytes){n^=b;for(let j=0;j<8;j++)n=(n>>>1)^((n&1)?0xedb88320:0)}return (n^0xffffffff)>>>0}for(const f of files){const name=enc.encode(f.name),bytes=f.bytes,sum=crc(bytes);const [a,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,0x21,true);v.setUint32(14,sum,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);chunks.push(a,name,bytes);const [c,cv]=header(46);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint16(14,0x21,true);cv.setUint32(16,sum,true);cv.setUint32(20,bytes.length,true);cv.setUint32(24,bytes.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);central.push(c,name);offset+=30+name.length+bytes.length}const length=central.reduce((a,c)=>a+c.length,0),[end,ev]=header(22);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,length,true);ev.setUint32(16,offset,true);return new Blob([...chunks,...central,end],{type:'application/zip'})}
function designManifest(layers,w,h){return {format:'com.compositor.project',version:11,colorSpace:'sRGB',documentID:crypto.randomUUID().toUpperCase(),width:w,height:h,resolution:150,activeLayerID:layers.at(-1).id,layers:layers.map(l=>({id:l.id,name:l.name,imageFile:l.id+'.png',isVisible:true,isGroup:false,opacity:1,blendMode:'Normal',transform:{origin:[0,0],size:[w,h],rotation:0,flipX:false,flipY:false,sampling:'High quality'}}))}}
window.ManhajDesign={designZip,designManifest};
(()=>{let image=null,logo=null,layers=[],busy=false;const sizes={square:[1080,1080],wide:[1920,1080],a4:[1240,1754]};const canvas=$('designCanvas'),status=$('designStatus');const ui=['designType','designSize','designTitle','designSchool','designTeacher','designColor','designText'];
function layer(name,w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'));return {id:crypto.randomUUID().toUpperCase(),name,canvas:c}}
function fitImage(ctx,img,x,y,w,h){const ratio=Math.min(w/img.width,h/img.height);ctx.drawImage(img,x+(w-img.width*ratio)/2,y+(h-img.height*ratio)/2,img.width*ratio,img.height*ratio)}
function writeLines(ctx,text,right,y,width,size,bottom){ctx.font=`600 ${size}px Cairo, Tahoma, Arial`;ctx.textAlign='right';ctx.direction='rtl';for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText(word).width>width)throw Error('هناك كلمة أو رابط طويل؛ قصّره أو ضع مسافات لتجنب قص النص.');const next=line?line+' '+word:word;if(ctx.measureText(next).width>width&&line){if(y>bottom)throw Error('النص أطول من مساحة التصميم. اختصره أو اختر مقاس A4.');ctx.fillText(line,right,y);y+=size*1.6;line=word}else line=next}if(y>bottom)throw Error('النص أطول من مساحة التصميم. اختصره أو اختر مقاس A4.');ctx.fillText(line,right,y);y+=size*1.6}return y}
async function renderDesign(){await document.fonts.ready;const [w,h]=sizes[$('designSize').value],scale=Math.min(w,h)/1080,pad=80*scale,color=$('designColor').value;const list=[];list.push(layer('الخلفية',w,h,c=>{c.fillStyle='#faf9f5';c.fillRect(0,0,w,h)}));list.push(layer('الإطار والهوية',w,h,c=>{c.fillStyle=color;c.fillRect(0,0,w,24*scale);c.strokeStyle=color;c.lineWidth=3*scale;c.strokeRect(35*scale,45*scale,w-70*scale,h-90*scale);c.globalAlpha=.08;c.fillStyle=color;c.fillRect(pad,h-130*scale,w-2*pad,65*scale)}));const imageY=265*scale,imageH=image?Math.min(h*.29,330*scale):0;if(image)list.push(layer('الصورة التوضيحية',w,h,c=>fitImage(c,image,pad,imageY,w-2*pad,imageH)));if(logo)list.push(layer('شعار المدرسة',w,h,c=>fitImage(c,logo,pad,75*scale,100*scale,100*scale)));list.push(layer('النصوص العربية',w,h,c=>{c.fillStyle=color;const title=$('designTitle').value.trim();if(!title)throw Error('أدخل عنوان التصميم');c.font=`800 ${54*scale}px Cairo, Tahoma, Arial`;c.direction='rtl';c.textAlign='right';if(c.measureText(title).width>w-2*pad-(logo?120*scale:0))throw Error('العنوان طويل. اختصره حتى يظهر كاملًا.');c.fillText(title,w-pad,140*scale);c.fillStyle='#4b555b';const school=$('designSchool').value.trim();if(c.measureText(school).width>w-2*pad)throw Error('اسم المدرسة طويل');c.font=`600 ${30*scale}px Cairo, Tahoma, Arial`;c.fillText(school,w-pad,205*scale);const start=image?imageY+imageH+70*scale:300*scale;c.fillStyle='#17272b';writeLines(c,$('designText').value,w-pad,start,w-2*pad,34*scale,h-185*scale);c.fillStyle=color;c.font=`600 ${28*scale}px Cairo, Tahoma, Arial`;const footer=$('designTeacher').value.trim()?'إعداد المعلم: '+$('designTeacher').value.trim():'إعداد عبر منهج — مساحة المعلم الكويتي';if(c.measureText(footer).width>w-2*pad)throw Error('اسم المعلم طويل');c.fillText(footer,w-pad,h-85*scale)}));canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');list.forEach(l=>ctx.drawImage(l.canvas,0,0));layers=list;status.textContent='المعاينة جاهزة. راجع الإملاء والحروف العربية قبل التنزيل.';return {w,h}}
async function action(fn){if(busy)return;busy=true;try{await fn()}catch(e){status.textContent=e.message||'تعذر إعداد التصميم';toast(status.textContent)}finally{busy=false}}
async function loadImage(input,kind){const file=input.files[0];if(!file)return;await action(async()=>{if(file.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('اختر صورة PNG أو JPEG أو WebP حتى ٥ ميغابايت');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('ملف الصورة غير صالح'));i.src=url});if(img.width*img.height>24000000)throw Error('أبعاد الصورة كبيرة؛ صغّرها قبل الرفع');if(kind==='logo')logo=img;else image=img;await renderDesign()}finally{URL.revokeObjectURL(url)}})}
$('designImage').onchange=e=>loadImage(e.target,'image');$('designLogo').onchange=e=>loadImage(e.target,'logo');$('clearDesignImage').onclick=()=>{image=null;$('designImage').value='';action(renderDesign)};$('clearDesignLogo').onclick=()=>{logo=null;$('designLogo').value='';action(renderDesign)};$('designForm').onsubmit=e=>{e.preventDefault();action(renderDesign)};ui.filter(k=>k!=='designType').forEach(k=>$(k).addEventListener('change',()=>action(renderDesign)));
$('designType').onchange=()=>{const t=$('designType').value;$('designTitle').value=t==='certificate'?'شهادة تقدير':t==='worksheet'?'ورقة عمل':'بطاقة نشاط تعليمي';$('designText').value=t==='certificate'?'تقديرًا للجهد والمشاركة الفاعلة في النشاط المدرسي.\nعنوان النشاط: ................................\nالتاريخ: ................................':t==='worksheet'?'المادة: ....................    الصف: ....................\nالهدف التعليمي: ................................\nالسؤال الأول: ................................\nالإجابة: ................................\nالسؤال الثاني: ................................\nالإجابة: ................................':'الهدف: تعزيز مهارات القراءة والتحليل.\nخطوات النشاط: اقرأ النص، ناقش الفكرة، ثم دوّن خلاصة ما تعلمته.';if(t==='worksheet')$('designSize').value='a4';action(renderDesign)};
function canvasBlob(c){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('تعذر تصدير الصورة')),'image/png'))}$('designPng').onclick=()=>action(async()=>{await renderDesign();download(await canvasBlob(canvas),'manhaj-teacher-design.png');status.textContent='تم تجهيز PNG للتنزيل'});$('designComp').onclick=()=>action(async()=>{const {w,h}=await renderDesign(),root='Manhaj-Teacher.comp/',manifest=designManifest(layers,w,h),enc=new TextEncoder();const files=[{name:root+'manifest.json',bytes:enc.encode(JSON.stringify(manifest,null,2))}];for(const l of layers)files.push({name:root+'images/'+l.id+'.png',bytes:new Uint8Array(await (await canvasBlob(l.canvas)).arrayBuffer())});files.push({name:'README.txt',bytes:enc.encode('فك الضغط ثم افتح Manhaj-Teacher.comp في Compositor على ماك. النصوص طبقات صور.\n')});download(designZip(files),'manhaj-compositor.zip');status.textContent='الحزمة جاهزة. فك الضغط وافتح مجلد .comp في Compositor على ماك.'});
document.addEventListener('click',e=>{const b=e.target.closest('[data-design-event]');if(!b)return;const item=data.events.find(x=>x.id===b.dataset.designEvent);if(!item)return;$('designTitle').value=item.name;$('designSchool').value=data.plan.school||'';$('designTeacher').value=item.owner;$('designText').value='المادة: '+item.subject+'\nالتاريخ: '+item.date+'\nالهدف: '+item.goal;show('studio');action(renderDesign)});
if(data.plan.school)$('designSchool').value=data.plan.school;action(renderDesign);
})();
