/* Preparing Teams exports does not grant Microsoft permissions or publish data. */
(function(){
 const sections=['projects','workplans','meetings','tasks','lessons','plans','events','library','analysis','reader','studio','evidence','reports','resources'];
 const dialog=document.createElement('dialog');dialog.id='teamsExportDialog';dialog.setAttribute('aria-labelledby','teamsExportTitle');dialog.innerHTML='<header><h2 id="teamsExportTitle">تصدير المحتوى إلى تيمز</h2><button type="button" id="teamsExportClose" aria-label="إغلاق">×</button></header><p id="teamsExportSection"></p><p class="note">المشاركة المباشرة إلى تيمز قيد التجهيز. جهّز المحتوى وراجعه بنفسك قبل مشاركته مع طلابك.</p><div class="field"><label for="teamsExportRecord">١. اختر المحتوى التعليمي</label><select id="teamsExportRecord"></select></div><div class="field"><label for="teamsExportMode">٢. اختر طريقة المشاركة</label><select id="teamsExportMode"><option value="post">منشور في قناة الصف</option><option value="assignment">واجب دراسي</option><option value="file">ملف تعليمي</option></select></div><div class="field"><label for="teamsExportHeading">٣. اكتب عنوان المحتوى للطلاب</label><input id="teamsExportHeading" type="text" maxlength="200"></div><div class="field"><label for="teamsExportBody">٤. راجع صياغة المحتوى وعدّلها</label><textarea id="teamsExportBody" rows="8" maxlength="20000"></textarea></div><p class="muted">راجع المحتوى واحذف ملاحظات المعلم أو البيانات الخاصة قبل مشاركته مع الطلاب.</p><p id="teamsExportHint" role="status"></p><div class="tools"><button type="button" class="btn secondary" id="teamsExportDraft">تنزيل مسودة المحتوى</button><button type="button" class="btn" disabled title="المشاركة المباشرة إلى تيمز قيد التجهيز">نشر إلى تيمز — غير مفعّل</button></div><p class="muted">عند تفعيل المشاركة، تسجّل الدخول بحسابك في تيمز، وتختار الصف أو القناة، ثم تؤكّد النشر بنفسك.</p>';
 document.body.append(dialog);let currentSection='',records=[],returnFocus=null;
 function rowsFor(k){if(data.hub?.[k])return data.hub[k].map(r=>({id:r.id,title:r.name,text:hubConfig[k].fields.filter(([f])=>!['name','owner','attendees','minutes','state','project'].includes(f)).map(([f,label])=>r[f]?label+': '+r[f]:'').filter(Boolean).join('\n\n')}));if(k==='events')return data.events.map(r=>({id:r.id,title:r.name,text:['المادة: '+r.subject,'التاريخ: '+r.date,'الهدف: '+r.goal].join('\n\n')}));if(k==='plans')return [{id:'plan',title:'خطة الأنشطة التعليمية',text:['المدرسة: '+(data.plan.school||''),'المرحلة: '+(data.plan.stage||''),'الفصل: '+(data.plan.term||''),'الهدف: '+(data.plan.goal||'')].join('\n\n')}];if(k==='studio')return [{id:'design',title:$('designTitle').value,text:$('designText').value}];return []}
 function fill(){const r=records.find(r=>r.id===$('teamsExportRecord').value);$('teamsExportHeading').value=r?.title||'';$('teamsExportBody').value=r?.text||''}
 function open(k){currentSection=k;returnFocus=document.activeElement;records=rowsFor(k);$('teamsExportSection').textContent='القسم: '+pages[k];$('teamsExportRecord').innerHTML='<option value="">اكتب محتوى تعليميًا جديدًا</option>'+records.map(r=>'<option value="'+esc(r.id)+'">'+esc(r.title)+'</option>').join('');if(records.length)$('teamsExportRecord').value=records[0].id;fill();$('teamsExportHint').textContent=k==='studio'?'يمكنك تنزيل الصورة من الاستوديو لإرفاقها عند تفعيل النشر.':records.length?'تُجهّز المسودة من السجل المختار. لا يتغيّر السجل الأصلي.':'اكتب المحتوى المسموح بمشاركته. لا تُنسخ المستندات أو الشواهد أو التقارير تلقائيًا.';window.ManhajLanguage.enhance(dialog);dialog.showModal()}
 for(const k of sections){const view=$(k+'View');if(!view)continue;const bar=document.createElement('div');bar.className='teams-export-bar no-print';const b=document.createElement('button');b.type='button';b.className='btn secondary';b.dataset.teamsExport=k;b.textContent='تصدير إلى تيمز';b.onclick=()=>open(k);bar.append(b);view.prepend(bar)}
 $('teamsExportRecord').onchange=fill;$('teamsExportClose').onclick=()=>dialog.close();dialog.addEventListener('close',()=>returnFocus?.focus());$('teamsExportDraft').onclick=()=>{const title=$('teamsExportHeading').value.trim(),text=$('teamsExportBody').value.trim();if(!title||!text){$('teamsExportHint').textContent='أدخل عنوانًا ومحتوى للمسودة.';return}download(new Blob([title+'\n\n'+text],{type:'text/plain;charset=utf-8'}),'manhaj-teams-draft.txt');$('teamsExportHint').textContent='تم تجهيز المسودة للتنزيل. لم تُرسل إلى Teams.'};
 window.ManhajLanguage.enhance(dialog);window.ManhajTeamsExport={sections,open};
})();
