"use client";
import { useOfficeRequest } from "./office-request";
import { useEffect, useState } from "react";
import {readResponse} from "./office-tools";
import { useI18n } from "./i18n";
type Review = {canExport?:boolean;versionNumber?:number;fileType?:string;hasOcr?:boolean;ocrQuality?:number|null;issueDate?:string;state:string;label:string;version:string;checkedAt:string|null;reviewer:string|null;canCite:boolean};
export default function DocumentReviewPanel({id,onDeleted}:{id:number;onDeleted?:()=>void}) {
  const { request, guest } = useOfficeRequest();

 const {t}=useI18n();const [review,setReview]=useState<Review|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [confirmed,setConfirmed]=useState(false);const [canApprove,setCanApprove]=useState(false);const [history,setHistory]=useState<Array<{action:string;date:string;actor:string}>>([]);const [originalAllowed,setOriginalAllowed]=useState(false);const [owned,setOwned]=useState(false);
 useEffect(()=>{let active=true;request("/api/legal/review?id="+id,{cache:"no-store"}).then(async r=>{const d=await readResponse<{review:Review;canApprove:boolean;document:{officeId:string|null;fileScanStatus:string};history:Array<{action:string;date:string;actor:string}>;error?:string}>(r);if(active){setReview(d.review);setCanApprove(d.canApprove);setHistory(d.history);setOwned(Boolean(d.document.officeId));setOriginalAllowed(!d.document.officeId||d.document.fileScanStatus==="text_clean");}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
 async function action(action:string,state?:string){setBusy(true);setError("");try{const r=await request("/api/legal/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action,state,version:review?.version,confirmed})});const d=await readResponse<{review:Review;canApprove:boolean;error?:string;message?:string;text?:string}>(r);if(!r.ok)throw new Error(d.error);if(d.review)setReview(d.review);if(d.text){if(action==="export"){const url=URL.createObjectURL(new Blob([d.text],{type:"text/plain;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="legal-document.txt";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else{await navigator.clipboard.writeText(d.text);}}else if(d.message)setError(d.message);setConfirmed(false);}catch(e){setError(e instanceof Error?e.message:t("تعذّر الحفظ"));}finally{setBusy(false);}}
 return <section className="review-panel" aria-label={t("مراجعة الوثيقة")} aria-busy={busy}>
 <strong>{t(review?.label||"جارٍ التحقق")}</strong><p>{t("النسخة")}: {review?.versionNumber || "—"} · {t("نوع الملف")}: {review?.fileType==="pdf"?"PDF":review?.fileType==="txt"?t("ملف نصي"):review?.fileType==="md"?"Markdown":t("غير محدد")} · {t("تاريخ الإصدار")}: {review?.issueDate || "—"}</p><p>{t("استخراج OCR")}: {t(review?.hasOcr?"نعم":"لا")} · {t("جودة OCR")}: {review?.ocrQuality ?? t("غير مقاسة")}</p>
 {review?.reviewer&&<p>{t("المراجع")}: {review.reviewer} · {review.checkedAt}</p>}
 {review&&review.state!=="verified"&&<p>{t("الاقتباس والتصدير مقفلان حتى اعتماد هذه النسخة.")}</p>}
 {review?.state==="verified"&&!review.canCite&&!review.canExport&&<p>{t("الوثيقة معتمدة، لكن دورك لا يسمح بالاقتباس أو التصدير.")}</p>}
 <div className="result-actions">{!guest&&originalAllowed&&review?.state!=="archived"&&(canApprove||review?.state==="verified")&&<a className="button subtle" href={"/api/legal/original?id="+id}>{t("فتح المصدر الأصلي")}</a>}<button className="button subtle" disabled={busy||!review} onClick={()=>action("request")}>{t("طلب مراجعة")}</button><button className="button subtle" disabled={busy||!review?.canCite} onClick={()=>action("cite")}>{t("نسخ اقتباس موثّق")}</button><button className="button subtle" disabled={busy||!review?.canExport} onClick={()=>action("export")}>{t("تصدير وثيقة")}</button></div>
 {canApprove&&<><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{t("راجعت النص كاملاً وطابقته بالمصدر الأصلي")}</label><div className="result-actions"><button className="button primary" disabled={busy||!confirmed} onClick={()=>action("review","verified")}>{t("اعتماد الوثيقة")}</button><button className="button subtle" disabled={busy||!confirmed} onClick={()=>action("review","not_citable")}>{t("غير صالح للاقتباس القضائي")}</button><button className="button subtle" disabled={busy||!confirmed} onClick={()=>action("review","archived")}>{t("أرشفة")}</button></div></>}
 {canApprove&&owned&&<button type="button" className="text-button danger-text" disabled={busy} onClick={async()=>{if(!window.confirm(t("هل تريد حذف هذه الوثيقة نهائياً؟")))return;setBusy(true);try{await readResponse(await request('/api/legal/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version:review?.version,confirmed:true})}));onDeleted?.();}catch(e){setError(e instanceof Error?e.message:'تعذّر حذف الوثيقة.');}finally{setBusy(false);}}}>{t("حذف الوثيقة")}</button>}
 {history.length>0&&<details><summary>{t("سجل مراجعات الوثيقة")}</summary><ul>{history.map((h,i)=><li key={i}>{t(h.action==="document_review"?"مراجعة الوثيقة":h.action==="copy_citation"?"نسخ اقتباس موثّق":h.action==="export_document"?"تصدير وثيقة":h.action==="upload_document"?"رفع وثيقة":"عملية إدارية مسجلة")} · {h.actor} · <time>{h.date}</time></li>)}</ul></details>}
 {error&&<p role="status">{t(error)}</p>}
 </section>;
}
