"use client";
import { useOfficeRequest } from "./office-request";
import {useEffect,useState,useRef,type FormEvent} from "react";
import {useI18n} from "./i18n";
export async function readResponse<T>(response:Response):Promise<T>{const value=await response.json() as T & {error?:string};if(!response.ok)throw new Error(value.error||"تعذّر إكمال الطلب.");return value;}
type Contact={type:string;masked:string;configured:boolean;canManage:boolean};
export function OfficeContact({settings=false}:{settings?:boolean}){
  const { request, guest } = useOfficeRequest();

 const {t}=useI18n();const [contact,setContact]=useState<Contact|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;request('/api/office/contact').then(readResponse<Contact>).then(c=>{if(active)setContact(c);}).catch(()=>{});return()=>{active=false;};},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setBusy(true);setMessage('');try{await readResponse(await request('/api/office/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(data))}));setContact(await readResponse<Contact>(await request('/api/office/contact')));form.reset();setMessage('تم حفظ إعدادات الاتصال.');}catch(e){setMessage(e instanceof Error?e.message:'تعذّر الحفظ');}finally{setBusy(false);}}
 if(!contact)return null;
 if(!settings)return !guest&&contact.configured?<a className="sidebar-signout" href="/api/office/contact?open=1">{t("تواصل مع إدارة المكتب")}</a>:null;
 return <section className="panel office-tool"><h3>{t("الاتصال والخصوصية")}</h3><p dir="ltr">{contact.masked||t("لم تُضف وسيلة اتصال")}</p>{contact.canManage&&<form onSubmit={save}><label><span>{t("نوع الاتصال")}</span><select name="type" defaultValue={contact.type}><option value="none">{t("إخفاء الاتصال")}</option><option value="email">{t("البريد")}</option><option value="phone">{t("الهاتف")}</option></select></label><label><span>{t("وسيلة الاتصال الجديدة")}</span><input name="value" dir="ltr" autoComplete="off" placeholder="+965…"/></label><button className="button primary" disabled={busy}>{t(busy?'جارٍ الحفظ...':'حفظ')}</button></form>}{message&&<p role="status">{t(message)}</p>}</section>;
}
export function UploadDocument({cases,onUploaded}:{cases:Array<{id:number;caseNumber:string}>;onUploaded:(id:number)=>void}){
  const { request, guest } = useOfficeRequest();

 const {t}=useI18n();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage('');try{const d=await readResponse<{id:number;message:string}>(await request('/api/legal/upload',{method:'POST',body:new FormData(form)}));form.reset();setMessage(d.message);onUploaded(d.id);}catch(e){setMessage(e instanceof Error?e.message:'تعذّر رفع الملف');}finally{setBusy(false);}}
 return <section className="panel office-tool" id="document-upload"><h3>{t("رفع وثيقة")}</h3><p>{t("النصوص TXT وMD قابلة للمراجعة. ملفات PDF تُعزل حتى اكتمال الفحص والاستخراج.")}</p><form onSubmit={upload}><label><span>{t("عنوان الوثيقة")}</span><input name="title" maxLength={240}/></label><label><span>{t("الملف")}</span><input name="file" type="file" accept=".txt,.md,.pdf" required/></label><label><span>{t("تاريخ الإصدار")}</span><input name="issueDate" type="date"/></label><label><span>{t("القضية المرتبطة")}</span><RecordPicker resource="cases" name="caseId" options={cases.map(c=>({id:c.id,label:c.caseNumber}))}/></label><button className="button primary" disabled={busy}>{t(busy?'جارٍ رفع الملف...':'رفع وثيقة')}</button></form>{message&&<p role="status">{t(message)}</p>}</section>;
}
const ACTIONS:Record<string,string>={delete_document:'حذف الوثيقة',export_memo:'تصدير مذكرة',copy_memo:'نسخ مذكرة',open_original:'فتح المصدر الأصلي',document_review:'مراجعة الوثيقة',upload_document:'رفع وثيقة',export_document:'تصدير وثيقة',copy_citation:'نسخ اقتباس موثّق',request_document_review:'طلب مراجعة',update_contact:'تعديل إعدادات الاتصال',open_contact:'فتح وسيلة الاتصال',create_memo:'إنشاء مذكرة',login:'تسجيل الدخول',update_member:'تعديل صلاحيات العضو',update_invoices:'تعديل فاتورة',create_invoices:'إنشاء فاتورة',delete_invoices:'حذف فاتورة'};
export function AuditPanel(){
  const { request, guest } = useOfficeRequest();
const {t}=useI18n();const [page,setPage]=useState(1);const [rows,setRows]=useState<Array<{id:string;action:string;date:string;actor:string}>>([]);const [more,setMore]=useState(false);const [error,setError]=useState('');const [loaded,setLoaded]=useState(false);useEffect(()=>{let active=true;request('/api/office/audit?page='+page).then(readResponse<{rows:typeof rows;hasMore:boolean}>).then(d=>{if(active){setRows(d.rows);setMore(d.hasMore);setLoaded(true);setError('');}}).catch(e=>{if(active){setError(e.message);setLoaded(true);}});return()=>{active=false;};},[page]);return <section className="panel office-tool"><h3>{t("سجل التدقيق")}</h3>{!loaded?<div className="skeleton-row"/>:error?<p role="alert">{t(error)}</p>:rows.length?rows.map(r=><p key={r.id}>{t(ACTIONS[r.action]||'عملية إدارية مسجلة')} · {r.actor} · <time>{r.date}</time></p>):<p>{t("لا توجد عمليات مسجلة بعد")}</p>}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>{t("السابق")}</button><span>{page}</span><button disabled={!more} onClick={()=>setPage(page+1)}>{t("التالي")}</button></div></section>}

type Choice={id:number;label:string};
export function RecordPicker({resource,name,initialId='',initialLabel='',options=[]}:{resource:'clients'|'cases';name:string;initialId?:string;initialLabel?:string;options?:Choice[]}){
  const { request, guest } = useOfficeRequest();

 const {t}=useI18n();const root=useRef<HTMLDivElement>(null);const [selected,setSelected]=useState(initialId);const [label,setLabel]=useState(initialLabel);const [query,setQuery]=useState('');const [rows,setRows]=useState(options);const [error,setError]=useState('');
 useEffect(()=>{const form=root.current?.closest('form');const reset=()=>{setSelected(initialId);setLabel(initialLabel);setQuery('');};form?.addEventListener('reset',reset);return()=>form?.removeEventListener('reset',reset);},[initialId,initialLabel]);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{request('/api/office/lookup?'+new URLSearchParams({resource,q:query,selected})).then(readResponse<{rows:Choice[]}>).then(d=>{if(active){setRows(d.rows);setError('');}}).catch(e=>{if(active)setError(e.message);});},250);return()=>{active=false;clearTimeout(timer);};},[resource,query,selected]);
 return <div ref={root} className="record-picker"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} aria-label={t(resource==='clients'?'البحث عن عميل':'البحث عن قضية')} placeholder={t('ابحث لعرض المزيد من الخيارات')}/><select name={name} aria-label={t(resource==='clients'?'العميل المرتبط':'القضية المرتبطة')} value={selected} onChange={e=>{setSelected(e.target.value);setLabel(e.target.selectedOptions[0]?.textContent||'');}}><option value="">{t('بدون ربط')}</option>{selected&&!rows.some(r=>String(r.id)===selected)&&<option value={selected}>{label||t('السجل المرتبط')+' '+selected}</option>}{rows.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select>{error&&<small role="alert">{t(error)}</small>}</div>;
}
const GROUPS:Record<string,string>={hearings:'الجلسات والمهام',documents:'الوثائق',invoices:'الفواتير',memos:'المذكرات'};
export function CaseRelated({id}:{id:number}){
  const { request, guest } = useOfficeRequest();
const {t}=useI18n();const [open,setOpen]=useState(false);const [page,setPage]=useState(1);const [data,setData]=useState<{groups:Record<string,Array<{id:number;title:string;date:string}>>;hasMore:boolean}|null>(null);const [error,setError]=useState('');useEffect(()=>{if(!open)return;let active=true;request('/api/office/case-links?id='+id+'&page='+page).then(readResponse<NonNullable<typeof data>>).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[open,id,page]);return <div><button className="text-button" type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>{t('الملفات والسجلات المرتبطة')}</button>{open&&<div className="case-relations">{error?<p role="alert">{t(error)}</p>:!data?<div className="skeleton-row"/>:Object.entries(data.groups).map(([key,rows])=><section key={key}><strong>{t(GROUPS[key])}</strong>{rows.length?<ul>{rows.map(r=><li key={r.id}>{r.title||t('سجل')+' '+r.id} · <time>{r.date}</time></li>)}</ul>:<p>{t('لا توجد سجلات مرتبطة بعد')}</p>}</section>)}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>{t('السابق')}</button><button disabled={!data?.hasMore} onClick={()=>setPage(page+1)}>{t('التالي')}</button></div></div>}</div>}
