import http from 'node:http';
import {readFile} from 'node:fs/promises';
let curriculum={items:[]};try{curriculum=JSON.parse(await readFile(new URL('../data/catalog.json',import.meta.url),'utf8'))}catch{}
import {randomBytes,randomUUID,createHash,pbkdf2,timingSafeEqual} from 'node:crypto';
import {promisify} from 'node:util';
const derive=promisify(pbkdf2),hash=x=>createHash('sha256').update(x).digest('hex'),now=()=>Date.now();
let pool,sqlite;
if(process.env.DATABASE_URL){const {Pool}=await import('pg');pool=new Pool({connectionString:process.env.DATABASE_URL,max:5,ssl:process.env.PG_SSL==='true'?{rejectUnauthorized:true}:undefined});}
else {if(process.env.RENDER)throw Error('Persistent DATABASE_URL is required on Render; ephemeral SQLite is disabled.');const {DatabaseSync}=await import('node:sqlite');sqlite=new DatabaseSync(process.env.SQLITE_PATH||'manhaj.sqlite');sqlite.exec('PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;');}
let queue=Promise.resolve();
async function rawSql(q,p=[],client=pool){if(pool)return client.query(q,p);const stmt=sqlite.prepare(q.replace(/\$\d+/g,'?'));if(/^\s*SELECT/i.test(q))return {rows:stmt.all(...p)};return {rows:[],rowCount:Number(stmt.run(...p).changes)}}
const sql=(q,p=[])=>pool?rawSql(q,p):(queue=queue.catch(()=>{}).then(()=>rawSql(q,p)));
async function transaction(fn){if(pool){const c=await pool.connect();try{await c.query('BEGIN');const r=await fn((q,p)=>rawSql(q,p,c));await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}sqlite.exec('BEGIN IMMEDIATE');try{const r=await fn(rawSql);sqlite.exec('COMMIT');return r}catch(e){sqlite.exec('ROLLBACK');throw e}}
// Serialize SQLite transactions in local mode; PostgreSQL uses its own transaction locks.
const withTransaction=fn=>pool?transaction(fn):(queue=queue.catch(()=>{}).then(()=>transaction(fn)));
for(const q of [
 'CREATE TABLE IF NOT EXISTS schools (id TEXT PRIMARY KEY, name TEXT NOT NULL, state TEXT, revision INTEGER NOT NULL DEFAULT 0)',
 'CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), email TEXT UNIQUE NOT NULL, password TEXT NOT NULL)',
 'CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires BIGINT NOT NULL)',
 'CREATE TABLE IF NOT EXISTS cards (token_hash TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), event_id TEXT NOT NULL, expires BIGINT NOT NULL, used INTEGER NOT NULL DEFAULT 0)',
 'CREATE TABLE IF NOT EXISTS files (id TEXT PRIMARY KEY, school_id TEXT NOT NULL REFERENCES schools(id), name TEXT NOT NULL, type TEXT NOT NULL, data TEXT NOT NULL)',
 'CREATE TABLE IF NOT EXISTS audit (id TEXT PRIMARY KEY, school_id TEXT NOT NULL, action TEXT NOT NULL, actor TEXT NOT NULL, at BIGINT NOT NULL)'
])await sql(q);
const origin=process.env.ALLOWED_ORIGIN||'https://q8-ux.github.io',attempts=new Map();
const fail=(status,message)=>{const e=Error(message);e.status=status;throw e};
function text(value,max=5000){if(typeof value!=='string'||value.length>max)fail(400,'حقل نصي غير صالح');return value.trim()}
function validateState(s){if(!s||typeof s!=='object'||Array.isArray(s)||JSON.stringify(s).length>1500000)fail(400,'حجم السجلات غير صالح');if(!Array.isArray(s.events)||!Array.isArray(s.costs)||s.events.length>2000||s.costs.length>2000)fail(400,'بيانات المدرسة غير صالحة');for(const e of s.events){for(const k of ['id','title','owner','date','grade','goal','lesson','bookId','notes','status'])text(e[k],k==='notes'?20000:5000);if(!Array.isArray(e.evidence))fail(400,'قائمة الشواهد غير صالحة');}for(const key of ['classes','teachers','meetings'])if(s[key]!==undefined&&!Array.isArray(s[key]))fail(400,'قائمة غير صالحة');return s}
async function audit(school,action,actor,run=sql){await run('INSERT INTO audit (id,school_id,action,actor,at) VALUES ($1,$2,$3,$4,$5)',[randomUUID(),school,action,actor,now()])}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>22*1024*1024)fail(413,'الطلب كبير جدًا');chunks.push(chunk)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{fail(400,'بيانات JSON غير صالحة')}}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))}
async function user(req){const token=(req.headers.authorization||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token))fail(401,'سجّل الدخول أولًا');const r=await sql('SELECT u.id,u.school_id,u.email FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.token_hash=$1 AND s.expires>$2',[hash(token),now()]);if(!r.rows[0])fail(401,'انتهت الجلسة؛ سجّل الدخول مرة أخرى');return r.rows[0]}
async function school(id){return (await sql('SELECT * FROM schools WHERE id=$1',[id])).rows[0]}
async function session(uid){const token=randomBytes(32).toString('hex');await sql('INSERT INTO sessions (token_hash,user_id,expires) VALUES ($1,$2,$3)',[hash(token),uid,now()+12*3600000]);return token}
function rate(req,path){if(!path.startsWith('/api/auth/'))return;const ip=req.socket.remoteAddress||'unknown',key=ip;const current=attempts.get(key)||{at:now(),count:0};if(now()-current.at>15*60000){current.at=now();current.count=0}if(++current.count>30)fail(429,'طلبات كثيرة؛ حاول لاحقًا');attempts.set(key,current);if(attempts.size>5000)for(const [k,v]of attempts)if(now()-v.at>15*60000)attempts.delete(k)}
export const server=http.createServer(async(req,res)=>{const path=new URL(req.url,'http://localhost').pathname;const requestOrigin=req.headers.origin;if(requestOrigin&&requestOrigin!==origin)return send(res,403,{error:'مصدر الاتصال غير مسموح'});res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}try{
 rate(req,path);
 if(path==='/health')return send(res,200,{status:'ok',service:'manhaj',persistent:Boolean(pool)});
 if(path==='/api/auth/register'&&req.method==='POST'){const data=await body(req),email=text(data.email,200).toLowerCase(),password=text(data.password,256),name=text(data.school,160);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<12||!name)fail(400,'أدخل بريدًا صحيحًا وكلمة مرور لا تقل عن 12 حرفًا واسم المدرسة');const salt=randomBytes(16).toString('hex'),digest=(await derive(password,salt,310000,32,'sha256')).toString('hex'),uid=randomUUID(),sid=randomUUID();try{await withTransaction(async run=>{await run('INSERT INTO schools (id,name) VALUES ($1,$2)',[sid,name]);await run('INSERT INTO users (id,school_id,email,password) VALUES ($1,$2,$3,$4)',[uid,sid,email,salt+':'+digest]);await audit(sid,'register',uid,run)})}catch(e){if(/unique|duplicate/i.test(e.message))fail(409,'البريد مسجل مسبقًا');throw e}return send(res,201,{token:await session(uid),revision:0})}
 if(path==='/api/auth/login'&&req.method==='POST'){const data=await body(req),email=text(data.email,200).toLowerCase(),password=text(data.password,256);const account=(await sql('SELECT * FROM users WHERE email=$1',[email])).rows[0];const salt=account?.password.split(':')[0]||'00000000000000000000000000000000';const digest=await derive(password,salt,310000,32,'sha256');if(!account||!timingSafeEqual(digest,Buffer.from(account.password.split(':')[1],'hex')))fail(401,'البريد أو كلمة المرور غير صحيحة');const s=await school(account.school_id);return send(res,200,{token:await session(account.id),revision:s.revision})}
 if(path==='/api/auth/logout'&&req.method==='POST'){const u=await user(req);await sql('DELETE FROM sessions WHERE token_hash=$1',[hash((req.headers.authorization||'').replace(/^Bearer /,''))]);return send(res,200,{success:true})}
 if(path==='/api/state'){const u=await user(req);if(req.method==='GET'){const s=await school(u.school_id);return send(res,200,{state:s.state?JSON.parse(s.state):null,revision:s.revision})}if(req.method==='PUT'){const data=await body(req),s=validateState(data.state);if(!Number.isInteger(data.revision)||data.revision<0)fail(400,'إصدار السجل غير صالح');const r=await sql('UPDATE schools SET state=$1,revision=revision+1 WHERE id=$2 AND revision=$3',[JSON.stringify(s),u.school_id,data.revision]);if(r.rowCount!==1)fail(409,'هناك تحديث أحدث؛ استعد بيانات الحساب قبل الحفظ');await audit(u.school_id,'save_state',u.id);return send(res,200,{revision:data.revision+1})}}
 if(path==='/api/cards'&&req.method==='POST'){const u=await user(req),data=await body(req),s=await school(u.school_id),state=s.state?JSON.parse(s.state):null;if(!state?.events.some(e=>e.id===data.eventId))fail(404,'احفظ البرنامج سحابيًا قبل إنشاء الرابط');const token=randomBytes(32).toString('hex');await sql('INSERT INTO cards (token_hash,school_id,event_id,expires) VALUES ($1,$2,$3,$4)',[hash(token),u.school_id,data.eventId,now()+7*86400000]);await audit(u.school_id,'share_card',u.id);return send(res,201,{token,expiresInDays:7})}
 if(path.startsWith('/api/cards/')){const token=path.slice('/api/cards/'.length);if(!/^[a-f0-9]{64}$/.test(token))fail(404,'الرابط غير صالح');const card=(await sql('SELECT * FROM cards WHERE token_hash=$1 AND expires>$2 AND used=0',[hash(token),now()])).rows[0];if(!card)fail(404,'الرابط منتهي أو سبق إرسال البطاقة');const s=await school(card.school_id),state=JSON.parse(s.state||'null'),event=state?.events.find(e=>e.id===card.event_id);if(!event)fail(404,'حُذف البرنامج من الخطة');if(req.method==='GET')return send(res,200,{event:{title:event.title,grade:event.grade,goal:event.goal,owner:event.owner,participants:event.participants||0,lesson:event.lesson,source:curriculum.items.find(b=>b.id===event.bookId)?.source||null},school:s.name});if(req.method==='POST'){const data=await body(req);const owner=text(data.owner,160),notes=text(data.notes,20000),evaluation=text(data.evaluation,10000),participants=Number(data.participants);if(!owner||!notes||!evaluation||!Number.isInteger(participants)||participants<0||participants>5000)fail(400,'استكمل بيانات التنفيذ');const attachments=data.attachments||[];if(!Array.isArray(attachments)||attachments.length>3)fail(400,'حتى 3 مرفقات');const files=attachments.map(f=>{const name=text(f.name,200),type=text(f.type,100),encoded=text(f.data,7*1024*1024),bytes=Buffer.from(encoded,'base64');if(bytes.length>5*1024*1024)fail(413,'المرفق أكبر من 5MB');const valid=(type==='application/pdf'&&bytes.subarray(0,4).toString()==='%PDF')||(type==='image/png'&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(type==='image/jpeg'&&bytes[0]===255&&bytes[1]===216)||(type==='image/webp'&&bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP');if(!valid)fail(400,'صيغة المرفق غير مدعومة');return {id:randomUUID(),name,type,data:encoded}});Object.assign(event,{owner,notes,evaluation,participants,status:'منفذة',evidence:[...(event.evidence||[]),...files.map(f=>({id:f.id,name:f.name,cloud:true}))]});await withTransaction(async run=>{const used=await run('UPDATE cards SET used=1 WHERE token_hash=$1 AND used=0',[hash(token)]);if(used.rowCount!==1)fail(409,'سبق إرسال البطاقة');const updated=await run('UPDATE schools SET state=$1,revision=revision+1 WHERE id=$2 AND revision=$3',[JSON.stringify(state),card.school_id,s.revision]);if(updated.rowCount!==1)fail(409,'تغير البرنامج أثناء التحرير؛ افتح الرابط مرة أخرى');for(const f of files)await run('INSERT INTO files (id,school_id,name,type,data) VALUES ($1,$2,$3,$4,$5)',[f.id,card.school_id,f.name,f.type,f.data]);await audit(card.school_id,'teacher_submission','shared_card',run)});return send(res,200,{success:true})}}
 if(path.startsWith('/api/files/')&&req.method==='GET'){const u=await user(req),id=path.slice('/api/files/'.length);const f=(await sql('SELECT * FROM files WHERE id=$1 AND school_id=$2',[id,u.school_id])).rows[0];if(!f)fail(404,'الملف غير موجود');return send(res,200,{name:f.name,type:f.type,data:f.data})}
 if(path==='/api/audit'&&req.method==='GET'){const u=await user(req);const result=await sql('SELECT action,actor,at FROM audit WHERE school_id=$1 ORDER BY at DESC LIMIT 100',[u.school_id]);return send(res,200,{entries:result.rows})}
 fail(404,'المسار غير موجود');
 }catch(e){if(!e.status)console.error('Request failure',e.name);send(res,e.status||500,{error:e.status?e.message:'تعذر تنفيذ العملية؛ حاول لاحقًا'})}});
const port=Number(process.env.PORT||8000);server.listen(port,'0.0.0.0',()=>console.log('Manhaj API listening on port',server.address().port));
