const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={grade:null,unit:null,semester:'A',stats:JSON.parse(localStorage.getItem('ekw-stats')||'{"lessons":0,"answers":0,"correct":0,"minutes":0,"skills":{"Vocabulary":0,"Grammar":0,"Listening":0,"Speaking":0}}')};
let start=Date.now();
function save(){state.stats.minutes=Math.max(state.stats.minutes,Math.round((Date.now()-start)/60000));localStorage.setItem('ekw-stats',JSON.stringify(state.stats));renderStats()}
setInterval(save,30000);
function scrollToGrades(){$('#grades').scrollIntoView({behavior:'smooth'})}
function renderGrades(){const g=$('#gradeGrid');g.innerHTML='';Object.entries(CURRICULUM).forEach(([id,x])=>{let p=Math.min(100,Math.round((state.stats.lessons/(x.units.length*4))*100));g.insertAdjacentHTML('beforeend',`<article class="grade-card ${state.grade==id?'active':''}" onclick="selectGrade('${id}')"><div class="num">${id}</div><h3>${x.title}</h3><p>مستوى تقريبي ${x.level} • ${x.units.length} وحدات نموذجية مفعلة</p><div class="progress"><i style="width:${p}%"></i></div></article>`)});}
function selectGrade(id){state.grade=id;state.unit=null;renderGrades();$('#sideTitle').textContent=CURRICULUM[id].title+' — الفصل '+state.semester;$('#unitList').innerHTML=CURRICULUM[id].units.map((u,i)=>`<button class="unit-btn" onclick="openUnit('${u.id}')"><b>الوحدة ${i+1}: ${u.title}</b><small>${u.theme}</small></button>`).join('');$('#lessonPanel').innerHTML='<div class="welcome-card"><div class="icon">📘</div><h2>اختر وحدة من القائمة</h2><p>ثم انتقل بين الشرح والكلمات والقواعد والاستماع والنطق والتدريب.</p></div>';}
function findUnit(uid){return CURRICULUM[state.grade].units.find(x=>x.id===uid)}
function openUnit(uid){state.unit=uid;$$('.unit-btn').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick').includes(uid)));renderLesson('overview')}
function renderLesson(tab){const u=findUnit(state.unit);if(!u)return;$('#lessonPanel').innerHTML=`<div class="lesson-head"><div><span class="eyebrow">${CURRICULUM[state.grade].title}</span><h2>${u.title}</h2><p>${u.theme}</p></div><button class="primary" onclick="completeLesson()">✓ إكمال الدرس</button></div><div class="lesson-tabs">${[['overview','الشرح'],['vocab','الكلمات'],['grammar','القواعد'],['listening','الاستماع'],['speaking','النطق'],['quiz','التدريب']].map(([k,n])=>`<button class="${tab===k?'active':''}" onclick="renderLesson('${k}')">${n}</button>`).join('')}</div><div id="lessonContent" class="lesson-content"></div>`;
 const c=$('#lessonContent');
 if(tab==='overview')c.innerHTML=`<h3>هدف الدرس</h3><p>يفهم الطالب موضوع <b>${u.theme}</b> ويستخدم الكلمات والقواعد المرتبطة به في سياق يومي مناسب.</p><div class="audio-box"><b>خطة التعلم المقترحة</b><p>1) اقرأ الكلمات. 2) افهم القاعدة. 3) استمع للمقطع مرتين. 4) أجب عن السؤال. 5) تدرب على النطق.</p></div>`;
 if(tab==='vocab')c.innerHTML=`<div class="word-grid">${u.vocab.map(([e,a])=>`<button class="word" onclick="speakText('${e}')"><b>${e} 🔊</b><span>${a}</span></button>`).join('')}</div>`;
 if(tab==='grammar')c.innerHTML=`<h3>قاعدة الوحدة</h3><div class="audio-box"><p>${u.grammar}</p></div><p>نصيحة: كوّن 3 جمل من حياتك مستخدماً نفس النمط، ثم اقرأها بصوت عالٍ.</p>`;
 if(tab==='listening')c.innerHTML=`<div class="audio-box"><h3>🎧 استماع</h3><p>اضغط تشغيل، استمع دون قراءة النص أولاً، ثم أعد الاستماع.</p><div class="audio-controls"><button class="primary" onclick="speakText(${JSON.stringify(u.listen)})">▶ تشغيل</button><button class="ghost" onclick="toggleTranscript()">إظهار / إخفاء النص</button></div><p id="transcript" style="display:none" dir="ltr">${u.listen}</p></div>${quizHTML(u,'listening')}`;
 if(tab==='speaking')c.innerHTML=`<div class="audio-box"><h3>🎙️ تدريب النطق</h3><p dir="ltr"><b>${u.speak}</b></p><div class="audio-controls"><button class="primary" onclick="speakText(${JSON.stringify(u.speak)})">🔊 استمع للنموذج</button><button class="ghost" onclick="startRecognition(${JSON.stringify(u.speak)})">🎙️ ابدأ التسجيل</button></div><p id="speechResult">سيظهر النص الذي التقطه المتصفح هنا.</p></div>`;
 if(tab==='quiz')c.innerHTML=quizHTML(u,'Grammar')+`<div class="audio-box"><b>تحدٍ كتابي</b><p>اكتب جملة من عندك باستخدام إحدى كلمات الوحدة.</p><textarea id="writing" style="width:100%;min-height:100px;border:1px solid #dce3ed;border-radius:12px;padding:12px;font:inherit" placeholder="Write your sentence here..."></textarea></div>`;
}
function quizHTML(u,skill){return `<div class="quiz-box"><h3>${u.question.q}</h3>${u.question.choices.map((c,i)=>`<button class="choice" onclick="answer(this,${i},${u.question.answer},'${skill}')">${c}</button>`).join('')}<p class="feedback"></p></div>`}
function answer(btn,i,a,skill){let box=btn.closest('.quiz-box');box.querySelectorAll('.choice').forEach(x=>x.disabled=true);state.stats.answers++;if(i===a){btn.classList.add('correct');box.querySelector('.feedback').textContent='إجابة صحيحة ✓';state.stats.correct++;state.stats.skills[skill]=Math.min(100,(state.stats.skills[skill]||0)+12)}else{btn.classList.add('wrong');box.querySelectorAll('.choice')[a].classList.add('correct');box.querySelector('.feedback').textContent='راجع الإجابة الصحيحة ثم استمع مرة أخرى.'}save()}
function completeLesson(){state.stats.lessons++;['Vocabulary','Grammar'].forEach(k=>state.stats.skills[k]=Math.min(100,(state.stats.skills[k]||0)+8));save();alert('تم تسجيل الدرس كمكتمل ✓')}
function speakText(text){if(!('speechSynthesis'in window)){alert('ميزة الصوت غير مدعومة في هذا المتصفح');return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}
function toggleTranscript(){let e=$('#transcript');e.style.display=e.style.display==='none'?'block':'none'}
function startRecognition(target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#speechResult').textContent='التعرف على النطق غير مدعوم في هذا المتصفح. استخدم Chrome/Edge على جهاز يدعم الميكروفون.';return}let r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{let heard=e.results[0][0].transcript;let score=similarity(heard.toLowerCase(),target.toLowerCase());$('#speechResult').innerHTML=`سمعت: <b dir="ltr">${heard}</b><br>تقارب تقريبي: <b>${score}%</b>`;state.stats.skills.Speaking=Math.min(100,(state.stats.skills.Speaking||0)+(score>70?15:6));save()};r.onerror=()=>$('#speechResult').textContent='تعذر الوصول للميكروفون أو لم يتم التقاط صوت واضح.';r.start()}
function similarity(a,b){const aw=new Set(a.replace(/[^a-z ]/g,'').split(/\s+/)),bw=new Set(b.replace(/[^a-z ]/g,'').split(/\s+/));let hit=[...aw].filter(x=>bw.has(x)).length;return Math.round((2*hit/(aw.size+bw.size||1))*100)}
function openTool(type){const b=$('#modalBody');$('#modal').classList.remove('hidden');if(type==='books'){b.innerHTML=`<h2>📚 الكتب والمصادر الرسمية</h2><p>يتم فتح الكتب من مكتبة وزارة التربية الرسمية، ولا نخزن نسخة غير مصرح بها داخل المنصة.</p><p><a class="primary link-btn" href="${OFFICIAL.library}" target="_blank">مكتبة الطالب – وزارة التربية ↗</a></p>${OFFICIAL.grade7?`<p><a href="${OFFICIAL.grade7}" target="_blank">كتاب الصف السابع – مصدر الوزارة</a></p>`:''}${OFFICIAL.grade9workbook?`<p><a href="${OFFICIAL.grade9workbook}" target="_blank">Workbook 9A – مصدر الوزارة</a></p>`:''}`;return}if(type==='worksheet'){let u=state.unit?findUnit(state.unit):CURRICULUM[6].units[0];b.innerHTML=`<h2>📝 ورقة عمل</h2><h3>${u.title}</h3><p>1. Match: ${u.vocab.slice(0,3).map(x=>x[0]).join(' / ')}</p><p>2. Write two sentences using the unit grammar.</p><p>3. Listening question: ${u.question.q}</p><hr><details><summary>نموذج الإجابة</summary><p>سؤال الاستماع: <b>${u.question.choices[u.question.answer]}</b></p><p>الكتابة: تقبل أي جملة صحيحة نحويًا ومناسبة للسياق.</p></details><button class="primary" onclick="window.print()">طباعة</button>`;return}if(type==='exam'){let qs=Object.values(CURRICULUM).flatMap(g=>g.units).slice(0,10);b.innerHTML=`<h2>🏆 اختبار تشخيصي</h2><p>اختر صفاً ووحدة للحصول على اختبار مخصص. حالياً هذه عينة من بنك الأسئلة.</p>${qs.slice(0,5).map((u,n)=>`<div class="quiz-box"><b>${n+1}. ${u.question.q}</b>${u.question.choices.map((c,i)=>`<button class="choice" onclick="answer(this,${i},${u.question.answer},'Grammar')">${c}</button>`).join('')}<p class="feedback"></p></div>`).join('')}`;return}if(type==='listening'){b.innerHTML='<h2>🎧 مختبر الاستماع</h2><p>اختر أي وحدة من الصفوف ثم افتح تبويب الاستماع. كل مقطع يمكن تشغيله وإعادته وإظهار النص بعد المحاولة.</p>';return}if(type==='speaking'){b.innerHTML='<h2>🎙️ مختبر النطق</h2><p>المنصة تستخدم التعرف الصوتي المتاح في المتصفح لالتقاط نطق الطالب وإظهار ما تم التعرف عليه مع درجة تقارب تقريبية. هذه ليست درجة نطق أكاديمية نهائية.</p>';return}if(type==='vocab'){let words=Object.values(CURRICULUM).flatMap(g=>g.units.flatMap(u=>u.vocab));b.innerHTML=`<h2>🧠 بنك الكلمات</h2><div class="word-grid">${words.slice(0,30).map(([e,a])=>`<button class="word" onclick="speakText('${e}')"><b>${e} 🔊</b><span>${a}</span></button>`).join('')}</div>`}}
function closeModal(){$('#modal').classList.add('hidden')}
function renderStats(){let s=state.stats,acc=s.answers?Math.round(s.correct/s.answers*100):0;$('#lessonsDone').textContent=s.lessons;$('#questionsDone').textContent=s.answers;$('#accuracy').textContent=acc+'%';$('#minutes').textContent=s.minutes;let overall=Math.round((Math.min(s.lessons,12)/12*.4+acc/100*.6)*100);$('#overallScore').textContent=overall+'%';$('#overallRing').style.background=`conic-gradient(var(--blue) ${overall*3.6}deg,#e7edf5 0)`;$('#streakText').textContent=s.lessons?`أكملت ${s.lessons} درس/دروس حتى الآن`:'ابدأ أول درس لتسجيل تقدمك';$('#skillBars').innerHTML=Object.entries(s.skills).map(([k,v])=>`<div class="skill"><span>${k}</span><div class="progress"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('')}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.semester=b.dataset.sem;if(state.grade)selectGrade(state.grade)});$('#langBtn').onclick=()=>alert('واجهة الطالب الأساسية عربية مع محتوى الإنجليزية داخل الدروس. يمكن إضافة نسخة واجهة إنجليزية كاملة في المرحلة التالية.');$('#parentBtn').onclick=()=>{$('#dashboard').scrollIntoView({behavior:'smooth'})};$('#adminBtn').onclick=()=>openTool('books');renderGrades();renderStats();