const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DEFAULT_STATS={lessons:0,answers:0,correct:0,minutes:0,skills:{Vocabulary:0,Grammar:0,Listening:0,Speaking:0},completed:[]};
function loadStats(){try{const raw=localStorage.getItem('ekw-stats');if(!raw)return structuredClone?structuredClone(DEFAULT_STATS):JSON.parse(JSON.stringify(DEFAULT_STATS));const parsed=JSON.parse(raw);return {...DEFAULT_STATS,...parsed,skills:{...DEFAULT_STATS.skills,...(parsed.skills||{})},completed:Array.isArray(parsed.completed)?parsed.completed:[]}}catch(e){return JSON.parse(JSON.stringify(DEFAULT_STATS))}}
const state={grade:null,unit:null,semester:'A',stats:loadStats()};
let start=Date.now();
function persist(){try{localStorage.setItem('ekw-stats',JSON.stringify(state.stats))}catch(e){console.warn('Progress storage unavailable',e)}}
function save(){state.stats.minutes=Math.max(state.stats.minutes,Math.round((Date.now()-start)/60000));persist();renderStats()}
setInterval(save,30000);
window.addEventListener('pagehide',save);
function scrollToGrades(){const el=$('#grades');if(el)el.scrollIntoView({behavior:'smooth'})}
function renderGrades(){const g=$('#gradeGrid');if(!g)return;g.innerHTML='';Object.entries(CURRICULUM).forEach(([id,x])=>{const done=state.stats.completed.filter(k=>k.startsWith(id+'-')).length;let p=Math.min(100,Math.round((done/Math.max(1,x.units.length))*100));g.insertAdjacentHTML('beforeend',`<article class="grade-card ${state.grade==id?'active':''}" tabindex="0" role="button" aria-label="فتح ${x.title}" onclick="selectGrade('${id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();selectGrade('${id}')}"><div class="num">${id}</div><h3>${x.title}</h3><p>مستوى تقريبي ${x.level} • ${x.units.length} وحدات تعليمية</p><div class="progress" aria-label="التقدم ${p}%"><i style="width:${p}%"></i></div></article>`)});}
function selectGrade(id){if(!CURRICULUM[id])return;state.grade=id;state.unit=null;renderGrades();$('#sideTitle').textContent=CURRICULUM[id].title+' — الفصل '+state.semester;$('#unitList').innerHTML=CURRICULUM[id].units.map((u,i)=>{const key=`${id}-${state.semester}-${u.id}`,done=state.stats.completed.includes(key);return `<button class="unit-btn" onclick="openUnit('${u.id}')"><b>${done?'✓ ':''}الوحدة ${i+1}: ${u.title}</b><small>${u.theme}</small></button>`}).join('');$('#lessonPanel').innerHTML='<div class="welcome-card"><div class="icon">📘</div><h2>اختر وحدة من القائمة</h2><p>ثم انتقل بين الشرح والكلمات والقواعد والاستماع والنطق والتدريب.</p></div>';updateTutorContext();}
function findUnit(uid){return state.grade&&CURRICULUM[state.grade]?CURRICULUM[state.grade].units.find(x=>x.id===uid):null}
function openUnit(uid){const u=findUnit(uid);if(!u)return;state.unit=uid;$$('.unit-btn').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick').includes(uid)));renderLesson('overview');updateTutorContext();}
function renderLesson(tab){const u=findUnit(state.unit);if(!u)return;$('#lessonPanel').innerHTML=`<div class="lesson-head"><div><span class="eyebrow">${CURRICULUM[state.grade].title}</span><h2>${u.title}</h2><p>${u.theme}</p></div><button class="primary" onclick="completeLesson()">✓ إكمال الدرس</button></div><div class="lesson-tabs" role="tablist">${[['overview','الشرح'],['vocab','الكلمات'],['grammar','القواعد'],['listening','الاستماع'],['speaking','النطق'],['quiz','التدريب']].map(([k,n])=>`<button role="tab" aria-selected="${tab===k}" class="${tab===k?'active':''}" onclick="renderLesson('${k}')">${n}</button>`).join('')}</div><div id="lessonContent" class="lesson-content"></div>`;
 const c=$('#lessonContent');
 if(tab==='overview')c.innerHTML=`<h3>هدف الدرس</h3><p>يفهم الطالب موضوع <b>${u.theme}</b> ويستخدم الكلمات والقواعد المرتبطة به في سياق يومي مناسب.</p><div class="audio-box"><b>خطة التعلم المقترحة</b><p>1) اقرأ الكلمات. 2) افهم القاعدة. 3) استمع للمقطع مرتين. 4) أجب عن السؤال. 5) تدرب على النطق.</p></div>`;
 if(tab==='vocab')c.innerHTML=`<div class="word-grid">${u.vocab.map(([e,a])=>`<button class="word" onclick='speakText(${JSON.stringify(e)})'><b>${e} 🔊</b><span>${a}</span></button>`).join('')}</div>`;
 if(tab==='grammar')c.innerHTML=`<h3>قاعدة الوحدة</h3><div class="audio-box"><p>${u.grammar}</p></div><p>كوّن 3 جمل من حياتك مستخدماً نفس النمط، ثم اقرأها بصوت عالٍ.</p>`;
 if(tab==='listening')c.innerHTML=`<div class="audio-box"><h3>🎧 استماع</h3><p>استمع أولاً دون قراءة النص، ثم أعد الاستماع.</p><div class="audio-controls"><button class="primary" onclick='speakText(${JSON.stringify(u.listen)})'>▶ تشغيل</button><button class="ghost" onclick="toggleTranscript()">إظهار / إخفاء النص</button></div><p id="transcript" style="display:none" dir="ltr">${u.listen}</p></div>${quizHTML(u,'Listening')}`;
 if(tab==='speaking')c.innerHTML=`<div class="audio-box"><h3>🎙️ تدريب النطق</h3><p dir="ltr"><b>${u.speak}</b></p><div class="audio-controls"><button class="primary" onclick='speakText(${JSON.stringify(u.speak)})'>🔊 استمع للنموذج</button><button class="ghost" onclick='startRecognition(${JSON.stringify(u.speak)})'>🎙️ ابدأ التسجيل</button></div><p id="speechResult" aria-live="polite">سيظهر النص الذي التقطه المتصفح هنا.</p></div>`;
 if(tab==='quiz')c.innerHTML=quizHTML(u,'Grammar')+`<div class="audio-box"><b>تحدٍ كتابي</b><p>اكتب جملة من عندك باستخدام إحدى كلمات الوحدة.</p><textarea id="writing" class="writing-box" placeholder="Write your sentence here..."></textarea><button class="ghost" onclick="reviewWriting()">مراجعة سريعة</button><p id="writingFeedback" aria-live="polite"></p></div>`;
}
function quizHTML(u,skill){return `<div class="quiz-box"><h3>${u.question.q}</h3>${u.question.choices.map((c,i)=>`<button class="choice" onclick="answer(this,${i},${u.question.answer},'${skill}')">${c}</button>`).join('')}<p class="feedback" aria-live="polite"></p></div>`}
function answer(btn,i,a,skill){const box=btn.closest('.quiz-box');if(!box)return;box.querySelectorAll('.choice').forEach(x=>x.disabled=true);state.stats.answers++;if(i===a){btn.classList.add('correct');box.querySelector('.feedback').textContent='إجابة صحيحة ✓';state.stats.correct++;state.stats.skills[skill]=Math.min(100,(state.stats.skills[skill]||0)+12)}else{btn.classList.add('wrong');const correct=box.querySelectorAll('.choice')[a];if(correct)correct.classList.add('correct');box.querySelector('.feedback').textContent='راجع الإجابة الصحيحة ثم حاول مرة أخرى في تدريب جديد.'}save()}
function completeLesson(){if(!state.grade||!state.unit)return;const key=`${state.grade}-${state.semester}-${state.unit}`;if(!state.stats.completed.includes(key)){state.stats.completed.push(key);state.stats.lessons=state.stats.completed.length;['Vocabulary','Grammar'].forEach(k=>state.stats.skills[k]=Math.min(100,(state.stats.skills[k]||0)+8));save();selectGrade(state.grade);openUnit(state.unit);alert('تم تسجيل الدرس كمكتمل ✓')}else alert('هذا الدرس مسجل كمكتمل بالفعل ✓')}
function speakText(text){if(!('speechSynthesis'in window)){alert('ميزة الصوت غير مدعومة في هذا المتصفح');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}
function toggleTranscript(){const e=$('#transcript');if(e)e.style.display=e.style.display==='none'?'block':'none'}
function startRecognition(target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){const out=$('#speechResult');if(out)out.textContent='التعرف على النطق غير مدعوم في هذا المتصفح. استخدم Chrome/Edge على جهاز يدعم الميكروفون.';return}const r=new SR();r.lang='en-US';r.interimResults=false;r.onresult=e=>{const heard=e.results[0][0].transcript,score=similarity(heard.toLowerCase(),target.toLowerCase());const out=$('#speechResult');if(out)out.innerHTML=`سمعت: <b dir="ltr">${heard}</b><br>تقارب تقريبي: <b>${score}%</b>`;state.stats.skills.Speaking=Math.min(100,(state.stats.skills.Speaking||0)+(score>70?15:6));save()};r.onerror=()=>{const out=$('#speechResult');if(out)out.textContent='تعذر الوصول للميكروفون أو لم يتم التقاط صوت واضح.'};r.start()}
function similarity(a,b){const aw=new Set(a.replace(/[^a-z ]/g,'').split(/\s+/).filter(Boolean)),bw=new Set(b.replace(/[^a-z ]/g,'').split(/\s+/).filter(Boolean));let hit=[...aw].filter(x=>bw.has(x)).length;return Math.round((2*hit/(aw.size+bw.size||1))*100)}
function reviewWriting(){const text=($('#writing')?.value||'').trim(),out=$('#writingFeedback');if(!out)return;if(!text){out.textContent='اكتب جملة أولاً.';return}const words=text.split(/\s+/);const end=/[.!?]$/.test(text);const starts=/^[A-Z]/.test(text);out.textContent=words.length<4?'الجملة قصيرة جداً. حاول إضافة فاعل وفعل وتفصيل.':(!starts||!end?'المعنى قابل للمراجعة، لكن ابدأ بحرف كبير وأنهِ الجملة بعلامة ترقيم.':'بنية أولية جيدة ✓ راجع زمن الفعل واستخدام كلمات الوحدة.');}
function openTool(type){const b=$('#modalBody');$('#modal').classList.remove('hidden');if(type==='books'){b.innerHTML=`<h2>📚 الكتب والمصادر الرسمية</h2><p>يتم فتح الكتب من مكتبة وزارة التربية الرسمية، ولا نخزن نسخة غير مصرح بها داخل المنصة.</p><p><a class="primary link-btn" href="${OFFICIAL.library}" target="_blank" rel="noopener">مكتبة الطالب – وزارة التربية ↗</a></p>${OFFICIAL.grade7?`<p><a href="${OFFICIAL.grade7}" target="_blank" rel="noopener">كتاب الصف السابع – مصدر الوزارة</a></p>`:''}${OFFICIAL.grade9workbook?`<p><a href="${OFFICIAL.grade9workbook}" target="_blank" rel="noopener">Workbook 9A – مصدر الوزارة</a></p>`:''}`;return}if(type==='worksheet'){const u=state.unit?findUnit(state.unit):CURRICULUM[6].units[0];b.innerHTML=`<h2>📝 ورقة عمل</h2><h3>${u.title}</h3><p>1. Match: ${u.vocab.slice(0,3).map(x=>x[0]).join(' / ')}</p><p>2. Write two sentences using the unit grammar.</p><p>3. Listening question: ${u.question.q}</p><hr><details><summary>نموذج الإجابة</summary><p>سؤال الاستماع: <b>${u.question.choices[u.question.answer]}</b></p><p>الكتابة: تقبل أي جملة صحيحة نحويًا ومناسبة للسياق.</p></details><button class="primary" onclick="window.print()">طباعة</button>`;return}if(type==='exam'){const qs=(state.grade?CURRICULUM[state.grade].units:Object.values(CURRICULUM).flatMap(g=>g.units)).slice(0,10);b.innerHTML=`<h2>🏆 اختبار تشخيصي</h2><p>${state.grade?'اختبار مخصص للصف '+state.grade:'اختر صفاً للحصول على اختبار أكثر تخصيصاً.'}</p>${qs.slice(0,5).map((u,n)=>`<div class="quiz-box"><b>${n+1}. ${u.question.q}</b>${u.question.choices.map((c,i)=>`<button class="choice" onclick="answer(this,${i},${u.question.answer},'Grammar')">${c}</button>`).join('')}<p class="feedback"></p></div>`).join('')}`;return}if(type==='listening'){b.innerHTML='<h2>🎧 مختبر الاستماع</h2><p>اختر أي وحدة ثم افتح تبويب الاستماع. كل مقطع يمكن تشغيله وإعادته وإظهار النص بعد المحاولة.</p>';return}if(type==='speaking'){b.innerHTML='<h2>🎙️ مختبر النطق</h2><p>تستخدم المنصة التعرف الصوتي المتاح في المتصفح لالتقاط نطق الطالب وإظهار درجة تقارب تقريبية. هذه ليست درجة نطق أكاديمية نهائية.</p>';return}if(type==='vocab'){const words=Object.values(CURRICULUM).flatMap(g=>g.units.flatMap(u=>u.vocab));b.innerHTML=`<h2>🧠 بنك الكلمات</h2><div class="word-grid">${words.slice(0,40).map(([e,a])=>`<button class="word" onclick='speakText(${JSON.stringify(e)})'><b>${e} 🔊</b><span>${a}</span></button>`).join('')}</div>`}}
function closeModal(){$('#modal').classList.add('hidden')}
function renderStats(){const s=state.stats,acc=s.answers?Math.round(s.correct/s.answers*100):0;$('#lessonsDone').textContent=s.lessons;$('#questionsDone').textContent=s.answers;$('#accuracy').textContent=acc+'%';$('#minutes').textContent=s.minutes;const overall=Math.round((Math.min(s.lessons,12)/12*.4+acc/100*.6)*100);$('#overallScore').textContent=overall+'%';$('#overallRing').style.background=`conic-gradient(var(--blue) ${overall*3.6}deg,#e7edf5 0)`;$('#streakText').textContent=s.lessons?`أكملت ${s.lessons} درس/دروس حتى الآن`:'ابدأ أول درس لتسجيل تقدمك';$('#skillBars').innerHTML=Object.entries(s.skills).map(([k,v])=>`<div class="skill"><span>${k}</span><div class="progress"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('')}
function updateTutorContext(){const el=$('#tutorContext');if(!el)return;if(!state.grade){el.textContent='اختر الصف والوحدة ليصبح الشرح مخصصاً.';return}const u=state.unit?findUnit(state.unit):null;el.textContent=u?`${CURRICULUM[state.grade].title} • ${u.title} • ${u.theme}`:`${CURRICULUM[state.grade].title} • اختر وحدة`}
function tutorAnswer(q){const text=(q||'').trim();if(!text)return 'اكتب سؤالك أولاً.';if(!state.grade)return 'اختر صفك أولاً حتى أشرح لك حسب مستواك.';const u=state.unit?findUnit(state.unit):CURRICULUM[state.grade].units[0],low=text.toLowerCase();if(/كلمات|vocab|word/.test(low))return `كلمات هذه الوحدة: ${u.vocab.map(x=>x[0]+' = '+x[1]).join('، ')}.`;if(/قاعد|grammar|tense/.test(low))return `قاعدة الوحدة: ${u.grammar} جرّب أن تكتب مثالاً واحداً وسأعطيك ملاحظة أولية.`;if(/استماع|listen/.test(low))return `تدريب الاستماع لهذه الوحدة: ${u.listen} افتح تبويب الاستماع واسمعه مرتين قبل إظهار النص.`;if(/نطق|pronoun|speak/.test(low))return `تدرب على هذه الجملة: “${u.speak}”. استمع للنموذج ثم استخدم الميكروفون للمقارنة.`;if(/اختبار|test|quiz/.test(low))return `افتح تبويب التدريب أو مركز الاختبار. السؤال الحالي: ${u.question.q}`;return `أنت في ${CURRICULUM[state.grade].title} — ${u.title}. اسألني عن الكلمات، القاعدة، الاستماع، النطق أو الاختبار وسأرشدك داخل الدرس.`}
function askTutor(){const input=$('#tutorInput'),out=$('#tutorReply');if(!input||!out)return;out.textContent=tutorAnswer(input.value);}
function startTutorVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#tutorReply').textContent='الإدخال الصوتي غير مدعوم على هذا المتصفح.';return}const r=new SR();r.lang='ar-KW';r.onresult=e=>{const text=e.results[0][0].transcript;$('#tutorInput').value=text;askTutor()};r.onerror=()=>$('#tutorReply').textContent='تعذر التقاط الصوت. تحقق من إذن الميكروفون.';r.start()}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.semester=b.dataset.sem;if(state.grade)selectGrade(state.grade)});
$('#langBtn').onclick=()=>alert('واجهة الطالب الأساسية عربية مع محتوى الإنجليزية داخل الدروس.');
$('#parentBtn').onclick=()=>$('#dashboard').scrollIntoView({behavior:'smooth'});
$('#adminBtn').onclick=()=>openTool('books');
$('#tutorAsk')?.addEventListener('click',askTutor);$('#tutorMic')?.addEventListener('click',startTutorVoice);$('#tutorInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')askTutor()});
renderGrades();renderStats();updateTutorContext();