window.CURRICULUM={
  6:{title:'الصف السادس',level:'A1–A2',units:[
    {id:'6-1',title:'Me and My World',theme:'التعريف بالنفس والحياة اليومية',vocab:[['introduce','يعرّف'],['hobby','هواية'],['routine','روتين يومي'],['friendly','ودود'],['usually','عادةً'],['sometimes','أحياناً']],grammar:'Present Simple: نستخدمه للعادات والحقائق. مثال: I go to school at 7.',listen:'Hello! My name is Yousef. I am twelve years old. I live in Kuwait. I usually play football after school and I sometimes read English stories.',question:{q:'What does Yousef usually do after school?',choices:['He plays football.','He goes shopping.','He sleeps.'],answer:0},speak:'I usually study English after school.'},
    {id:'6-2',title:'My School Day',theme:'المدرسة والمواد والوقت',vocab:[['subject','مادة دراسية'],['timetable','جدول'],['break','فسحة'],['library','مكتبة'],['science','علوم'],['lesson','درس']],grammar:'Adverbs of frequency: always, usually, often, sometimes, never.',listen:'Our school starts at seven thirty. We have English three times a week. My favourite subject is science because I enjoy experiments.',question:{q:'Why does the speaker like science?',choices:['Because of experiments.','Because it is easy.','Because there is no homework.'],answer:0},speak:'My favourite subject is English because it is useful.'},
    {id:'6-3',title:'Healthy Living',theme:'الصحة والغذاء والنشاط',vocab:[['healthy','صحي'],['exercise','تمرين'],['meal','وجبة'],['water','ماء'],['energy','طاقة'],['sleep','نوم']],grammar:'Countable / uncountable nouns with some and any.',listen:'To stay healthy, drink enough water, eat fresh food, sleep well and exercise regularly.',question:{q:'Which habit is mentioned?',choices:['Drinking enough water.','Skipping sleep.','Eating only sweets.'],answer:0},speak:'I drink enough water every day.'}
  ]},
  7:{title:'الصف السابع',level:'A2',officialBook:'https://elibrary.moe.edu.kw/api/File/download/book/1297',units:[
    {id:'7-1',title:'People and Places',theme:'الأشخاص والأماكن',vocab:[['community','مجتمع'],['neighbourhood','منطقة سكنية'],['visitor','زائر'],['traditional','تقليدي'],['modern','حديث'],['famous','مشهور']],grammar:'Past Simple: نستخدمه للأحداث التي انتهت في الماضي.',listen:'Last weekend, Sara visited Kuwait Towers with her family. They took photos and learned interesting facts about Kuwait.',question:{q:'Where did Sara go?',choices:['Kuwait Towers.','The airport.','A school.'],answer:0},speak:'Last weekend, I visited my grandparents.'},
    {id:'7-2',title:'Travel and Culture',theme:'السفر والثقافة',vocab:[['journey','رحلة'],['culture','ثقافة'],['museum','متحف'],['souvenir','تذكار'],['passport','جواز سفر'],['explore','يستكشف']],grammar:'Comparatives: bigger, more interesting, better.',listen:'Fahad thinks travelling by plane is faster than travelling by car, but he enjoys road trips because he can see more places.',question:{q:'What is faster according to Fahad?',choices:['Travelling by plane.','Travelling by car.','Walking.'],answer:0},speak:'Travelling by plane is faster than travelling by car.'},
    {id:'7-3',title:'Technology Around Us',theme:'التكنولوجيا والاستخدام الآمن',vocab:[['device','جهاز'],['online','عبر الإنترنت'],['password','كلمة مرور'],['private','خاص'],['screen','شاشة'],['search','يبحث']],grammar:'must / mustn’t for rules and safety.',listen:'When you use the internet, you must protect your password and you must not share private information with strangers.',question:{q:'What must you protect?',choices:['Your password.','Your chair.','Your lunch.'],answer:0},speak:'I must keep my password private.'}
  ]},
  8:{title:'الصف الثامن',level:'A2–B1',units:[
    {id:'8-1',title:'Future Kuwait',theme:'المستقبل والمشروعات',vocab:[['future','مستقبل'],['project','مشروع'],['sustainable','مستدام'],['innovation','ابتكار'],['develop','يطور'],['environment','بيئة']],grammar:'Future forms: will / be going to.',listen:'Kuwait is developing new projects for the future. Many young people are going to study technology and help create sustainable solutions.',question:{q:'What are many young people going to study?',choices:['Technology.','Only history.','Cooking.'],answer:0},speak:'I am going to learn new digital skills.'},
    {id:'8-2',title:'Our Environment',theme:'البيئة والمسؤولية',vocab:[['recycle','يعيد التدوير'],['pollution','تلوث'],['protect','يحمي'],['waste','نفايات'],['climate','مناخ'],['reduce','يقلل']],grammar:'First Conditional: If + present, will + verb.',listen:'If we reduce waste and recycle more, we will help protect the environment for future generations.',question:{q:'What will help protect the environment?',choices:['Reducing waste and recycling.','Using more plastic.','Throwing rubbish.'],answer:0},speak:'If I recycle, I will help the environment.'},
    {id:'8-3',title:'Media and Communication',theme:'الإعلام والتواصل',vocab:[['message','رسالة'],['report','تقرير'],['source','مصدر'],['reliable','موثوق'],['headline','عنوان خبر'],['communicate','يتواصل']],grammar:'Present Perfect for experiences and recent actions.',listen:'Mariam has used English websites to research school projects. She has also learned to check whether online sources are reliable.',question:{q:'What has Mariam learned to check?',choices:['Whether sources are reliable.','The weather only.','Bus times.'],answer:0},speak:'I have used English to search for information.'}
  ]},
  9:{title:'الصف التاسع',level:'B1',officialBook:'https://elibrary.moe.edu.kw/api/File/download/book/1476',units:[
    {id:'9-1',title:'Goals and Ambitions',theme:'الأهداف والطموح',vocab:[['ambition','طموح'],['achieve','يحقق'],['challenge','تحدٍ'],['career','مسار مهني'],['improve','يحسن'],['opportunity','فرصة']],grammar:'Gerunds and infinitives: enjoy doing / want to do.',listen:'Ali wants to become an engineer. He enjoys solving problems and plans to improve his English because it will help him at university.',question:{q:'Why does Ali want to improve his English?',choices:['It will help him at university.','He dislikes engineering.','He wants to stop studying.'],answer:0},speak:'I want to improve my English to achieve my goals.'},
    {id:'9-2',title:'Science and Discovery',theme:'العلم والاكتشاف',vocab:[['discover','يكتشف'],['research','بحث'],['experiment','تجربة'],['evidence','دليل'],['result','نتيجة'],['scientist','عالم']],grammar:'Passive voice: is made / was discovered.',listen:'New medicines are tested carefully before they are used. Scientists collect evidence and study the results.',question:{q:'What do scientists study?',choices:['The results.','Only pictures.','Sports scores.'],answer:0},speak:'Scientific results are checked carefully.'},
    {id:'9-3',title:'Global Communication',theme:'الإنجليزية والتواصل العالمي',vocab:[['global','عالمي'],['confident','واثق'],['presentation','عرض'],['discussion','نقاش'],['opinion','رأي'],['fluency','طلاقة']],grammar:'Reported speech: He said that… / She told me that…',listen:'Our teacher said that English helps us communicate with people around the world. She told us to practise speaking every day.',question:{q:'What did the teacher tell the students to do?',choices:['Practise speaking every day.','Stop speaking.','Study only once a month.'],answer:0},speak:'My teacher told me to practise English every day.'}
  ]}
};
window.OFFICIAL={library:'https://elibrary.moe.edu.kw/StudentsLibrary',grade7:'https://elibrary.moe.edu.kw/api/File/download/book/1297',grade9workbook:'https://elibrary.moe.edu.kw/api/File/download/book/1476'};