'use strict';
const $=s=>document.querySelector(s);
let lang='ar',mode='text',image=null,imageUrl=null,api='',token='',busy=false,videoUrl='',activeJob=null;
let drafts=[];try{drafts=JSON.parse(localStorage.getItem('saad-video-drafts')||'[]');if(!Array.isArray(drafts))drafts=[];drafts=drafts.filter(d=>d&&typeof d.prompt==='string'&&typeof d.id==='string')}catch{}
const text=(ar,en)=>lang==='ar'?ar:en;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),5000)}
function show(page){document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==page);document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#pageTitle').textContent=text({studio:'استوديو الفيديو',library:'أعمالي',ideas:'أفكار البداية'}[page],{studio:'Video studio',library:'My projects',ideas:'Scene starters'}[page]);if(page==='library')renderDrafts();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>show(n.dataset.page));
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(n=>{n.classList.toggle('active',n.dataset.mode===mode);n.setAttribute('aria-selected',String(n.dataset.mode===mode))});$('#uploadBox').hidden=mode!=='image'}
document.querySelectorAll('[data-mode]').forEach(n=>n.onclick=()=>setMode(n.dataset.mode));
function setConnected(){ $('#connection').classList.toggle('connected',!!api);$('#connection span').textContent=api?text('المحرك متصل','Engine connected'):text('ربط محرك التوليد','Connect engine');$('#engineNote').textContent=api?text('الخادم متصل. زمن التوليد يعتمد على قدرات GPU.','Engine connected. Generation time depends on GPU capacity.'):text('التوليد ينتظر اتصال خادم GPU. يمكنك تجهيز المشاهد وحفظها الآن.','Generation requires a connected GPU server. Prepare and save scenes now.')}
$('#language').onclick=()=>{lang=lang==='ar'?'en':'ar';document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar]').forEach(n=>n.textContent=n.dataset[lang]);$('#language').textContent=lang==='ar'?'EN':'عربي';$('#prompt').placeholder=text('مثال: قارب خشبي يبحر بهدوء قرب الساحل عند الغروب، انعكاس ذهبي على الماء، حركة كاميرا بطيئة…','Example: A wooden boat glides near the coast at sunset. Golden reflections on the water, slow camera movement…');setConnected();renderIdeas();renderDrafts();show(document.querySelector('.page:not([hidden])').id)};
$('#prompt').oninput=()=>$('#charCount').textContent=$('#prompt').value.length;
function brief(){const prompt=$('#prompt').value.trim(),seed=Number($('#seed').value);if(!prompt){toast(text('اكتب وصف المشهد أولًا.','Describe your scene first.'));return null}if(!Number.isInteger(seed)||seed<0||seed>2147483647){toast(text('اختر بذرة صحيحة بين 0 و2147483647.','Choose an integer seed from 0 to 2147483647.'));return null}return {prompt,mode,seed,style:$('#style').value,camera:$('#camera').value,resolution:'480p',width:832,height:480,num_frames:93,fps:15}}
function inferencePrompt(b){return b.prompt+'\nVisual style: '+b.style+'. Camera movement: '+b.camera+'. Consistent subject, natural movement, coherent lighting.'}
$('#buildPrompt').onclick=()=>{if(!$('#prompt').value.trim())return toast(text('اكتب الفكرة الأساسية أولًا.','Write your main idea first.'));const extra=text(' إضاءة متوازنة، تفاصيل واضحة، حركة طبيعية، وتناسق بصري بين إطارات المشهد.',' Balanced lighting, clear details, natural motion and consistent frames.');if(!$('#prompt').value.includes(extra.trim()))$('#prompt').value=($('#prompt').value+extra).slice(0,2000);$('#prompt').oninput();toast(text('أُضيفت تفاصيل ثابتة؛ يمكنك تعديلها.','Fixed descriptive details added; you can edit them.'))};
function clearImage(){image=null;if(imageUrl)URL.revokeObjectURL(imageUrl);imageUrl=null;$('#imageInput').value='';$('#imagePreview').hidden=true;$('#removeImage').hidden=true}
$('#removeImage').onclick=clearImage;
$('#imageInput').onchange=()=>{const f=$('#imageInput').files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024){clearImage();return toast(text('اختر JPG أو PNG أو WEBP بحجم لا يتجاوز 10 MB.','Choose JPG, PNG or WEBP up to 10 MB.'))}clearImage();image=f;imageUrl=URL.createObjectURL(f);$('#imagePreview').src=imageUrl;$('#imagePreview').hidden=false;$('#removeImage').hidden=false};
$('#newProject').onclick=()=>{if(busy)return toast(text('انتظر انتهاء الطلب الحالي.','Wait for the current request.'));$('#prompt').value='';$('#prompt').oninput();clearImage();setMode('text');videoUrl='';$('#resultVideo').hidden=true;$('#resultVideo').removeAttribute('src');$('#resultVideo').load();$('#canvas').hidden=false;$('#downloadVideo').hidden=true;$('#seed').value=42;$('#prompt').focus()};
function persist(){try{localStorage.setItem('saad-video-drafts',JSON.stringify(drafts));$('#projectCount').textContent=drafts.length;return true}catch{toast(text('تعذر الحفظ. قد تكون مساحة المتصفح ممتلئة.','Could not save. Browser storage may be full.'));return false}}
$('#saveDraft').onclick=()=>{const b=brief();if(!b)return;drafts.unshift({...b,id:crypto.randomUUID(),created:new Date().toISOString()});if(!persist()){drafts.shift();return}toast(text('حُفظ المشهد في أعمالي.','Scene saved in My projects.'))};
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#exportDraft').onclick=()=>{const b=brief();if(b)download(JSON.stringify({...b,engine:'LongCat-Video',inference_prompt:inferencePrompt(b)},null,2),'saad-scene.json','application/json')};
function renderDrafts(){const root=$('#drafts');root.replaceChildren();$('#projectCount').textContent=drafts.length;if(!drafts.length){const p=document.createElement('p');p.className='empty';p.textContent=text('لا توجد مشاهد محفوظة بعد. اكتب فكرتك ثم اضغط «حفظ المشهد».','No saved scenes yet. Write an idea and choose Save scene.');root.append(p);return}drafts.forEach(d=>{const card=document.createElement('article');card.className='draft';const small=document.createElement('small');small.textContent=new Date(d.created).toLocaleDateString(lang==='ar'?'ar-KW':'en-GB')+' · '+(d.mode==='image'?text('صورة إلى فيديو','Image to video'):text('نص إلى فيديو','Text to video'));const p=document.createElement('p');p.textContent=d.prompt;const actions=document.createElement('div');const open=document.createElement('button');open.className='outline';open.textContent=text('تعديل المشهد','Edit scene');open.onclick=()=>{$('#prompt').value=d.prompt;$('#seed').value=d.seed;$('#style').value=d.style;$('#camera').value=d.camera;setMode(d.mode);clearImage();$('#prompt').oninput();show('studio');if(d.mode==='image')toast(text('اختر الصورة المرجعية مرة أخرى.','Choose the reference image again.'))};const del=document.createElement('button');del.className='text-button';del.textContent=text('حذف','Delete');del.onclick=()=>{drafts=drafts.filter(x=>x.id!==d.id);persist();renderDrafts()};actions.append(open,del);card.append(small,p,actions);root.append(card)})}
const ideas=[
{ar:'هدوء الغروب',en:'Golden silence',tagAr:'طبيعة · سينمائي',tagEn:'Nature · cinematic',art:'desert',promptAr:'كثبان رملية هادئة عند الغروب، رياح خفيفة تحرك الرمال، ضوء ذهبي دافئ، حركة كاميرا بطيئة تكشف امتداد الصحراء.',promptEn:'Quiet dunes at sunset, soft wind moving the sand, warm golden light, a slow camera pan reveals the vast desert.'},
{ar:'رحلة على الساحل',en:'Along the coast',tagAr:'سفر · واقعي',tagEn:'Travel · realistic',art:'ocean',promptAr:'قارب خشبي صغير يبحر قرب الساحل بهدوء، أمواج لطيفة وانعكاس الشمس على سطح الماء، مشهد واقعي بكاميرا تقترب ببطء.',promptEn:'A small wooden boat sails quietly along the coast, gentle waves and sunlight reflecting on the water, realistic imagery with a slow dolly in.'},
{ar:'منتج في دائرة الضوء',en:'In the spotlight',tagAr:'منتجات · إعلان',tagEn:'Product · advertising',art:'product',promptAr:'كوب خزفي بسيط على طاولة بلون أخضر هادئ، ضوء نافذة جانبي، بخار خفيف يرتفع من الكوب، كاميرا تتحرك ببطء لإظهار التفاصيل دون نصوص.',promptEn:'A minimalist ceramic cup on a muted green table, side window lighting, delicate steam rises, a slow camera movement reveals texture, no text.'}
];
function renderIdeas(){['starterGrid','ideaGrid'].forEach(id=>{const root=$('#'+id);root.replaceChildren();ideas.forEach(i=>{const b=document.createElement('button');b.className='idea';const art=document.createElement('div');art.className='idea-art '+i.art;const c=document.createElement('div');c.className='idea-caption';const t=document.createElement('div');const name=document.createElement('strong');name.textContent=text(i.ar,i.en);const tag=document.createElement('small');tag.textContent=text(i.tagAr,i.tagEn);const arrow=document.createElement('span');arrow.textContent='↗';t.append(name,tag);c.append(t,arrow);b.append(art,c);b.onclick=()=>{$('#prompt').value=text(i.promptAr,i.promptEn);$('#prompt').oninput();show('studio');$('#prompt').focus()};root.append(b)})})}
$('#allIdeas').onclick=()=>show('ideas');
$('#connection').onclick=()=>$('#connectDialog').showModal();
$('#closeDialog').onclick=()=>$('#connectDialog').close();
$('#disconnect').onclick=()=>{if(busy)return toast(text('الطلب الحالي قيد المعالجة.','A request is processing.'));api='';token='';$('#apiToken').value='';setConnected();$('#connectDialog').close()};
async function request(path,opts={}){const r=await fetch(api+path,{...opts,headers:{...(opts.headers||{}),Authorization:'Bearer '+token},signal:AbortSignal.timeout(20000)});if(!r.ok){let msg='HTTP '+r.status;try{const e=await r.json();msg=typeof e.detail==='string'?e.detail:msg}catch{}throw new Error(msg)}return r}
$('#connectForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const u=new URL($('#apiUrl').value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash)throw new Error(text('استخدم عنوان HTTPS صالحًا.','Use a valid HTTPS URL.'));const next=u.href.replace(/\/$/,'');const r=await fetch(next+'/health',{headers:{Authorization:'Bearer '+$('#apiToken').value},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(data.engine!=='LongCat-Video'||data.ready!==true)throw new Error(text('خادم التوليد غير جاهز.','Generation server is not ready.'));if(busy)throw new Error(text('انتظر انتهاء الطلب الحالي قبل تغيير الخادم.','Wait for the active job before changing servers.'));api=next;token=$('#apiToken').value;setConnected();$('#connectDialog').close();toast(text('تم الاتصال بالمحرك.','Engine connected.'))}catch(err){$('#connectMessage').textContent=text('تعذر الربط: ','Connection failed: ')+err.message}finally{button.disabled=false}};
function setBusy(v){busy=v;$('#generate').disabled=v;$('#generate b').textContent=v?text('المعالجة على الخادم…','Processing on the server…'):text('توليد الفيديو','Generate video')}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
$('#generate').onclick=async()=>{const b=brief();if(!b)return;if(!api){$('#connectDialog').showModal();return}if(mode==='image'&&!image)return toast(text('اختر صورة مرجعية أولًا.','Select a reference image first.'));setBusy(true);try{const form=new FormData();form.append('prompt',inferencePrompt(b));form.append('mode',b.mode);form.append('seed',String(b.seed));if(image&&mode==='image')form.append('image',image);const created=await (await request('/jobs',{method:'POST',body:form})).json();activeJob=created.id;toast(text('أُرسل الطلب. يمكنك إبقاء الصفحة مفتوحة حتى تظهر النتيجة.','Request submitted. Keep this page open for the result.'));let complete=false;for(let i=0;i<720;i++){await wait(5000);const result=await (await request('/jobs/'+encodeURIComponent(activeJob))).json();if(result.status==='failed')throw new Error(result.error||'Generation failed');if(result.status==='completed'){videoUrl=api+'/jobs/'+encodeURIComponent(activeJob)+'/video';const blob=await (await request('/jobs/'+encodeURIComponent(activeJob)+'/video')).blob();if($('#resultVideo').src.startsWith('blob:'))URL.revokeObjectURL($('#resultVideo').src);$('#resultVideo').src=URL.createObjectURL(blob);$('#resultVideo').hidden=false;$('#canvas').hidden=true;$('#downloadVideo').hidden=false;toast(text('الفيديو جاهز.','Your video is ready.'));complete=true;break}}if(!complete)throw new Error(text('انتهت مهلة المتابعة. رقم الطلب: ','Tracking timed out. Job ID: ')+activeJob)}catch(err){toast(text('لم يكتمل الطلب: ','Request incomplete: ')+err.message)}finally{setBusy(false)}};
$('#downloadVideo').onclick=()=>{if(!videoUrl)return;const a=document.createElement('a');a.href=$('#resultVideo').src;a.download='saad-video.mp4';a.click()};
renderIdeas();renderDrafts();setConnected();
$('#freeGPU').onclick=()=>$('#freeDialog').showModal();
$('#closeFree').onclick=()=>$('#freeDialog').close();
$('#openSpace').onclick=()=>{try{const u=new URL($('#spaceUrl').value);if(u.protocol!=='https:'||u.hostname!=='huggingface.co'||!/^\/spaces\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\/?$/.test(u.pathname)||u.username||u.password||u.search||u.hash)throw new Error();window.open(u.href,'_blank','noopener,noreferrer')}catch{toast(text('أدخل رابط مساحة Hugging Face صالحًا.','Enter a valid Hugging Face Space URL.'))}};
$('#copyPrompt').onclick=async()=>{const b=brief();if(!b)return;try{await navigator.clipboard.writeText(inferencePrompt(b));toast(text('نُسخ وصف المشهد. الصقه في مساحة التوليد.','Prompt copied. Paste it in your generation Space.'))}catch{toast(text('تعذر النسخ؛ استخدم تصدير الوصف.','Copy failed; use Export brief.'))}};
