'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={dashboard:'لوحة التحكم',library:'مكتبة المناهج',plans:'الخطة السنوية',events:'البرامج والفعاليات',evidence:'الشواهد والمراجعة',reports:'التقارير',assistant:'مساعد النشاط',studio:'استوديو المحتوى',paths:'المسارات والتكاملات',finance:'المتابعة المالية',settings:'المدرسة والإعدادات'};
const defaults={school:'مدرستي',region:'العاصمة',stage:'المتوسط',year:'2026/2027',goal:'تعزيز مشاركة الطلبة وربط النشاط بالمنهج',budget:100,events:[],costs:[]};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem('sinad-v1')||'{}')}}catch{state=structuredClone(defaults)}
let catalog={items:[]}, corpus=[], view='dashboard', selected=null, filters={}, libraryError='', evidenceCount=0;
const kindNames={book:'كتاب دراسي',worksheet:'مراجعات وأوراق عمل',video:'فيديو تعليمي'};
const pathways=[
 ['مسار أدوات التصميم','مفعّل','واجهة عربية RTL، قائمة يمين، خط القاهرة، مظهر فاتح وداكن، طباعة متجاوبة.'],
 ['مسار التحليل','مفعّل','مزامنة واجهات وزارة التربية العامة والتحقق من المخطط وإزالة التكرار وحفظ آخر فهرس ناجح.'],
 ['مسار تحليل قوقل','مطبّق كمنهج عمل','فهم الهدف ← اختيار المصدر ← اقتراح النشاط ← مراجعة المصدر ← اعتماد المعلم. لا توجد خدمة Google Agents متصلة.'],
 ['مسار الوكلاء','مفعّل محليًا','مخطط نشاط ومراجع اكتمال وموجّه مصادر؛ يعمل بقواعد واضحة دون استدعاء نموذج خارجي.'],
 ['مسار البرومبتات','مفعّل','تصدير تعليمات مكتملة تحمل المصدر والدرس والقيود التعليمية والمخرجات المطلوبة.'],
 ['مسار المواصفات Spec Kit','موثّق','ملف SPEC.md يحدد نطاق النسخة ومعايير القبول والانتقال إلى تشغيل المدارس المتعدد.'],
 ['مسار MarkItDown','موصل جاهز للتشغيل','سكربت استخراج الكتب العامة إلى مقاطع مع رقم الصفحة والرابط؛ يتطلب تثبيت تبعيات Python وتشغيل الاستخراج.'],
 ['مسار Buzz','مهيّأ','فصل الصياغة عن مراجعة المصادر في البرومبت المصدّر؛ مكتبة Buzz نفسها لم تُثبّت.'],
 ['مسار الهندسي','مفعّل','فصل بيانات المناهج العامة عن سجلات المدرسة الخاصة، وفحص المدخلات والنشر المعزول.'],
 ['مسار الفوتوشوب / Compositor','بديل محلي مفعّل','قالب إعلان نشاط عربي على Canvas مع تنزيل PNG؛ Compositor وCanva لم يتصلا بحساب بعد.'],
 ['المسار العاشر / OpenShorts','حزمة مهام جاهزة','تصدير موجز فيديو عمودي وتسلسل المشاهد ومراجع الكتاب بصيغة JSON؛ التنفيذ والنشر الاجتماعي يحتاجان خدمة فيديو.'],
 ['مسار الصوت والفيديو','مفعّل جزئيًا','إملاء صوتي عند دعم المتصفح وقراءة النص العربي؛ توليد الفيديو الخارجي غير متصل.'],
 ['مسار المحتوى / AutoClip','جاهز بالبرومبت','موجز إعلان ونشاط وأسئلة مراجعة؛ لا يجري توليد فيديو أو إعادة نشر كتب.'],
 ['المسار المالي','مفعّل محليًا','ميزانية النشاط والمصروفات والتنبيه عند تجاوز 80%؛ استهلاك الكريدتس يتطلب ربط مزودي الخدمة.'],
 ['المسار الصيني / NVIDIA','غير متصل','يُترك للنشر الخلفي فقط؛ لا مفاتيح أو طلبات API من المتصفح.'],
 ['مسار الجودة','مفعّل','كشف نقص الهدف والصف والمصدر والدرس والشاهد قبل اعتماد النشاط.']
];
function save(){try{localStorage.setItem('sinad-v1',JSON.stringify(state));return true}catch{toast('تعذر الحفظ؛ صدّر نسخة احتياطية قبل مغادرة الصفحة.');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500)}
function download(name,data,type='application/json'){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function options(values,current,all='الكل'){return `<option value="">${all}</option>`+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')).map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('')}
function field(label,name,value='',type='text',extra=''){return `<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function show(k){view=k;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==k+'View');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===k));$('#pageTitle').textContent=names[k];$('#sidebar').classList.remove('open');$('#menuBtn').setAttribute('aria-expanded','false');render()}
function panel(title,content){return `<div class="panel section"><h3>${title}</h3>${content}</div>`}
function empty(text){return `<p class="empty">${text}</p>`}
function sourceBook(id){return catalog.items.find(x=>x.id===id)}
function review(e){return [!e.title&&'اسم النشاط',!e.goal&&'الهدف',!e.grade&&'الصف',!sourceBook(e.bookId)&&'المصدر الرسمي',!e.lesson&&'الدرس والصفحة',!e.evidence?.length&&'شاهد التنفيذ'].filter(Boolean)}
function eventRows(){return state.events.map(e=>`<tr><td><strong>${esc(e.title)}</strong><br><small>${esc(e.grade)} • ${esc(e.lesson)}</small></td><td>${esc(e.owner)}</td><td>${esc(e.date)}</td><td>${esc(e.status)}</td><td><button class="btn secondary" data-edit="${esc(e.id)}">تعديل</button></td></tr>`).join('')}
function render(){const el=$('#'+view+'View');
 if(view==='dashboard'){const done=state.events.filter(e=>e.status==='معتمد').length;el.innerHTML=`<div class="hero"><div class="panel hero-card"><p>${esc(state.school)} • ${esc(state.year)}</p><h3>من المنهج إلى نشاط له أثر</h3><p>اختر كتابًا رسميًا، حدّد الدرس، ثم خطّط للنشاط ووثّق التنفيذ وراجع التقرير.</p><div class="hero-metrics"><div class="metric"><span class="label">المصادر المفهرسة</span><strong>${catalog.items.length}</strong></div><div class="metric"><span class="label">الفعاليات</span><strong>${state.events.length}</strong></div><div class="metric"><span class="label">المعتمد بالمراجعة</span><strong>${done}</strong></div></div><div class="actions"><button class="btn" data-goto="library">ابدأ من المنهج</button><button class="btn secondary" data-goto="plans">جهّز الخطة</button></div></div>${panel('حالة النظام',`<p>آخر مزامنة: ${catalog.syncedAt?new Date(catalog.syncedAt).toLocaleString('ar-KW',{timeZone:'Asia/Kuwait'}):'لم تكتمل'}</p><p>${libraryError?esc(libraryError):'الفهرس يعرض بيانات المصدر الرسمي وروابطه.'}</p><div class="notice">سجلات المدرسة والمرفقات محفوظة في هذا المتصفح. مشاركة البيانات بين المستخدمين تحتاج خادمًا وصلاحيات.</div><button class="btn secondary" data-goto="paths">عرض حالة المسارات</button>`)}</div>${panel('فعاليات المدرسة',state.events.length?`<div class="table-wrap"><table><thead><tr><th>النشاط</th><th>المسؤول</th><th>التاريخ</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${eventRows()}</tbody></table></div>`:empty('لا توجد فعاليات مسجلة بعد. أضف أول فعالية من مكتبة المناهج.'))}`}
 if(view==='library')renderLibrary();
 if(view==='events')el.innerHTML=panel('الفعاليات',state.events.length?`<div class="table-wrap"><table><thead><tr><th>النشاط والمنهج</th><th>المسؤول</th><th>التاريخ</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>${eventRows()}</tbody></table></div>`:empty('ابدأ بإضافة فعالية وربطها بكتاب.'));
 if(view==='plans')el.innerHTML=panel('خطة النشاط المدرسي',`<form id="planForm"><div class="form-grid">${field('المدرسة','school',state.school)}${field('العام الدراسي','year',state.year)}<div class="field"><label for="region">المنطقة التعليمية</label><select id="region" name="region">${options(['العاصمة','حولي','الفروانية','الجهراء','الأحمدي','مبارك الكبير'],state.region,'اختر المنطقة')}</select></div><div class="field"><label for="stage">المرحلة</label><select id="stage" name="stage">${options(['رياض الأطفال','الإبتدائية','المتوسط','الثانوية'],state.stage,'اختر المرحلة')}</select></div><div class="field" style="grid-column:1/-1"><label for="goal">هدف الخطة</label><textarea id="goal" name="goal">${esc(state.goal)}</textarea></div></div><div class="actions"><button class="btn">حفظ الخطة</button><button type="button" class="btn secondary" data-goto="library">اختيار المناهج</button></div></form><p>المواعيد والمناسبات تُحدّد داخل الفعاليات وفق تعميم المدرسة؛ لا يفترض النظام تقويمًا وزاريًا معتمدًا.</p>`);
 if(view==='evidence')el.innerHTML=panel('مراجعة المصدر والتنفيذ',`<p class="muted">الاعتماد هنا مراجعة داخلية في الجهاز، ويحتاج النظام الإنتاجي حسابات مدير ومعلم وسجل تدقيق.</p><div class="list">${state.events.map(e=>{const gaps=review(e);return `<div class="task"><div><strong>${esc(e.title)}</strong><small>${gaps.length?'ناقص: '+esc(gaps.join('، ')):'اكتملت حقول المراجعة'} • ${e.evidence?.length||0} شاهد</small><div class="actions">${(e.evidence||[]).map(f=>`<button class="btn secondary" data-file="${esc(f.id)}">${esc(f.name)}</button>`).join('')}</div></div><div class="actions"><button class="btn secondary" data-edit="${e.id}">استكمال</button><button class="btn" data-approve="${e.id}" ${gaps.length?'disabled':''}>اعتماد</button></div></div>`}).join('')||empty('الشواهد تظهر بعد تسجيل الفعاليات.')}</div>`);
 if(view==='reports')el.innerHTML=panel('تقرير النشاط المدرسي',`<div class="actions no-print"><button class="btn" data-print>طباعة / حفظ PDF</button><button class="btn secondary" id="csvBtn">تصدير CSV</button></div><div class="report"><h2>${esc(state.school)}</h2><p>المنطقة: ${esc(state.region)} • العام: ${esc(state.year)}</p><p>هدف الخطة: ${esc(state.goal)}</p><p>الفعاليات: ${state.events.length} • المعتمدة: ${state.events.filter(e=>e.status==='معتمد').length}</p>${state.events.map(e=>{const b=sourceBook(e.bookId);return `<article class="section"><h3>${esc(e.title)}</h3><p>الصف: ${esc(e.grade)} • المسؤول: ${esc(e.owner)} • التاريخ: ${esc(e.date)}</p><p>الهدف: ${esc(e.goal)}</p><p>الدرس والصفحة: ${esc(e.lesson)}</p><p>المصدر: ${b?esc(b.title):'لم يحدد'} ${b?`<a href="${esc(b.source)}" target="_blank" rel="noopener">المصدر الرسمي</a>`:''}</p><p>التنفيذ: ${esc(e.notes)}</p><p>الحالة: ${esc(e.status)} • الشواهد: ${e.evidence?.length||0}</p></article>`}).join('')}</div>`);
 if(view==='paths')el.innerHTML=panel('حالة المسارات الفعلية',`<div class="notice">كل بطاقة توضح ما يعمل الآن وما يحتاج خدمة خارجية. لم تُشغّل خدمات مدفوعة أو تُربط حسابات Canva أو نماذج AI دون إعداد.</div><div class="cards">${pathways.map(([n,s,d])=>`<article class="panel book"><span class="badge">${s}</span><h3>${n}</h3><p>${d}</p></article>`).join('')}</div>`);
 if(view==='assistant')el.innerHTML=panel('مساعد تخطيط النشاط',`<p>يقترح قالبًا بقواعد تربوية، ويبحث في نصوص الكتب المستخرجة إن كانت متاحة. مقترحاته تحتاج مراجعة المعلم.</p><div class="field"><label for="question">هدف النشاط أو السؤال</label><textarea id="question" placeholder="أريد نشاطًا عن المحافظة على البيئة"></textarea></div><div class="actions"><button class="btn" id="askBtn">إعداد مقترح</button><button class="btn secondary" id="micBtn">إملاء صوتي</button><button class="btn secondary" id="speakBtn">قراءة المقترح</button><button class="btn secondary" id="promptBtn">تصدير البرومبت</button></div><div class="field"><label for="assistantBook">الكتاب المرجعي</label><select id="assistantBook">${bookOptions(selected)}</select></div><div class="field"><label for="assistantLesson">الدرس ورقم الصفحة بعد مراجعتهما في الكتاب</label><input id="assistantLesson" placeholder="اسم الدرس • الصفحة"></div><pre id="answer" class="notice" aria-live="polite">حدد الهدف والمصدر لبدء التخطيط.</pre>`);
 if(view==='studio')el.innerHTML=panel('استوديو إعلان النشاط',`<div class="form-grid">${field('العنوان','posterTitle','نشاطنا المدرسي')}${field('التاريخ','posterDate','')}${field('وصف مختصر','posterText','من المنهج إلى التجربة')}${field('المدرسة','posterSchool',state.school)}</div><div class="actions"><button class="btn" id="posterBtn">إنشاء وتنزيل PNG</button><button class="btn secondary" id="videoBtn">تصدير مهمة فيديو</button></div><canvas id="poster" width="1080" height="1350" style="width:min(100%,360px);border-radius:20px" aria-label="معاينة إعلان النشاط"></canvas><p class="muted">قالب أصلي لهذا النظام. لا يُستخدم أي مشروع خاص كقالب.</p>`);
 if(view==='finance'){const total=state.costs.reduce((a,c)=>a+Number(c.amount),0);el.innerHTML=panel('ميزانية الأنشطة بالدينار الكويتي',`<div class="notice">المصروف: ${total.toFixed(3)} د.ك من ${Number(state.budget).toFixed(3)} د.ك • ${total>=Number(state.budget)*.8?'تنبيه: اقتربت الميزانية من الحد أو تجاوزته':'ضمن الميزانية'}</div><form id="costForm"><div class="form-grid">${field('وصف المصروف','costTitle','','text','required')}${field('المبلغ بالدينار','costAmount','','number','required min="0.001" step="0.001"')}</div><div class="actions"><button class="btn">إضافة مصروف</button></div></form><div class="list">${state.costs.map(c=>`<div class="task"><span>${esc(c.title)} • ${Number(c.amount).toFixed(3)} د.ك</span><button class="btn secondary" data-cost-delete="${c.id}">حذف</button></div>`).join('')}</div><p class="muted">هذه ميزانية النشاط. لا توجد قراءة آلية لاستهلاك كريدتس مزودي AI.</p>`)}
 if(view==='settings')el.innerHTML=panel('الإعدادات والنسخة الاحتياطية',`<form id="settingsForm"><div class="form-grid">${field('اسم المدرسة','school',state.school,'text','required')}${field('ميزانية النشاط د.ك','budget',state.budget,'number','required min="0" step="0.001"')}</div><div class="actions"><button class="btn">حفظ</button></div></form><div class="notice">البيانات محفوظة في جهازك، وليست مشتركة بين المدارس. النسخة الاحتياطية تضم السجلات فقط؛ احتفظ بالمرفقات الأصلية بصورة منفصلة.</div><div class="actions"><button class="btn secondary" id="backupBtn">تصدير السجلات</button><label class="btn secondary" for="restore">استعادة السجلات</label><input id="restore" type="file" accept=".json" hidden></div><p>الدفع KNET والحسابات والصلاحيات لم تُفعّل في هذه النسخة. الأسعار التجارية تُحدد بعد اختبار المدارس.</p>`);
}
function renderLibrary(){let list=catalog.items.filter(b=>Object.entries(filters).every(([k,v])=>!v||(k==='q'?(b.title+' '+b.subject).includes(v):String(b[k])===v)));$('#libraryView').innerHTML=panel('المناهج الرسمية الكويتية',`<div class="actions"><a class="btn secondary" target="_blank" rel="noopener" href="https://elibrary.moe.edu.kw/StudentsLibrary">مكتبة الطالب الرسمية</a><button class="btn secondary" id="reloadBtn">إعادة تحميل الفهرس</button></div><p>${catalog.items.length} مصدر • آخر مزامنة ${catalog.syncedAt?new Date(catalog.syncedAt).toLocaleDateString('ar-KW'):'غير متاحة'}</p><p class="muted sub">الفهرس يحتوي العناوين والتصنيفات والروابط. نصوص الدروس تتاح بعد الاستخراج، وسنة الإصدار تحتاج مراجعة الكتاب.</p><div class="filters"><div class="field"><label for="filter-q">بحث بالعنوان</label><input id="filter-q" data-filter="q" value="${esc(filters.q||'')}"></div>${['type','stage','grade','subject'].map((k,i)=>`<div class="field"><label for="filter-${k}">${['نوع التعليم','المرحلة','الصف','المادة'][i]}</label><select id="filter-${k}" data-filter="${k}">${options(catalog.items.map(b=>b[k]),filters[k])}</select></div>`).join('')}<div class="field"><label for="filter-term">الفصل</label><select id="filter-term" data-filter="term"><option value="">الكل</option><option value="1" ${filters.term==='1'?'selected':''}>الأول</option><option value="2" ${filters.term==='2'?'selected':''}>الثاني</option></select></div><div class="field"><label for="filter-kind">المصدر</label><select id="filter-kind" data-filter="kind"><option value="">الكل</option>${Object.entries(kindNames).map(([k,n])=>`<option value="${k}" ${filters.kind===k?'selected':''}>${n}</option>`).join('')}</select></div><button class="btn secondary" id="clearFilters">مسح الفلاتر</button></div><div class="notice" role="status">${list.length} نتيجة • عرض أول 60 نتيجة؛ ضيّق البحث لرؤية الكتاب المطلوب. ${esc(libraryError)}</div><div class="cards">${list.slice(0,60).map(b=>`<article class="panel book"><span class="badge">${kindNames[b.kind]||''}</span><h3>${esc(b.title)}</h3><p>${esc(b.type)} • ${esc(b.stage)} • ${esc(b.grade)}</p><p>${esc(b.subject)} • الفصل ${b.term===1?'الأول':'الثاني'}</p><small>تاريخ رفع المصدر: ${esc((b.sourceDate||'غير متاح').slice(0,10))}</small><div class="actions"><a class="btn secondary" target="_blank" rel="noopener" href="${esc(b.source)}">فتح المصدر</a>${b.kind==='book'?`<button class="btn" data-book="${esc(b.id)}">ربط بنشاط</button>`:''}</div></article>`).join('')||empty(libraryError||'لا توجد نتائج لهذه الفلاتر.')}</div>`)}
function bookOptions(current){return '<option value="">حدد كتابًا</option>'+catalog.items.filter(b=>b.kind==='book').map(b=>`<option value="${b.id}" ${b.id===current?'selected':''}>${esc(b.title+' • '+b.grade+' • الفصل '+b.term)}</option>`).join('')}
function editor(id,bookId){const e=state.events.find(x=>x.id===id)||{id:crypto.randomUUID(),title:'',owner:'',date:'',grade:sourceBook(bookId)?.grade||'',goal:'',lesson:'',bookId:bookId||'',notes:'',status:'مسودة',evidence:[]};$('#editor').innerHTML=`<form id="eventForm"><h2>${id?'تعديل':'إضافة'} فعالية</h2><input name="id" type="hidden" value="${e.id}"><div class="form-grid">${field('اسم النشاط','title',e.title,'text','required maxlength="160"')}${field('المسؤول','owner',e.owner)}${field('التاريخ','date',e.date,'date')}${field('الصف','grade',e.grade)}<div class="field" style="grid-column:1/-1"><label for="bookId">الكتاب المرجعي</label><select id="bookId" name="bookId">${bookOptions(e.bookId)}</select></div>${field('الدرس ورقم الصفحة','lesson',e.lesson)}<div class="field"><label for="status">الحالة</label><select id="status" name="status">${options(['مسودة','مجدولة','منفذة'],e.status==='معتمد'?'منفذة':e.status,'حدد الحالة')}</select></div><div class="field"><label for="eventGoal">الهدف</label><textarea name="goal" id="eventGoal">${esc(e.goal)}</textarea></div><div class="field"><label for="notes">ملاحظات التنفيذ</label><textarea name="notes" id="notes">${esc(e.notes)}</textarea></div><div class="field"><label for="files">شواهد PDF أو صور (10MB لكل ملف)</label><input id="files" name="files" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf"></div></div><p class="muted">${e.evidence?.length||0} مرفق محفوظ. أي تعديل يعيد النشاط إلى المراجعة.</p><div class="actions"><button class="btn">حفظ</button><button type="button" class="btn secondary" id="closeEditor">إغلاق</button>${id?`<button type="button" class="btn secondary" data-delete="${id}">حذف النشاط</button>`:''}</div></form>`;$('#editor').showModal()}
function db(){return new Promise((resolve,reject)=>{const r=indexedDB.open('sinad-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putFiles(files){if(!files.length)return [];for(const f of files)if(f.size>10*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type))throw Error('ارفع صورة أو PDF بحد 10MB لكل ملف.');const d=await db();const records=files.map(f=>({id:crypto.randomUUID(),name:f.name,blob:f}));await new Promise((r,j)=>{const t=d.transaction('files','readwrite');for(const f of records)t.objectStore('files').put(f);t.oncomplete=r;t.onerror=()=>j(t.error)});d.close();return records.map(({id,name})=>({id,name}))}
async function getFile(id){const d=await db();const f=await new Promise((r,j)=>{const q=d.transaction('files').objectStore('files').get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});d.close();if(f)download(f.name,f.blob,f.blob.type);else toast('المرفق غير موجود في هذا المتصفح. استعد الملف الأصلي.')}
async function loadCatalog(){try{const r=await fetch('data/catalog.json',{cache:'no-cache'});if(!r.ok)throw Error();const c=await r.json();if(!Array.isArray(c.items))throw Error();catalog=c;libraryError=''}catch{libraryError='تعذر تحميل الفهرس. افتح الموقع المنشور أو أعد المحاولة.'}try{const r=await fetch('data/corpus.json');if(r.ok)corpus=(await r.json()).chunks||[]}catch{}render()}
function draft(){const q=$('#question').value.trim(),b=sourceBook($('#assistantBook').value),lesson=$('#assistantLesson').value.trim();if(!q){toast('اكتب الهدف أولًا.');return ''}const hits=corpus.filter(c=>c.reviewed===true&&c.bookId===b?.id&&q.split(/\s+/).some(w=>w.length>2&&c.text.includes(w))).slice(0,3);return `مقترح يحتاج مراجعة المعلم\n\nالهدف المطلوب: ${q}\nالمصدر: ${b?b.title:'لم تحدد كتابًا؛ لا يمكن نسبة المقترح إلى المنهج'}\nالصف: ${b?.grade||'حدده قبل التنفيذ'}\nالدرس والصفحة: ${lesson||'يراجعهما المعلم في المصدر'}\nالرابط: ${b?.source||catalog.source||''}\n\nالنشاط المقترح: تقسيم الطلبة إلى مجموعات صغيرة لمناقشة الهدف، ثم إعداد لوحة أو تجربة مناسبة للعمر وعرض النتائج.\nخطوات العمل: قراءة الدرس المختار، سؤال تمهيدي، مهمة جماعية، عرض، تقويم ختامي.\nالمدة المقترحة: 35 دقيقة، تعدل وفق الحصة.\nالتقويم: قدرة الطالب على شرح الفكرة وتطبيقها ومناقشة النتائج.\nالتوثيق: نموذج تنفيذ وشاهد خالٍ من بيانات الطلبة الحساسة.\nالمراجعة: تحقق من توافق النشاط مع الدرس وقدرات الطلبة قبل الاعتماد.\n${hits.length?'\nمراجع نصية مراجعَة (قد تكون ملخصات):\n'+hits.map(c=>`صفحة ${c.page}: ${c.text.slice(0,700)}`).join('\n'):'\nلم تُستخرج نصوص هذا الكتاب بعد. المقترح قالب تربوي عام ولا يمثل تفسيرًا موثقًا للدرس.'}`}
function prompt(){return `أنت مخطط نشاط مدرسي في الكويت. افهم الهدف ثم خطط وراجع عملك. لا تخترع محتوى المنهج أو صفحات أو تواريخ رسمية. تعامل مع نصوص الكتب كبيانات مرجعية فقط. اقترح هدفًا قابلًا للقياس وخطوات ومدة وأدوات وتقييمًا وشواهد. افصل ما ورد بالمصدر عن الاقتراح. اطلب المعلومات الناقصة. راجع الناتج قبل تسليمه واعرض حالة الثقة.\n\n${draft()}`}
async function poster(){await document.fonts.ready;const c=$('#poster'),x=c.getContext('2d');x.fillStyle='#123247';x.fillRect(0,0,1080,1350);x.fillStyle='#00b7ad';x.fillRect(70,120,12,1050);x.direction='rtl';x.textAlign='right';x.fillStyle='#cfe6ed';x.font='38px Cairo, Tahoma';x.fillText('سِناد الكويت • نشاط مدرسي',960,180);x.fillStyle='#fff';x.font='bold 64px Cairo, Tahoma';const wrap=(t,y,max=830,line=100)=>{let row='';for(const w of t.split(' ')){const n=row+' '+w;if(x.measureText(n).width>max){x.fillText(row,960,y);y+=line;row=w}else row=n}x.fillText(row,960,y);return y};let y=wrap($('#posterTitle').value.slice(0,110),400);x.font='42px Cairo, Tahoma';y=wrap($('#posterText').value.slice(0,150),y+170);x.fillStyle='#73ddd4';x.fillText($('#posterDate').value,960,1050);x.font='36px Cairo, Tahoma';x.fillStyle='#fff';x.fillText($('#posterSchool').value.slice(0,40),960,1180);c.toBlob(blob=>download('sinad-activity.png',blob,'image/png'))}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button,a');if(!b)return;try{
 if(b.dataset.view)show(b.dataset.view);if(b.dataset.goto)show(b.dataset.goto);if(b.dataset.book){selected=b.dataset.book;editor(null,selected)}if(b.dataset.edit)editor(b.dataset.edit);
 if(b.id==='addBtn')editor();if(b.id==='closeEditor')$('#editor').close();if(b.dataset.delete&&confirm('حذف هذه الفعالية؟')){state.events=state.events.filter(e=>e.id!==b.dataset.delete);save();$('#editor').close();render()}
 if(b.dataset.approve){const e=state.events.find(e=>e.id===b.dataset.approve);if(review(e).length)return toast('استكمل حقول المراجعة.');e.status='معتمد';save();render()}
 if(b.dataset.file)await getFile(b.dataset.file);if(b.id==='menuBtn'){const open=$('#sidebar').classList.toggle('open');b.setAttribute('aria-expanded',String(open))}if(b.id==='themeBtn'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark'}
 if(b.id==='printBtn'){show('reports');window.print()}if(b.dataset.print!==undefined)window.print();if(b.id==='reloadBtn')await loadCatalog();if(b.id==='clearFilters'){filters={};renderLibrary()}
 if(b.id==='backupBtn')download('sinad-backup.json',JSON.stringify({version:1,state},null,2));if(b.id==='csvBtn'){const q=x=>'"'+String(x??'').replaceAll('"','""')+'"';download('sinad-events.csv','\uFEFF'+[['النشاط','الصف','التاريخ','الهدف','الحالة'],...state.events.map(e=>[e.title,e.grade,e.date,e.goal,e.status])].map(r=>r.map(v=>q(/^[=+@-]/.test(String(v))?'\''+v:v)).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 if(b.id==='askBtn'){$('#answer').textContent=draft()}if(b.id==='promptBtn')download('sinad-prompt.txt',prompt(),'text/plain;charset=utf-8');if(b.id==='speakBtn'){if(!('speechSynthesis'in window))return toast('القراءة الصوتية غير مدعومة.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('#answer').textContent);u.lang='ar-KW';speechSynthesis.speak(u)}
 if(b.id==='micBtn'){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return toast('الإملاء غير مدعوم في هذا المتصفح. استخدم لوحة المفاتيح الصوتية.');const r=new R();r.lang='ar-KW';r.onresult=e=>{$('#question').value=e.results[0][0].transcript;b.textContent='إملاء صوتي'};r.onerror=()=>{toast('تعذر التقاط الصوت؛ راجع إذن الميكروفون.');b.textContent='إملاء صوتي'};r.onend=()=>b.textContent='إملاء صوتي';r.start();b.textContent='جارٍ الاستماع…'}
 if(b.id==='posterBtn')await poster();if(b.id==='videoBtn')download('sinad-video-job.json',JSON.stringify({pipeline:'openshorts',status:'requires_external_executor',aspectRatio:'9:16',language:'ar-KW',school:$('#posterSchool').value,title:$('#posterTitle').value,brief:$('#posterText').value,scenes:['عنوان النشاط','هدف النشاط','مشاركة الطلبة دون كشف هويتهم','الموعد والدعوة'],source:selected?sourceBook(selected)?.source:null,consentRequired:true},null,2));if(b.dataset.costDelete){state.costs=state.costs.filter(c=>c.id!==b.dataset.costDelete);save();render()}
 }catch(e){toast(e.message||'تعذر إتمام العملية.')}});
document.addEventListener('change',async e=>{if(e.target.dataset.filter){filters[e.target.dataset.filter]=e.target.value;renderLibrary()}if(e.target.id==='restore'){try{const x=JSON.parse(await e.target.files[0].text());if(x.version!==1||!Array.isArray(x.state?.events)||!Array.isArray(x.state?.costs)||!Number.isFinite(Number(x.state?.budget)))throw Error();if(confirm('استبدال سجلات هذا الجهاز بالنسخة الاحتياطية؟')){state={...defaults,...x.state};save();render();toast('تمت استعادة السجلات. المرفقات الأصلية تحتاج استعادة منفصلة.')}}catch{toast('ملف النسخة الاحتياطية غير صالح.')}}});
document.addEventListener('submit',async ev=>{ev.preventDefault();const f=ev.target,values=Object.fromEntries(new FormData(f));try{if(f.id==='eventForm'){const old=state.events.find(x=>x.id===values.id);const files=await putFiles([...f.elements.files.files]);const item={...values,evidence:[...(old?.evidence||[]),...files]};delete item.files;state.events=state.events.filter(x=>x.id!==item.id);state.events.push(item);save();$('#editor').close();render();toast('حُفظت الفعالية في هذا الجهاز.')}
 if(['planForm','settingsForm'].includes(f.id)){Object.assign(state,values);save();render();toast('تم الحفظ.')}if(f.id==='costForm'){const amount=Number(values.costAmount);if(!(amount>0&&Number.isFinite(amount)))throw Error('أدخل مبلغًا صحيحًا.');state.costs.push({id:crypto.randomUUID(),title:values.costTitle,amount});save();render()}}catch(e){toast(e.message)}});
show('dashboard');loadCatalog();
