'use strict';
const workflowNames={welcome:'منهج للنشاط المدرسي',programs:'البرامج والقيم',classes:'الصفوف والمعلمون',weekly:'الجدول الأسبوعي',execution:'بطاقات التنفيذ',assignments:'تكليفات المعلمين',meetings:'محاضر الاجتماعات',store:'مكتبة النماذج',profile:'بيانات المدرسة',cloud:'الحساب والمشاركة',document:'معاينة المستند'};
Object.assign(names,workflowNames);
function migrate(){for(const k of ['classes','teachers','meetings'])if(!Array.isArray(state[k]))state[k]=[];state.principal??='';state.coordinator??='';state.schoolType??='حكومية';state.gender??='بنين';state.targetPct??='';}
migrate();
const programBank=[
 {id:'reading',title:'نادي القراءة والتعبير',domain:'ثقافي',value:'حب المعرفة',grades:'الأول–الثاني عشر',goal:'أن يعرض الطالب فكرة رئيسية من نص قرأه ويشرحها بأسلوبه.',steps:'اختيار نص مناسب للعمر\nقراءة فردية ومناقشة جماعية\nعرض الفكرة وتبادل الأسئلة',tools:'نصوص من المنهج وبطاقات قراءة',assess:'وضوح الفكرة ودقة التعبير ومشاركة الطالب',subject:'اللغة العربية'},
 {id:'science',title:'مختبر العلوم الصغير',domain:'علمي',value:'التفكير العلمي',grades:'الرابع–الثاني عشر',goal:'أن يسجل الطالب ملاحظاته ويقارن النتيجة بالتوقع.',steps:'اختيار تجربة آمنة من الدرس\nصياغة توقع\nتنفيذ بإشراف المعلم وتسجيل النتائج',tools:'أدوات التجربة وفق تعليمات السلامة',assess:'دقة الملاحظات وتفسير النتيجة',subject:'العلوم'},
 {id:'math',title:'الرياضيات في حياتنا',domain:'علمي',value:'حل المشكلات',grades:'الأول–الثاني عشر',goal:'أن يستخدم الطالب مفهومًا رياضيًا لحل مسألة من الحياة اليومية.',steps:'اختيار المسألة والمفهوم من الدرس\nعمل مجموعات\nمقارنة الحلول وتفسيرها',tools:'ورق قياس وجداول بيانات مناسبة',assess:'صحة الحل وقدرة الطالب على تفسيره',subject:'الرياضيات'},
 {id:'volunteer',title:'مدرستي تتطوع',domain:'اجتماعي',value:'المسؤولية',grades:'السادس–الثاني عشر',goal:'أن يخطط الطالب لمهمة تطوعية مدرسية ويحدد أثرها.',steps:'تحديد احتياج داخل المدرسة\nتوزيع الأدوار واعتماد الإدارة\nالتنفيذ وتقييم الأثر',tools:'نموذج أدوار وقائمة متابعة',assess:'التعاون والالتزام وتحقق الأثر',subject:'التطوع'},
 {id:'green',title:'مدرسة صديقة للبيئة',domain:'بيئي',value:'المحافظة على البيئة',grades:'الأول–الثاني عشر',goal:'أن يقترح الطالب ممارسة قابلة للتنفيذ لتقليل الهدر.',steps:'ملاحظة مصدر هدر\nجمع معلومات مبسطة\nتنفيذ مبادرة وقياس التحسن',tools:'لوحة متابعة ومواد آمنة لإعادة الاستخدام',assess:'قابلية التطبيق ومقارنة قبل وبعد',subject:'العلوم'},
 {id:'digital',title:'المواطن الرقمي الواعي',domain:'تقني',value:'الأمان الرقمي',grades:'الرابع–الثاني عشر',goal:'أن يميّز الطالب بين سلوك رقمي آمن وسلوك يحتاج تجنبًا.',steps:'عرض حالات تعليمية دون بيانات حقيقية\nمناقشة حماية الخصوصية\nإعداد رسالة توعوية',tools:'بطاقات مواقف تعليمية',assess:'اختيار السلوك الآمن وتفسيره',subject:'الذكاء الرقمي'},
 {id:'kuwait',title:'الكويت في عيون طلبتها',domain:'وطني',value:'الانتماء',grades:'الأول–الثاني عشر',goal:'أن يقدم الطالب معلومة موثقة عن تراث الكويت أو تاريخها.',steps:'تحديد موضوع من المنهج\nمراجعة المصدر مع المعلم\nإعداد معرض أو عرض قصير',tools:'الكتاب ومراجع يراجعها المعلم',assess:'دقة المعلومة وتوثيق المصدر',subject:'دولة الكويت'},
 {id:'sport',title:'الحركة والصحة',domain:'رياضي',value:'التعاون',grades:'الأول–الثاني عشر',goal:'أن يشارك الطالب في نشاط حركي يناسب قدراته مع احترام قواعد السلامة.',steps:'تحديد نشاط مع معلم التربية البدنية\nشرح القواعد\nتنفيذ وتقييم المشاركة',tools:'أدوات يحددها معلم التربية البدنية',assess:'الالتزام بالقواعد والتعاون',subject:'التربية البدنية'},
 {id:'art',title:'الفن من بيئتنا',domain:'فني',value:'الإبداع',grades:'الأول–الثاني عشر',goal:'أن ينتج الطالب عملًا فنيًا يعبر عن عنصر من البيئة الكويتية.',steps:'ملاحظة عنصر بصري\nتجربة خامات آمنة\nعرض العمل وشرح اختياراته',tools:'أدوات رسم وخامات آمنة',assess:'التعبير عن الفكرة والمحافظة على الأدوات',subject:'التربية الفنية'},
 {id:'english',title:'English in Action',domain:'لغوي',value:'الثقة بالنفس',grades:'الأول–الثاني عشر',goal:'أن يستخدم الطالب مفردات الدرس في حوار قصير مناسب للمستوى.',steps:'اختيار مفردات من الدرس\nتدريب في مجموعات ثنائية\nعرض الحوار وتغذية راجعة',tools:'الكتاب وبطاقات مفردات',assess:'استخدام المفردات ووضوح التواصل',subject:'English'},
 {id:'values',title:'قيم نعيشها',domain:'قيمي',value:'الاحترام',grades:'الأول–الثاني عشر',goal:'أن يربط الطالب قيمة تربوية بموقف عملي داخل المدرسة.',steps:'اختيار موقف تعليمي\nمناقشة البدائل\nتمثيل السلوك المناسب',tools:'بطاقات مواقف',assess:'اختيار التصرف وتوضيح أثره',subject:'التربية الإسلامية'},
 {id:'media',title:'إذاعة مدرسية هادفة',domain:'إعلامي',value:'المبادرة',grades:'الرابع–الثاني عشر',goal:'أن يعد الطالب فقرة قصيرة موثقة ويقدمها بوضوح.',steps:'توزيع الأدوار\nمراجعة النص والمصدر\nتدريب وتقديم وتقييم',tools:'نص الفقرة وأجهزة المدرسة',assess:'الدقة والتوقيت والتعاون',subject:'اللغة العربية'}
];
let programFilter='', weekOffset=0, docMarkup='';
const oldRender=render;
render=function(){migrate();if(!workflowNames[view]){oldRender();if(view==='dashboard'){const d=state.events.filter(e=>['منفذة','معتمد'].includes(e.status)).length;$('#dashboardView').insertAdjacentHTML('afterbegin',`<div class="workflow-ribbon"><strong>مركز النشاط المدرسي</strong><span>${d} منفّذ من ${state.events.length} • الإنجاز ${state.events.length?Math.round(d/state.events.length*100):0}%</span><button class="btn secondary" data-goto="weekly">أسبوعي</button><button class="btn secondary" data-goto="execution">بطاقات التنفيذ</button><button class="btn secondary" data-goto="assignments">التكليفات</button></div>`)}if(view==='reports'){$('#reportsView .actions').insertAdjacentHTML('beforeend','<button class="btn secondary" id="registerCsv">سجل النشاط Excel / CSV</button>')}return}const el=$('#'+view+'View');
 if(view==='welcome')el.innerHTML=`<div class="manhaj-hero"><div><span class="eyebrow">للمدارس الكويتية • منهج</span><h2>خطّط بثقة.<br>نفّذ بوضوح.<br><em>وثّق أثر مدرستك.</em></h2><p>مساحة عمل لمسؤول ومسؤولة النشاط: خطة مرتبطة بالمناهج، تكليفات واضحة، بطاقات تنفيذ، شواهد وتقرير ختامي منظم.</p><div class="actions"><button class="btn" data-goto="dashboard">ابدأ العمل</button><button class="btn secondary" data-goto="store">تصفح النماذج</button></div><div class="hero-pills"><span>المناهج الكويتية</span><span>المناطق التعليمية الست</span><span>المطبوعات العربية</span></div></div><div class="journey-board"><span class="badge">رحلة النشاط</span><article><b>01</b><div><h3>الخطة</h3><p>هدف ومصدر وصف ومعلم وموعد</p></div></article><article><b>02</b><div><h3>التنفيذ</h3><p>تكليف وبطاقة وشاهد وتقييم</p></div></article><article><b>03</b><div><h3>الإنجاز</h3><p>متابعة ومحاضر وتقرير ختامي</p></div></article></div></div><div class="cards">${[['الخطط المرنة','برنامج لكل هدف، وربط مباشر بكتاب رسمي.','programs'],['ملف المعلم','التكليفات والبطاقات والشواهد في سير عمل واحد.','assignments'],['النماذج المدرسية','قوالب أصلية قابلة للتعبئة والطباعة بالعربية.','store'],['التقرير الختامي','مؤشرات من سجلاتك الفعلية ومراجع وشواهد.','reports']].map(([n,d,k])=>`<article class="panel book"><h3>${n}</h3><p>${d}</p><button class="btn secondary" data-goto="${k}">استعرض</button></article>`).join('')}</div><div class="notice">ابدأ بإكمال بيانات مدرستك، ثم أضف الصفوف والمعلمين واختر برنامجًا مناسبًا من البنك. مواد البنك مقترحات تربوية يراجعها المعلم.</div>`;
 if(view==='profile')el.innerHTML=panel('بيانات المدرسة الكويتية',`<form id="profileForm"><div class="form-grid">${field('اسم المدرسة','school',state.school,'text','required')}${field('العام الدراسي','year',state.year,'text','required pattern="[0-9]{4}/[0-9]{4}"')}<div class="field"><label for="region">المنطقة التعليمية</label><select name="region" id="region" required>${options(['العاصمة','حولي','الفروانية','الجهراء','الأحمدي','مبارك الكبير'],state.region,'اختر المنطقة')}</select></div><div class="field"><label for="stage">المرحلة</label><select name="stage" id="stage" required>${options(['رياض الأطفال','الإبتدائية','المتوسط','الثانوية'],state.stage,'اختر المرحلة')}</select></div><div class="field"><label for="schoolType">نوع المدرسة</label><select name="schoolType" id="schoolType">${options(['حكومية','خاصة','تعليم ديني','تربية خاصة'],state.schoolType,'اختر النوع')}</select></div><div class="field"><label for="gender">الفئة</label><select name="gender" id="gender">${options(['بنين','بنات','مختلط'],state.gender,'اختر الفئة')}</select></div>${field('مدير / مديرة المدرسة','principal',state.principal)}${field('مسؤول / مسؤولة النشاط','coordinator',state.coordinator)}${field('نسبة التنفيذ المستهدفة (اختيارية)','targetPct',state.targetPct,'number','min="0" max="100" step="1"')}<div class="field"><label for="goal">الهدف السنوي</label><textarea name="goal" id="goal">${esc(state.goal)}</textarea></div></div><div class="actions"><button class="btn">حفظ بيانات المدرسة</button><button type="button" class="btn secondary" data-goto="classes">الصفوف والمعلمون</button></div></form><p class="muted">المستهدف يُدخل من خطة المدرسة؛ نسب النشاط وتواريخ الدراسة تحتاج مرجعًا أو تعميمًا معتمدًا.</p>`);
 if(view==='programs')el.innerHTML=panel('بنك البرامج والقيم',`<p class="muted">قوالب أصلية مقترحة للمدارس الكويتية، وتُكيّف بحسب العمر والدرس وموافقة الإدارة.</p><div class="actions"><select aria-label="تصفية المجال" id="programFilter">${options(programBank.map(p=>p.domain),programFilter,'جميع المجالات')}</select><button class="btn secondary" data-goto="library">الكتب الرسمية</button></div><div class="cards">${programBank.filter(p=>!programFilter||p.domain===programFilter).map(p=>`<article class="panel book"><span class="badge">${esc(p.domain)} • ${esc(p.value)}</span><h3>${esc(p.title)}</h3><small>${esc(p.grades)}</small><p>${esc(p.goal)}</p><div class="actions"><button class="btn" data-program="${p.id}">أضف إلى الخطة</button><button class="btn secondary" data-program-doc="${p.id}">حقيبة البرنامج</button></div></article>`).join('')}</div>`);
 if(view==='classes')el.innerHTML=`<div class="split">${panel('المعلمون',`<form id="teacherForm"><div class="form-grid">${field('اسم المعلم','teacherName','','text','required maxlength="120"')}${field('المادة أو القسم','teacherSubject','','text','required')}</div><div class="actions"><button class="btn">إضافة معلم</button></div></form><div class="list">${state.teachers.map(t=>`<div class="task"><div><strong>${esc(t.name)}</strong><small>${esc(t.subject)}</small></div><button class="btn secondary" data-remove-teacher="${esc(t.id)}">حذف</button></div>`).join('')||empty('أضف المعلمين المكلفين بالنشاط.')}</div>`)}${panel('الصفوف والشعب',`<p class="muted">الابتدائية 1–5، المتوسطة 6–9، الثانوية 10–12. يُدخل التوقيت حسب جدول المدرسة.</p><form id="classForm"><div class="form-grid"><div class="field"><label for="classGrade">الصف</label><select id="classGrade" name="grade" required>${options(['الأول','الثاني','الثالث','الرابع','الخامس','السادس','السابع','الثامن','التاسع','العاشر','الحادي عشر','الثاني عشر'],'','حدد الصف')}</select></div>${field('الشعبة','section','','text','required')}${field('عدد الطلبة','count','','number','required min="1" max="100" step="1"')}<div class="field"><label for="teacherId">المعلم المسؤول</label><select name="teacherId" id="teacherId"><option value="">غير محدد</option>${state.teachers.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></div></div><div class="actions"><button class="btn">إضافة صف</button></div></form><div class="list">${state.classes.map(c=>`<div class="task"><div><strong>${esc(c.grade)} / ${esc(c.section)}</strong><small>${Number(c.count)||0} طالبًا • ${esc(state.teachers.find(t=>t.id===c.teacherId)?.name||'لم يحدد المعلم')}</small></div><button class="btn secondary" data-remove-class="${esc(c.id)}">حذف</button></div>`).join('')||empty('لا توجد صفوف بعد.')}</div>`)}</div>`;
 if(view==='weekly'){const start=weekStart(weekOffset);el.innerHTML=panel('أسبوعي — التخطيط والتنفيذ',`<div class="actions"><button class="btn secondary" data-week="-1">الأسبوع السابق</button><strong>${formatDate(start)}</strong><button class="btn secondary" data-week="1">الأسبوع التالي</button><button class="btn secondary" data-week="0">هذا الأسبوع</button><button class="btn" id="weeklyPrint">طباعة الأسبوع</button></div><div class="week-grid">${Array.from({length:5},(_,i)=>{const d=new Date(start);d.setUTCDate(d.getUTCDate()+i);const iso=d.toISOString().slice(0,10),events=state.events.filter(e=>e.date===iso);return `<article class="day-column"><h3>${['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس'][i]}</h3><small>${iso}</small>${events.map(e=>`<button class="week-event" data-edit="${esc(e.id)}"><strong>${esc(e.title)}</strong><small>${esc(e.owner)} • ${esc(e.grade)}</small><span>${esc(e.status)}</span></button>`).join('')||'<p class="muted">لم يُجدول نشاط</p>'}<button class="btn secondary" data-add-date="${iso}">إضافة</button></article>`}).join('')}</div><div class="notice">التخطيط الأسبوعي وفق أيام الأحد إلى الخميس. تواريخ العطل والفترات الدراسية تضبطها المدرسة حسب التعميم.</div>`)}
 if(view==='execution')el.innerHTML=panel('بطاقات تنفيذ البرامج',`<div class="actions"><button class="btn" id="addBtn">بطاقة جديدة</button><button class="btn secondary" data-goto="evidence">مراجعة الشواهد</button></div><div class="cards">${state.events.map(e=>`<article class="panel book"><span class="badge">${esc(e.status)} • ${esc(e.domain||'نشاط مدرسي')}</span><h3>${esc(e.title)}</h3><p>${esc(e.owner)} • ${esc(e.date)} • ${esc(e.grade)}</p><small>${e.evidence?.length||0} شاهد • ${Number(e.participants)||0} مشارك</small><div class="actions"><button class="btn" data-card-fill="${esc(e.id)}">إكمال البطاقة</button><button class="btn secondary" data-card-doc="${esc(e.id)}">طباعة</button><button class="btn secondary" data-share-card="${esc(e.id)}">رابط للمعلم</button></div></article>`).join('')||empty('أضف برنامجًا إلى الخطة لإصدار بطاقة.')}</div>`);
 if(view==='assignments'){const teachers=[...new Set(state.events.map(e=>e.owner).filter(Boolean))];el.innerHTML=panel('تكليفات المعلمين',`<p>خطاب مستقل لكل معلم من البرامج المسندة إليه، مع مساحة للتوقيع وتاريخ الاستلام.</p><div class="cards">${teachers.map((name,i)=>`<article class="panel book"><h3>${esc(name)}</h3><p>${state.events.filter(e=>e.owner===name).length} برنامج مسند</p><button class="btn" data-assignment="${i}">معاينة وطباعة التكليف</button></article>`).join('')||empty('حدد اسم المسؤول في البرنامج لتكوين التكليف.')}</div>`)}
 if(view==='meetings')el.innerHTML=panel('محاضر لجنة النشاط',`<div class="actions"><button class="btn" id="meetingBtn">محضر جديد</button></div><div class="list">${state.meetings.map(m=>`<div class="task"><div><strong>${esc(m.title)}</strong><small>${esc(m.date)} • ${esc(m.attendees)}</small></div><div class="actions"><button class="btn secondary" data-meeting-doc="${esc(m.id)}">معاينة وطباعة</button><button class="btn secondary" data-remove-meeting="${esc(m.id)}">حذف</button></div></div>`).join('')||empty('سجّل الاجتماع والقرارات والمسؤولين عن المتابعة.')}</div>`);
 if(view==='store')el.innerHTML=panel('مكتبة النماذج المدرسية',`<p>نماذج أصلية قابلة للتعبئة والطباعة، تشمل احتياجات مسؤول النشاط والمعلم. متاحة للاستخدام في هذه المرحلة.</p><div class="cards">${[['annual','الخطة السنوية','جدول البرامج والأهداف والصفوف والتوقيت والمسؤولين.'],['card','بطاقة تنفيذ','الهدف والخطوات والمشاركون والتقييم والشواهد.'],['assignment','خطاب تكليف','خطاب من بيانات المدرسة وحقول للبرامج والمعلم.'],['meeting','محضر اجتماع','الحضور والموضوعات والقرارات والمتابعة.'],['attendance','كشف حضور','قائمة قابلة للتعبئة بالرموز أو الأسماء لدى المدرسة.'],['certificate','شهادة مشاركة','شهادة مدرسية باسم المشارك والبرنامج.'],['evaluation','استمارة تقييم','تقييم التعلم والتعاون والالتزام والتوصيات.'],['final','التقرير الختامي','ملخص التنفيذ وبرامج المدرسة والتوصيات.']].map(([id,title,desc])=>`<article class="panel book template-card"><span class="template-icon">${title.slice(0,1)}</span><h3>${title}</h3><p>${desc}</p><div class="actions"><button class="btn" data-template="${id}">تعبئة ومعاينة</button><button class="btn secondary" data-template-file="${id}">تنزيل النموذج</button></div></article>`).join('')}</div>`);
 if(view==='cloud')renderCloud(el);
 if(view==='document')el.innerHTML=`<div class="actions no-print"><button class="btn" id="docPrint">طباعة / حفظ PDF</button><button class="btn secondary" id="docDownload">تنزيل HTML</button><button class="btn secondary" data-goto="store">النماذج</button></div><div class="paper report">${docMarkup}</div>`;
};
function weekStart(offset=0){const now=new Date();const d=new Date(Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()));d.setUTCDate(d.getUTCDate()-d.getUTCDay()+offset*7);return d}
function formatDate(d){return new Date(d).toLocaleDateString('ar-KW',{timeZone:'Asia/Kuwait'})}
function docHeader(title){return `<div class="doc-head"><b>منهج</b><span>النشاط المدرسي • ${esc(state.year)}</span></div><h1>${esc(title)}</h1><p>${esc(state.school)} • منطقة ${esc(state.region)} التعليمية • ${esc(state.stage)}</p>`}
function docFooter(){return `<div class="signatures"><p>مسؤول النشاط: ${esc(state.coordinator)}<br>التوقيع: ....................</p><p>مدير المدرسة: ${esc(state.principal)}<br>التوقيع: ....................</p></div><small>نموذج من إعداد منصة منهج؛ يراجع ويعتمد داخل المدرسة.</small>`}
function previewDoc(title,content){docMarkup=docHeader(title)+content+docFooter();show('document')}
function programDocument(p){return `<h2>${esc(p.title)}</h2><p>المجال: ${esc(p.domain)} • القيمة: ${esc(p.value)}</p><p>المراحل المقترحة: ${esc(p.grades)}</p><h3>الهدف</h3><p>${esc(p.goal)}</p><h3>خطوات التنفيذ</h3><ol>${p.steps.split('\n').map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p>الأدوات: ${esc(p.tools)}</p><p>التقويم: ${esc(p.assess)}</p><p>الدرس والصفحة والكتاب: .........................................</p><p>مقترح تربوي؛ اختر مصدرًا رسميًا وراجعه قبل التنفيذ.</p>`}
function cardDocument(e){const b=sourceBook(e.bookId);return `<h2>${esc(e.title)}</h2><table><tbody>${[['المعلم',e.owner],['الصف',e.grade],['التاريخ',e.date],['الهدف',e.goal],['الدرس والصفحة',e.lesson],['المرجع',b?.title||'لم يحدد'],['عدد المشاركين',e.participants||0],['خطوات التنفيذ',e.notes],['التقويم',e.evaluation||''],['الحالة',e.status]].map(([k,v])=>`<tr><th>${k}</th><td>${esc(v)}</td></tr>`).join('')}</tbody></table>${b?`<p>رابط المصدر: <a href="${esc(b.source)}">${esc(b.source)}</a></p>`:''}<h3>الشواهد</h3>${e.evidence?.map(f=>`<p>${esc(f.name)}</p>`).join('')||'<p>تضاف الشواهد قبل الاعتماد.</p>'}`}
function templateBody(id){const blanks='<p>اسم البرنامج: .....................................</p><p>المعلم المسؤول: .....................................</p><p>الصف والتاريخ: .....................................</p>';
 const bodies={annual:`<p>الهدف السنوي: ${esc(state.goal)}</p><table><thead><tr><th>البرنامج</th><th>الهدف</th><th>الصف</th><th>المعلم</th><th>التاريخ</th></tr></thead><tbody>${state.events.length?state.events.map(e=>`<tr><td>${esc(e.title)}</td><td>${esc(e.goal)}</td><td>${esc(e.grade)}</td><td>${esc(e.owner)}</td><td>${esc(e.date)}</td></tr>`).join(''):'<tr><td>........</td><td>........</td><td>........</td><td>........</td><td>........</td></tr>'}</tbody></table>`,card:blanks+'<p>الهدف: .....................................</p><p>خطوات التنفيذ: .....................................</p><p>التقويم والأثر: .....................................</p><p>الشواهد: .....................................</p>',assignment:blanks+'<p>يرجى تنفيذ البرامج المسندة وفق الخطة، وتوثيق التنفيذ وإكمال بطاقة البرنامج، ورفع ملاحظات التحسين إلى مسؤول النشاط.</p>',meeting:'<p>التاريخ: .................... • مكان الاجتماع: ....................</p><p>الحضور: .....................................</p><h3>جدول الأعمال</h3><p>................................................................</p><h3>القرارات ومسؤول المتابعة</h3><p>................................................................</p>',attendance:blanks+`<table><tr><th>م</th><th>الاسم أو الرمز</th><th>الحضور</th><th>المشاركة</th></tr>${Array.from({length:20},(_,i)=>`<tr><td>${i+1}</td><td>........................</td><td>........</td><td>........</td></tr>`).join('')}</table>`,certificate:'<h2 style="text-align:center">شهادة مشاركة</h2><p style="font-size:24px;text-align:center">تتقدم إدارة المدرسة بالشكر إلى</p><h2 style="text-align:center">.....................................</h2><p style="text-align:center">لمشاركته / مشاركتها في برنامج .....................................</p><p style="text-align:center">بتاريخ .................... متمنين له / لها دوام التقدم.</p>',evaluation:blanks+'<table><tr><th>المعيار</th><th>يحتاج دعمًا</th><th>حقق المطلوب</th><th>متقدم</th></tr>'+['فهم الهدف','تطبيق المعرفة','التعاون','الالتزام والسلامة'].map(s=>`<tr><td>${s}</td><td>□</td><td>□</td><td>□</td></tr>`).join('')+'</table><p>التوصيات: .....................................</p>',final:`<p>البرامج بالخطة: ${state.events.length}</p><p>المنفّذ: ${state.events.filter(e=>['منفذة','معتمد'].includes(e.status)).length}</p><p>المعلمون المشاركون: ${new Set(state.events.map(e=>e.owner).filter(Boolean)).size}</p><h3>أبرز الإنجازات</h3><p>................................................................</p><h3>التحديات والتحسينات</h3><p>................................................................</p>`};return bodies[id]||''}
const templateTitles={annual:'الخطة السنوية',card:'بطاقة تنفيذ برنامج',assignment:'خطاب تكليف',meeting:'محضر اجتماع',attendance:'كشف حضور',certificate:'شهادة مشاركة',evaluation:'استمارة تقييم',final:'التقرير الختامي'};
function fullDoc(content){return `<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="UTF-8"><title>منهج — مستند النشاط</title><style>body{font:18px Tahoma,Arial;line-height:2;color:#122e42;max-width:900px;margin:30px auto;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #c9d8dd;padding:10px;text-align:right}h1{color:#007c83}.doc-head,.signatures{display:flex;justify-content:space-between;gap:30px}.signatures{margin-top:70px}@media print{body{margin:0;padding:0}tr{break-inside:avoid}}</style></head><body contenteditable="true">${content}</body></html>`}
const localGetFile=getFile;getFile=async function(id){const meta=state.events.flatMap(e=>e.evidence||[]).find(f=>f.id===id);if(meta?.cloud){const f=await cloudFetch('/api/files/'+encodeURIComponent(id));const bytes=Uint8Array.from(atob(f.data),c=>c.charCodeAt(0));download(f.name,bytes,f.type)}else await localGetFile(id)};
const baseEditor=editor;editor=function(id,book){baseEditor(id,book);const e=state.events.find(e=>e.id===id)||{};$('#eventForm .form-grid').insertAdjacentHTML('beforeend',`<div class="field"><label for="domain">المجال</label><select name="domain" id="domain">${options(programBank.map(p=>p.domain),e.domain,'اختر المجال')}</select></div><div class="field"><label for="classId">الصف والشعبة</label><select name="classId" id="classId"><option value="">غير محدد</option>${state.classes.map(c=>`<option value="${esc(c.id)}" ${c.id===e.classId?'selected':''}>${esc(c.grade)} / ${esc(c.section)}</option>`).join('')}</select></div><div class="field"><label for="term">الفصل الدراسي</label><select name="term" id="term"><option value="1" ${e.term!=='2'?'selected':''}>الأول</option><option value="2" ${e.term==='2'?'selected':''}>الثاني</option></select></div>${field('عدد الحصص المخطط','sessions',e.sessions||1,'number','min="1" max="100" step="1"')}${field('عدد المشاركين','participants',e.participants||0,'number','min="0" max="5000" step="1"')}<div class="field"><label for="evaluation">نتيجة التقييم والأثر</label><textarea name="evaluation" id="evaluation">${esc(e.evaluation||'')}</textarea></div>`)};
function meetingEditor(){ $('#editor').innerHTML=`<form id="meetingForm"><h2>محضر اجتماع لجنة النشاط</h2><div class="form-grid">${field('عنوان الاجتماع','title','','text','required')}${field('التاريخ','date','','date','required')}${field('مكان الاجتماع','location','','text','required')}${field('الحضور','attendees','','text','required')}<div class="field"><label for="agenda">جدول الأعمال</label><textarea name="agenda" id="agenda" required></textarea></div><div class="field"><label for="decisions">القرارات والمسؤولون والموعد</label><textarea name="decisions" id="decisions" required></textarea></div></div><div class="actions"><button class="btn">حفظ المحضر</button><button type="button" class="btn secondary" id="closeEditor">إغلاق</button></div></form>`;$('#editor').showModal()}
const cloudConfig=()=>{try{return JSON.parse(localStorage.getItem('manhaj-cloud-config')||'{}')}catch{return {}}};
let cloudSession;try{cloudSession=JSON.parse(sessionStorage.getItem('manhaj-session')||'null')}catch{cloudSession=null}
async function cloudFetch(path,opts={}){const base=cloudConfig().api;if(!base)throw Error('إعداد الخدمة السحابية لم يكتمل.');const r=await fetch(base+path,{...opts,headers:{'Content-Type':'application/json',...(cloudSession&&!path.startsWith('/api/cards/')?{Authorization:'Bearer '+cloudSession.token}:{}),...opts.headers}});const data=await r.json();if(!r.ok)throw Error(data.error||'تعذر الاتصال');return data}
function renderCloud(el){el.innerHTML=panel('حساب المدرسة والمشاركة مع المعلمين',`<p>يمكن متابعة العمل على هذا الجهاز، أو ربط حساب المدرسة بالخدمة السحابية بعد إعدادها.</p>${cloudSession?`<div class="notice">حساب المدرسة: ${esc(cloudSession.email)} • آخر إصدار ${cloudSession.revision||0}</div><div class="actions"><button class="btn" id="cloudSave">حفظ السجلات سحابيًا</button><button class="btn secondary" id="cloudLoad">استعادة السجلات من الحساب</button><button class="btn secondary" id="cloudLogout">خروج</button></div>`:`<form id="cloudAuthForm"><div class="form-grid">${field('البريد الإلكتروني','email','','email','required autocomplete="username"')}${field('كلمة المرور','password','','password','required minlength="12" autocomplete="current-password"')}</div><div class="actions"><button class="btn" name="mode" value="login">دخول</button><button class="btn secondary" name="mode" value="register">إنشاء حساب مدرسة</button></div></form>`}<div class="notice">تسجيل الحسابات والمشاركة يعتمد على ربط الخدمة السحابية. البيانات المحلية لا تُرفع إلا عند اختيار الحفظ.</div><details><summary>إعداد الاتصال</summary><form id="cloudConfigForm">${field('رابط الخدمة HTTPS','api',cloudConfig().api||'','url','required')}<div class="actions"><button class="btn secondary">حفظ الاتصال</button></div></form></details>`)}
async function teacherCard(token){try{const data=await cloudFetch('/api/cards/'+encodeURIComponent(token));$('#editor').innerHTML=`<form id="teacherCardForm"><h2>بطاقة تنفيذ: ${esc(data.event.title)}</h2><p>${esc(data.event.grade)} • ${esc(data.event.goal)}</p><p>الدرس: ${esc(data.event.lesson||'لم يحدد')}</p>${data.event.source?`<a class="btn secondary" href="${esc(data.event.source)}" target="_blank" rel="noopener">فتح المرجع الرسمي</a>`:''}<input type="hidden" name="token" value="${esc(token)}"><div class="form-grid">${field('اسم المعلم المنفذ','owner',data.event.owner,'text','required')}${field('عدد المشاركين','participants',data.event.participants||0,'number','required min="0" max="5000"')}<div class="field"><label for="notes">وصف التنفيذ</label><textarea name="notes" id="notes" required></textarea></div><div class="field"><label for="evaluation">التقويم والتوصيات</label><textarea name="evaluation" id="evaluation" required></textarea></div><div class="field"><label for="files">شاهد PDF أو صورة (حتى 5MB)</label><input name="files" id="files" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf"></div></div><div class="actions"><button class="btn">إرسال بطاقة التنفيذ</button></div></form>`;$('#editor').showModal()}catch(e){toast(e.message)}}
document.addEventListener('change',e=>{if(e.target.id==='programFilter'){programFilter=e.target.value;render()}if(e.target.id==='classId'){const c=state.classes.find(c=>c.id===e.target.value);if(c){$('#eventForm [name="grade"]').value=c.grade+' / '+c.section;const t=state.teachers.find(t=>t.id===c.teacherId);if(t)$('#eventForm [name="owner"]').value=t.name}}});
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;try{
 if(b.dataset.program){const p=programBank.find(p=>p.id===b.dataset.program);editor();for(const [key,value]of Object.entries({title:p.title,goal:p.goal,notes:p.steps,domain:p.domain,evaluation:p.assess}))$('#eventForm [name="'+key+'"]').value=value;toast('اختر الصف والمعلم والكتاب والدرس قبل الاعتماد.')}
 if(b.dataset.programDoc){const p=programBank.find(p=>p.id===b.dataset.programDoc);previewDoc('حقيبة برنامج النشاط',programDocument(p))}
 if(b.dataset.week!==undefined){weekOffset=b.dataset.week==='0'?0:weekOffset+Number(b.dataset.week);render()}
 if(b.dataset.addDate){editor();$('#eventForm [name="date"]').value=b.dataset.addDate}
 if(b.id==='weeklyPrint'){const start=weekStart(weekOffset),end=new Date(start);end.setUTCDate(end.getUTCDate()+5);previewDoc('خطة الأسبوع — '+formatDate(start),state.events.filter(e=>e.date>=start.toISOString().slice(0,10)&&e.date<end.toISOString().slice(0,10)).map(e=>cardDocument(e)).join('<hr>')||'<p>لا توجد برامج مجدولة لهذا الأسبوع.</p>')}
 if(b.dataset.cardFill)editor(b.dataset.cardFill);if(b.dataset.cardDoc)previewDoc('بطاقة تنفيذ',cardDocument(state.events.find(e=>e.id===b.dataset.cardDoc)));
 if(b.dataset.assignment!==undefined){const teachers=[...new Set(state.events.map(e=>e.owner).filter(Boolean))],name=teachers[Number(b.dataset.assignment)];previewDoc('خطاب تكليف معلم',`<h2>الأستاذ / الأستاذة ${esc(name)}</h2><p>نكلّفكم بتنفيذ البرامج التالية وفق الخطة المعتمدة، وتوثيق التنفيذ واستكمال البطاقة والتقييم.</p><table><tr><th>البرنامج</th><th>الصف</th><th>الموعد</th></tr>${state.events.filter(e=>e.owner===name).map(e=>`<tr><td>${esc(e.title)}</td><td>${esc(e.grade)}</td><td>${esc(e.date)}</td></tr>`).join('')}</table><p>توقيع المعلم بالاستلام: .................... التاريخ: ....................</p>`)}
 if(b.id==='meetingBtn')meetingEditor();if(b.dataset.meetingDoc){const m=state.meetings.find(m=>m.id===b.dataset.meetingDoc);previewDoc(m.title,`<p>التاريخ: ${esc(m.date)} • المكان: ${esc(m.location)}</p><p>الحضور: ${esc(m.attendees)}</p><h3>جدول الأعمال</h3><p>${esc(m.agenda).replaceAll('\n','<br>')}</p><h3>القرارات والمتابعة</h3><p>${esc(m.decisions).replaceAll('\n','<br>')}</p>`)}
 for(const [key,attr]of [['teachers','removeTeacher'],['classes','removeClass'],['meetings','removeMeeting']])if(b.dataset[attr]&&confirm('حذف هذا السجل؟')){state[key]=state[key].filter(x=>x.id!==b.dataset[attr]);save();render()}
 if(b.dataset.template){previewDoc(templateTitles[b.dataset.template],templateBody(b.dataset.template));toast('راجع المستند قبل طباعته. النسخة المنزّلة قابلة للتعبئة.')}
 if(b.dataset.templateFile){const id=b.dataset.templateFile;download('manhaj-'+id+'.html',fullDoc(docHeader(templateTitles[id])+templateBody(id)+docFooter()),'text/html;charset=utf-8')}
 if(b.id==='docPrint')window.print();if(b.id==='docDownload')download('manhaj-document.html',fullDoc(docMarkup),'text/html;charset=utf-8');
 if(b.id==='registerCsv'){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['البرنامج','المجال','الهدف','الصف','المعلم','التاريخ','الفصل','الحصص','المشاركون','الحالة','التقويم','المرجع'],...state.events.map(e=>[e.title,e.domain,e.goal,e.grade,e.owner,e.date,e.term,e.sessions,e.participants,e.status,e.evaluation,sourceBook(e.bookId)?.source])];download('manhaj-register.csv','\uFEFF'+rows.map(r=>r.map(v=>q(/^[=+@-]/.test(String(v))?'\''+v:v)).join(',')).join('\r\n'),'text/csv;charset=utf-8')}
 if(b.id==='cloudSave'){const result=await cloudFetch('/api/state',{method:'PUT',body:JSON.stringify({state,revision:cloudSession.revision||0})});cloudSession.revision=result.revision;sessionStorage.setItem('manhaj-session',JSON.stringify(cloudSession));toast('تم حفظ سجلات المدرسة. المرفقات المحلية تبقى على الجهاز.');render()}
 if(b.id==='cloudLoad'){const result=await cloudFetch('/api/state');if(result.state&&confirm('استبدال سجلات هذا الجهاز ببيانات حساب المدرسة؟')){state={...defaults,...result.state};cloudSession.revision=result.revision;sessionStorage.setItem('manhaj-session',JSON.stringify(cloudSession));save();migrate();render()}}
 if(b.id==='cloudLogout'){await cloudFetch('/api/auth/logout',{method:'POST',body:'{}'});cloudSession=null;sessionStorage.removeItem('manhaj-session');render()}
 if(b.dataset.shareCard){if(!cloudSession)return toast('سجّل دخول حساب المدرسة واربط الخدمة أولًا.');const result=await cloudFetch('/api/cards',{method:'POST',body:JSON.stringify({eventId:b.dataset.shareCard})});const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('card',result.token);u.searchParams.set('api',cloudConfig().api);$('#editor').innerHTML=`<h2>رابط بطاقة المعلم</h2><p>ينتهي خلال 7 أيام. احفظ سجلات المدرسة سحابيًا قبل إصدار الروابط.</p><div class="field"><label for="cardLink">الرابط</label><input id="cardLink" readonly value="${esc(u.href)}"></div><div class="actions"><button class="btn secondary" id="closeEditor">إغلاق</button></div>`;$('#editor').showModal()}
 }catch(e){toast(e.message)}});
document.addEventListener('submit',async ev=>{const f=ev.target,values=Object.fromEntries(new FormData(f));try{
 if(f.id==='profileForm'){Object.assign(state,values);if(save()){toast('حُفظت بيانات المدرسة.');show('dashboard')}}
 if(f.id==='teacherForm'){state.teachers.push({id:crypto.randomUUID(),name:values.teacherName,subject:values.teacherSubject});save();render()}
 if(f.id==='classForm'){const count=Number(values.count);if(!Number.isInteger(count)||count<1||count>100)throw Error('عدد الطلبة غير صحيح');state.classes.push({id:crypto.randomUUID(),grade:values.grade,section:values.section,count,teacherId:values.teacherId});save();render()}
 if(f.id==='meetingForm'){state.meetings.push({...values,id:crypto.randomUUID()});save();$('#editor').close();render()}
 if(f.id==='cloudConfigForm'){const u=new URL(values.api);if(u.protocol!=='https:')throw Error('استخدم رابط HTTPS');localStorage.setItem('manhaj-cloud-config',JSON.stringify({api:u.origin}));toast('حُفظ عنوان الخدمة.');render()}
 if(f.id==='cloudAuthForm'){const mode=ev.submitter?.value||'login',result=await cloudFetch('/api/auth/'+mode,{method:'POST',body:JSON.stringify({email:values.email,password:values.password,school:state.school})});cloudSession={token:result.token,email:values.email,revision:result.revision};sessionStorage.setItem('manhaj-session',JSON.stringify(cloudSession));toast('تم الدخول إلى حساب المدرسة.');render()}
 if(f.id==='teacherCardForm'){const files=[...f.elements.files.files];if(files.length>3)throw Error('حتى 3 مرفقات');const attachments=[];for(const file of files){if(file.size>5*1024*1024)throw Error('المرفق أكبر من 5MB');const data=await new Promise((r,j)=>{const reader=new FileReader();reader.onload=()=>r(reader.result.split(',')[1]);reader.onerror=j;reader.readAsDataURL(file)});attachments.push({name:file.name,type:file.type,data})}await cloudFetch('/api/cards/'+encodeURIComponent(values.token),{method:'POST',body:JSON.stringify({owner:values.owner,participants:Number(values.participants),notes:values.notes,evaluation:values.evaluation,attachments})});$('#editor').close();toast('أرسلت البطاقة للمدرسة وتحتاج المراجعة قبل الاعتماد.')}
 }catch(e){toast(e.message)}});
const params=new URLSearchParams(location.search);if(params.get('card')){const api=params.get('api');if(api&&/^https:\/\/[a-z0-9-]+\.onrender\.com$/.test(api)){if(cloudConfig().api&&cloudConfig().api!==api){toast('الرابط يعود لخدمة مختلفة عن حساب المدرسة. افتحه في متصفح منفصل.')}else{localStorage.setItem('manhaj-cloud-config',JSON.stringify({api}));teacherCard(params.get('card'))}}}else show('welcome');
