import http from 'node:http';
import { URL } from 'node:url';
const PORT=process.env.PORT||10000,UA='KuwaitProfessionalDirectory/4.0';
const CATEGORIES={ministries:{label:'الوزارات',queries:['site:gov.kw الكويت مدير إدارة OR مديرة إدارة OR وكيل مساعد OR رئيس قسم','site:moh.gov.kw الكويت مدير OR مديرة OR رئيس قسم','site:moe.edu.kw الكويت مدير OR مديرة OR وكيل مساعد']},banks:{label:'البنوك',queries:['الكويت بنك رئيس تنفيذي OR نائب رئيس تنفيذي OR مدير عام OR مدير إدارة','site:cbk.gov.kw الكويت نائب المحافظ OR مجلس الإدارة','site:nbk.com الكويت الإدارة التنفيذية']},authorities:{label:'الهيئات',queries:['الكويت هيئة مدير عام OR نائب مدير OR مدير إدارة','site:cma.gov.kw الكويت مدير OR رئيس قطاع']},companies:{label:'الشركات',queries:['Kuwait CEO founder managing director executive company','الكويت رئيس تنفيذي مؤسس شريك مدير عام شركة']},universities:{label:'الجامعات',queries:['site:ku.edu.kw dean vice dean director leadership الكويت','site:ku.edu.kw عميد OR مدير OR رئيس قسم']},healthcare:{label:'القطاع الصحي',queries:['site:moh.gov.kw الكويت مستشفى مدير OR رئيس قسم','site:ku.edu.kw public health dean Kuwait']}};
const SEEDS=[{name:'سحر عبدالعزيز الرميح',role:'نائب محافظ بنك الكويت المركزي',organization:'بنك الكويت المركزي',category:'banks',url:'https://www.cbk.gov.kw/ar/about-cbk/board-of-directors/members'},{name:'أسيل سليمان المنيفي',role:'وكيل وزارة المالية وعضو مجلس إدارة بنك الكويت المركزي',organization:'وزارة المالية / بنك الكويت المركزي',category:'ministries',url:'https://www.cbk.gov.kw/ar/about-cbk/board-of-directors/members'},{name:'هناء عبدالرزاق رزوقي',role:'عضو مجلس إدارة - القطاع الخاص',organization:'بنك الكويت المركزي',category:'banks',url:'https://www.cbk.gov.kw/ar/about-cbk/board-of-directors/members'},{name:'فاطمة محمد البدر',role:'عضو مجلس إدارة - القطاع الخاص',organization:'بنك الكويت المركزي',category:'banks',url:'https://www.cbk.gov.kw/ar/about-cbk/board-of-directors/members'},{name:'شيخة خالد البحر',role:'نائب الرئيس التنفيذي لمجموعة بنك الكويت الوطني',organization:'بنك الكويت الوطني',category:'banks',url:'https://www.nbk.com/ar/nbk-group/about-nbk-group/who-we-are.html'},{name:'هدى محمد الرفاعي',role:'عضو مجلس إدارة غير تنفيذي',organization:'بنك الكويت الوطني',category:'banks',url:'https://www.nbk.com/kuwait/About.html'},{name:'نورة السويح',role:'قائم بأعمال نائب مدير الجامعة للعلوم الصحية',organization:'جامعة الكويت',category:'universities',url:'https://ku.edu.kw/university-leadership'},{name:'إلهام الدوسري',role:'قائم بأعمال نائب العميد للأبحاث والدراسات العليا',organization:'جامعة الكويت - كلية العلوم الطبية المساعدة',category:'universities',url:'https://ahs.ku.edu.kw/about/college-leadership'},{name:'أبرار الحسن',role:'قائم بأعمال مساعد العميد لشؤون الطلبة',organization:'جامعة الكويت - كلية العلوم الإدارية',category:'universities',url:'https://cba.ku.edu.kw/leadership'},{name:'فتحية الكندري',role:'المدير الإداري',organization:'جامعة الكويت - كلية العلوم الإدارية',category:'universities',url:'https://cba.ku.edu.kw/leadership'}];
const TENDER_SEEDS=[
{title:'تجديد تراخيص برمجيات VMware VCloud',agency:'وزارة المالية',type:'برمجيات وبنية سحابية',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'شراء أجهزة الحائط الناري Palo Alto و F5',agency:'وزارة المالية',type:'أمن سيبراني',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'مركز عمليات أمن المعلومات SOC - خدمات مدارة',agency:'وزارة المالية',type:'أمن سيبراني وخدمات مدارة',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'الكشف المدار عن التهديدات والاستجابة لها',agency:'وزارة المالية',type:'أمن سيبراني',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'إعادة هيكلة البنية التحتية للشبكة الرئيسية',agency:'وزارة المالية',type:'شبكات وبنية تحتية',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'نظام النسخ الاحتياطية للخوادم الرئيسية',agency:'وزارة المالية',type:'بنية تحتية ونسخ احتياطي',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'خدمات مدارة في مجال تقنية المعلومات',agency:'وزارة المالية',type:'خدمات تقنية معلومات',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'},
{title:'التحول الرقمي لوثائق وزارة المالية وإجراءاتها',agency:'وزارة المالية',type:'تحول رقمي وأرشفة إلكترونية',status:'خطة شراء رسمية',url:'https://www.mof.gov.kw/otherPDF/Plan_2025-2024.pdf'}
];
const DIGITAL_TERMS=['نظام','أنظمة','تطبيق','تطبيقات','موقع','بوابة','منصة','تحول رقمي','ذكاء اصطناعي','أتمتة','برمجيات','تقنية المعلومات','أمن سيبراني','SOC','شبكة','شبكات','خوادم','سحابة','cloud','software','digital','website','application','app','cyber','IT','SMS','social media','data center','مركز بيانات','أرشفة','إلكتروني'];
function cors(r){r.setHeader('Access-Control-Allow-Origin','*');r.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');r.setHeader('Cache-Control','no-store')}function json(r,s,d){cors(r);r.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});r.end(JSON.stringify(d))}function dec(s=''){return String(s).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'")}function strip(s=''){return dec(String(s)).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}
async function ft(u){let r=await fetch(u,{headers:{'User-Agent':UA},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error(String(r.status));return r.text()}
async function news(q){let xml=await ft('https://news.google.com/rss/search?q='+encodeURIComponent(q)+'&hl=ar&gl=KW&ceid=KW:ar');return[...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].slice(0,20).map(m=>{let s=m[1],g=t=>strip((s.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`))||[])[1]||'');return{title:g('title'),text:g('description'),url:g('link'),created:g('pubDate')||null}})}
function dynamicItem(x,id,label){let t=(x.title+' '+x.text).toLowerCase();let score=/مدير|مديرة|رئيس|رئيسة|وكيل|عميد|ceo|director|founder|executive|manager|dean/.test(t)?72:62;return{title:x.title,text:x.text,organization:'',category:id,categoryLabel:label,url:x.url,created:x.created,sourceType:'public-index',confidence:score,verified:false}}
function seedItem(s){return{title:s.name,text:s.role,organization:s.organization,category:s.category,categoryLabel:CATEGORIES[s.category]?.label||'',url:s.url,created:null,sourceType:'official',confidence:98,verified:true}}
async function scanCategory(id){let cat=CATEGORIES[id]||CATEGORIES.companies,seeds=SEEDS.filter(s=>s.category===id).map(seedItem),raw=[];let settled=await Promise.allSettled(cat.queries.map(news));for(const r of settled)if(r.status==='fulfilled')raw.push(...r.value);let dyn=raw.map(x=>dynamicItem(x,id,cat.label)).filter(x=>x.confidence>=68);let seen=new Set(),items=[];for(const x of [...seeds,...dyn]){let k=(x.title+'|'+x.organization+'|'+x.url).toLowerCase();if(seen.has(k))continue;seen.add(k);items.push(x)}return{category:id,label:cat.label,rawCount:raw.length,items}}
async function directory(category='all'){let ids=category==='all'?Object.keys(CATEGORIES):[category],results=await Promise.all(ids.map(scanCategory)),items=[],sources=[];for(const r of results){items.push(...r.items);sources.push({id:r.category,label:r.label,status:'connected',count:r.items.length,rawCount:r.rawCount})}let seen=new Set();items=items.filter(x=>{let k=(x.title+'|'+x.organization).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>b.confidence-a.confidence).slice(0,250);return{generatedAt:new Date().toISOString(),version:'4.0',mode:'verified-seed-plus-live-index',category,sources,count:items.length,officialCount:items.filter(x=>x.sourceType==='official').length,items}}
function isDigital(t=''){let x=t.toLowerCase();return DIGITAL_TERMS.some(k=>x.includes(k.toLowerCase()))}
async function tenders(q=''){const liveQueries=['site:capt.gov.kw الكويت مناقصة نظام OR تطبيق OR منصة OR برمجيات OR تقنية المعلومات OR أمن سيبراني','site:mof.gov.kw الكويت مناقصة نظام OR تطبيق OR تحول رقمي OR برمجيات OR تقنية المعلومات','site:e.gov.kw الكويت مناقصة نظام OR منصة OR تطبيق OR مشروع رقمي'];let settled=await Promise.allSettled(liveQueries.map(news)),raw=[];for(const r of settled)if(r.status==='fulfilled')raw.push(...r.value);let live=raw.filter(x=>isDigital(x.title+' '+x.text)).map(x=>({title:x.title,agency:'جهة حكومية - حسب المصدر',type:'فرصة رقمية',status:'نتيجة مباشرة',url:x.url,created:x.created,sourceType:'public-index'}));let seeds=TENDER_SEEDS.map(x=>({...x,created:null,sourceType:'official'}));let all=[...seeds,...live],seen=new Set();all=all.filter(x=>{let k=(x.title+'|'+x.url).toLowerCase();if(seen.has(k))return false;seen.add(k);return true});if(q){let s=q.toLowerCase();all=all.filter(x=>(x.title+' '+x.agency+' '+x.type+' '+x.status).toLowerCase().includes(s))}return{generatedAt:new Date().toISOString(),count:all.length,officialCount:all.filter(x=>x.sourceType==='official').length,items:all.slice(0,200),sources:[{id:'capt',label:'الجهاز المركزي للمناقصات العامة',status:'connected'},{id:'mof',label:'وزارة المالية',status:'connected'},{id:'egov',label:'البوابة الحكومية',status:'connected'}]}}
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){cors(res);res.writeHead(204);return res.end()}let u=new URL(req.url,`http://${req.headers.host}`);try{if(u.pathname==='/api/health')return json(res,200,{ok:true,version:'kuwait-directory-4.0',seedCount:SEEDS.length,tenderSeedCount:TENDER_SEEDS.length});if(u.pathname==='/api/categories')return json(res,200,{categories:Object.entries(CATEGORIES).map(([id,v])=>({id,label:v.label}))});if(u.pathname==='/api/directory'||u.pathname==='/api/radar')return json(res,200,await directory(u.searchParams.get('category')||'all'));if(u.pathname==='/api/tenders')return json(res,200,await tenders(u.searchParams.get('q')||''));return json(res,404,{error:'not_found'})}catch(e){return json(res,500,{error:'server_error',message:String(e.message||e)})}}).listen(PORT,'0.0.0.0');