import http from 'node:http';
import { URL } from 'node:url';
const PORT=process.env.PORT||10000,UA='PublicRelationshipRadar/1.0';
const DATING=['looking for a relationship','serious relationship','looking to meet','looking for someone','dating','f4m','f4r','seeking a partner','want to meet someone','أبحث عن شريك','أبحث عن شخص','تعارف جاد','علاقة جادة','أرغب بالتعارف','أبي أتعرف','راغبة بالتعارف','恋人を探しています','出会いを探しています','진지한 관계','만남을 원해요','找对象','认真交往','寻找伴侣','尋找伴侶'];
const BUSINESS=['founder','co-founder','business owner','entrepreneur','ceo','own a business','my business','my company','startup founder','رائدة أعمال','صاحبة مشروع','مالكة شركة','مؤسسة شركة','رئيسة تنفيذية','عندي شركة','مشروعي','女性経営者','女性起業家','会社経営','여성 창업자','사업가','여성 ceo','女性创业者','女企业家','女老板','女性創業者','女企業家','女老闆'];
const SELF=['i am','i’m','im ','my ','i own','i run','أنا ','انا ','عندي ','مشروعي','شركتي','私は','私の','저는','제 ','나는','我是','我的'];
const EXCLUDE=['escort','sugar baby','sugar daddy','onlyfans','nsfw','hookup only','sex work','agency','matchmaking service','dating service','we help','join our','register now','نقدم خدمة','مكتب زواج','وسيط زواج','تطبيق تعارف'];
function cors(r){r.setHeader('Access-Control-Allow-Origin','*');r.setHeader('Access-Control-Allow-Methods','GET,OPTIONS');r.setHeader('Cache-Control','no-store')}function json(r,s,d){cors(r);r.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});r.end(JSON.stringify(d))}function strip(s=''){return String(s).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}function hits(t,a){t=t.toLowerCase();return a.filter(x=>t.includes(x.toLowerCase()))}
function qualify(x){let text=(x.title+' '+x.text).trim(),dating=hits(text,DATING),business=hits(text,BUSINESS),self=hits(text,SELF),bad=hits(text,EXCLUDE);let score=45+Math.min(30,dating.length*10)+Math.min(20,business.length*10)+Math.min(5,self.length*5);return{qualified:dating.length>0&&business.length>0&&self.length>0&&bad.length===0,score:Math.min(98,score),evidence:{dating:dating.slice(0,3),business:business.slice(0,3)}}}
async function fj(u){let r=await fetch(u,{headers:{'User-Agent':UA,'Accept':'application/json'},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error(String(r.status));return r.json()}
async function redditSearch(q,sub=null,label='Reddit'){let base=sub?`https://www.reddit.com/r/${sub}/search.json`:'https://www.reddit.com/search.json';let u=base+'?sort=new&limit=50&raw_json=1'+(sub?'&restrict_sr=1':'')+'&q='+encodeURIComponent(q);let d=await fj(u);return(d?.data?.children||[]).map(v=>v.data).filter(Boolean).map(x=>({source:label,title:x.title||'',text:strip(x.selftext||''),url:'https://www.reddit.com'+x.permalink,author:x.author||'',created:x.created_utc?new Date(x.created_utc*1000).toISOString():null,region:'Global',via:'direct public endpoint'}))}
async function redditBatch(){const qs=['F4M entrepreneur','F4M business owner','F4M founder','F4R entrepreneur','woman founder relationship','female entrepreneur dating','business owner serious relationship','CEO looking for relationship','entrepreneur looking for partner'];const subs=['r4r','R4R30Plus','ForeverAloneDating','datingoverthirty','datingoverforty'];let jobs=[];for(const q of qs)jobs.push(redditSearch(q));for(const s of subs){jobs.push(redditSearch('F4M entrepreneur',s,`Reddit • r/${s}`));jobs.push(redditSearch('F4M business owner',s,`Reddit • r/${s}`));jobs.push(redditSearch('founder relationship',s,`Reddit • r/${s}`))}let st=await Promise.allSettled(jobs),out=[];for(const r of st)if(r.status==='fulfilled')out.push(...r.value);return out}
async function radar(){let raw=await redditBatch(),seen=new Set(),leads=[];for(const x of raw){if(!x.url||seen.has(x.url))continue;seen.add(x.url);let q=qualify(x);if(!q.qualified)continue;leads.push({...x,score:q.score,evidence:q.evidence,verified:true,postType:'self-disclosed-public'})}leads.sort((a,b)=>b.score-a.score||String(b.created).localeCompare(String(a.created)));return{generatedAt:new Date().toISOString(),mode:'public-self-disclosed',sources:[{id:'reddit_direct',status:'connected',count:raw.length},{id:'reddit_communities',status:'connected',count:raw.filter(x=>x.source.includes('r/')).length}],rawCount:raw.length,qualifiedCount:leads.length,leads:leads.slice(0,100)}}
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){cors(res);res.writeHead(204);return res.end()}let u=new URL(req.url,`http://${req.headers.host}`);try{if(u.pathname==='/api/health')return json(res,200,{ok:true,version:'relationship-1.0',mode:'public-self-disclosed'});if(u.pathname==='/api/radar')return json(res,200,await radar());return json(res,404,{error:'not_found'})}catch(e){return json(res,500,{error:'server_error',message:String(e.message||e)})}}).listen(PORT,'0.0.0.0');