/* Sources reviewed on 2026-09-14. No live vacancy, eligibility or income guarantee. */
(function(root){
  'use strict';
  const work = (id,name,category,url,description,tags,note,extra={}) => ({id,name,category,url,description,tags,note,section:'work',...extra});
  const sg='https://www.nvidia.com/en-sg/learn/ai-learning-essentials/';
  const catalog='https://www.nvidia.com/en-gb/training/online/';
  const course=(id,name,title,category,url,description,tags,note,source,extra={})=>({id,name,title,category,url,description,tags,note,source,section:'learn',logo:'NV',badge:'NVIDIA',...extra});
  const resources=[
    work('wwr','We Work Remotely','jobs','https://weworkremotely.com/','وظائف في البرمجة والتصميم والتسويق وخدمة العملاء لدى شركات تعمل عن بُعد.',['وظائف متنوعة','حسب بلد الوظيفة'],'ابدأ بتحديد المنطقة؛ ليست كل الوظائف متاحة من الكويت.',{logo:'W',color:'#087466',bg:'#e0f3ed'}),
    work('remotive','Remotive','jobs','https://remotive.com/','دليل للوظائف عن بُعد، يسهّل الوصول إلى تخصصك والشركات التي تبحث عن مهاراتك.',['تقنية وأعمال','وظائف وعقود'],'راجع الموقع الجغرافي ونوع العقد داخل كل إعلان.',{logo:'R',color:'#a25031',bg:'#fff0e7'}),
    work('remote-ok','Remote OK','jobs','https://remoteok.com/','وظائف عن بُعد في التطوير والتصميم والتسويق، مع تصنيفات للمجالات والمناطق.',['تقنية وتسويق','تصنيفات جغرافية'],'دُمجت روابط Remote OK وأوروبا وآسيا هنا؛ اختر المنطقة من داخل الموقع.',{logo:'OK',color:'#b34743',bg:'#ffedeb',aliases:'Remote OK Europe Remote OK Asia remoteok.io remoteok.com أوروبا آسيا'}),
    work('linkedin','LinkedIn','jobs','https://www.linkedin.com/jobs/','البحث عن وظائف والتواصل المهني مع الشركات، بما في ذلك فرص إدارة المشاريع والمحتوى.',['إدارة وتسويق','شبكة مهنية'],'اختر «عن بُعد» ضمن نوع مكان العمل وراجع متطلبات الإقامة.',{logo:'in',color:'#0a66c2',bg:'#e7f1fd',aliases:'لينكد إن لينكدان project management إدارة مشاريع محتوى'}),
    work('upwork','Upwork','freelance','https://www.upwork.com/','مشاريع مستقلة في البرمجة والتصميم والكتابة والتسويق والأتمتة، بعقود قصيرة أو مستمرة.',['عمل حر','رسوم وعمولات'],'جهّز نماذج أعمال، وراجع تكلفة تقديم العروض والعمولة قبل التعاقد.',{logo:'Up',color:'#147339',bg:'#e4f6e9',aliases:'أب وورك اب ورك اوب ورك automation أتمتة'}),
    work('working-nomads','Working Nomads','jobs','https://www.workingnomads.com/jobs','وظائف عن بُعد موزعة حسب المهارة والمجال، من الإدارة إلى التطوير وخدمة العملاء.',['وظائف متنوعة','مزايا مدفوعة'],'راجع البلد والمهارات المطلوبة؛ بعض أدوات المنصة ضمن اشتراك إضافي.',{logo:'WN',color:'#936a10',bg:'#fff5d8',aliases:'workingnomads.com workingnomads.co'}),
    work('himalayas','Himalayas','jobs','https://himalayas.app/','دليل وظائف وشركات تعمل عن بُعد، مع أدوات تساعدك على البحث عن فرصة مناسبة.',['شركات عن بُعد','أدوات بحث'],'تحقق من المنطقة الزمنية والبلدان المقبولة في الإعلان.',{logo:'H',color:'#4d53a8',bg:'#eeeefe'}),
    work('wellfound','Wellfound','jobs','https://wellfound.com/','وظائف لدى الشركات الناشئة، خصوصاً في التقنية والمنتجات والتسويق.',['شركات ناشئة','الاسم محدّث'],'AngelList Talent الوارد في الصورة أصبح Wellfound.',{logo:'Wf',badge:'اسم محدّث',aliases:'AngelList angel.co أنجل ليست ويلفاوند',source:'https://www.angellist.com/'}),
    work('nodesk','NoDesk','jobs','https://nodesk.co/','وظائف لدى شركات وفرق موزعة، مع صفحات تساعدك على استكشاف العمل عن بُعد.',['وظائف عن بُعد','تصفّح مجاني'],'يمكن تصفح الوظائف دون حساب؛ التقديم يتبع شروط الجهة المعلنة.',{logo:'N',color:'#255582',bg:'#eaf2fc'}),
    work('toptal','Toptal','freelance','https://www.toptal.com/','شبكة عمل مستقل للمحترفين في البرمجة والتصميم والتمويل وإدارة المشاريع.',['خبرة مهنية','عملية تقييم'],'التقديم يتضمن تقييماً؛ يناسب من لديه أعمال وخبرة يمكن إثباتهما.',{logo:'T',aliases:'توبتال project management إدارة مشاريع'}),
    work('freelancer','Freelancer','freelance','https://www.freelancer.com/','سوق للمشاريع والمسابقات في التطوير والتصميم وإدخال البيانات والمهارات الرقمية.',['مشاريع ومسابقات','رسوم وعضويات'],'اقرأ نطاق المشروع والرسوم وآلية الدفع قبل إرسال عرضك.',{logo:'Fr',color:'#1675a5',bg:'#e8f6fc',aliases:'فريلانسر فري لانسر'}),
    work('skipthedrive','SkipTheDrive','jobs','https://www.skipthedrive.com/','محرك لتصفح وظائف العمل من المنزل عبر مجالات وشركات متعددة.',['وظائف عن بُعد','بحث حسب المجال'],'قد ينقلك التقديم إلى موقع صاحب العمل.',{logo:'SD'}),
    work('justremote','JustRemote','jobs','https://justremote.co/','فرص في التصميم والتطوير والتسويق والكتابة، مع أدوات لاستكشاف الوظائف عن بُعد.',['وظائف متنوعة','مزايا إضافية'],'تحقق من الرسوم إن اخترت إحدى أدوات البحث المدفوعة.',{logo:'JR'}),
    work('flexjobs','FlexJobs','jobs','https://www.flexjobs.com/','منصة للوظائف المرنة والعمل عن بُعد بدوام كامل أو جزئي.',['اشتراك مدفوع','عمل مرن'],'الوصول الكامل يعتمد على الاشتراك؛ راجع السعر وشروطه أولاً.',{logo:'F',color:'#b26222',bg:'#fff0df'}),
    work('remote-co','Remote.co','jobs','https://remote.co/','وظائف ومقالات عن العمل عن بُعد في التسويق والإدارة وخدمة العملاء وغيرها.',['وظائف ومحتوى','تخصصات متعددة'],'راجع شروط الوصول والتقديم في المنصة.',{logo:'Co'}),
    work('jobspresso','Jobspresso','jobs','https://jobspresso.co/','فرص عن بُعد في التقنية والتسويق وخدمة العملاء لدى شركات مختلفة.',['وظائف عن بُعد','تقنية وتسويق'],'اقرأ متطلبات الخبرة والموقع قبل التقديم.',{logo:'J',color:'#97402a',bg:'#fff0e8'}),
    work('virtual-vocations','Virtual Vocations','jobs','https://www.virtualvocations.com/','دليل لوظائف العمل من المنزل والعمل عن بُعد في مجالات متنوعة.',['وظائف متنوعة','حساب ومزايا مدفوعة'],'راجع نطاق البلدان وخصائص الاشتراك قبل الدفع.',{logo:'VV'}),
    work('remote4me','Remote4Me','jobs','https://remote4me.com/','يجمع وظائف عن بُعد من عدة لوحات توظيف، مصنفة بحسب المهنة والتقنية.',['مجمّع وظائف','تصفية بالتخصص'],'تحقق من تاريخ الإعلان في المصدر؛ التجميع لا يضمن بقاء الوظيفة متاحة.',{logo:'R4'}),
    work('remotehabits','RemoteHabits','jobs','https://remotehabits.com/jobs/','وظائف ومقابلات وتجارب عملية تساعدك على فهم أسلوب العمل عن بُعد.',['وظائف وتجارب','محتوى إرشادي'],'ليس كل محتوى الموقع إعلان وظيفة؛ يضم أيضاً مقابلات وأدلة.',{logo:'RH',source:'https://remotehabits.com/'}),
    work('remotecrew','RemoteCrew','jobs','https://www.remotecrew.io/','خدمة توظيف تقني تربط المرشحين بشركات تبحث عن مطورين ومتخصصين.',['توظيف تقني','حسب خبرة المرشح'],'المنصة متخصصة في الاستقطاب التقني؛ راجع قسم Find a Job.',{logo:'RC'}),
    work('simplyhired','SimplyHired','jobs','https://www.simplyhired.com/','محرك بحث عام للوظائف، ويمكن استخدام كلمة Remote للعثور على فرص عن بُعد.',['محرك وظائف','حضوري وعن بُعد'],'لا تعرض كل النتائج عملاً عن بُعد؛ استخدم حقل الموقع والفلاتر.',{logo:'SH'}),
    work('monster','Monster','jobs','https://www.monster.com/','منصة عامة للبحث عن الوظائف وتصفح الفرص لدى جهات مختلفة.',['وظائف عامة','حسب البلد'],'استخدم فلاتر الموقع ونمط العمل، ولا تفترض أن كل إعلان عن بُعد.',{logo:'M'}),
    work('hubstaff','Hubstaff Talent','freelance','https://hubstafftalent.net/','دليل للمستقلين وفرص العمل عن بُعد، يرتبط بخدمة Hubstaff Talent.',['ملفات مستقلين','وظائف وعقود'],'الرابط talent.hubstaff.com أعاد التوجيه إلى hubstafftalent.net وقت المراجعة.',{logo:'HT',badge:'رابط محدّث',aliases:'hubstafftalent.com talent.hubstaff.com',source:'https://talent.hubstaff.com/'}),
    work('dribbble','Dribbble','content','https://dribbble.com/','مجتمع للمصممين لعرض أعمالهم وتقديم خدمات التصميم والتواصل مع العملاء.',['تصميم وتجربة مستخدم','معرض أعمال'],'أنشئ معرضاً يوضح أسلوبك وتخصصك؛ الحساب وحده لا يضمن الحصول على عمل.',{logo:'D',color:'#98415d',bg:'#fcecf2',aliases:'دريبل design UI UX'}),
    work('textbroker','Textbroker','content','https://www.textbroker.com/','منصة لخدمات كتابة المحتوى؛ تختلف شروط العمل ككاتب حسب السوق واللغة.',['كتابة محتوى','تقييم لغة وكتابة'],'تحقق من قبول الكتّاب في بلدك ومن شروط الأهلية.',{logo:'Tb',aliases:'تكست بروكر كتابة محتوى SEO'}),
    work('rev','Rev','content','https://www.rev.com/','خدمات تفريغ صوتي ونصوص وترجمة مرئية، مع مسارات عمل للمستقلين بحسب التوفر.',['تفريغ وترجمة','مهارات استماع'],'راجع صفحة العمل الحر لقبول الطلبات والبلدان والاختبارات المطلوبة.',{logo:'Rev',aliases:'ريف صوت ترجمة transcription captions'}),
    work('scribie','Scribie','content','https://scribie.com/','خدمة تفريغ صوتي تعتمد على المراجعة البشرية؛ راجع مسار الانضمام كمفرّغ.',['تفريغ صوتي','مراجعة نصوص'],'وجود الخدمة لا يعني أن باب قبول مستقلين جدد مفتوح حالياً.',{logo:'Sc',aliases:'سكريبي تفريغ transcription'}),
    work('clearvoice','ClearVoice / Fiverr','content','https://www.fiverr.com/','الرابط الأصلي لمنصة المحتوى ClearVoice أصبح يعيد التوجيه إلى سوق Fiverr.',['كتابة وخدمات','تحويل إلى Fiverr'],'لا تتعامل معه كبوابة مستقلة للتقديم على ClearVoice حالياً.',{logo:'CV',badge:'رابط تغيّر',review:true,source:'https://www.clearvoice.com/',aliases:'كلير فويس فايفر fiverr clearvoice.com',action:'فتح Fiverr'}),
    work('trymata','Trymata','testing','https://trymata.com/','منصة لاختبار تجربة استخدام المواقع والتطبيقات وتقديم الملاحظات.',['اختبار استخدام','مهام حسب التوفر'],'تعذّر إكمال فحص الصفحة بسبب حد الطلبات؛ تحقق من أهلية المختبِرين والدفع.',{logo:'Tr',review:true,badge:'تحتاج مراجعة',aliases:'تراي ماتا usability testing'}),
    work('user-interviews','User Interviews','testing','https://www.userinterviews.com/','المشاركة في دراسات ومقابلات بحثية عند توافق ملفك مع الفئة المطلوبة.',['أبحاث مستخدمين','مقابل لكل دراسة'],'الاختيار غير مضمون؛ تختلف الدول والحوافز بحسب الدراسة.',{logo:'UI',color:'#3253aa',bg:'#eaf0fd'}),
    work('zoombucks','ZoomBucks','testing','https://zoombucks.com/','استطلاعات وعروض تمنح مكافآت وفق شروط المنصة والجهات المقدمة.',['استطلاعات ومكافآت','دخل إضافي متغير'],'المكافآت ليست راتباً؛ راجع حد السحب والدولة ووسيلة الاستلام.',{logo:'Z',aliases:'زووم باكس surveys'}),
    work('pollpay','Poll Pay','testing','https://pollpay.com/','اسم وارد في القائمة للاستطلاعات والمكافآت؛ تختلف الإتاحة بحسب الموقع والتطبيق.',['استطلاعات','تحقق من الأهلية'],'لم تظهر تفاصيل قابلة للتحقق في الصفحة. راجع الجهة المشغلة وشروط السحب أولاً.',{logo:'PP',review:true,badge:'تحتاج مراجعة',aliases:'بول باي pollpay.app'}),
    work('gigwalk','Gigwalk','local','https://www.gigwalk.com/','مهام لجمع البيانات والتحقق من المتاجر والعلامات التجارية، وقد تتطلب حضوراً ميدانياً.',['مهام ميدانية','حسب موقعك'],'ليست وظيفة منزلية بالكامل؛ توفر المهام مرتبط بالمدينة.',{logo:'G',aliases:'جيج ووك mystery shopping'}),
    work('taskrabbit','Taskrabbit','local','https://www.taskrabbit.com/','خدمات محلية مثل التجميع والنقل والإصلاحات، ينفذها مقدمو الخدمة في مدن مدعومة.',['عمل محلي','خدمات منزلية'],'ليست منصة عمل عبر اللابتوب فقط. تحقق من دعم بلدك ومدينتك.',{logo:'Ta',color:'#257246',bg:'#e6f4e8',aliases:'تاسك رابيت'}),
    work('preply','Preply','teaching','https://preply.com/','التدريس الخصوصي عبر الإنترنت، خصوصاً اللغات، من خلال ملف تعريفي وحصص مباشرة.',['تدريس لغات','عمولة منصة'],'جهّز فيديو تعريفياً وخطة تدريس، وراجع قبول المدرّسين والعمولات.',{logo:'Pr',color:'#4a5697',bg:'#edf0ff',aliases:'بريبلي تعليم تدريس tutoring'}),
    work('nexrep','NexRep','jobs','https://nexrep.com/','فرص تعاقد لخدمة العملاء والمبيعات من المنزل وفق متطلبات الموقع والسوق.',['خدمة عملاء','متطلبات إقامة'],'تحقق من الإقامة المقبولة والمعدات وساعات العمل قبل التقديم.',{logo:'Nx',aliases:'نكس ريب customer service support'}),
    work('pangian','Pangian','jobs','https://pangian.com/','منصة واردة في القائمة الأصلية؛ الموقع حالياً يعرض رسالة شكر ومرحلة انتقال.',['حالة انتقال','لا قائمة وظائف مؤكدة'],'لم تظهر لوحة وظائف نشطة وقت المراجعة. احتُفظ بها لتوضيح تغير حالتها.',{logo:'Pa',badge:'حالة انتقال',review:true,action:'عرض تحديث المنصة'}),
    work('remotees','Remotees','jobs','https://weworkremotely.com/','الرابط remotees.com الوارد في الصورة يعيد التوجيه إلى We Work Remotely.',['رابط قديم','وجهة بديلة'],'احتُفظ بالاسم الأصلي للتوضيح؛ الوجهة ليست منصة إضافية مستقلة.',{logo:'Re',review:true,badge:'رابط تغيّر',source:'https://remotees.com/',action:'فتح الوجهة الحالية',aliases:'remotees.com'}),
    work('europe-remotely','Europe Remotely','jobs','https://europeremotely.com/','اسم لوحة وظائف أوروبية ورد في الصورة الأصلية. لم نتمكن من تأكيد نشاط رابطها.',['تركيز أوروبي','رابط غير محسوم'],'لم ينجح التحقق من الرابط؛ استخدم منصات أخرى إذا لم يفتح.',{logo:'ER',review:true,badge:'تحتاج مراجعة',action:'فتح الرابط الأصلي',source:'https://hr.linkedin.com/company/europe-remotely'}),
    work('outsourcely','Outsourcely','freelance','https://outsourcely.com/','منصة وردت في القائمة الأصلية لربط الشركات بمستقلين يعملون عن بُعد.',['عمل مستقل','رابط غير محسوم'],'تعذّر التحقق من نشاط المنصة. راجع هويتها وشروطها قبل إنشاء حساب.',{logo:'O',review:true,badge:'تحتاج مراجعة',action:'فتح الرابط الأصلي'}),
    work('stack-overflow','Stack Overflow Jobs','jobs','https://meta.stackexchange.com/questions/417874/sunsetting-stack-overflow-jobs','خدمة توظيف تقني وردت في الصورة، وقد أعلنت Stack Overflow إنهاءها بعد انتهاء تعاون Indeed.',['خدمة انتهت','تحديث رسمي'],'لا تعتمد الرابط القديم للبحث عن وظائف. زر البطاقة يفتح الإعلان الرسمي.',{logo:'SO',review:true,badge:'أُعلن إيقافها',action:'اقرأ تحديث الخدمة',aliases:'stackoverflow.com/jobs ستاك اوفرفلو'}),
    course('genai','Generative AI Explained','فهم الذكاء الاصطناعي التوليدي','basics','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-07+V1','مدخل إلى المفاهيم والاستخدامات والفرص، دون الحاجة إلى كتابة كود.',['مجاني في المصدر','ساعتان','بداية مناسبة'],'قد يتطلب التسجيل حساب NVIDIA.',sg),
    course('brain','Building a Brain in 10 Minutes','شبكة عصبية في عشر دقائق','basics','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+T-FX-01+V1','تمرين قصير يشرح كيف تتعلم شبكة عصبية من البيانات.',['مجاني في المصدر','10 دقائق','Python'],'المعرفة الأساسية ببايثون تساعدك على فهم المثال.', 'https://developer.nvidia.com/blog/get-free-training-in-deep-learning-accelerated-computing-and-data-science/'),
    course('ai-for-all','AI for All: From Basics to GenAI Practice','الذكاء الاصطناعي للجميع','basics','https://www.nvidia.com/en-us/training/academy/self-paced-courses/','مدخل عام للذكاء الاصطناعي وتطبيقاته للمبتدئين.',['مجاني في المصدر','دراسة ذاتية'],'رابط الأكاديمية القديم تغيّر؛ افتح الكتالوج وابحث عن الاسم الإنجليزي. المدة تختلف بين صفحات NVIDIA.','https://www.nvidia.com/en-us/training/academy/self-paced-courses/',{badge:'من الكتالوج',action:'فتح كتالوج الدورة',review:true}),
    course('jetson','Getting Started with AI on Jetson Nano','الذكاء الاصطناعي على Jetson Nano','development','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-RX-02+V2','تدريب نموذج لتصنيف الصور على جهاز Jetson Nano.',['الدورة مجانية','8 ساعات','تطبيق عملي'],'تنفيذ التدريب يتطلب العتاد المناسب؛ مجانية الدورة لا تشمل الجهاز.',sg),
    course('data-center','Introduction to AI in the Data Center','الذكاء الاصطناعي في مركز البيانات','infrastructure','https://www.nvidia.com/en-gb/training/online/','مدخل إلى البنية التحتية وعتاد وبرمجيات الذكاء الاصطناعي.',['مدفوع في الكتالوج','3.5 ساعات'],'ورد بسعر 49 دولاراً في الكتالوج؛ الرابط القديم انتقل. ابحث بالعنوان وتحقق من السعر الحالي.',catalog,{badge:'مدفوع',action:'عرض كتالوج الدورة',review:true}),
    course('cuda-intro','An Even Easier Introduction to CUDA','مقدمة عملية إلى CUDA','development','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+T-AC-01+V1','تعلّم مبادئ البرمجة المتوازية على معالجات الرسوميات.',['مجاني في المصدر','ساعة','CUDA C++'],'تحتاج إلى أساس في البرمجة لفهم التمرين.',sg),
    course('nim','Introduction to NVIDIA NIM Microservices','نشر النماذج باستخدام NIM','development','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-23+V1','مدخل لبناء التطبيقات ونشر نماذج الذكاء الاصطناعي وتوسيع استخدامها.',['مجاني في المصدر','ساعتان','واجهات نماذج'],'البيئة العملية قد تتطلب حساباً وصلاحيات إضافية.',sg),
    course('health','Getting Started with NVIDIA Tools for Generative AI in Digital Health','الذكاء الاصطناعي في الصحة الرقمية','applications','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-HX-03+V1','تطبيقات تتعامل مع البيانات الصحية والبحثية باستخدام الذكاء الاصطناعي التوليدي.',['مجاني في المصدر','ساعتان','تطبيق متخصص'],'مورد تعليمي تقني؛ ليس اعتماداً طبياً.',sg),
    course('earth2','Applying AI Weather Models with NVIDIA Earth-2','نماذج الطقس مع Earth-2','applications','https://learn.nvidia.com/courses/course-detail?course_id=course-v1:DLI+S-FX-31+V1','تعلّم توظيف نماذج الطقس بالذكاء الاصطناعي ضمن سير عمل مخصص.',['مدفوع في المصدر','3 ساعات'],'المصدر يعرض 30 دولاراً؛ لا تُصنّف الدورة مجانية. تحقق من السعر عند التسجيل.',sg,{badge:'مدفوع'}),
    course('cuda-cpp','Accelerated Computing with CUDA C/C++','الحوسبة المسرّعة باستخدام CUDA','development','https://www.nvidia.com/en-gb/training/online/','تدريب على تسريع التطبيقات باستخدام CUDA C/C++.',['مدفوع في الكتالوج','8 ساعات','C/C++'],'العنوان المطابق في الكتالوج يبدأ بـ Getting Started ويعرض 90 دولاراً. رابط الدورة القديم انتقل.',catalog,{badge:'مدفوع',action:'عرض كتالوج الدورة',review:true}),
    course('nemo','Generative AI with NeMo','الذكاء الاصطناعي التوليدي مع NeMo','development','https://developer.nvidia.com/blog/streamline-generative-ai-development-with-nvidia-nemo-on-gpu-accelerated-google-cloud/','مورد رسمي يشرح دور NeMo في تخصيص النماذج ونشرها.',['مقال تقني','قراءة متاحة'],'لم نثبت دورة مستقلة بهذا العنوان؛ أُضيف مورد رسمي بديل، وليس وعداً بدورة أو شهادة.','https://developer.nvidia.com/blog/streamline-generative-ai-development-with-nvidia-nemo-on-gpu-accelerated-google-cloud/',{badge:'مورد بديل',review:true,action:'قراءة المورد'})
  ];
  // Keep every distinct platform mentioned in the screenshots, including legacy entries.
  const categories={
    work:[{id:'all',label:'كل المنصات',icon:'grid'},{id:'jobs',label:'وظائف عن بُعد',icon:'briefcase'},{id:'freelance',label:'العمل الحر',icon:'laptop'},{id:'content',label:'كتابة وتصميم',icon:'pen'},{id:'testing',label:'اختبارات واستطلاعات',icon:'research'},{id:'local',label:'خدمات ميدانية',icon:'pin'},{id:'teaching',label:'التدريس',icon:'book'}],
    learn:[{id:'all',label:'كل موارد NVIDIA',icon:'grid'},{id:'basics',label:'الأساسيات',icon:'book'},{id:'development',label:'التطوير والبرمجة',icon:'laptop'},{id:'applications',label:'تطبيقات متخصصة',icon:'research'},{id:'infrastructure',label:'البنية التحتية',icon:'grid'}]
  };
  function normalize(value){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').toLocaleLowerCase().trim();}
  function select(state){
    const terms=normalize(state.query).split(/\s+/).filter(Boolean);
    const list=resources.filter(r=>r.section===state.section&&(state.category==='all'||r.category===state.category)&&(!state.review||r.review)&&terms.every(t=>normalize([r.name,r.title,r.description,r.note,r.aliases,...r.tags].join(' ')).includes(t)));
    if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'en'));
    return list;
  }
  const api={resources,categories,select,normalize};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  else root.MADAR=api;
})(typeof window!=='undefined'?window:globalThis);
