const projects=[
{name:'AI Legal Office',tier:'A',status:'تنفيذ الآن',price:600,clients:20,target:12000,score:96,model:'اشتراك شهري لمكاتب المحاماة',offer:'إدارة ملفات + مساعد قانوني + مذكرات + CRM + مواعيد',next:'بناء باقة White-label وعرض تجريبي لأول 5 مكاتب',repo:'https://github.com/Q8-ux/sabeq-legal-system'},
{name:'AI Business Command Center',tier:'A',status:'تنفيذ الآن',price:1000,clients:12,target:12000,score:95,model:'SaaS B2B للشركات',offer:'مركز قيادة يربط المشاريع والمهام والوثائق والوكلاء',next:'تحويل هذه اللوحة إلى منتج متعدد الشركات',repo:'https://github.com/Q8-ux/saad/tree/main/project-command-center'},
{name:'AI Website Sales Factory',tier:'A',status:'تنفيذ الآن',price:1500,clients:8,target:12000,score:92,model:'خدمة إنتاج مواقع مدعومة بالذكاء الاصطناعي',offer:'بحث + محتوى + تصميم + CRM + نشر',next:'إنشاء 3 قوالب قطاعية وصفحة طلب وتسعير',repo:'https://github.com/Q8-ux/saad'},
{name:'AI Social Media OS',tier:'B',status:'التالي',price:600,clients:20,target:12000,score:88,model:'منصة + خدمة مُدارة',offer:'محتوى + تقويم + موافقات + منافسين + تقارير',next:'MVP لإدارة 5 عملاء تجريبيين',repo:'https://github.com/Q8-ux/saad'},
{name:'Restaurant AI OS',tier:'B',status:'التالي',price:300,clients:40,target:12000,score:86,model:'اشتراك للمطاعم',offer:'طلبات + مخزون + مشتريات + موردين + مساعد صوتي',next:'دمج التموينات والطلب الصوتي في منتج واحد',repo:'https://github.com/Q8-ux/zad-restaurants'},
{name:'WhatsApp & SMS AI',tier:'B',status:'التالي',price:400,clients:30,target:12000,score:84,model:'Automation B2B',offer:'حملات + Leads + تذكير + ردود AI + تقارير',next:'بناء محرك Workflows وقوالب قطاعات',repo:'https://github.com/Q8-ux/saad'},
{name:'AI Procurement Marketplace',tier:'C',status:'توسع',price:0,clients:0,target:12500,score:80,model:'2.5% عمولة من GMV',offer:'مقارنة أسعار وموردين وطلبات B2B',next:'استهداف GMV شهري 500,000 دولار',repo:'https://github.com/Q8-ux/zad-restaurants'},
{name:'AI Document Intelligence',tier:'C',status:'توسع',price:2000,clients:6,target:12000,score:83,model:'عقود شركات',offer:'استخراج + تصنيف + بحث دلالي + Q&A',next:'إنشاء Demo لعقود وأرشيف شركة',repo:'https://github.com/Q8-ux/saad'},
{name:'Kuwait AI Education',tier:'D',status:'لاحقاً',price:0,clients:0,target:12000,score:76,model:'مدارس + طلبة B2B2C',offer:'دروس + استماع + امتحانات + معلم AI',next:'إثبات الاستخدام مع صف واحد قبل التوسع',repo:'https://github.com/Q8-ux/saad/tree/main/english-kuwait'},
{name:'Arabic AI Telecom VAS',tier:'D',status:'لاحقاً',price:4000,clients:3,target:12000,score:79,model:'B2B / Revenue Share',offer:'خدمات AI عربية جاهزة لشركات الاتصالات',next:'إعداد 3 منتجات VAS قابلة للعرض على المشغلين',repo:'https://github.com/Q8-ux/saad'}];
const $=s=>document.querySelector(s);const money=n=>'$'+n.toLocaleString('en-US');
function render(){const q=($('#search')?.value||'').toLowerCase(),tier=$('#tier')?.value||'all';const list=projects.filter(p=>(tier==='all'||p.tier===tier)&&p.name.toLowerCase().includes(q));$('#projects').innerHTML=list.map((p,i)=>`<article class="project-card"><div class="project-top"><div><small>Tier ${p.tier}</small><h3>${p.name}</h3></div><span class="badge ${p.tier==='A'?'active':p.tier==='B'?'ready':'attention'}">${p.status}</span></div><div class="project-meta"><div class="meta-box"><small>هدف MRR</small><b>${money(p.target)}</b></div><div class="meta-box"><small>درجة الأولوية</small><b>${p.score}/100</b></div><div class="meta-box"><small>السعر</small><b>${p.price?money(p.price):'عمولة/مختلط'}</b></div><div class="meta-box"><small>العملاء المطلوبون</small><b>${p.clients||'حسب GMV'}</b></div></div><div class="progress"><span style="width:${p.score}%"></span></div><p>${p.offer}</p><div class="project-actions"><button onclick="room(${projects.indexOf(p)})">غرفة التحكم</button><a class="primary" href="${p.repo}" target="_blank" rel="noopener">GitHub</a></div></article>`).join('');}
window.room=i=>{const p=projects[i];$('#room').innerHTML=`<div class="room-grid"><div class="room-section"><h4>نموذج الإيراد</h4><p>${p.model}</p><b>${money(p.target)} / شهر</b></div><div class="room-section"><h4>الحسبة</h4><p>${p.price&&p.clients?`${p.clients} عميل × ${money(p.price)}`:'نموذج عمولة أو دخل مختلط'}</p></div><div class="room-section"><h4>الخطوة التالية</h4><p>${p.next}</p></div><div class="room-section"><h4>القرار</h4><p>الأولوية ${p.score}/100 — ${p.status}</p><a href="${p.repo}" target="_blank">فتح GitHub</a></div></div>`;$('#room').scrollIntoView({behavior:'smooth'});};
function answer(text){text=text.toLowerCase();let msg;if(text.includes('ابدأ')||text.includes('اولو')||text.includes('أولو'))msg='ابدأ بثلاثة مشاريع Tier A فقط: AI Legal Office ثم AI Business Command Center ثم AI Website Sales Factory. هدف المرحلة الأولى 36,000 دولار MRR، وبعد إثبات المبيعات نفتح Tier B.';else if(text.includes('دخل')||text.includes('12000'))msg='هدف المحفظة الكامل 120,000 دولار MRR. لا أتعامل معه كضمان؛ لكل مشروع معادلة عملاء/سعر واضحة، ويجب قياس Pipeline وCAC وChurn قبل زيادة الاستثمار.';else if(text.includes('خطر')||text.includes('مخاطر'))msg='أكبر خطر هو تشغيل 10 فرق بيع ومنتجات في وقت واحد. الحل: Core Platform مشتركة، وثلاثة مشاريع Tier A فقط في التنفيذ التجاري الأول.';else msg='التوصية التنفيذية: ركّز الآن على Tier A، ابنِ عرضاً قابلاً للبيع خلال أسابيع، وسجّل لكل مشروع العملاء المحتملين والعروض والمبيعات الفعلية. لا نرفع أولوية مشروع بسبب اكتمال الكود فقط.';$('#aiAnswer').textContent=msg;}
document.addEventListener('DOMContentLoaded',()=>{$('#totalTarget').textContent=money(projects.reduce((s,p)=>s+p.target,0));$('#projectCount').textContent=projects.length;$('#tierA').textContent=projects.filter(p=>p.tier==='A').length;$('#firstTarget').textContent='$36,000';$('#search')?.addEventListener('input',render);$('#tier')?.addEventListener('change',render);$('#ask')?.addEventListener('click',()=>answer($('#aiInput').value));$('#aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')answer(e.target.value)});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{ $('#aiInput').value=b.dataset.prompt;answer(b.dataset.prompt)});render();});