'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
type Employee={id:string;employeeNo:string;fullNameAr:string};
type Station={id:string;nameAr:string};
type Permit={id:string;status:string;reason:string;expectedDistanceKm?:string;validFrom:string;validUntil:string;employee:Employee;originStation:Station;destinationStation:Station};
type AiResult={summary?:string;riskLevel?:string;findings?:string[];recommendations?:string[];requiresHumanReview?:boolean;confidenceNote?:string};
const shortName=(n:string)=>n.trim().split(/\s+/).slice(0,2).join(' ');
const statusLabel:Record<string,string>={PENDING_APPROVAL:'بانتظار الاعتماد',APPROVED:'معتمد',READY:'جاهز',DEPARTED:'غادر المنشأة',IN_TRANSIT:'في الطريق',ARRIVED:'وصل',AT_DESTINATION:'داخل المنشأة',RETURNING:'في العودة',COMPLETED:'مكتمل',DELAYED:'متأخر',EXPIRED:'منتهي',CANCELLED:'ملغي',REVIEW_REQUIRED:'للمراجعة'};
export default function TransfersPage(){
 const api=process.env.NEXT_PUBLIC_API_URL!;const [employees,setEmployees]=useState<Employee[]>([]);const [stations,setStations]=useState<Station[]>([]);const [permits,setPermits]=useState<Permit[]>([]);const [message,setMessage]=useState('');const [aiLoading,setAiLoading]=useState(false);const [aiResult,setAiResult]=useState<AiResult|null>(null);
 const headers=()=>({Authorization:`Bearer ${window.localStorage.getItem('token')||''}`,'Content-Type':'application/json'});
 async function load(){const [e,s,p]=await Promise.all([fetch(`${api}/employees`,{headers:headers()}),fetch(`${api}/stations`,{headers:headers()}),fetch(`${api}/transfers`,{headers:headers()})]);if(e.ok)setEmployees(await e.json());if(s.ok)setStations(await s.json());if(p.ok)setPermits(await p.json())}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setMessage('جارٍ إنشاء التصريح...');const r=await fetch(`${api}/transfers`,{method:'POST',headers:headers(),body:JSON.stringify({employeeId:f.get('employeeId'),originStationId:f.get('originStationId'),destinationStationId:f.get('destinationStationId'),reason:f.get('reason'),validFrom:new Date(String(f.get('validFrom'))).toISOString(),validUntil:new Date(String(f.get('validUntil'))).toISOString(),expectedDurationMinutes:Number(f.get('expectedDurationMinutes')||0)||undefined})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d.message||'تعذر إنشاء التصريح');return}setMessage('تم إنشاء تصريح الانتقال وإرساله للاعتماد.');e.currentTarget.reset();await load()}
 async function analyzeTransfers(){setAiLoading(true);setAiResult(null);try{const r=await fetch(`${api}/ai/analyze`,{method:'POST',headers:headers(),body:JSON.stringify({section:'TRANSFERS',task:'حلل تصاريح الانتقال الحالية وحدد حالات التأخير أو المخاطر أو البيانات غير المنطقية، ثم قدم توصيات تشغيلية مرتبة.',language:'ar',data:{permits:permits.slice(0,100).map(p=>({status:p.status,reason:p.reason,expectedDistanceKm:p.expectedDistanceKm,validFrom:p.validFrom,validUntil:p.validUntil,origin:p.originStation.nameAr,destination:p.destinationStation.nameAr,employeeNo:p.employee.employeeNo}))}})});const d=await r.json();if(!r.ok)throw new Error(d.message||'تعذر التحليل');setAiResult(d)}catch(e:any){setMessage(e.message||'تعذر تشغيل التحليل الذكي')}finally{setAiLoading(false)}}
 return <main className="appMain"><section className="pageHero"><div><span className="eyebrow">منصة نطاق العمل</span><h1>🚗 الانتقالات الذكية</h1><p>طلب واعتماد الانتقال بين المنشآت ومتابعة حالة الرحلة.</p></div><Link href="/dashboard" className="heroBack">العودة</Link></section>{message&&<div className="notice section">{message}</div>}
 <section className="card section aiInlinePanel"><div className="incidentHead"><div><h2>🤖 تحليل الانتقالات بالذكاء الاصطناعي</h2><p className="muted">يفحص التصاريح النشطة والمنتهية وحالات التأخير والمسافات.</p></div><button type="button" className="secondaryButton" onClick={analyzeTransfers} disabled={aiLoading}>{aiLoading?'جارٍ التحليل...':'تحليل التصاريح الآن'}</button></div>{aiResult&&<div className="aiResultBox"><h3>{aiResult.summary||'نتيجة التحليل'}</h3><div className="badge badgeGray">مستوى المخاطر: {aiResult.riskLevel||'غير محدد'}</div>{aiResult.findings?.length?<><h4>الملاحظات</h4><ul>{aiResult.findings.map((x,i)=><li key={i}>{x}</li>)}</ul></>:null}{aiResult.recommendations?.length?<><h4>التوصيات</h4><ol>{aiResult.recommendations.map((x,i)=><li key={i}>{x}</li>)}</ol></>:null}{aiResult.requiresHumanReview&&<p className="notice">تحتاج النتيجة إلى مراجعة بشرية قبل اتخاذ أي إجراء.</p>}</div>}</section>
 <section className="grid twoCols section"><form className="card servicePanel" onSubmit={create}><h2>طلب تصريح انتقال</h2><label>الموظف</label><select name="employeeId" required>{employees.map(x=><option key={x.id} value={x.id}>{x.employeeNo} — {shortName(x.fullNameAr)}</option>)}</select><label>من المنشأة</label><select name="originStationId" required>{stations.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><label>إلى المنشأة</label><select name="destinationStationId" required>{stations.map(x=><option key={x.id} value={x.id}>{x.nameAr}</option>)}</select><label>سبب الانتقال</label><textarea name="reason" required placeholder="اكتب سبب المهمة"/><label>بداية التصريح</label><input name="validFrom" type="datetime-local" required/><label>نهاية التصريح</label><input name="validUntil" type="datetime-local" required/><label>المدة المتوقعة بالدقائق</label><input name="expectedDurationMinutes" type="number" min="1"/><button>إرسال طلب التصريح</button></form>
 <section className="card servicePanel"><h2>حالة التصاريح</h2>{permits.length===0?<p className="muted">لا توجد تصاريح انتقال.</p>:permits.slice(0,20).map(p=><article className="permitCard" key={p.id}><div className="incidentHead"><b>{shortName(p.employee.fullNameAr)}</b><span className="badge badgeGray">{statusLabel[p.status]||p.status}</span></div><p>{p.originStation.nameAr} ← {p.destinationStation.nameAr}</p><small className="muted">{p.reason}</small>{p.expectedDistanceKm&&<div className="permitMeta">المسافة المباشرة: {Number(p.expectedDistanceKm).toFixed(1)} كم</div>}</article>)}</section></section>
 <nav className="mobileNav"><Link href="/dashboard">⌂<span>الرئيسية</span></Link><Link href="/attendance-smart">📍<span>الحضور</span></Link><Link href="/transfers">🚗<span>الانتقال</span></Link><Link href="/notifications">🔔<span>التنبيهات</span></Link><Link href="/profile">👤<span>حسابي</span></Link></nav></main>}
