const closing=['احفظ المعلومة','احفظ هذا المنشور للرجوع إليه، وشاركه مع من يهمّه الموضوع.'];
const posts=[
{title:'ألم الركبة',subtitle:'ما أشهر أسبابه؟',theme:'light',palette:'الفضي الفاتح · الأزرق الطبي',en:'KNEE PAIN · COMMON CAUSES',caption:'ألم الركبة له أسباب متعددة، وفهم الأعراض والفحص يساعدان على تحديد السبب. تصفّح الشرائح للتعرّف على أبرز الاحتمالات ومتى تحتاج إلى تقييم.',slides:[['ألم الركبة','ما أشهر أسبابه؟'],['الألم ليس تشخيصًا واحدًا','مكان الألم ووقت ظهوره وطريقة بدايته تساعد على تضييق الاحتمالات، لكنها لا تكفي وحدها لتحديد السبب.'],['أسباب مرتبطة بالإجهاد','من الأسباب الشائعة: ألم مقدمة الركبة، تهيّج الأوتار أو الأجربة، وزيادة الحمل أو التمرين بسرعة أكبر من قدرة الجسم على التكيف.'],['أسباب مرتبطة بالإصابة','الالتواء أو السقوط قد يسبب إصابة في الأربطة أو الغضروف الهلالي، وأحيانًا كسرًا. التورم السريع أو عدم الثبات بعد الإصابة يحتاج إلى تقييم.'],['أسباب داخل المفصل','قد يكون الألم ناتجًا عن خشونة الركبة، التهاب المفصل، النقرس، أو مشكلة أخرى داخل المفصل. العمر وحده لا يحدد السبب.'],['كيف نعرف السبب؟','يبدأ التشخيص بالقصة المرضية والفحص السريري. لا يحتاج كل ألم إلى أشعة أو رنين؛ يُطلب التصوير عندما يضيف معلومة ستؤثر في القرار العلاجي.'],['متى لا تنتظر؟','راجع الطبيب سريعًا عند ألم شديد بعد إصابة، أو عجز عن تحميل الوزن، أو قفل الركبة، أو تورم واحمرار وسخونة مع حرارة أو شعور عام بالتعب.'],closing]},
{title:'خشونة الركبة',subtitle:'ما هي؟ وكيف تحدث؟',theme:'dark',palette:'الكحلي · الأزرق الطبي',en:'KNEE OSTEOARTHRITIS · WHAT IS IT?',caption:'خشونة الركبة تغيّرات قد تؤثر في المفصل كله. هذا المنشور يشرح ما يحدث داخل الركبة، والأعراض وطريقة التقييم، وأهمية الحركة المناسبة.',slides:[['خشونة الركبة','ما هي؟ وكيف تحدث؟'],['ليست تآكلًا فقط','خشونة الركبة ليست مجرد نقص في الغضروف، بل تغيّرات تدريجية قد تؤثر في المفصل كله وفي طريقة عمله.'],['ماذا يتغيّر داخل المفصل؟','قد تتأثر الغضاريف والعظم تحت الغضروف والغشاء الزليلي والغضروف الهلالي، إضافة إلى العضلات والأنسجة المحيطة بالركبة.'],['لماذا تحدث؟','يزداد الاحتمال مع التقدم في العمر، وإصابة سابقة في الركبة، وزيادة الوزن، وبعض أنماط المحاذاة والعوامل الوراثية. لكنها ليست نتيجة حتمية للعمر.'],['أشهر الأعراض','ألم يرتبط بالنشاط، تيبّس قصير بعد الراحة أو صباحًا، تورم متقطع، ونقص في الحركة. شدة الأعراض لا تتطابق دائمًا مع صورة الأشعة.'],['كيف يتم التشخيص؟','يمكن تشخيص حالات كثيرة سريريًا، خصوصًا بعد سن 45 مع ألم مرتبط بالحركة وتيبّس صباحي لا يتجاوز 30 دقيقة. تُطلب الأشعة عند الحاجة لا تلقائيًا.'],['الرسالة الأهم','الخشونة لا تعني التوقف عن الحركة. التمارين المناسبة، وإدارة الوزن عند الحاجة، وخطة علاج فردية تساعد على تخفيف الألم وتحسين الوظيفة.'],closing]},
{title:'طقطقة الركبة',subtitle:'متى تكون طبيعية ومتى تحتاج إلى فحص؟',theme:'warm',palette:'البيج · العنابي',en:'KNEE CREPITUS · WHEN TO CHECK IT',caption:'صوت الركبة وحده لا يكفي لتشخيص الخشونة. الأعراض المصاحبة هي التي تساعد على معرفة متى تكون الطقطقة مطمئنة ومتى تحتاج إلى فحص.',slides:[['طقطقة الركبة','متى تكون طبيعية ومتى تحتاج إلى فحص؟'],['الصوت شائع','قد تنتج الأصوات عن حركة الأوتار والأنسجة أو تغيّر الضغط داخل المفصل. وجود الصوت وحده لا يعني أن الركبة متضررة.'],['هل تعني وجود خشونة؟','الطقطقة قد تظهر مع الخشونة وقد تظهر دون ألم أو مرض واضح. لذلك لا يمكن تشخيص الخشونة من الصوت وحده.'],['متى تكون مطمئنة غالبًا؟','إذا كانت بلا ألم أو تورم أو قفل أو عدم ثبات، ولا تمنعك من الحركة أو النشاط المعتاد، فهي غالبًا لا تحتاج إلى علاج لمجرد الصوت.'],['متى تحتاج إلى فحص؟','إذا بدأت بعد إصابة، أو صاحبها ألم واضح أو تورم، أو إحساس بأن الركبة تخونك، أو صعوبة في فرد الركبة أو تحميل الوزن.'],['ماذا يفحص الطبيب؟','يراجع موضع الألم ومدى الحركة والثبات والتورم وطبيعة الإصابة. قد يُطلب التصوير إذا كان سيغيّر التشخيص أو الخطة.'],['لا تعالج الصوت وحده','الهدف هو تقييم الألم والوظيفة والأعراض المصاحبة، وليس إسكات كل صوت يصدر من الركبة.'],closing]}
];
const $=s=>document.querySelector(s);const viewer=$('#viewer');let active=0,index=0,lastFocus=null,savedOnly=false;let saved=new Set;try{saved=new Set(JSON.parse(localStorage.getItem('hamad-demo-saved')||'[]'))}catch{}
function slideMarkup(p,n){const [title,body]=p.slides[n];return `<article class="slide ${p.theme} ${n===0?'cover':''}" aria-label="${p.title}، ${n+1} من 8"><div class="top-strip"></div><div class="corner-line"></div><div class="slide-logo logo" role="img" aria-label="شعار الدكتور حمد"></div><div class="slide-count"><span>${String(n+1).padStart(2,'0')}</span><i></i><span>08</span></div><span class="series">SERIES ${String(posts.indexOf(p)+1).padStart(2,'0')}</span><div class="knee" role="img" aria-label="رسم هندسي لمفصل الركبة"></div><h2 class="slide-heading">${title}</h2>${n===0?`<p class="cover-subtitle">${body}</p><p class="cover-note">معلومة طبية موثوقة بلغة واضحة</p>`:`<div class="text-card"><p>${body}</p></div>`}<div class="slide-footer"><span class="english-badge" lang="en">${p.en}</span><span class="account-badge">◎ DrHamad.s</span></div></article>`}
function renderGrid(){const visible=posts.map((p,i)=>({p,i})).filter(({i})=>!savedOnly||saved.has(i));$('#grid').innerHTML=visible.length?visible.map(({p,i})=>`<button class="tile" data-open="${i}" aria-label="فتح ${p.title}، 8 شرائح"><span class="badge">▣ 8</span>${slideMarkup(p,0)}<div class="tile-title">${p.title}</div></button>`).join(''):'<p class="empty">لم تحفظ منشورًا بعد. افتح أي كاروسيل واضغط «حفظ المنشور».</p>'}
function renderSlide(){const p=posts[active];$('#slide-mount').innerHTML=slideMarkup(p,index);$('#counter').textContent=`${index+1} / 8`;$('#prev').disabled=index===0;$('#next').disabled=index===7;$('#dots').innerHTML=p.slides.map((_,i)=>`<button data-slide="${i}" class="${i===index?'active':''}" aria-label="انتقل إلى ${i+1} من 8" ${i===index?'aria-current="true"':''}></button>`).join('');$('#save').setAttribute('aria-pressed',String(saved.has(active)));$('#save').textContent=saved.has(active)?'◆ تم الحفظ':'◇ حفظ المنشور'}
function openPost(n){active=n;index=0;lastFocus=document.activeElement;const p=posts[n];$('#post-title').textContent=p.title;$('#post-caption').textContent=p.caption;$('#palette-label').textContent=p.palette;$('#toast').textContent='';renderSlide();if(!viewer.open)viewer.showModal();document.body.style.overflow='hidden';$('#close').focus()}
function closePost(){viewer.close();document.body.style.overflow='';lastFocus?.focus()}
function move(delta){index=Math.min(7,Math.max(0,index+delta));renderSlide()}
document.addEventListener('click',e=>{const opener=e.target.closest('[data-open]');if(opener)openPost(Number(opener.dataset.open));const dot=e.target.closest('[data-slide]');if(dot){index=Number(dot.dataset.slide);renderSlide()}});
$('#close').onclick=closePost;$('#prev').onclick=()=>move(-1);$('#next').onclick=()=>move(1);viewer.addEventListener('cancel',e=>{e.preventDefault();closePost()});viewer.addEventListener('click',e=>{if(e.target===viewer){const r=viewer.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePost()}});
document.addEventListener('keydown',e=>{if(!viewer.open)return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}});
let touch=null;$('.visual').addEventListener('touchstart',e=>{touch={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});$('.visual').addEventListener('touchend',e=>{if(!touch)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);touch=null},{passive:true});
$('#save').onclick=()=>{if(saved.has(active))saved.delete(active);else saved.add(active);try{localStorage.setItem('hamad-demo-saved',JSON.stringify([...saved]))}catch{}renderSlide();renderGrid()};
function setTab(isSaved){savedOnly=isSaved;$('#saved-tab').classList.toggle('active',isSaved);$('#all-tab').classList.toggle('active',!isSaved);$('#saved-tab').setAttribute('aria-selected',String(isSaved));$('#all-tab').setAttribute('aria-selected',String(!isSaved));renderGrid()}
$('#all-tab').onclick=()=>setTab(false);$('#saved-tab').onclick=()=>setTab(true);
$('#share').onclick=async()=>{const url=new URL(location.href);url.hash=`post-${active+1}`;try{if(navigator.share)await navigator.share({title:posts[active].title,url:url.href});else{await navigator.clipboard.writeText(url.href);$('#toast').textContent='تم نسخ رابط المنشور'}}catch(e){if(e.name!=='AbortError')$('#toast').textContent='رابط المنشور: '+url.href}};
renderGrid();const match=location.hash.match(/^#post-([1-3])$/);if(match)openPost(Number(match[1])-1);
