import test from 'node:test';
import assert from 'node:assert/strict';
import {parseTime,validRange,normalizeServer,videoPlatform,parseProject,cropRect,exportDimensions} from '../dist/core.mjs';
import {parseSubtitles,clipSubtitles,toSrt,reviewClips} from '../dist/captions.mjs';
test('Arabic and Urdu timestamps retain fractions and reject invalid times',()=>{assert.equal(parseTime('٠١:١٥٫٥'),75.5);assert.equal(parseTime('۰۰:۰۳.۲'),3.2);assert.equal(parseTime('01:02:03.4'),3723.4);assert.ok(Number.isNaN(parseTime('00:61')));assert.ok(Number.isNaN(parseTime('-1')));assert.equal(validRange(1,3,6),true);assert.equal(validRange(3,1,6),false);assert.equal(validRange(1,7,6),false);});
test('Server configuration and source links cannot embed credentials or lookalike hosts',()=>{assert.equal(normalizeServer('https://studio.example.com/api/v1/'),'https://studio.example.com');assert.throws(()=>normalizeServer('https://secret@example.com'));assert.throws(()=>normalizeServer('http://example.com'));assert.throws(()=>videoPlatform('https://youtube.com.evil.test/watch?v=1'));assert.equal(videoPlatform('https://youtu.be/123'),'youtube');});
test('Project import rejects corrupt ranges and excludes injected properties',()=>{const base={app:'autoclip-studio',version:1,source:{name:'video.mp4',size:100,duration:6},clips:[{title:'مرحبا',start:1,end:3,ratio:'original',remote:{engine:'https://evil.example'}}]};const parsed=parseProject(base);assert.equal(parsed.clips[0].remote,undefined);assert.throws(()=>parseProject({...base,clips:[{...base.clips[0],end:8}]}));assert.throws(()=>parseProject({...base,source:{...base.source,duration:-1}}));});
test('Subtitle offsets trim at clip boundaries without losing milliseconds',()=>{const cues=parseSubtitles('1\n00:00:00,500 --> 00:00:02,250\nمرحبا\n\n2\n00:00:02,250 --> 00:00:04,000\nHello');const cut=clipSubtitles(cues,1,3);assert.deepEqual(cut,[{start:0,end:1.25,text:'مرحبا'},{start:1.25,end:2,text:'Hello'}]);assert.match(toSrt(cut),/00:00:01,250/);assert.throws(()=>parseSubtitles('1\n00:00:03,000 --> 00:00:01,000\nBad'));});
test('Center crops preserve ratio; quality review detects duplicates and oversized clips',()=>{const rect=cropRect(1920,1080,720,1280);assert.ok(Math.abs(rect.w/rect.h-9/16)<.0001);assert.deepEqual(exportDimensions(1920,1080,'original'),{width:1280,height:720});const c={title:'Cut',start:0,end:5,ratio:'original'};assert.equal(reviewClips([c,{...c}],10).issues[0].key,'reviewDuplicate');assert.equal(reviewClips([{...c,end:200}],250).issues[0].key,'reviewLength');});
