export type Language = "ar" | "en" | "ur";

export const team = [
  { prefix: { ar: "المحامي الدكتور", en: "Attorney", ur: "Attorney" }, name: { ar: "خليفة محمد الخليفة", en: "Dr. Khalifa Mohammed Al Khalifa", ur: "Dr. Khalifa Mohammed Al Khalifa" }, image: "/images/team/dr-khalifa-original-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "خالد علي الحبيب", en: "Khalid Ali Al Habib", ur: "Khalid Ali Al Habib" }, image: "/images/team/khalid-alhabib-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "مشعل متعب", en: "Mishal Metaab", ur: "Mishal Metaab" }, image: "/images/team/mishal-metaab-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "محمد ساحب الشمري", en: "Mohammed Saheb Al Shammari", ur: "Mohammed Saheb Al Shammari" }, image: "/images/team/mohammed-saheb-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "عبدالعزيز مشعان العازمي", en: "Abdulaziz Mashaan Al Azmi", ur: "Abdulaziz Mashaan Al Azmi" }, image: "/images/team/abdulaziz-mashaan-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "حمد ناصر الماضي", en: "Hamad Nasser Al Madi", ur: "Hamad Nasser Al Madi" }, image: "/images/team/hamad-almadi-navy.png" },
  { prefix: { ar: "المحامي", en: "Attorney", ur: "Attorney" }, name: { ar: "خالد مشعل الظفيري", en: "Khalid Mishal Al Dhafiri", ur: "Khalid Mishal Al Dhafiri" }, image: "/images/team/khalid-aldhafiri-navy.png" },
] as const;

export const mediaVideos = [
  {
    src: "/media/sabeq-khalifa-01.mp4",
    poster: "/media/sabeq-khalifa-01.jpg",
    title: "المحامي د. خليفة محمد الخليفة",
  },
  {
    src: "/media/sabeq-hamad-01.mp4",
    poster: "/media/sabeq-hamad-01.jpg",
    title: "المحامي حمد الماضي",
  },
  {
    src: "/media/sabeq-reel-dadhmiwgyuj.mp4",
    poster: "/media/sabeq-reel-dadhmiwgyuj.jpg",
    title: "المحامي مشعل متعب",
  },
  {
    src: "/media/sabeq-reel-dasqk7vabcy.mp4",
    poster: "/media/sabeq-reel-dasqk7vabcy.jpg",
    title: "المحامي خالد الحزيم",
  },
  {
    src: "/media/sabeq-reel-daaoyxdg64h.mp4",
    poster: "/media/sabeq-reel-daaoyxdg64h.jpg",
    title: "المحامي مشعل متعب — أخصائي إفصاح معتمد",
  },
  {
    src: "/media/sabeq-reel-dzujidwgtzt.mp4",
    poster: "/media/sabeq-reel-dzujidwgtzt.jpg",
    title: "المحامي د. خليفة محمد الخليفة",
  },
  {
    src: "/media/sabeq-reel-dxhpbxjqhdf.mp4",
    poster: "/media/sabeq-reel-dxhpbxjqhdf.jpg",
    title: "توعية قانونية من سابق القانونية",
  },
] as const;

export const copy = {
  ar: {
    dir: "rtl" as const,
    label: "العربية",
    brand: "مجموعة سابق القانونية",
    nav: ["الرئيسية", "فريقنا", "خدماتنا", "سابق ميديا", "لماذا نحن", "تواصل معنا"],
    heroTitle: "حلول قانونية متطورة",
    heroAccent: "وخدمات احترافية",
    heroText: "خبرة قانونية راسخة تلتقي بالتقنية الحديثة لحماية حقوقك وصناعة حلول دقيقة لكل قضية.",
    book: "احجز استشارتك الآن",
    memo: "محرك توليد المذكرات",
    assistant: "المساعد القانوني",
    library: "مكتبة التشريعات الكويتية",
    trust: ["سرية تامة", "خبرة قانونية", "تقنيات حديثة"],
    teamKicker: "الخبرة التي تقف إلى جانبك",
    teamTitle: "فريقنا القانوني",
    teamText: "نخبة من المحامين يجمعهم الالتزام بالدقة والمهنية وحماية مصالح موكلينا.",
    memoKicker: "صياغة مدعومة بقاعدة قانونية موثقة",
    memoTitle: "محرك توليد المذكرات القانونية",
    memoText: "نظام متطور يولد مذكرات قانونية احترافية مبنية على مبادئ قانونية مستقرة من مختلف أنواع القضايا.",
    memoFeatures: [
      ["صياغة قضائية محكمة ودقيقة", "مذكرات مصاغة بلغة قانونية دقيقة ومحكمة حسب معايير المحاكم."],
      ["استناد قانوني قوي ومصادر موثقة", "يبنى الاستدلال من النصوص السليمة مع إظهار مصدر كل سند بوضوح."],
      ["رفع ملفات القضية واستخراج محتواها", "تحليل المستندات واستخراج المعلومات القانونية اللازمة للصياغة."],
    ],
    memoStart: "ابدأ إعداد المذكرة",
    arabicOnly: "تُولد المذكرة النهائية بالعربية حصراً",
    servicesKicker: "خدمات قانونية متكاملة",
    servicesTitle: "خبرة متخصصة لكل مسألة",
    services: [
      ["القضايا المدنية والتجارية", "نقدم استشارات قانونية متخصصة في القضايا المدنية والتجارية بخبرة عالية وكفاءة مثبتة."],
      ["قضايا الأحوال الشخصية", "نساعدك في حل قضايا الأحوال الشخصية بحساسية واحترافية تامة."],
      ["القضايا الجزائية", "دفاع قوي وتمثيل قانوني محكم في جميع أنواع القضايا الجزائية."],
      ["القضايا الإدارية", "خبرة واسعة في التعامل مع القضايا الإدارية والطعون الحكومية."],
    ],
    packagesKicker: "اختر الخدمة الأنسب",
    packagesTitle: "حلول واضحة لاحتياجك القانوني",
    packages: [
      ["استشارة سريعة", "استشارة فورية عبر الهاتف أو واتساب", ["الرد خلال 24 ساعة", "إجابة موجزة ومركزة", "مدة 15 دقيقة"]],
      ["استشارة موسعة", "استشارة تفصيلية مع مراجعة المستندات", ["مدة 30–45 دقيقة", "مراجعة المستندات الأساسية", "خطة قانونية أولية"]],
      ["محرك المذكرات", "إعداد مذكرة قانونية منظمة ومدعومة بالمصادر", ["مبادئ قانونية مستقرة", "صياغة قضائية محكمة", "حفظ وتنزيل المذكرة"]],
      ["مكتبة الصيغ القانونية", "نماذج عملية قابلة للتخصيص", ["صيغ متنوعة ومحدثة", "تخصيص سريع", "نسخ أو تحميل"]],
    ],
    choose: "اختر الخدمة",
    mediaKicker: "معرفة قانونية مرئية",
    mediaTitle: "سابق ميديا",
    mediaText: "محتوى قانوني توعوي من فريق العمل في سابق القانونية",
    watch: "شاهد على إنستغرام",
    allMedia: "عرض جميع فيديوهات سابق",
    whyKicker: "لماذا تختارنا؟",
    whyTitle: "منهج قانوني يصنع الفارق",
    whyText: "مكتب محاماة واستشارات قانونية متخصص، يجمع بين العمق المعرفي والخبرة العملية الواسعة، لتقديم حلول قانونية متكاملة تحقق العدالة وتحمي الحقوق في مختلف المجالات القانونية.",
    why: [
      ["منهجية قانونية دقيقة", "ندرس كل قضية من جميع جوانبها، ونبني الرأي والإجراء على تحليل منظم ونصوص قانونية موثقة."],
      ["خبرة واسعة ومتنوعة", "خبرات متكاملة في القضايا المدنية والتجارية والجزائية والإدارية والأحوال الشخصية."],
      ["سرية ومصداقية تامة", "نحمي خصوصية موكلينا ونتعامل مع المعلومات والمستندات وفق أعلى درجات السرية."],
      ["متابعة دقيقة ونتائج فعالة", "نواكب تطورات الملف، ونوضح الخطوات والخيارات للوصول إلى أفضل نتيجة قانونية ممكنة."],
    ],
    experience: "عاماً من الخبرة القانونية",
    contactKicker: "نحن هنا لمساعدتك",
    contactTitle: "تواصل معنا",
    contactText: "أرسل تفاصيل استفسارك، وسيعاود فريقنا التواصل معك بسرية تامة.",
    phone: "الهاتف",
    whatsapp: "واتساب",
    email: "البريد الإلكتروني",
    address: "العنوان",
    addressText: "القبلة - شارع مبارك الكبير، برج علي حسين مكي الجمعة - الدور الخامس",
    hours: "ساعات العمل",
    hoursText: "الأحد - الخميس، 5:00 مساءً - 8:00 مساءً",
    map: "عرض الموقع على الخريطة",
    form: { name: "الاسم الكامل", email: "البريد الإلكتروني", phone: "رقم الهاتف", subject: "الموضوع", message: "اكتب رسالتك", send: "إرسال الرسالة" },
    footer: "حلول قانونية متكاملة تجمع بين الخبرة المهنية والتقنية الحديثة.",
    rights: "جميع الحقوق محفوظة",
    quick: "روابط سريعة",
    bookingTitle: "حجز استشارة قانونية",
    bookingText: "اترك بياناتك وسيتواصل معك فريقنا لتحديد الموعد المناسب.",
    preferred: "وسيلة التواصل المفضلة",
    submitBooking: "طلب موعد",
    assistantWelcome: "مرحباً بك. اكتب سؤالك عن القانون الكويتي، وسأبحث في المصادر القانونية المتاحة مع بيان المرجع.",
    assistantPlaceholder: "اكتب سؤالك القانوني...",
    disclaimer: "معلومات إرشادية لا تغني عن استشارة محامٍ بعد مراجعة وقائع القضية.",
    libraryText: "ابحث في التشريعات الكويتية الموثقة حسب العنوان أو رقم القانون أو الموضوع.",
    searchPlaceholder: "مثال: قانون العمل أو التعويض...",
    search: "بحث",
    emptySearch: "ابدأ بكتابة كلمة أو موضوع قانوني.",
    memoModal: "إعداد مذكرة قانونية",
    steps: ["بيانات القضية", "الوقائع والطلبات والمستندات", "البحث القانوني", "المراجعة والتوليد"],
    next: "التالي",
    previous: "السابق",
    generate: "توليد المذكرة العربية",
    caseType: "نوع القضية",
    clientName: "الاسم الكامل",
    court: "المحكمة",
    otherParty: "اسم الخصم أو الطرف الآخر",
    role: "صفته في الدعوى",
    facts: "وقائع القضية",
    requests: "الطلبات",
    issues: "المسائل القانونية المطلوب بحثها",
    review: "راجع المعلومات قبل التوليد",
    privacy: "لن ننشر مستنداتك أو تفاصيل قضيتك.",
    caseTypes: ["مدني", "تجاري", "جزائي", "أحوال شخصية", "إداري", "عمالي", "عقاري", "عسكري"],
    courts: ["الكلية", "الاستئناف", "التمييز", "الدستورية", "الأسرة", "الإدارية", "التجارية", "العسكرية"],
    roles: ["مدعي", "مدعى عليه", "أخرى"],
    loading: "جارٍ التنفيذ...",
    sent: "تم استلام طلبك بنجاح.",
    error: "تعذر تنفيذ الطلب الآن. يرجى المحاولة مجدداً.",
  },
  en: {
    dir: "ltr" as const,
    label: "English",
    brand: "Sabeq Legal Group",
    nav: ["Home", "Our team", "Services", "Sabeq Media", "Why Sabeq", "Contact"],
    heroTitle: "Advanced legal solutions",
    heroAccent: "delivered professionally",
    heroText: "Established legal experience meets modern technology to protect your rights and build a precise strategy for every matter.",
    book: "Book a consultation",
    memo: "Legal memo engine",
    assistant: "Legal assistant",
    library: "Kuwaiti legislation library",
    trust: ["Strict confidentiality", "Legal experience", "Modern technology"],
    teamKicker: "Experience on your side",
    teamTitle: "Our legal team",
    teamText: "A team of lawyers united by accuracy, professionalism, and the protection of our clients’ interests.",
    memoKicker: "Drafting grounded in verified legal sources",
    memoTitle: "Legal memorandum generator",
    memoText: "An advanced system for drafting professional legal memoranda grounded in established legal principles across different case types.",
    memoFeatures: [
      ["Precise judicial drafting", "Structured legal language aligned with the standards of court submissions."],
      ["Strong, traceable legal grounding", "Built from verified legal texts, with every supporting source shown clearly."],
      ["Case-file content extraction", "Analyse documents and extract the information needed to prepare the memorandum."],
    ],
    memoStart: "Start a memorandum",
    arabicOnly: "The final memorandum is always generated in Arabic",
    servicesKicker: "Integrated legal services",
    servicesTitle: "Specialised experience for every matter",
    services: [
      ["Civil and commercial cases", "Specialised advice and representation in civil and commercial matters, backed by proven experience."],
      ["Personal status cases", "Sensitive, professional support for personal status and family matters."],
      ["Criminal cases", "Strong defence and precise representation across criminal proceedings."],
      ["Administrative cases", "Broad experience in administrative disputes and challenges involving public authorities."],
    ],
    packagesKicker: "Choose the right service",
    packagesTitle: "Clear solutions for your legal need",
    packages: [
      ["Quick consultation", "An immediate phone or WhatsApp consultation", ["Response within 24 hours", "Concise, focused answer", "15 minutes"]],
      ["Extended consultation", "Detailed consultation with document review", ["30–45 minutes", "Review of key documents", "Initial legal plan"]],
      ["Memo generator", "A structured legal memorandum supported by sources", ["Established legal principles", "Court-ready drafting", "Save and download"]],
      ["Legal forms library", "Practical, customisable legal templates", ["Varied and updated forms", "Quick customisation", "Copy or download"]],
    ],
    choose: "Choose service",
    mediaKicker: "Visual legal knowledge",
    mediaTitle: "Sabeq Media",
    mediaText: "Legal awareness content from the Sabeq Legal team.",
    watch: "Watch on Instagram",
    allMedia: "View all Sabeq videos",
    whyKicker: "Why choose us?",
    whyTitle: "A legal method that makes a difference",
    whyText: "A specialised law and legal consultancy practice combining deep legal knowledge with broad practical experience to deliver integrated solutions that uphold justice and protect rights.",
    why: [
      ["Precise legal methodology", "We examine every matter from all angles and ground each opinion and action in structured analysis and verified legal texts."],
      ["Broad, diverse experience", "Integrated experience across civil, commercial, criminal, administrative, and personal status matters."],
      ["Complete confidentiality and trust", "We protect client privacy and handle information and documents with the highest degree of confidentiality."],
      ["Close follow-up and effective results", "We track developments and explain the available steps and options to pursue the best possible legal outcome."],
    ],
    experience: "years of legal experience",
    contactKicker: "We are here to help",
    contactTitle: "Contact us",
    contactText: "Send us the details of your enquiry and our team will contact you in complete confidence.",
    phone: "Phone", whatsapp: "WhatsApp", email: "Email", address: "Address",
    addressText: "Al-Qibla, Mubarak Al-Kabeer Street, Ali Hussein Maki Al-Juma Tower, 5th floor",
    hours: "Working hours", hoursText: "Sunday–Thursday, 5:00 PM–8:00 PM", map: "View on map",
    form: { name: "Full name", email: "Email", phone: "Phone number", subject: "Subject", message: "Write your message", send: "Send message" },
    footer: "Integrated legal solutions combining professional experience with modern technology.",
    rights: "All rights reserved", quick: "Quick links",
    bookingTitle: "Book a legal consultation", bookingText: "Leave your details and our team will contact you to arrange a suitable time.",
    preferred: "Preferred contact method", submitBooking: "Request appointment",
    assistantWelcome: "Welcome. Ask about Kuwaiti law and I will search the available legal sources and identify the supporting reference.",
    assistantPlaceholder: "Type your legal question...", disclaimer: "General guidance only; it does not replace advice from a lawyer who has reviewed the facts.",
    libraryText: "Search verified Kuwaiti legislation by title, law number, or subject.", searchPlaceholder: "Example: labour law or compensation...", search: "Search", emptySearch: "Enter a keyword or legal topic to begin.",
    memoModal: "Prepare a legal memorandum", steps: ["Case details", "Facts, requests and documents", "Legal research", "Review and generate"],
    next: "Next", previous: "Previous", generate: "Generate Arabic memorandum", caseType: "Case type", clientName: "Full name", court: "Court", otherParty: "Other party’s name", role: "Role in proceedings", facts: "Case facts", requests: "Requested relief", issues: "Legal issues to research", review: "Review the information before generation", privacy: "We do not publish your documents or case details.",
    caseTypes: ["Civil", "Commercial", "Criminal", "Personal status", "Administrative", "Labour", "Real estate", "Military"],
    courts: ["Court of First Instance", "Court of Appeal", "Court of Cassation", "Constitutional Court", "Family Court", "Administrative Court", "Commercial Court", "Military Court"],
    roles: ["Claimant", "Defendant", "Other"], loading: "Processing...", sent: "Your request has been received.", error: "The request could not be completed. Please try again.",
  },
  ur: {
    dir: "rtl" as const,
    label: "اردو",
    brand: "Sabeq Legal Group",
    nav: ["ہوم", "ہماری ٹیم", "خدمات", "سابق میڈیا", "سابق کیوں", "رابطہ"],
    heroTitle: "جدید قانونی حل",
    heroAccent: "اور پیشہ ورانہ خدمات",
    heroText: "آپ کے حقوق کے تحفظ اور ہر مقدمے کے لیے درست حکمتِ عملی بنانے کے لیے گہرا قانونی تجربہ اور جدید ٹیکنالوجی۔",
    book: "مشاورت بُک کریں", memo: "قانونی یادداشت کا نظام", assistant: "قانونی معاون", library: "کویتی قوانین کی لائبریری",
    trust: ["مکمل رازداری", "قانونی تجربہ", "جدید ٹیکنالوجی"],
    teamKicker: "تجربہ آپ کے ساتھ", teamTitle: "ہماری قانونی ٹیم", teamText: "درستگی، پیشہ ورانہ معیار اور موکلین کے مفادات کے تحفظ کے لیے متحد وکلاء کی ٹیم۔",
    memoKicker: "مصدقہ قانونی ذرائع پر مبنی تحریر", memoTitle: "قانونی یادداشت تیار کرنے کا نظام", memoText: "مختلف مقدمات کے لیے مستحکم قانونی اصولوں پر مبنی پیشہ ورانہ قانونی یادداشتیں تیار کرنے والا جدید نظام۔",
    memoFeatures: [["درست عدالتی تحریر", "عدالتی معیار کے مطابق منظم اور مضبوط قانونی زبان۔"], ["قابلِ تصدیق قانونی بنیاد", "مصدقہ قانونی متن پر مبنی، اور ہر حوالہ واضح طور پر دکھایا جاتا ہے۔"], ["کیس فائل سے معلومات کا اخراج", "دستاویزات کا تجزیہ کرکے یادداشت کے لیے ضروری معلومات اخذ کرنا۔"]],
    memoStart: "یادداشت تیار کریں", arabicOnly: "حتمی قانونی یادداشت ہمیشہ عربی میں تیار ہوگی",
    servicesKicker: "مکمل قانونی خدمات", servicesTitle: "ہر معاملے کے لیے مخصوص تجربہ",
    services: [["دیوانی اور تجارتی مقدمات", "ثابت شدہ تجربے کے ساتھ دیوانی اور تجارتی معاملات میں خصوصی مشورہ اور نمائندگی۔"], ["عائلی قوانین کے مقدمات", "خاندانی اور ذاتی حیثیت کے معاملات میں حساس اور پیشہ ورانہ معاونت۔"], ["فوجداری مقدمات", "فوجداری کارروائیوں میں مضبوط دفاع اور محتاط قانونی نمائندگی۔"], ["انتظامی مقدمات", "سرکاری اداروں سے متعلق انتظامی تنازعات اور اپیلوں میں وسیع تجربہ۔"]],
    packagesKicker: "مناسب خدمت منتخب کریں", packagesTitle: "آپ کی قانونی ضرورت کے لیے واضح حل",
    packages: [["فوری مشاورت", "فون یا واٹس ایپ پر فوری قانونی مشورہ", ["24 گھنٹے میں جواب", "مختصر اور واضح جواب", "15 منٹ"]], ["تفصیلی مشاورت", "دستاویزات کے جائزے کے ساتھ تفصیلی مشورہ", ["30–45 منٹ", "اہم دستاویزات کا جائزہ", "ابتدائی قانونی منصوبہ"]], ["یادداشت کا نظام", "ذرائع کے ساتھ منظم قانونی یادداشت", ["مستحکم قانونی اصول", "عدالتی معیار کی تحریر", "محفوظ اور ڈاؤن لوڈ"]], ["قانونی نمونوں کی لائبریری", "حسبِ ضرورت عملی قانونی نمونے", ["متنوع اور تازہ نمونے", "فوری تخصیص", "کاپی یا ڈاؤن لوڈ"]]],
    choose: "خدمت منتخب کریں",
    mediaKicker: "بصری قانونی آگاہی", mediaTitle: "سابق میڈیا", mediaText: "سابق لیگل کی ٹیم کی جانب سے قانونی آگاہی کا مواد۔", watch: "انسٹاگرام پر دیکھیں", allMedia: "سابق کی تمام ویڈیوز دیکھیں",
    whyKicker: "ہمیں کیوں منتخب کریں؟", whyTitle: "نتیجہ خیز قانونی طریقۂ کار", whyText: "ایک خصوصی قانونی دفتر جو گہرے قانونی علم اور وسیع عملی تجربے کو یکجا کرکے ایسے مکمل حل فراہم کرتا ہے جو انصاف اور حقوق کی حفاظت کریں۔",
    why: [["درست قانونی طریقۂ کار", "ہر مقدمے کا ہر زاویے سے جائزہ، منظم تجزیہ اور مصدقہ قانونی متن۔"], ["وسیع اور متنوع تجربہ", "دیوانی، تجارتی، فوجداری، انتظامی اور عائلی معاملات میں جامع تجربہ۔"], ["مکمل رازداری اور اعتماد", "موکل کی رازداری، معلومات اور دستاویزات کا اعلیٰ ترین تحفظ۔"], ["قریب سے پیروی اور مؤثر نتائج", "پیش رفت کی نگرانی اور دستیاب قانونی اقدامات کی واضح تشریح۔"]],
    experience: "سال کا قانونی تجربہ", contactKicker: "ہم مدد کے لیے موجود ہیں", contactTitle: "ہم سے رابطہ کریں", contactText: "اپنی قانونی استفسار کی تفصیل بھیجیں؛ ہماری ٹیم مکمل رازداری کے ساتھ رابطہ کرے گی۔",
    phone: "فون", whatsapp: "واٹس ایپ", email: "ای میل", address: "پتہ", addressText: "القبلہ، شارع مبارک الکبیر، برج علی حسین مکی الجمعہ، پانچویں منزل", hours: "اوقاتِ کار", hoursText: "اتوار تا جمعرات، شام 5:00 تا 8:00", map: "نقشے پر مقام دیکھیں",
    form: { name: "پورا نام", email: "ای میل", phone: "فون نمبر", subject: "موضوع", message: "اپنا پیغام لکھیں", send: "پیغام بھیجیں" },
    footer: "پیشہ ورانہ تجربے اور جدید ٹیکنالوجی پر مبنی مکمل قانونی حل۔", rights: "جملہ حقوق محفوظ ہیں", quick: "فوری روابط",
    bookingTitle: "قانونی مشاورت بُک کریں", bookingText: "اپنی معلومات دیں؛ ہماری ٹیم مناسب وقت طے کرنے کے لیے رابطہ کرے گی۔", preferred: "رابطے کا پسندیدہ ذریعہ", submitBooking: "وقت کی درخواست",
    assistantWelcome: "خوش آمدید۔ کویتی قانون کے بارے میں سوال لکھیں؛ دستیاب قانونی ذرائع میں تلاش کرکے حوالہ دکھایا جائے گا۔", assistantPlaceholder: "اپنا قانونی سوال لکھیں...", disclaimer: "یہ عمومی رہنمائی ہے؛ حقائق دیکھنے والے وکیل کے مشورے کا متبادل نہیں۔",
    libraryText: "عنوان، قانون نمبر یا موضوع کے ذریعے مصدقہ کویتی قوانین تلاش کریں۔", searchPlaceholder: "مثال: قانونِ محنت یا معاوضہ...", search: "تلاش", emptySearch: "تلاش شروع کرنے کے لیے قانونی موضوع لکھیں۔",
    memoModal: "قانونی یادداشت تیار کریں", steps: ["مقدمے کی تفصیل", "حقائق، مطالبات اور دستاویزات", "قانونی تحقیق", "جائزہ اور تیاری"], next: "اگلا", previous: "پچھلا", generate: "عربی یادداشت تیار کریں", caseType: "مقدمے کی قسم", clientName: "پورا نام", court: "عدالت", otherParty: "دوسرے فریق کا نام", role: "مقدمے میں حیثیت", facts: "مقدمے کے حقائق", requests: "مطالبات", issues: "تحقیق کے قانونی نکات", review: "تیاری سے پہلے معلومات کا جائزہ لیں", privacy: "ہم آپ کی دستاویزات یا مقدمے کی تفصیل شائع نہیں کرتے۔",
    caseTypes: ["دیوانی", "تجارتی", "فوجداری", "عائلی", "انتظامی", "محنت", "جائیداد", "فوجی"], courts: ["ابتدائی عدالت", "اپیل عدالت", "عدالتِ تمییز", "آئینی عدالت", "خاندانی عدالت", "انتظامی عدالت", "تجارتی عدالت", "فوجی عدالت"], roles: ["مدعی", "مدعا علیہ", "دیگر"], loading: "کارروائی جاری ہے...", sent: "آپ کی درخواست موصول ہوگئی ہے۔", error: "درخواست مکمل نہیں ہوسکی۔ دوبارہ کوشش کریں۔",
  },
} as const;

export type SiteCopy = (typeof copy)[Language];
