const seed=[
{id:'r1',title:'SaaS founder seeking wealth and complexity control',source:'Reddit',country:'Australia',sector:'SaaS',pain:'Founder complexity after rapid wealth creation: investments, property, liquidity and decision overload.',capacity:'High',authority:'Founder / sole owner',urgency:78,fit:92,evidence:82,score:88,stage:'review',url:'https://www.reddit.com/r/fatFIRE/comments/1ohvyu5/no_one_to_tell_hit_5m_at_29/',linkedin:'',company:'',solution:'Executive Wealth & Business Intelligence Dashboard',message:'Hi — I read your post about the complexity that comes after building a successful SaaS business. I work on AI systems that consolidate business, asset and decision information into one private dashboard. I am not trying to sell you something blindly; I would be interested in understanding which part of the complexity is most costly for you right now. If useful, I can outline a simple decision system based on what you already described.',notes:'Identity not inferred. Contact only through channels voluntarily published by the account.'},
{id:'r2',title:'UK tech co-founder considering exit after PE investment',source:'Reddit',country:'United Kingdom',sector:'Technology',pain:'Founder wants to reduce or exit her operating role while PE and company growth create legal, financial and M&A complexity.',capacity:'Very High',authority:'Co-founder / shareholder',urgency:91,fit:89,evidence:90,score:91,stage:'review',url:'https://www.reddit.com/r/fatFIRE/comments/10sx47h/',linkedin:'',company:'',solution:'Founder Exit Intelligence + M&A Readiness Workspace',message:'Hi — your post about balancing an exit, PE expectations and the next 18 months stood out because the problem is less about one decision and more about coordinating legal, financial and operating information. I build decision systems for exactly that kind of complexity. If you are still dealing with this, I can share a concise framework for mapping the options, dependencies and risks before any outreach to advisers.',notes:'Do not attempt to identify the anonymous poster from private clues.'},
{id:'r3',title:'Fintech CFO building independent cross-border wealth strategy',source:'Reddit',country:'Asia / potential Dubai',sector:'Fintech',pain:'Personal financial independence, cross-border planning and family wealth complexity despite high household net worth.',capacity:'High',authority:'CFO',urgency:70,fit:75,evidence:83,score:79,stage:'new',url:'https://www.reddit.com/r/fatFIRE/comments/1358opq/',linkedin:'',company:'',solution:'Cross-border Private Wealth Decision Dashboard',message:'Hi — I saw your post about building personal financial independence while evaluating a potential move to Dubai. The cross-border part creates a decision problem across tax, investments, residency and family priorities. I work on private AI decision dashboards that organize those inputs before specialist advice is taken. If the issue is still relevant, I can show you the structure without needing any sensitive financial data.',notes:'Use professional public channels only if the user voluntarily discloses them.'}
];
let leads=JSON.parse(localStorage.getItem('leadIntel.leads')||'null')||seed;
let selected=leads[0]?.id||null;
const stages={new:'جديد',review:'مراجعة',approved:'موافق عليه',contacted:'تم التواصل',qualified:'فرصة مؤهلة'};
function save(){localStorage.setItem('leadIntel.leads',JSON.stringify(leads));}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function calc(l){return Math.round((Number(l.urgency||0)*.25)+(Number(l.fit||0)*.35)+(Number(l.evidence||0)*.2)+((l.capacity==='Very High'?100:l.capacity==='High'?85:60)*.2));}
function filtered(){const q=document.getElementById('q').value.trim().toLowerCase(),src=document.getElementById('source').value,st=document.getElementById('stage').value;return leads.filter(l=>(src==='all'||l.source===src)&&(st==='all'||l.stage===st)&&(!q||[l.title,l.country,l.sector,l.pain,l.solution,l.company].join(' ').toLowerCase().includes(q)));}
function render(){leads.forEach(l=>l.score=calc(l));save();document.getElementById('kAll').textContent=leads.length;document.getElementById('kHot').textContent=leads.filter(l=>l.score>=85).length;document.getElementById('kApproval').textContent=leads.filter(l=>l.stage==='review').length;document.getElementById('kContacted').textContent=leads.filter(l=>l.stage==='contacted').length;document.getElementById('kWon').textContent=leads.filter(l=>l.stage==='qualified').length;
const rows=filtered();document.getElementById('leadList').innerHTML=rows.length?rows.sort((a,b)=>b.score-a.score).map(l=>`<article class="lead" data-id="${l.id}"><div class="lead-head"><div><h3>${esc(l.title)}</h3><div class="meta">${esc(l.source)} · ${esc(l.country)} · ${esc(l.sector)} · ${esc(stages[l.stage])}</div><div class="pain">${esc(l.pain)}</div><div class="tags"><span class="tag">${esc(l.authority)}</span><span class="tag">قدرة شرائية: ${esc(l.capacity)}</span><span class="tag">${esc(l.solution)}</span></div></div><div class="score">${l.score}</div></div></article>`).join(''):'<div class="empty">لا توجد فرص مطابقة</div>';
document.querySelectorAll('.lead').forEach(el=>el.onclick=()=>{selected=el.dataset.id;renderDetail();});renderDetail();}
function renderDetail(){const l=leads.find(x=>x.id===selected);const d=document.getElementById('detail');if(!l){d.innerHTML='<div class="empty">اختر فرصة</div>';return;}const pipeline=['new','review','approved','contacted','qualified'];d.innerHTML=`<h2>${esc(l.title)}</h2><div class="meta">Lead Score: <b>${l.score}/100</b> · ${esc(l.source)} · ${esc(l.country)}</div><div class="pipeline section">${pipeline.map(s=>`<div class="stage ${s===l.stage?'active':''}">${stages[s]}</div>`).join('')}</div><div class="section"><h4>المشكلة المكتشفة</h4><div class="pain">${esc(l.pain)}</div></div><div class="section"><h4>تحليل AI</h4><div class="tags"><span class="tag">Urgency ${l.urgency}</span><span class="tag">Solution fit ${l.fit}</span><span class="tag">Evidence ${l.evidence}</span><span class="tag">Buying capacity ${esc(l.capacity)}</span></div><p>${esc(l.solution)}</p></div><div class="section"><h4>المصادر العامة</h4><div class="source-links">${l.url?`<a target="_blank" rel="noopener" href="${esc(l.url)}">فتح المصدر</a>`:''}${l.linkedin?`<a target="_blank" rel="noopener" href="${esc(l.linkedin)}">LinkedIn</a>`:''}${l.company?`<a target="_blank" rel="noopener" href="${esc(l.company)}">موقع الشركة</a>`:''}</div></div><div class="section"><h4>رسالة التواصل المقترحة</h4><textarea id="msg" class="message">${esc(l.message)}</textarea><div class="approval"><button class="btn good" id="approve">✓ أوافق</button><button class="btn warn" id="contacted">تم التواصل</button><button class="btn danger" id="reject">رفض</button></div></div><div class="section notice">قاعدة النظام: لا يتم كشف هوية حساب مجهول أو استنتاج بيانات شخصية غير منشورة. الانتقال إلى LinkedIn أو البريد يتم فقط عندما يكون الرابط أو اسم الشركة منشوراً علناً أو يقدمه صاحب الحساب بنفسه.</div><div class="section"><h4>ملاحظات التدقيق</h4><div class="pain">${esc(l.notes)}</div></div>`;
document.getElementById('msg').onchange=e=>{l.message=e.target.value;save();};document.getElementById('approve').onclick=()=>{l.stage='approved';save();render();};document.getElementById('contacted').onclick=()=>{l.stage='contacted';save();render();};document.getElementById('reject').onclick=()=>{l.stage='new';save();render();};}
function addLead(){const title=prompt('عنوان الفرصة أو اسم الشركة:');if(!title)return;const source=prompt('المصدر: Reddit / LinkedIn / Web','Web')||'Web';const url=prompt('رابط المصدر العام:','')||'';const pain=prompt('ما المشكلة التي تبحث عن حل لها؟','')||'';const sector=prompt('القطاع:','Business')||'Business';const country=prompt('البلد:','')||'';const l={id:'l'+Date.now(),title,source,country,sector,pain,capacity:'High',authority:'Decision maker',urgency:70,fit:80,evidence:65,stage:'review',url,linkedin:'',company:'',solution:'AI-assisted business solution',message:`Hi — I came across your public post about ${pain||'the challenge you described'}. I work on practical AI and automation systems for business problems. If this is still relevant, I can share a concise approach focused on the problem you raised.`,notes:'Manually added lead. Verify evidence before outreach.'};leads.push(l);selected=l.id;render();}
['q','source','stage'].forEach(id=>document.getElementById(id).addEventListener(id==='q'?'input':'change',render));document.getElementById('addLead').onclick=addLead;render();