(() => {
  'use strict';
  const API='https://sabeq-legal-research-api.onrender.com';
  const key='sabeq-admin-session';let token=sessionStorage.getItem(key)||'';
  const message=document.getElementById('admin-message');
  const form=document.getElementById('settings-form');
  function h(tag,text){const node=document.createElement(tag);if(text!=null)node.textContent=text;return node;}
  async function api(path,body,method){const response=await fetch(API+path,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(35000)});const data=await response.json();if(!response.ok){const error=new Error(data.error||'تعذر تنفيذ الطلب.');error.status=response.status;throw error;}return data;}
  function act(text,handler){const b=h('button',text);b.type='button';b.className='sc-secondary';b.addEventListener('click',async()=>{b.disabled=true;message.textContent='';try{await handler();}catch(error){message.textContent=error.message;}finally{b.disabled=false;}});return b;}
  function table(host,headers,rows){host.replaceChildren();if(!rows.length){host.append(h('p','لا توجد سجلات.'));return;}const table=h('table');const tr=h('tr');for(const title of headers)tr.append(h('th',title));const head=h('thead');head.append(tr);table.append(head);const body=h('tbody');for(const values of rows){const row=h('tr');for(const value of values){const cell=h('td');if(value instanceof Node)cell.append(value);else cell.textContent=String(value??'');row.append(cell);}body.append(row);}table.append(body);host.append(table);}
  const statuses={unpaid:'بانتظار الدفع',creating:'إنشاء عملية الدفع',pending:'بانتظار التأكيد',unknown:'تحتاج مراجعة',paid:'مدفوع',canceled:'ملغي',waiting:'بانتظار التوليد',queued:'بانتظار التوليد',processing:'جارٍ التوليد',completed:'مكتمل',failed:'تعذر التوليد',requested:'طلب جديد',reviewing:'قيد المراجعة',submitted_to_bank:'أُرسل إلى البنك',declined:'لم يُعتمد'};
  async function load(){
    const settings=await api('/api/admin/billing/settings');
    document.getElementById('admin-login').hidden=true;document.getElementById('admin-workspace').hidden=false;
    for(const[name,value]of Object.entries(settings.settings)){const input=form.elements.namedItem(name);if(!input)continue;if(input.type==='password'){input.value='';const label=form.querySelector('[data-secret="'+name+'"]');if(label)label.textContent=value?'قيمة محفوظة؛ اكتب قيمة جديدة للاستبدال.':'لم تُضف قيمة بعد.';}else input.value=Array.isArray(value)?value.join(','):value;}
    form.elements.priceDinars.value=(settings.settings.priceFils/1000).toFixed(3);
    document.getElementById('setup-status').textContent=[settings.storage.durable?'حفظ البيانات الدائم متصل.':'هذه بيئة تطوير محلية؛ يلزم حفظ دائم قبل الإنتاج.',settings.status.channels.length?'قنوات الإرسال المهيأة: '+settings.status.channels.map(x=>({email:'البريد',sms:'الرسائل النصية',whatsapp:'واتساب'})[x]).join('، '):'خدمة الإرسال تحتاج إلى إعداد.',settings.status.paymentReady?'متطلبات الدفع مهيأة؛ يلزم اختبار البوابة الفعلي.':'إعدادات الدفع غير مكتملة.',settings.status.environment==='test'?'الدفع في بيئة الاختبار.':'الدفع مضبوط على التشغيل الفعلي.'].join('\n');
    const results=await Promise.all([api('/api/admin/billing/orders'),api('/api/admin/billing/refunds'),api('/api/admin/billing/audit')]);
    table(document.getElementById('admin-orders'),['الطلب','العميل','المبلغ','الدفع','التوليد','الإجراء'],results[0].orders.map(o=>{const actions=h('div');actions.append(act('التحقق من الدفع',async()=>{await api('/api/admin/billing/orders/'+o.id+'/check-payment',{});await load();}));if(o.paymentStatus==='paid'&&o.generationStatus==='failed')actions.append(act('إعادة التوليد',async()=>{await api('/api/admin/billing/orders/'+o.id+'/retry',{});await load();}));return[o.id.slice(0,8),o.customer,(o.amountFils/1000).toFixed(3)+' د.ك',statuses[o.paymentStatus]||o.paymentStatus,statuses[o.generationStatus]||o.generationStatus,actions];}));
    table(document.getElementById('admin-refunds'),['الطلب','السبب','الحالة','مرجع البنك','المتابعة'],results[1].refunds.map(r=>{const controls=h('div');const select=h('select');for(const value of ['reviewing','submitted_to_bank','declined']){const option=h('option',statuses[value]);option.value=value;select.append(option);}select.value=['reviewing','submitted_to_bank','declined'].includes(r.status)?r.status:'reviewing';const ref=h('input');ref.placeholder='مرجع طلب البنك';ref.maxLength=200;ref.value=r.provider_reference||'';controls.append(select,ref,act('حفظ المتابعة',async()=>{await api('/api/admin/billing/refunds/'+r.id,{status:select.value,reference:ref.value},'PATCH');await load();}));return[r.order_id.slice(0,8),r.reason,statuses[r.status]||r.status,r.provider_reference||'—',controls];}));
    const actions={settings_updated:'تحديث الإعدادات',order_created:'إنشاء طلب',checkout_started:'بدء الدفع',payment_verified:'تأكيد الدفع',generation_started:'بدء التوليد',generation_completed:'اكتمال التوليد',generation_retry:'إعادة محاولة التوليد',refund_requested:'طلب مراجعة استرداد',refund_reviewed:'متابعة الاسترداد'};
    table(document.getElementById('admin-audit'),['الوقت','الإجراء','الطلب'],results[2].events.map(e=>[new Date(Number(e.created_at)).toLocaleString('ar-KW'),actions[e.action]||e.action,(e.order_id||'').slice(0,8)]));
  }
  async function enter(result){token=result.token;sessionStorage.setItem(key,token);try{await load();message.textContent='';}catch(error){token='';sessionStorage.removeItem(key);throw error;}}
  document.getElementById('bootstrap-form').addEventListener('submit',async event=>{event.preventDefault();const loginForm=event.currentTarget;const submit=loginForm.querySelector('button');submit.disabled=true;try{await enter(await api('/api/admin/billing/login',{secret:loginForm.elements.secret.value}));loginForm.reset();}catch(error){message.textContent=error.message;}finally{submit.disabled=false;}});
  document.getElementById('email-login').addEventListener('click',async()=>{try{await enter(await window.SabeqCommerce.login());}catch(error){message.textContent=error.message;}});
  form.addEventListener('submit',async event=>{event.preventDefault();const submit=form.querySelector('button[type=submit]');submit.disabled=true;try{const body=Object.fromEntries(new FormData(form));if(!/^\d+(?:\.\d{1,3})?$/.test(body.priceDinars))throw new Error('أدخل سعراً بحد أقصى ثلاث خانات عشرية.');body.priceFils=Math.round(Number(body.priceDinars)*1000);delete body.priceDinars;await api('/api/admin/billing/settings',body,'PUT');await load();message.textContent='تم حفظ الإعدادات بأمان.';}catch(error){message.textContent=error.message;}finally{submit.disabled=false;}});
  document.getElementById('admin-refresh').addEventListener('click',()=>load().catch(error=>{message.textContent=error.message;}));
  document.getElementById('admin-logout').addEventListener('click',async()=>{try{await api('/api/auth/logout',{});}catch(_){}token='';sessionStorage.removeItem(key);location.reload();});
  if(token)load().catch(error=>{message.textContent=error.message;token='';sessionStorage.removeItem(key);});
})();
