'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
type Station={id:string;nameAr:string;code:string};type SafeLocation={id:string;nameAr:string;code:string;capacity?:number;geofenceM:number};type Evacuation={id:string;status:string;employee:{fullNameAr:string;employeeNo:string}};type Incident={id:string;titleAr:string;type:string;severity:number;status:string;activatedAt:string;station:Station;evacuations:Evacuation[]};type AiResult={summary:string;riskLevel:string;findings:string[];recommendations:string[];requiresHumanReview:boolean;confidenceNote:string};
const shortName=(n:string)=>n.trim().split(/\s+/).slice(0,2).join(' ');const types=[['FIRE','حريق'],['EXPLOSION','انفجار'],['FUEL_LEAK','تسرب وقود'],['HAZARDOUS_MATERIAL','مواد خطرة'],['MEDICAL','حالة طبية'],['POWER_FAILURE','انقطاع كهرباء'],['OPERATIONAL_FAILURE','عطل تشغيلي'],['SECURITY','حادث أمني'],['NATURAL_DISASTER','كارثة طبيعية'],['EVACUATION','إخلاء'],['OTHER','أخرى']];
export default function EmergencyPage(){const api=process.env.NEXT_PUBLIC_API_URL!;const [stations,setStations]=useState<Station[]>([]);const [stationId,setStationId]=useState('');const [safe,setSafe]=useState<any>({assemblyPoints:[],shelters:[],criticalAssets:[]});const [incidents,setIncidents]=useState<Incident[]>([]);const [message,setMessage]=useState('');const [ai,setAi]=useState<AiResult|null>(null);const [aiLoading,setAiLoading]=useState('');const headers=()=>({Authorization:`Bearer ${window.localStorage.getItem('token')||''}`,'Content-Type':'application/json'});
async function load(){const[s,i]=await Promise.all([fetch(`${api}/stations`,{headers:headers()}),fetch(`${api}/emergency/incidents`,{headers:headers()})]);if(s.ok){const d=await s.json();setStations(d);if(!stationId&&d[0])setStationId(d[0].id)}if(i.ok)setIncidents(await i.json())}async function loadSafe(id:string){if(!id)return;const r=await fetch(`${api}/emergency/stations/${id}/safe-locations`,{headers:headers()});if(r.ok)setSafe(await r.json())}useEffect(()=>{load()},[]);useEffect(()=>{loadSafe(stationId)},[stationId]);
const active=useMemo(()=>incidents.filter(x=>x.status==='ACTIVE'),[incidents]);const totals=useMemo(()=>{const e=active.flatMap(x=>x.evacuations||[]);return{all:e.length,safe:e.filter(x=>x.status==='SAFE').length,transit:e.filter(x=>x.status==='IN_TRANSIT'||x.status==='DIRECTED').length,missing:e.filter(x=>x.status==='MISSING'||x.status==='NOT_CONFIRMED').length}},[active]);
async function post(path:string,body:any){setMessage('جارٍ الحفظ...');const r=await fetch(`${api}${path}`,{method:'POST',headers:headers(),body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(Array.isArray(d.message)?d.message.join('، '):d.message||'تعذر التنفيذ');return false}setMessage('تم التنفيذ بنجاح');await load();await loadSafe(stationId);return true}async function createIncident(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/emergency/incidents',{stationId,type:f.get('type'),titleAr:f.get('titleAr'),description:f.get('description'),severity:Number(f.get('severity')||1)}))e.currentTarget.reset()}async function createAssembly(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/emergency/assembly-points',{stationId,code:f.get('code'),nameAr:f.get('nameAr'),latitude:Number(f.get('latitude')),longitude:Number(f.get('longitude')),geofenceM:Number(f.get('geofenceM')||50),capacity:Number(f.get('capacity')||0)||undefined}))e.currentTarget.reset()}async function createShelter(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await post('/emergency/shelters',{stationId,code:f.get('code'),nameAr:f.get('nameAr'),shelterType:f.get('shelterType'),latitude:Number(f.get('latitude')),longitude:Number(f.get('longitude')),geofenceM:Number(f.get('geofenceM')||50),capacity:Number(f.get('capacity')||0)||undefined}))e.currentTarget.reset()}
async function analyze(path:string,key:string){setAiLoading(key);setAi(null);const r=await fetch(`${api}${path}`,{method:'POST',headers:headers(),body:'{}'});const d=await r.json().catch(()=>({}));setAiLoading('');if(!r.ok){setMessage(d.message||'تعذر تشغيل التحليل');return}setAi(d.result)}
return <main className="appMain"><section className="innerHero"><div><span className="eyebrow">منصة نطاق العمل</span><h1>مركز إدارة الطوارئ</h1><p>إدارة الحوادث ونقاط التجمع والملاجئ لجميع المنشآت</p></div><div className={`locationPill ${active.length?'pending':'ready'}`}>{active.length?`${active.length} حادث نشط`:'الوضع مستقر'}</div></section>{message&&<div className="notice">{message}</div>}
<div className="grid kpis statsGrid"><div className="card"><div>الحوادث النشطة</div><div className="metric">{active.length}</div></div><div className="card"><div>الموظفون المشمولون</div><div className="metric">{totals.all}</div></div><div className="card"><div>آمنون</div><div className="metric">{totals.safe}</div></div><div className="card"><div>في الطريق</div><div className="metric">{totals.transit}</div></div><div className="card"><div>غير مؤكدين</div><div className="metric">{totals.missing}</div></div></div>
<div className="card section"><h2>المنشأة الحالية</h2><select value={stationId} onChange={e=>setStationId(e.target.value)}>{stations.map(s=><option key={s.id} value={s.id}>{s.nameAr} — {s.code}</option>)}</select><button type="button" onClick={()=>analyze(`/ai/assets/station/${stationId}`,'assets')} disabled={!stationId||!!aiLoading}>{aiLoading==='assets'?'جارٍ تحليل الأصول...':'🤖 تحليل الأصول الحرجة'}</button></div>
<div className="grid forms"><form className="card" onSubmit={createIncident}><h2>إعلان حالة طوارئ</h2><input name="titleAr" placeholder="عنوان الحالة" required/><select name="type">{types.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select name="severity">{[1,2,3,4,5].map(x=><option key={x} value={x}>مستوى {x}{x===5?' — حرج':''}</option>)}</select><textarea name="description" placeholder="وصف الحالة"/><button>تفعيل الطوارئ</button></form><form className="card" onSubmit={createAssembly}><h2>إضافة نقطة تجمع</h2><input name="code" placeholder="الرمز" required/><input name="nameAr" placeholder="الاسم" required/><input name="latitude" type="number" step="any" placeholder="خط العرض" required/><input name="longitude" type="number" step="any" placeholder="خط الطول" required/><input name="geofenceM" type="number" defaultValue="50"/><input name="capacity" type="number" placeholder="السعة"/><button>حفظ</button></form><form className="card" onSubmit={createShelter}><h2>إضافة ملجأ</h2><input name="code" placeholder="الرمز" required/><input name="nameAr" placeholder="الاسم" required/><input name="shelterType" placeholder="النوع" required/><input name="latitude" type="number" step="any" required/><input name="longitude" type="number" step="any" required/><input name="geofenceM" type="number" defaultValue="50"/><input name="capacity" type="number" placeholder="السعة"/><button>حفظ</button></form></div>
<div className="grid section"><div className="card"><h2>نقاط التجمع</h2>{safe.assemblyPoints.map((x:any)=><div className="row" key={x.id}><span>{x.nameAr}</span><b>{x.capacity||'—'}</b></div>)}</div><div className="card"><h2>الملاجئ</h2>{safe.shelters.map((x:any)=><div className="row" key={x.id}><span>{x.nameAr}</span><b>{x.capacity||'—'}</b></div>)}</div><div className="card"><h2>الأصول الحرجة</h2>{safe.criticalAssets.map((x:any)=><div className="row" key={x.id}><span>{x.nameAr}</span><b>مستوى {x.riskLevel}</b></div>)}</div></div>
<div className="card section"><h2>الحوادث والإخلاء</h2>{incidents.length===0?<p className="muted">لا توجد حوادث.</p>:incidents.map(i=><div className="incident" key={i.id}><div className="incidentHead"><div><b>{i.titleAr}</b><div className="muted">{i.station.nameAr} — مستوى {i.severity}</div></div><span className={`badge ${i.status==='ACTIVE'?'badgeRed':'badgeGray'}`}>{i.status==='ACTIVE'?'نشط':'مغلق'}</span></div><div className="grid mini"><div>الإجمالي: <b>{i.evacuations.length}</b></div><div>آمنون: <b>{i.evacuations.filter(x=>x.status==='SAFE').length}</b></div><div>غير مؤكدين: <b>{i.evacuations.filter(x=>x.status==='NOT_CONFIRMED'||x.status==='MISSING').length}</b></div></div><button type="button" onClick={()=>analyze(`/ai/emergency/${i.id}`,i.id)} disabled={!!aiLoading}>{aiLoading===i.id?'جارٍ تحليل الحادث...':'🤖 تحليل الحادث'}</button>{i.evacuations.slice(0,20).map(e=><div className="row" key={e.id}><span>{shortName(e.employee.fullNameAr)} ({e.employee.employeeNo})</span><b>{statusLabel(e.status)}</b></div>)}</div>)}</div>
{ai&&<section className="card section aiResult"><div className="incidentHead"><h2>نتيجة الذكاء الاصطناعي</h2><span className="badge badgeGray">{ai.riskLevel}</span></div><p>{ai.summary}</p><h3>الملاحظات</h3><ul>{ai.findings.map((x,i)=><li key={i}>{x}</li>)}</ul><h3>التوصيات</h3><ul>{ai.recommendations.map((x,i)=><li key={i}>{x}</li>)}</ul>{ai.requiresHumanReview&&<div className="notice">تتطلب النتيجة مراجعة بشرية واعتماد المسؤول.</div>}<small className="muted">{ai.confidenceNote}</small></section>}
<nav className="mobileNav"><Link href="/dashboard">⌂<span>الرئيسية</span></Link><Link href="/attendance-smart">📍<span>الحضور</span></Link><Link href="/transfers">🚗<span>الانتقال</span></Link><Link href="/ai-tools">🤖<span>الذكاء</span></Link><Link href="/profile">👤<span>حسابي</span></Link></nav></main>}
function statusLabel(v:string){return({NOT_CONFIRMED:'غير مؤكد',DIRECTED:'تم التوجيه',IN_TRANSIT:'في الطريق',SAFE:'آمن',MISSING:'مفقود',INJURED:'مصاب',EXEMPT:'مستثنى'} as Record<string,string>)[v]||v}
