import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import OpenAI from 'openai';

const app = express();
const PORT = Number(process.env.PORT || 10000);
const JWT_SECRET = process.env.JWT_SECRET || 'tamweenat-dev-secret';
const ADMIN_USERNAME = process.env.ADMIN_USERNAME || 'admin';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'change-me';
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-5';
const REALTIME_MODEL = process.env.OPENAI_REALTIME_MODEL || 'gpt-realtime';
const allowedOrigins = (process.env.CORS_ORIGIN || 'https://q8-ux.github.io,http://localhost:3000,http://127.0.0.1:5500')
  .split(',').map(x=>x.trim()).filter(Boolean);

app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin(origin,cb){if(!origin||allowedOrigins.some(x=>origin.startsWith(x))) return cb(null,true); cb(new Error('CORS blocked'));}}));
app.use(express.json({limit:'1mb'}));
app.use(express.text({type:['application/sdp','text/plain'],limit:'2mb'}));

const now=()=>new Date().toISOString();
const rid=p=>`${p}_${crypto.randomBytes(5).toString('hex')}`;
const money=n=>Math.round((Number(n)||0)*1000)/1000;
const addDays=(d,n)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x.toISOString();};

const catalog=[
['chicken','دجاج مبرد','دواجن ولحوم','كجم',1.75],['rice','أرز بسمتي','أرز وحبوب','كجم',0.78],['oil','زيت قلي','زيوت','لتر',1.25],
['tomatoes','طماطم','خضار وفواكه','كجم',0.42],['onions','بصل','خضار وفواكه','كجم',0.35],['potatoes','بطاطا','خضار وفواكه','كجم',0.32],
['garlic','ثوم','خضار وفواكه','كجم',1.10],['lemons','ليمون','خضار وفواكه','كجم',0.55],['cucumbers','خيار','خضار وفواكه','كجم',0.48],
['flour','طحين','أساسيات','كجم',0.28],['sugar','سكر','أساسيات','كجم',0.31],['salt','ملح','أساسيات','كجم',0.16],
['spices','بهارات مشكلة','توابل','كجم',2.40],['cardamom','هيل','توابل','كجم',5.80],['chickpeas','حمص','بقوليات','كجم',0.66],
['eggs','بيض','ألبان وبيض','كرتون',12.5],['dairy','منتجات ألبان','ألبان وبيض','كرتون',9.75],['cheese','جبن','ألبان وبيض','كرتون',14.25],
['water','مياه','مشروبات','كرتون',1.2],['juice','عصائر','مشروبات','كرتون',3.6],['tea','شاي','مشروبات','كرتون',7],['coffee','قهوة','مشروبات','كرتون',18],
['cleaning','مواد تنظيف','تشغيل وتنظيف','كرتون',11.5],['canned','مواد معلبة','معلبات','كرتون',8.4],['frozen','خضروات مجمدة','مجمدات','كرتون',9.9]
].map(([id,name,category,unit,price])=>({id,name,category,unit,price,active:true}));

const store={restaurants:[],orders:[],invoices:[],payments:[],messages:[],audit:[],settings:{warningThreshold:.60,riskThreshold:.80,hardStopThreshold:1,defaultTermsDays:30}};
function audit(actor,action,target,details={}){store.audit.unshift({id:rid('aud'),at:now(),actor,action,target,details});store.audit=store.audit.slice(0,1000);}
function state(r){const usage=r.creditLimit? r.outstanding/r.creditLimit:0;const available=Math.max(0,money(r.creditLimit-r.outstanding));let level='safe',locked=false,reason='الحساب ضمن المستوى الآمن.';if(!r.active){level='locked';locked=true;reason='الحساب موقوف من الإدارة.';}else if(r.overdue>0){level='locked';locked=true;reason=`يوجد مبلغ متأخر ${money(r.overdue).toFixed(3)} د.ك.`;}else if(usage>=1){level='locked';locked=true;reason='تم بلوغ الحد الائتماني النهائي.';}else if(usage>=.8){level='risk';reason='استخدام الكريدت في مستوى الخطر.';}else if(usage>=.6){level='warning';reason='استخدام الكريدت تجاوز مستوى التنبيه.';}const health=Math.max(0,Math.min(100,Math.round(100-usage*35-(r.overdue>0?35:0)-Math.min(20,(r.latePayments||0)*4))));return{usage,available,level,locked,reason,health};}
function seed(){if(store.restaurants.length)return;const r1={id:'rest_001',code:'R-1001',name:'مطعم الديرة',legalName:'شركة مطعم الديرة',phone:'+96550000001',email:'accounts@aldira.example',address:'الكويت',branches:['القبلة','السالمية'],active:true,creditLimit:5000,outstanding:3800,overdue:0,termsDays:30,monthlyBudget:5200,monthSpend:3975,creditSpendMonth:2150,latePayments:0,createdAt:now(),users:[{id:'u_001',username:'restaurant1',password:'123456',name:'مدير المشتريات',role:'owner',active:true}]};const r2={id:'rest_002',code:'R-1002',name:'مطعم الساحة',legalName:'مطعم الساحة ذ.م.م',phone:'+96550000002',email:'finance@alsaha.example',address:'حولي',branches:['حولي'],active:true,creditLimit:8000,outstanding:7250,overdue:450,termsDays:15,monthlyBudget:9000,monthSpend:7100,creditSpendMonth:5100,latePayments:2,createdAt:now(),users:[{id:'u_002',username:'alsaha',password:'123456',name:'مسؤول المشتريات',role:'buyer',active:true}]};store.restaurants.push(r1,r2);store.orders.push({id:'ord_10567',number:'#10567',restaurantId:r1.id,createdAt:addDays(now(),-1),paymentMethod:'credit',total:245,status:'dispatched',items:[{productId:'oil',name:'زيت قلي',qty:40,unit:'لتر',price:1.25}],delivery:{branch:'القبلة',driver:'مندوب تموينات',phone:'+96550168888',eta:'اليوم 11:30'},tracking:[{status:'placed',label:'تم استلام الطلب',at:addDays(now(),-1)},{status:'confirmed',label:'تم تأكيد الطلب',at:addDays(now(),-1)},{status:'preparing',label:'جاري تجهيز التموينات',at:addDays(now(),-.5)},{status:'dispatched',label:'خرج الطلب للتوصيل',at:addDays(now(),-.1)}]},{id:'ord_10540',number:'#10540',restaurantId:r1.id,createdAt:addDays(now(),-3),paymentMethod:'credit',total:310,status:'delivered',items:[{productId:'rice',name:'أرز بسمتي',qty:100,unit:'كجم',price:.78}],tracking:[{status:'placed',label:'تم استلام الطلب',at:addDays(now(),-3)},{status:'delivered',label:'تم التسليم',at:addDays(now(),-2)}]});store.invoices.push({id:'inv_1082',number:'INV-1082',restaurantId:r1.id,amount:750,paid:0,status:'due',issuedAt:addDays(now(),-9),dueAt:addDays(now(),6)},{id:'inv_1074',number:'INV-1074',restaurantId:r1.id,amount:450,paid:0,status:'due',issuedAt:addDays(now(),-13),dueAt:addDays(now(),4)},{id:'inv_2081',number:'INV-2081',restaurantId:r2.id,amount:450,paid:0,status:'overdue',issuedAt:addDays(now(),-26),dueAt:addDays(now(),-11)});store.messages.push({id:'msg_001',restaurantId:r1.id,subject:'موعد التوصيل',body:'متى يصل طلب #10567؟',from:'restaurant',createdAt:addDays(now(),-.2),status:'open',replies:[]});}
seed();

const sign=p=>jwt.sign(p,JWT_SECRET,{expiresIn:'12h'});
function auth(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');try{req.user=jwt.verify(token,JWT_SECRET);next();}catch{return res.status(401).json({error:'unauthorized'});}}
const adminOnly=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({error:'forbidden'});
function findRestaurantForUser(username,password){for(const r of store.restaurants){const u=r.users.find(x=>x.username===username&&x.password===password&&x.active);if(u&&r.active)return{r,u};}return null;}
function restaurantView(r){const s=state(r);return{...r,users:undefined,...s,orders:store.orders.filter(o=>o.restaurantId===r.id),invoices:store.invoices.filter(i=>i.restaurantId===r.id),messages:store.messages.filter(m=>m.restaurantId===r.id)};}

app.get('/health',(req,res)=>res.json({ok:true,service:'tamweenat-api',ai:Boolean(process.env.OPENAI_API_KEY),time:now()}));
app.get('/api/catalog',(req,res)=>res.json(catalog.filter(x=>x.active)));
app.post('/api/auth/admin',(req,res)=>{const{username,password}=req.body||{};if(username!==ADMIN_USERNAME||password!==ADMIN_PASSWORD)return res.status(401).json({error:'invalid_credentials'});audit(username,'login','admin');res.json({token:sign({role:'admin',username}),user:{role:'admin',username}});});
app.post('/api/auth/restaurant',(req,res)=>{const{username,password}=req.body||{};const hit=findRestaurantForUser(username,password);if(!hit)return res.status(401).json({error:'invalid_credentials'});audit(username,'login',hit.r.id);res.json({token:sign({role:'restaurant',username,restaurantId:hit.r.id,userId:hit.u.id}),user:{role:hit.u.role,name:hit.u.name,restaurantId:hit.r.id,restaurantName:hit.r.name,username}});});
app.get('/api/me',auth,(req,res)=>{if(req.user.role==='admin')return res.json({role:'admin',username:req.user.username});const r=store.restaurants.find(x=>x.id===req.user.restaurantId);if(!r)return res.status(404).json({error:'not_found'});res.json(restaurantView(r));});

app.get('/api/admin/dashboard',auth,adminOnly,(req,res)=>{const rows=store.restaurants.map(r=>({...restaurantView(r),usersCount:r.users.length}));const totalCredit=money(rows.reduce((s,r)=>s+r.creditLimit,0)),outstanding=money(rows.reduce((s,r)=>s+r.outstanding,0)),overdue=money(rows.reduce((s,r)=>s+r.overdue,0));res.json({kpis:{restaurants:rows.length,active:rows.filter(r=>r.active).length,totalCredit,outstanding,available:money(totalCredit-outstanding),overdue,orders:store.orders.length,openMessages:store.messages.filter(m=>m.status==='open').length},restaurants:rows,recentOrders:store.orders.slice().reverse().slice(0,20),messages:store.messages.filter(m=>m.status==='open'),audit:store.audit.slice(0,50)});});
app.get('/api/admin/restaurants',auth,adminOnly,(req,res)=>res.json(store.restaurants.map(r=>({...restaurantView(r),users:r.users.map(({password,...u})=>u)}))));
app.post('/api/admin/restaurants',auth,adminOnly,(req,res)=>{const b=req.body||{};const r={id:rid('rest'),code:b.code||`R-${1000+store.restaurants.length+1}`,name:b.name||'مطعم جديد',legalName:b.legalName||'',phone:b.phone||'',email:b.email||'',address:b.address||'',branches:b.branches||[],active:b.active!==false,creditLimit:money(b.creditLimit||0),outstanding:money(b.outstanding||0),overdue:money(b.overdue||0),termsDays:Number(b.termsDays||30),monthlyBudget:money(b.monthlyBudget||0),monthSpend:0,creditSpendMonth:0,latePayments:0,createdAt:now(),users:[]};store.restaurants.push(r);audit(req.user.username,'create_restaurant',r.id,{name:r.name});res.status(201).json(restaurantView(r));});
app.patch('/api/admin/restaurants/:id',auth,adminOnly,(req,res)=>{const r=store.restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'not_found'});const allowed=['code','name','legalName','phone','email','address','branches','active','creditLimit','outstanding','overdue','termsDays','monthlyBudget'];for(const k of allowed)if(k in req.body)r[k]=['creditLimit','outstanding','overdue','monthlyBudget'].includes(k)?money(req.body[k]):req.body[k];audit(req.user.username,'update_restaurant',r.id,req.body);res.json(restaurantView(r));});
app.delete('/api/admin/restaurants/:id',auth,adminOnly,(req,res)=>{const r=store.restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'not_found'});r.active=false;audit(req.user.username,'disable_restaurant',r.id);res.json({ok:true});});
app.post('/api/admin/restaurants/:id/users',auth,adminOnly,(req,res)=>{const r=store.restaurants.find(x=>x.id===req.params.id);if(!r)return res.status(404).json({error:'not_found'});if(r.users.some(x=>x.username===req.body.username))return res.status(409).json({error:'username_exists'});const u={id:rid('u'),username:req.body.username,password:req.body.password||'123456',name:req.body.name||req.body.username,role:req.body.role||'buyer',active:req.body.active!==false,createdAt:now()};r.users.push(u);audit(req.user.username,'create_user',r.id,{username:u.username});const{password,...safe}=u;res.status(201).json(safe);});
app.patch('/api/admin/restaurants/:rid/users/:uid',auth,adminOnly,(req,res)=>{const r=store.restaurants.find(x=>x.id===req.params.rid),u=r?.users.find(x=>x.id===req.params.uid);if(!u)return res.status(404).json({error:'not_found'});for(const k of ['username','password','name','role','active'])if(k in req.body)u[k]=req.body[k];audit(req.user.username,'update_user',r.id,{userId:u.id});const{password,...safe}=u;res.json(safe);});
app.delete('/api/admin/restaurants/:rid/users/:uid',auth,adminOnly,(req,res)=>{const r=store.restaurants.find(x=>x.id===req.params.rid),u=r?.users.find(x=>x.id===req.params.uid);if(!u)return res.status(404).json({error:'not_found'});u.active=false;audit(req.user.username,'disable_user',r.id,{userId:u.id});res.json({ok:true});});

app.get('/api/orders',auth,(req,res)=>{const restId=req.user.role==='admin'?req.query.restaurantId:req.user.restaurantId;res.json(store.orders.filter(o=>!restId||o.restaurantId===restId));});
app.post('/api/orders',auth,(req,res)=>{const restaurantId=req.user.role==='admin'?req.body.restaurantId:req.user.restaurantId;const r=store.restaurants.find(x=>x.id===restaurantId);if(!r)return res.status(404).json({error:'restaurant_not_found'});const s=state(r);let paymentMethod=req.body.paymentMethod==='credit'?'credit':'direct';if(paymentMethod==='credit'&&s.locked)paymentMethod='direct';const items=(req.body.items||[]).map(x=>{const p=catalog.find(c=>c.id===x.productId);return p?{productId:p.id,name:p.name,qty:Number(x.qty||1),unit:p.unit,price:p.price}:null;}).filter(Boolean);const total=money(items.reduce((sum,x)=>sum+x.qty*x.price,0));if(paymentMethod==='credit'&&total>s.available)paymentMethod='direct';const o={id:rid('ord'),number:`#${10600+store.orders.length}`,restaurantId,createdAt:now(),paymentMethod,total,status:'placed',items,tracking:[{status:'placed',label:'تم استلام الطلب',at:now()}],delivery:req.body.delivery||{}};store.orders.push(o);if(paymentMethod==='credit'){r.outstanding=money(r.outstanding+total);r.creditSpendMonth=money(r.creditSpendMonth+total);}r.monthSpend=money(r.monthSpend+total);audit(req.user.username||req.user.role,'create_order',o.id,{restaurantId,paymentMethod,total});res.status(201).json({...o,creditState:state(r)});});
app.patch('/api/admin/orders/:id/status',auth,adminOnly,(req,res)=>{const o=store.orders.find(x=>x.id===req.params.id);if(!o)return res.status(404).json({error:'not_found'});const labels={confirmed:'تم تأكيد الطلب',preparing:'جاري تجهيز التموينات',dispatched:'خرج الطلب للتوصيل',delivered:'تم التسليم',cancelled:'تم إلغاء الطلب'};o.status=req.body.status||o.status;o.tracking.push({status:o.status,label:labels[o.status]||o.status,at:now()});if(req.body.delivery)o.delivery={...(o.delivery||{}),...req.body.delivery};audit(req.user.username,'order_status',o.id,{status:o.status});res.json(o);});

app.get('/api/messages',auth,(req,res)=>{const restId=req.user.role==='admin'?req.query.restaurantId:req.user.restaurantId;res.json(store.messages.filter(m=>!restId||m.restaurantId===restId));});
app.post('/api/messages',auth,(req,res)=>{const restaurantId=req.user.role==='admin'?req.body.restaurantId:req.user.restaurantId;const m={id:rid('msg'),restaurantId,subject:req.body.subject||'استفسار',body:req.body.body||'',from:req.user.role,createdAt:now(),status:'open',replies:[]};store.messages.unshift(m);audit(req.user.username||req.user.role,'message',restaurantId,{messageId:m.id});res.status(201).json(m);});
app.post('/api/messages/:id/reply',auth,(req,res)=>{const m=store.messages.find(x=>x.id===req.params.id);if(!m)return res.status(404).json({error:'not_found'});if(req.user.role!=='admin'&&m.restaurantId!==req.user.restaurantId)return res.status(403).json({error:'forbidden'});m.replies.push({id:rid('reply'),from:req.user.role,body:req.body.body||'',createdAt:now()});if(req.user.role==='admin')m.status='answered';res.json(m);});

function contextFor(restaurantId){const r=store.restaurants.find(x=>x.id===restaurantId);if(!r)return null;const s=state(r);return{restaurant:{id:r.id,name:r.name,branches:r.branches,creditLimit:r.creditLimit,outstanding:r.outstanding,overdue:r.overdue,monthlyBudget:r.monthlyBudget,monthSpend:r.monthSpend,...s},orders:store.orders.filter(o=>o.restaurantId===r.id).slice(-10),invoices:store.invoices.filter(i=>i.restaurantId===r.id).slice(-10),catalog:catalog.filter(x=>x.active).map(x=>({id:x.id,name:x.name,category:x.category,unit:x.unit,price:x.price}))};}
app.post('/api/ai/assistant',auth,async(req,res)=>{if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'ai_not_configured'});const restaurantId=req.user.role==='admin'?req.body.restaurantId:req.user.restaurantId;const context=contextFor(restaurantId);if(!context)return res.status(404).json({error:'restaurant_not_found'});try{const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const response=await client.responses.create({model:OPENAI_MODEL,instructions:'أنت مساعد تموينات الذكي للمطاعم. أجب بالعربية الكويتية المهنية المختصرة. اعتمد فقط على بيانات الحساب المرسلة. لا تخترع أسعاراً أو حالات طلب. ساعد في الحسابات والميزانية والشراء والتذكير والمتابعة.',input:`بيانات الحساب:\n${JSON.stringify(context)}\n\nسؤال المستخدم: ${String(req.body.message||'')}`});res.json({text:response.output_text});}catch(e){res.status(502).json({error:'ai_error',message:e.message});}});

app.post('/api/ai/realtime-call',auth,async(req,res)=>{if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'ai_not_configured'});if(req.user.role!=='restaurant')return res.status(403).json({error:'restaurant_only'});const context=contextFor(req.user.restaurantId);const offer=String(req.body||'');if(!offer.startsWith('v=0'))return res.status(400).json({error:'invalid_sdp'});const session={type:'realtime',model:REALTIME_MODEL,output_modalities:['audio'],instructions:`أنت المساعد الصوتي لمنصة تموينات. تحدث بالعربية الخليجية/الكويتية بوضوح وباختصار. هذه بيانات المطعم الحالية: ${JSON.stringify(context)}. تستطيع شرح الكريدت والمديونية والفواتير والطلبات والمنتجات والميزانية. لا تخترع أي بيانات غير موجودة. إذا طلب العميل تنفيذ إجراء مالي حساس فاشرح له الخطوة ولا تنفذه دون تأكيد داخل واجهة النظام.`,audio:{output:{voice:'marin'},input:{noise_reduction:{type:'near_field'},turn_detection:{type:'server_vad',create_response:true,interrupt_response:true}}}};try{const fd=new FormData();fd.set('sdp',offer);fd.set('session',new Blob([JSON.stringify(session)],{type:'application/json'}));const r=await fetch('https://api.openai.com/v1/realtime/calls',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:fd});const text=await r.text();if(!r.ok)return res.status(r.status).send(text);res.type('application/sdp').send(text);}catch(e){res.status(502).json({error:'realtime_error',message:e.message});}});

app.get('/api/admin/audit',auth,adminOnly,(req,res)=>res.json(store.audit.slice(0,500)));
app.get('/api/admin/settings',auth,adminOnly,(req,res)=>res.json({...store.settings,aiEnabled:Boolean(process.env.OPENAI_API_KEY)}));
app.patch('/api/admin/settings',auth,adminOnly,(req,res)=>{Object.assign(store.settings,req.body||{});audit(req.user.username,'settings','system',req.body);res.json(store.settings);});

app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'server_error'});});
app.listen(PORT,'0.0.0.0',()=>console.log(`Tamweenat API listening on ${PORT}`));
