import http from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomUUID,scrypt,timingSafeEqual,createHash} from 'node:crypto';
import {promisify} from 'node:util';
const root=dirname(fileURLToPath(import.meta.url)),prod=process.env.NODE_ENV==='production',port=+(process.env.PORT||8787),origin=process.env.APP_ORIGIN||`http://localhost:${port}`,allowed=new Set([origin,...(process.env.FRONTEND_ORIGINS||'').split(',').filter(Boolean)]),enabled=process.env.ACCOUNTS_ENABLED==='true';
if(prod&&enabled&&(!process.env.DATA_DIR||process.env.DURABLE_STORAGE_CONFIRMED!=='true'))throw Error('Accounts require confirmed durable storage. Do not store customer data on ephemeral disks.');
const dir=process.env.DATA_DIR||resolve(root,'.data');await mkdir(dir,{recursive:true});const db=new DatabaseSync(resolve(dir,'studio.sqlite'));db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,document TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS project_owner ON projects(user_id);
`);const derive=promisify(scrypt),digest=s=>createHash('sha256').update(s).digest('hex');
async function passwordHash(p){const salt=randomBytes(16).toString('hex');return salt+':'+(await derive(p,salt,64)).toString('hex')}
async function passwordCheck(p,h){const [salt,key]=h.split(':');return timingSafeEqual(Buffer.from(key,'hex'),await derive(p,salt,64))}
const cookie=(token,maxAge=604800)=>`studio_session=${token}; HttpOnly; Path=/; SameSite=Lax; Max-Age=${maxAge}${prod?'; Secure':''}`;
function session(req){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('studio_session='))?.slice(15);if(!raw)return null;return db.prepare('SELECT u.id,u.name,u.email FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>?').get(digest(raw),Date.now())}
function issue(res,u){db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),u.id,Date.now()+604800000);res.setHeader('Set-Cookie',cookie(token))}
async function body(req){let n=0,chunks=[];for await(const c of req){n+=c.length;if(n>12*1024*1024)throw Object.assign(Error('حجم الملف يتجاوز الحد المسموح'),{status:413});chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}')}catch{throw Object.assign(Error('بيانات غير صالحة'),{status:400})}}
function validate(d){return d&&typeof d.id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(d.id)&&typeof d.name==='string'&&d.name.length<=100&&Number.isInteger(d.width)&&Number.isInteger(d.height)&&d.width>=100&&d.width<=4096&&d.height>=100&&d.height<=4096&&Array.isArray(d.pages)&&d.pages.length>0&&d.pages.length<=20&&d.pages.every(p=>/^#[0-9a-f]{3,8}$/i.test(p.background)&&Array.isArray(p.elements)&&p.elements.length<=200&&p.elements.every(e=>typeof e.id==='string'&&['text','rect','image'].includes(e.type)&&['x','y','w','h'].every(k=>Number.isFinite(e[k])&&Math.abs(e[k])<20000)&&(e.type!=='text'||(typeof e.text==='string'&&e.text.length<=3000&&Number.isFinite(e.size)&&e.size>=8&&e.size<=500&&[400,700].includes(e.weight)&&['left','right','center'].includes(e.align)))&&(e.type!=='image'||(typeof e.src==='string'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(e.src)))&&(e.type==='image'||/^#[0-9a-f]{3,8}$/i.test(e.color))))}
const limits=new Map();function limited(key,max=20){const now=Date.now();let r=limits.get(key);if(!r||r.until<now)limits.set(key,r={count:0,until:now+900000});return ++r.count>max}setInterval(()=>{for(const[k,v]of limits)if(v.until<Date.now())limits.delete(k)},60000).unref();
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
const publicUser=u=>({id:u.id,name:u.name,email:u.email});
const server=http.createServer(async(req,res)=>{try{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");const requestOrigin=req.headers.origin;if(requestOrigin&&allowed.has(requestOrigin)){res.setHeader('Access-Control-Allow-Origin',requestOrigin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin')}if(req.method==='OPTIONS'){if(!allowed.has(requestOrigin))return send(res,403,{error:'مصدر غير مصرح'});res.writeHead(204,{'Access-Control-Allow-Methods':'GET,POST,PUT,DELETE','Access-Control-Allow-Headers':'Content-Type'});return res.end()}const url=new URL(req.url,origin),p=url.pathname;if(p==='/api/status')return send(res,200,{accounts:enabled,billing:false,canva:false,stage:'beta'});if(p==='/health')return send(res,200,{ok:true});if(p.startsWith('/api/')){if(!enabled)return send(res,503,{error:'الحسابات قيد التجهيز'});if(['POST','PUT','DELETE'].includes(req.method)&&(!requestOrigin||!allowed.has(requestOrigin)||!req.headers['content-type']?.startsWith('application/json')))return send(res,403,{error:'مصدر أو نوع طلب غير مصرح'});const ip=req.socket.remoteAddress;if(limited('all:'+ip,300))return send(res,429,{error:'طلبات كثيرة، حاول لاحقاً'});
if(p==='/api/auth/register'&&req.method==='POST'){if(limited('auth:'+ip))return send(res,429,{error:'محاولات كثيرة، حاول لاحقاً'});const {name,email,password}=await body(req);if(typeof name!=='string'||!name.trim()||name.length>80||typeof email!=='string'||email.length>254||!/^\S+@\S+\.\S+$/.test(email)||typeof password!=='string'||password.length<12||password.length>128)return send(res,400,{error:'راجع البيانات واستخدم كلمة مرور من 12 حرفاً على الأقل'});const normalized=email.trim().toLowerCase();if(db.prepare('SELECT id FROM users WHERE email=?').get(normalized))return send(res,409,{error:'تعذر إنشاء الحساب بهذه البيانات'});const u={id:randomUUID(),name:name.trim(),email:normalized};const hash=await passwordHash(password);try{db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(u.id,u.email,u.name,hash,Date.now())}catch{return send(res,409,{error:'تعذر إنشاء الحساب بهذه البيانات'})}issue(res,u);return send(res,201,{user:u})}
if(p==='/api/auth/login'&&req.method==='POST'){if(limited('auth:'+ip))return send(res,429,{error:'محاولات كثيرة، حاول لاحقاً'});const {email,password}=await body(req);if(typeof email!=='string'||typeof password!=='string'||password.length>128)return send(res,400,{error:'بيانات غير صالحة'});const u=db.prepare('SELECT * FROM users WHERE email=?').get(email.trim().toLowerCase());if(!u||!await passwordCheck(password,u.password))return send(res,401,{error:'البريد أو كلمة المرور غير صحيح'});issue(res,u);return send(res,200,{user:publicUser(u)})}
const u=session(req);if(!u)return send(res,401,{error:'يرجى تسجيل الدخول'});if(p==='/api/auth/me')return send(res,200,{user:u});if(p==='/api/auth/logout'&&req.method==='POST'){const raw=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('studio_session='))?.slice(15);if(raw)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(raw));res.setHeader('Set-Cookie',cookie('',0));return send(res,200,{ok:true})}
if(p==='/api/projects'&&req.method==='GET')return send(res,200,{projects:db.prepare('SELECT id,name,updated_at FROM projects WHERE user_id=? ORDER BY updated_at DESC').all(u.id)});const match=p.match(/^\/api\/projects\/([a-zA-Z0-9-]{1,80})$/);if(match){const id=match[1];if(req.method==='GET'){const row=db.prepare('SELECT document FROM projects WHERE id=? AND user_id=?').get(id,u.id);return row?send(res,200,{document:JSON.parse(row.document)}):send(res,404,{error:'المشروع غير موجود'})}if(req.method==='DELETE'){const r=db.prepare('DELETE FROM projects WHERE id=? AND user_id=?').run(id,u.id);return send(res,r.changes?200:404,r.changes?{ok:true}:{error:'المشروع غير موجود'})}if(req.method==='PUT'){const {document:d}=await body(req);if(!validate(d)||d.id!==id)return send(res,400,{error:'ملف التصميم غير صالح'});const existing=db.prepare('SELECT user_id FROM projects WHERE id=?').get(id);if(existing&&existing.user_id!==u.id)return send(res,404,{error:'المشروع غير موجود'});if(!existing&&db.prepare('SELECT COUNT(*) n FROM projects WHERE user_id=?').get(u.id).n>=20)return send(res,403,{error:'وصلت إلى الحد التجريبي: 20 مشروعاً'});const encoded=JSON.stringify(d);const storage=db.prepare('SELECT COALESCE(SUM(LENGTH(document)),0) n FROM projects WHERE user_id=? AND id<>?').get(u.id,id).n;if(storage+Buffer.byteLength(encoded)>50*1024*1024)return send(res,403,{error:'وصلت إلى حد التخزين التجريبي: 50 ميغابايت'});db.prepare('INSERT INTO projects VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,document=excluded.document,updated_at=excluded.updated_at').run(id,u.id,d.name,encoded,Date.now());return send(res,200,{ok:true})}}
return send(res,404,{error:'الخدمة المطلوبة غير متاحة'})}
const files={"/samples.html":"samples.html","/social.html":"social.html","/print.html":"print.html","/resumes.html":"resumes.html","/education.html":"education.html","/instagram.html":"instagram.html","/business.html":"business.html","/events.html":"events.html","/brand.html":"brand.html","/all.html":"all.html","/packaging.html":"packaging.html","/service.html":"service.html","/websites.html":"websites.html","/how-it-works.html":"how-it-works.html",'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/mesh.svg':'mesh.svg','/config.js':'config.js','/translations.js':'translations.js','/i18n.js':'i18n.js','/fonts/al-mohanad.woff':'fonts/al-mohanad.woff','/fonts/al-mohanad-bold.woff':'fonts/al-mohanad-bold.woff'},file=files[p]||(/^\/fonts\/cairo-(regular|bold|extrabold)\.woff$/.test(p)?p.slice(1):undefined)||(/^\/samples\/[a-z]+-\d{2}\.webp$/.test(p)?p.slice(1):undefined);if(!file||req.method!=='GET')return send(res,404,{error:'غير موجود'});const data=await readFile(resolve(root,'public',file));res.writeHead(200,{'Content-Type':file.endsWith('.webp')?'image/webp':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.woff')?'font/woff':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'});res.end(data)
}catch(e){send(res,e.status||500,{error:e.status?e.message:'تعذر إتمام الطلب'})}});server.listen(port,'0.0.0.0',()=>console.log(`Studio listening on ${port}; accounts=${enabled}`));
